### ISSUE TITLE
Resolve missing Grand Central Dispatch support on Linux.

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#1]
Linux builds are currently broken by dependency on Grand Central Dispatch libraries. We need to revise this or find an implementation of GCD that we can use.

**Comment by johndpope** [comment]
fyi there does exist a  grpc swift library online which supposedly works on linux 
 https://github.com/Huawei-PTLab/SwiftGRPC
https://github.com/Huawei-PTLab/CGRPC
but I couldn't get grpc patched. Huawei-PTLab/CGRPC#2

**Comment by johndpope** [comment]
You want libdispatch  / GCD
this may help


rm -rf swift-corelibs-libdispatch
git clone -b experimental/foundation http://github.com/apple/swift-corelibs-libdispatch
cd swift-corelibs-libdispatch
git submodule init
git submodule update
cd ..

https://gist.github.com/romainmenke/506a4b0858c22f10e2598517b978f8c7

**Comment by timburks** [comment]
I heard from Carl Brown at IBM that the changes that we need are in Swift 3 and it appears that the initial Linux examples work with swift-3.0.1-RELEASE-ubuntu16.04.

**Comment by timburks** [comment]
[This commit](https://github.com/grpc/grpc-swift/commit/c3f35da0ccba33c0d4641a7015c375f9e18247a8#diff-ddb1cdde444da5b45dacc58bd3db81c7) updates the simple Client and Server in the Packages directory to synchronize client and server threads with NSCondition variables. The result appears to run correctly on Linux.
