### ISSUE TITLE
Robust error handling

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#10]
These error situations that aren't handled well.

- Server methods receiving invalid message protocol buffers from clients.
- Clients receiving invalid protocol buffers from servers.
- Authentication failures from servers.
- Server handler (aka "provider") failures inside dispatched threads.

**Comment by dvaldivia** [comment]
Indeed, right now the handling of errors while doing of streams make it really complicated to cancel a stream

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.

**Comment by talksik** [comment]
Following up on one of the scenarios, what would be a robust solution to notify a swiftUI model of a session expiry. Currently, I can only think of initializing interceptors with callbacks for `onUnauthenticated` errors that the interceptor `receive` method catches.

Is there any way of doing this to propagate or send events to the UI layer globally when there is an auth issue?
