### ISSUE TITLE
grpc-swift servers reject requests with "grpc-encoding: identity" when compression is disabled, even though such a request is not compressed.

### ISSUE THREAD

**Issue by Lukasa** [grpc/grpc-swift#1005]
If a gRPC server is set up without compression support, and it receives an rpc containing a `grpc-encoding: identity` header, [that request will be rejected](https://github.com/grpc/grpc-swift/blob/a374528d108008795bc587549cda5c21dca970ee/Sources/GRPC/HTTP1ToGRPCServerCodec.swift#L569) despite the rpc not actually being compressed. We should add an escape hatch for this case to continue to accept the request.

**Comment by glbrntt** [comment]
That's pretty silly. Looks like the fix should be pretty straightforward though: an additional case for `(.disabled, .some("identity"))` and a test to validate the fix.
