### ISSUE TITLE
Carthage build broken -- no shared framework schemes for ios platform

### ISSUE THREAD

**Issue by tklebanoff** [grpc/grpc-swift#1007]
### Describe the bug
From an ios project directory, using carthage:

$ carthage update --platform iOS grpc-swift
*** Checking out grpc-swift at "992cf22f1553b3b83353cfe6f1253cfd98e33596"
*** xcodebuild output can be found in /var/folders/b5/tdrk414n3vd6bprfq3v26_m40000gp/T/carthage-xcodebuild.ZYwwSz.log
*** Skipped building grpc-swift due to the error:
Dependency "grpc-swift" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/grpc/grpc-swift/issues/new

### Expected behaviour

I expect to be able to use grpc-swift from the main branch in a project with carthage.  Is this supported?  It seems like it was at one point, but not any more.  If support for carthage was dropped, could we please bring it back? the rest of my project's dependencies use carthage. I am not opposed to maintaining a fork of grpc for carthage, but don't know quite how to set that up cleanly, in a way that is stable in the long term.  I would be grateful for any help to figure out the shortest path towards a working and stable carthage build.

**Comment by tklebanoff** [comment]
I am trying to do this manually, by running a custom script in build phases, after generating a .xcodeproj file.

Xcode is refusing to run the swift build commands associated with "make && make project"
does anybody have any idea why it is doing this?  the error makes no sense.  I can't find anything about it online.  The same commands work directly from my shell.  I have tried several variations of the commands (all of which work from the shell) but none of which work from xcode.

Sometimes I wish apple would stop condescending to developers and trying to control everything.  running a script before a build should be the easiest thing in the world.

**Comment by tklebanoff** [comment]
<img width="535" alt="Screen Shot 2020-10-22 at 5 14 12 PM" src="https://user-images.githubusercontent.com/48869587/96931052-b2a2fb00-148a-11eb-89a3-8d41067ce4d5.png">
<img width="1395" alt="Screen Shot 2020-10-22 at 5 14 32 PM" src="https://user-images.githubusercontent.com/48869587/96931057-b46cbe80-148a-11eb-913a-8e993d414846.png">

removing the run script build phase (or changing its contents "make && make project" to echo "hi") leads to "build success"

no clue why one of the errors emerging from the inclusion of the build script references the macosx library or a manifest.  as far as i can tell, there is no reason to parse any manifest or load any standard library for macosx simply because of the run script: make && make project

**Comment by tklebanoff** [comment]
I have tried calling the swift build invocations:
swift build --build-path=./.build --configuration=debug
swift package --build-path=./.build --configuration=debug generate-xcodeproj --output GRPC.xcodeproj

directly, but that gives the same error.  In other words, the run script is indeed getting called, and it is not a problem with the make invocation.  I have also tried various configurations of 
 /usr/bin/env zsh -c "swift build --build-path=./.build --configuration=debug" 
etc. but that gives the same error for some reason.

**Comment by Lukasa** [comment]
You are building your project for iOS, but `swift build` without further clarification will target macOS. Anything you build in this way will fail to link with your project. `swift build` cannot target iOS either, sadly. However, `xcodebuild` can build a Swift package. Try `xcodebuild -scheme GRPC` as an example.

**Comment by tklebanoff** [comment]
Hi @Lukasa , thanks for helping.  I suppose my basic question then is this:
How can I get grpc-swift to build for iOS with Carthage? what is the cleanest way to achieve this?

**Comment by Lukasa** [comment]
`swift package generate-xcodeproj` will build an Xcode project. You can then use that. However, that's a fairly substantial pain to maintain in the long term as it requires that the maintainers of grpc continue to update the xcodeproj every time they make changes to the package structure on disk (e.g. adding/removing files).

My first-order recommendation, if it's at all possible, is to depend on grpc using Xcode's Swift Package Manager support. This is the primary way the grpc developers develop grpc, and it's going to work the best. This should work well unless your Carthage dependencies also need to depend on grpc-swift.
