### ISSUE TITLE
gRPC server in App don't receive requests immediately when iOS app enter background

### ISSUE THREAD

**Issue by yonglam** [grpc/grpc-swift#1015]
### Describe the bug

gRPC version:  ` pod 'gRPC-Swift', '1.0.0-alpha.20'`
swift version: Swift 5

I wanna run a gRPC Server in my iOS App, and my App maybe runs on background for a long time. It works fine when App is in the foreground mode, but in background mode, the gRPC Server will not response to any Client connection. And It will work again once App comes back to foreground. 

If I start the Server on main thread, everything works fine. But I don't want to block my main thread.

    class ViewController: UIViewController {
        override func viewDidLoad() {
            super.viewDidLoad()
            
            // Move to a background thread to do some long running work
            DispatchQueue.global(qos: .userInitiated).async {
                self.startServer()
            }
            
        }
        
        func startServer() {
            let group = MultiThreadedEventLoopGroup(numberOfThreads: 2)
            defer {
              try! group.syncShutdownGracefully()
            }
    
            // Start the server and print its address once it has started.
            let server = Server.insecure(group: group)
              .withServiceProviders([GreeterProvider()])
              .bind(host: "0.0.0.0", port: 53442)
            
            server.map {
                $0.channel.localAddress
            }.whenSuccess { address in
              print("server started on port \(address!.port!)")
            }
            // Wait on the server's `onClose` future to stop the program from exiting.
            _ = try! server.flatMap {
                $0.onClose
            }.wait()
        }
    }

### To reproduce

1. Run iOS App
2. Press home button

### Expected behaviour

gRPC Server (running at background thread)  responses to Client connections when iOS App in background mode

### Additional information

When iOS App in background mode, gRPC Server works greatly if it runs on main thread.

**Comment by Lukasa** [comment]
The server does not run on the main thread: it spawns its own threads to run. You can safely launch the server from your main thread and, instead of using `.wait()`, ask to be notified on a dispatch queue of the server exiting:

```
class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        startServer()
    }
    
    func startServer() {
        let group = MultiThreadedEventLoopGroup(numberOfThreads: 2)
        defer {
          try! group.syncShutdownGracefully()
        }

        // Start the server and print its address once it has started.
        let server = Server.insecure(group: group)
          .withServiceProviders([GreeterProvider()])
          .bind(host: "0.0.0.0", port: 53442)
        
        server.map {
            $0.channel.localAddress
        }.whenSuccess { address in
          print("server started on port \(address!.port!)")
        }
        // Wait on the server's `onClose` future to stop the program from exiting.
        server.flatMap {
            $0.onClose
        }.whenCompleteBlocking(onto: .main) { 
            print("server exited")
        }
    }
}
```

For what it's worth, grpc doesn't care about which thread you run it from, so I think this is a strange interaction with iOS backgrounding the process.

**Comment by yonglam** [comment]
@Lukasa Thanks for your reply. Yes, it's not blocking the main thread when used your code. But when app entered background, gRPC Server would stop working. How can I run it under background?

**Comment by Lukasa** [comment]
grpc servers don't have any special privileges for running in the background. There are standard guidelines for running in the background on iOS: those apply to your application. You can request appropriate entitlements or request a specific background task as usual.

**Comment by yonglam** [comment]
I was debugging using Xcode, and I believed my App can run for a few seconds after enter background, but grpc server stop immediately which is abnormal. I found it was something about the swift-NIO, because SelectableEventLoop didn't fire any event in that case.

**Comment by Lukasa** [comment]
SelectableEventLoop does not detect backgrounding in iOS because it cannot.
