### ISSUE TITLE
How can we run multiple services?

### ISSUE THREAD

**Issue by saga-dash** [grpc/grpc-swift#102]
Hi
There are two files as follows
* one.proto
```
syntax = "proto3";
package test;

message OneRequest {
  string text = 1;
}
message OneResponse {
  string text = 1;
}
service One {
  rpc Get(OneRequest) returns (OneResponse) {}
}
```
* two.proto
```
syntax = "proto3";
package test;

message TwoRequest {
  string text = 1;
}
message TwoResponse {
  string text = 1;
}
service Two {
  rpc Get(TwoRequest) returns (TwoResponse) {}
}
```

When I convert these files with protoc-gen-swiftgrpc,` Test_OneServer` and `Test_TwoServer` are output to each grpc.swift file.

Can I start these servers on one host, one port?

Or may I have to make one proto file for service?

I'd like two services to be put together on something like `Test_Server`.

**Comment by timburks** [comment]
Hi, thanks for raising this. Merging two servers could be done, but it would require some manual rework of the generated code. As you may have already found, an example of the relevant code is here: https://github.com/grpc/grpc-swift/blob/master/Examples/Echo/Generated/echo.grpc.swift#L617

If you had two servers to merge, you would need to merge the cases in the switch statement in this function.

This looks like a common situation, so I think we'd want to support it in the code generator. Please follow up if you have any suggested patterns for this.

**Comment by saga-dash** [comment]
Thanks for the reply.
I understood how to merge some services.
I tried changing the template of protoc-gen-swiftgrpc, but it seemed to require some modifications.
Think about a little time.

Thank you.
