### ISSUE TITLE
Split out ConnectionBackoff into its own package?

### ISSUE THREAD

**Issue by daltonclaybrook** [grpc/grpc-swift#1023]
### What are you trying to achieve?

I've found myself using the [ConnectionBackoff](https://github.com/grpc/grpc-swift/blob/main/Sources/GRPC/ConnectionBackoff.swift) type in contexts outside of gRPC because I think it's a great implementation of backoff that stands on its own. Is there any appetite for splitting this type out into its own package so folks can choose to use it without bringing in the rest of gRPC?

**Comment by glbrntt** [comment]
From the gRPC perspective, I don't think it's something we'd want to do as we'd like to keep our number of dependencies as low as possible. 

There is of course nothing to stop _you_ from extracting it into a separate library providing you include the license etc.
