### ISSUE TITLE
How to get TLS secret Keys to decrypt HTTP2

### ISSUE THREAD

**Issue by BioZrod** [grpc/grpc-swift#1026]
### What are you trying to achieve?

Hello I am receiving error 401 "not authenticated" when trying to connect to a secured server. To be able to figure out what is wrong I am trying to decrypt the http2 message using wireshark. But it requires both the kRSA key I am using and the TLS keys from the connection. I am wondering how I can get the TLS keys from the connection.

### What have you tried so far?

gRPC-Swift version: 1.0.0-alpha.19

I understand this library relies on boringssl to do the TLS connection so I tried using Frida to get the keys following the tutorial in the link [https://andydavies.me/blog/2019/12/12/capturing-and-decrypting-https-traffic-from-ios-apps/](url). I changed the code to use the offset for boringssl on IOS version 13.7 which is the version I am using but when running I can't get any key. I wonder if it doesn't work because not using BoringSSL directly for TLS and going through gRPC-Swift or the issue is another one.

I would appreciate if someone could point me in the right direction to get the TLS keys.

**Comment by glbrntt** [comment]
I think you have a couple of options here: either you can collect a PCAP of the decrypted traffic using gRPC (there's an example [here](https://github.com/grpc/grpc-swift/tree/main/Examples/PCAPExample)), or you can set a [keylog callback](https://github.com/apple/swift-nio-ssl/blob/4de53b6c848a5e2bd20b681f6605983e3b092ed7/Sources/NIOSSL/TLSConfiguration.swift#L210) on your TLS configuration. Note that option this isn't exposed on the 'normal' gRPC connection builder: you'll need to create the connection configuration and set the TLS configuration manually.

**Comment by BioZrod** [comment]
> I think you have a couple of options here: either you can collect a PCAP of the decrypted traffic using gRPC (there's an example [here](https://github.com/grpc/grpc-swift/tree/main/Examples/PCAPExample)), or you can set a [keylog callback](https://github.com/apple/swift-nio-ssl/blob/4de53b6c848a5e2bd20b681f6605983e3b092ed7/Sources/NIOSSL/TLSConfiguration.swift#L210) on your TLS configuration. Note that option this isn't exposed on the 'normal' gRPC connection builder: you'll need to create the connection configuration and set the TLS configuration manually.

Thank I will try both to see what works best for me. When I added NIOExtras 1.7.0 as dependency I get 5 errors:
- Redefinition of module 'CNIOAtomics'
- Redefinition of module 'CNIODarwin'
- Redefinition of module 'CNIOLinux'
- Redefinition of module 'SHA1'
- Could not build Objective-C module SwiftShims.

**Comment by BioZrod** [comment]
I did not manage to get the decrypted PCAP using GRPC. But I got to print the Secret Key using a keylog Callback I paste the code here for future reference if anyone finds it helpful.

```
let keyLogCallback : NIOSSLKeyLogCallback = { byteBuffer in
                print("Start of Byte Buffer Code")
                print(byteBuffer)
                print(byteBuffer.getString(at: 0, length: byteBuffer.readableBytes))
                print("End of Byte Buffer Code")
            }
            
            var configTLS = TLSConfiguration.forClient()
            configTLS.trustRoots = .certificates(pemCert)
            configTLS.certificateChain = [.certificate(serverSignedCert)]
            configTLS.privateKey = .privateKey(privKey)
            configTLS.minimumTLSVersion = TLSVersion.tlsv12
            configTLS.maximumTLSVersion = TLSVersion.tlsv12
            configTLS.certificateVerification = .fullVerification
            configTLS.applicationProtocols = ["grpc-exp", "h2"]
            configTLS.signingSignatureAlgorithms = [SignatureAlgorithm.rsaPkcs1Sha256]
            configTLS.verifySignatureAlgorithms = [SignatureAlgorithm.rsaPkcs1Sha256]
            configTLS.keyLogCallback = keyLogCallback
```

Those print statements ouput the secret Key on console. You can also include any code that you need to use with the bytebuffer from the key there if you need to make any operations with it.
