### ISSUE TITLE
How to change HTTP authority Header.

### ISSUE THREAD

**Issue by BioZrod** [grpc/grpc-swift#1029]
# What are you trying to achieve?

I am trying to change the HTTP "authority" header to a different one from the host specified. I can see that on "ClientConnection"class the authority is specified as an internal var and it takes the value from the host specified.

For my project my server requires a different authority than the host name. I was wondering if there is any way I can set this. 

### What have you tried so far?

I was trying to make a connection and I run into a Error "401 Unauthorized" discussed in  #978 After doing some research and trying to change the authority using a callback and setting the HPACK header I was still getting the error. So I decrypted the HTTP2 packet using what was suggested on #1026. After decrypting the packet I saw that I had 2 authority headers set, one was equal to the host and the second one was the one set in the callback so I decided to check grpc-swift code and found out that in "ClientConnection" class the authority takes the value of the host. As a temporary solution I modified the class and made authority a public var then changed its value to the one I needed and removed the callback with the HPACKHeader. After doing that I successfully connected to my server.

gRPC-swift version: 1.0.0-alpha.19
TLS connection made using a custom configuration:

```
var configTLS = TLSConfiguration.forClient()
            configTLS.trustRoots = .certificates(pemCert)
            configTLS.certificateChain = [.certificate(serverSignedCert)]
            configTLS.privateKey = .privateKey(privKey)
            configTLS.minimumTLSVersion = TLSVersion.tlsv12
            configTLS.maximumTLSVersion = TLSVersion.tlsv12
            configTLS.certificateVerification = .fullVerification
            configTLS.applicationProtocols = ["grpc-exp", "h2"]
            configTLS.signingSignatureAlgorithms = [SignatureAlgorithm.rsaPkcs1Sha256]
            configTLS.verifySignatureAlgorithms = [SignatureAlgorithm.rsaPkcs1Sha256]
            configTLS.keyLogCallback = keyLogCallback

let config = ClientConnection.Configuration(target: ConnectionTarget.hostAndPort(self.CONTROLLER_ADDRESS, self.CONTROLLER_PORT), eventLoopGroup: group, errorDelegate: LoggingClientErrorDelegate(), connectivityStateDelegate: nil, connectivityStateDelegateQueue: nil, tls: ClientConnection.Configuration.TLS.init(configuration: configTLS, hostnameOverride: self.METRICS_AUTHORITY_HEADER), connectionBackoff: ConnectionBackoff(), connectionKeepalive: ClientConnectionKeepalive(), connectionIdleTimeout: .minutes(30), callStartBehavior: .waitsForConnectivity, httpTargetWindowSize: 65535, backgroundActivityLogger: logger, debugChannelInitializer: nil)

let connection = ClientConnection.init(configuration: config)
connection.authority = self.METRICS_AUTHORITY_HEADER

```

**Comment by glbrntt** [comment]
This sounds like a bug, I think gRPC should automatically use the TLS hostname override you provided in the TLS configuration as the ":authority" pseudo header (it doesn't right now). Does that sound right @Lukasa?

**Comment by Lukasa** [comment]
Yup, seems sensible.
