### ISSUE TITLE
Service name in client 

### ISSUE THREAD

**Issue by mengxiangyue** [grpc/grpc-swift#1036]
Hello team, I am do the investigation how to integrate with `client load balance` strategy, but I find I can't get the service name which I want to request in client code. 

In provider side, I can use service name to register instance, but in client side, I can't get the same service name, because I want to use `service name` to find right instance to create `channel` to pass into client.

Can we add `serviceName` property in client side code?

I also check the code, it is easy.

**Comment by glbrntt** [comment]
Yes, I think we can add a similar `var serviceName: String { get }` requirement to the generated client protocol.

**Comment by glbrntt** [comment]
Closed via #1059
