### ISSUE TITLE
Why build protoc-gen-swift also?

### ISSUE THREAD

**Issue by FreeMobility** [grpc/grpc-swift#105]
The build instructions create binaries from protoc-gen-swift along with protoc-gen-swiftgrpc. If I'm adding the protobuf library via Carthage - the tags from the swift-protobuf repo do not align with the tags for grpc-swift. Is the usage of the compiled protoc-gen-swift plugin in this repository necessary, or may I use the one from swift-protobuf repo without breaking grpc-swift ?

**Comment by timburks** [comment]
Sure, that would be fine. Thanks!
