### ISSUE TITLE
0.9.1 Carthage project does not build successfully on Xcode 12

### ISSUE THREAD

**Issue by banjun** [grpc/grpc-swift#1051]
I have a workaround for this error below. I would like to send a PR on top of 0.9.1 if there's a target branch just on it (such as `maintenance/0.9.x`).

# Describe the bug

On Xcode 12, SwiftGRPC-Carthage.xcodeproj of grpc-swift 0.9.1 does not build successfully.

### To reproduce

Xcode: Xcode 12 (Xcode 12.2)

Steps to reproduce the bug you've found:
1. `git checkout 0.9.1`
2. `rm -rf .build` # make sure there are no intermediates
3. `open SwiftGRPC-Carthage.xcodeproj`
4. Build SwiftGRPC-Package

### Expected behaviour

the build succeeds

Actual behaviour:

> error: Build input files cannot be found: '/Users/user/project/github/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONDecodingOptions.swift', ...

### Additional information

The error is caused indirectly by `swift package resolve` in the build pre-action of SwiftGRPC-Carthage.xcodeproj. An available workaround is here:

* https://github.com/banjun/grpc-swift/commit/faaaa2370e67d8699486f7f93b8ee546d1d7e0f2
* https://github.com/banjun/grpc-swift/commit/e924a757f9b224725af02a81d35c726334736b20

I really want to stick with 0.9.1 for the time being before migrating to 1.0.0 to save some time.

**Comment by glbrntt** [comment]
> I have a workaround for this error below. I would like to send a PR on top of 0.9.1 if there's a target branch just on it (such as `maintenance/0.9.x`).

Thanks for reporting this with a fix @banjun -- you can open a PR targeting the [`cgrpc`](https://github.com/grpc/grpc-swift/tree/cgrpc) branch.

**Comment by banjun** [comment]
@glbrntt I can try sending a PR to the `cgrpc` branch but I want a minimum fix to 0.9.1 for now. Would you mind if you create 0.9.2 for the issue?

**Comment by glbrntt** [comment]
Oh sorry, I incorrectly had it in my head that the 0.x branch was on 0.9.1. Try https://github.com/grpc/grpc-swift/tree/maintenance/0.9.x
