### ISSUE TITLE
Release 1.0.0-alpha.21 to CocoaPods

### ISSUE THREAD

**Issue by vyshane** [grpc/grpc-swift#1056]
### What are you trying to achieve?

My library depends on gRPC Swift. I'm updating the gRPC Swift dependency in my podspec to the latest `1.0.0-alpha.21` release, but it appears that this version has not been pushed to CocoaPods yet.

### What have you tried so far?

I've checked https://cocoapods.org/pods/gRPC-Swift, and can't see `1.0.0-alpha.21` there. Latest version on CocoaPods is `1.0.0-alpha.20`.

**Comment by glbrntt** [comment]
Sorry I didn't have time to do them earlier, just pushing them now.

**Comment by glbrntt** [comment]
FYI: A bunch of the NIO dependencies need releases as we now support watchOS as a platform. This is going to take a little while (i.e. not today).

**Comment by glbrntt** [comment]
Done!

**Comment by vyshane** [comment]
Thanks @glbrntt!
