### ISSUE TITLE
grpc-gen-swift generates all dependency protos instead of only requested ones

### ISSUE THREAD

**Issue by jagobagascon** [grpc/grpc-swift#1057]
### Describe the bug

We recently upgraded form version `alpha.14` to `alpha.20`. After this change, when we try to generate a proto that has a dependency on another proto, the generator is creating code for both protos (and not only the requested one).

Let's say `foo.proto` depends on `bar.proto`, we generate both independently and move each of them to a different swift module. After upgrading to `alpha.20` generating `foo.proto` is creating files for `bar.proto` (which I think is wrong).
```
foo/
    foo.grpc.swift
    bar.grpc.swift <-- This should not be created when generating code using only foo.proto
bar/
    bar.grpc.swift
```
### To reproduce

I created this repo for another bug, but it can be reproduced by calling `make generate` in it: _ModuleB_ will contain code generated from `b.proto` and _ModuleA_ will contain both code generated from **`a.proto` and also `b.proto`**.
https://github.com/jagobagascon/grpc-swift-modules-test

### Expected behaviour

grpc compiler should only generate code for explicitly passed protos, not its dependencies.

### Additional information

**This happened in the past and was fixed in [this PR](https://github.com/grpc/grpc-swift/commit/b899330214d013530882d6ff47155e73631fdb64). I think this is a regression added in [this commit](https://github.com/grpc/grpc-swift/commit/248f554e3ce81dec535f6aad18dbc9a85ad5d913)**. 

Unless it was added by some reason, I think that reverting back to the change made by the PR should fix this problem.

**Comment by glbrntt** [comment]
Agh, sorry for regressing this @jagobagascon.

**Comment by jagobagascon** [comment]
Thank you for the quick response!

**Comment by jagobagascon** [comment]
Hi! This issue is messing with our automated build (the code does not compile) and we want to avoid using a specific commit so, is it too much to ask for an `alpha.22` release? 😇
Anyway it would be really helpful to know when it's planned. To add a temporary fix or just wait for the release.

Thanks!

**Comment by glbrntt** [comment]
There are a couple of outstanding PRs which I'd like to get merged then I'll happily tag a release for you. ETA is next couple of days if that's not too big a problem for you?

**Comment by jagobagascon** [comment]
Two days is completely acceptable 😄 . Thank you very much!

**Comment by glbrntt** [comment]
@jagobagascon done! Thanks for your patience with this one.
