### ISSUE TITLE
How to get this working with iOS project

### ISSUE THREAD

**Issue by ldelossa** [grpc/grpc-swift#106]
Hello,

I'm not too familiar with iOS development however I'm trying to bridge the gap between gRPC services I've written on the backend and an iOS front end. I typically use xcode to init my project, as it creates the AppDelegate and initial ViewController folder. I'm attempting to integrate this package into a Single View Application template. I have tried the following:

* Cloned this repo into a location on my workstation "/opt/grpc-swift"
* ran Make at the root directory
* Clicked and dragged the SwiftGRPC.xcodeproj folder into the project navigation on the left of xcode

I have created the generated code with the protoc-gen-swift* plugins without a problem so far, however the generated code cannot find the "gRPC" module and I get errors about finding this package. Can anyone assist ? I am not sure if using this library in an iOS project is completely supported.

**Comment by takasek** [comment]
You need to do:

- Set a path to `CgRPC/include` to `Header Search Paths` 
    - refer to https://github.com/grpc/grpc-swift/issues/44#issuecomment-310936047
- Delete `zlib-example` from TARGETS 
    - refer to https://github.com/grpc/grpc-swift/issues/100#issuecomment-354943475

**Comment by MrMage** [comment]
Also see https://github.com/grpc/grpc-swift/issues/218#issuecomment-412986474.
