### ISSUE TITLE
Conflict using Firestore and a Pod using gRPC-Swift as a dependency its podspec file

### ISSUE THREAD

**Issue by nshoura** [grpc/grpc-swift#1067]
### What are you trying to achieve?

Use `gRPC-Swift` as a dependency in a `.podspec` file of a Pod, let's call it `X`, and use `X` in a project where `Firebase/Firestore` is used as well:

Project's `Podfile`:

```
target '<Project name>' do
  use_frameworks!

  pod 'Firebase/Firestore'
  pod 'X'
end
```

`X.podspec` file:
```
Pod::Spec.new do |spec|
  spec.name = "X"
  spec.dependency 'gRPC-Swift', '1.0.0-alpha.21'
end
```

This results in the same problem mentioned in this [issue](https://github.com/grpc/grpc-swift/issues/915).

### What have you tried so far?

I have tried the solution mentioned [here](https://github.com/grpc/grpc-swift/pull/945#issuecomment-676051018). However, this solution doesn't work when `gRPC-Swift` is used as a dependency for another pod since, in podspec files, it's only allowed to define the name and the version specifier of a Pod and it's not possible to provide a specific `podspec` file. Basically, the following isn't valid in a `podspec` file: `s.dependency 'gRPC-Swift', :podspec => 'gRPC-Swift.podspec'`

**Comment by glbrntt** [comment]
Unfortunately I don't think we have a solution for this. It boils down to the fact that module name for one of the pods from https://github.com/grpc/grpc is 'grpc' while our module name is 'GRPC'. Changing either of these names isn't really feasible for either project at this point.

**Comment by nshoura** [comment]
In case anyone is struggling with this, I've fixed it by running a script after the pods are installed to use the custom `gRPC-Swift`module name in the Pod that has a dependency on `gRPC-Swift`:

```ruby
post_install do |installer|

  string_to_replace = "import GRPC"
  string_replacement = "import <gRPC-Swift custom module name>"

  # Find all ruby files in this directory and its subdirectories.
  Dir.glob('./Pods/<The name of the Pod depending on gRPC-Swift>/**/*.swift').each do |file|

    # Read the file and store the contents in memory.
    content = File.read(file)
    # Don't do anything if the file doesn't include "import GRPC".
    next unless content.include?(string_to_replace+"\n")
    # Unlock the file to enable writing to it.
    File.chmod(0600, file)
    # ReWrite the file after replacing "import GRPC" with "import <gRPC-Swift custom module name>".
    File.open(file, 'w+') { |f| f.write(content.gsub(string_to_replace, string_replacement)) }
    # Relock the file.
    File.chmod(0444, file)
  end
end
```

**Comment by Artfire** [comment]
@nshoura hi,

Thanks for your solution but I want to clarify one moment. For me:
`post_install do |installer|`
will not be called, because I have 
`[!] The 'Pods-MyProject' target has frameworks with conflicting names: grpc.`
before `post_install do |installer|` will be executed and the script stops.

For example here is Podfile where I want to test that `post_install do |installer|` is executed.
SkarbSDK depends on `gRPC-Swift`:
```
platform :ios, '11.2'

target 'MyProject' do
  use_frameworks!
  pod 'Firebase/Firestore'
  pod 'SkarbSDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
```
If I run `pod install` I will not see the output for the project targets, because in terminal I see`[!] The 'Pods-MyProject' target has frameworks with conflicting names: grpc.` stops the script. If I comment `pod 'Firebase/Firestore'` or `pod 'SkarbSDK'` the project targets will be printed into terminal.

Any help is appreciated,
Thanks.

**Comment by CureleaAndrei** [comment]
Hi, I am facing the same issue right now. Have you find a solution ?

**Comment by Artfire** [comment]
@CureleaAndrei hi,
I've just use one Firebase with SPM and other with Cocoapods, and it works for me
