### ISSUE TITLE
Should we raise the minimum Swift version?

### ISSUE THREAD

**Issue by glbrntt** [grpc/grpc-swift#1072]
### Should we raise the minimum Swift version?

Raising the minimum supported language version has a few benefits: we unlock new language features and lessen the support burden. One downside is that it's a SemVer major breaking change, so if at all, we should do this before 1.0.0.

#1070 raises the minimum supported version from 5.0 to 5.1; this is a pretty safe bet, you have to be using Xcode 10 to not meet this requirement.

I'm interested to hear whether users would object if the minimum Swift version was raised further to either 5.2 or 5.3?

**Comment by glbrntt** [comment]
cc @MrMage @SebastianThiebaud @IgorRosocha @daltonclaybrook @decanus @FranzBusch

**Comment by decanus** [comment]
@glbrntt fine by me

**Comment by daltonclaybrook** [comment]
No objections from me. My team is on 5.3.

**Comment by MrMage** [comment]
👍 from me.

**Comment by IgorRosocha** [comment]
Fine for our team also, we are on 5.3. 🙂

**Comment by mRs-** [comment]
Would be okay for us as well (currently on 5.3)
