### ISSUE TITLE
Stream stops receiving messages after changing connection from one wifi to another

### ISSUE THREAD

**Issue by datmassdevs** [grpc/grpc-swift#1088]
I updated grpc-swift to the latest version

You can see that it looks like issue #337 but here's another case.

When I change the iphone connection from wifi to another wifi, the stream stops reveiving message from server.
In my case, when I changed connect and I called the request, it took a long time for it to reconnect to run as normal.
I'm not sure why? Do you have a way for me to restart the stream after changing the connection?

**Comment by glbrntt** [comment]
No; it's a new connection and a new RPC so you're responsible for creating the new stream.

**Comment by dannyhertz** [comment]
@glbrntt Super late to the party here, but I've been working on making my GRPC abstraction layer is more resilient across network connectivity changes. Im still a bit confused as to whether an entirely new connection/channel needs to be creating or just existing calls need to be restarted. Any help is appreciated!
