### ISSUE TITLE
Project with GRPC dependencies not build from commandline

### ISSUE THREAD

**Issue by ibaho** [grpc/grpc-swift#1099]
SPMs for SwiftNIO builds in wrong order 

Steps to reproduce:
1. Create new project
2. File -> Swift packages -> add package dependency Use https://github.com/grpc/grpc-swift.git exact Swift 1.0.0-alpha.21
3. build in XCode. Build succeeded
4. close xcode 
5. run terminal 
6. Goto folder with project cd ~/projects/<use your path>/
7. Run xcodebuild

Actual result:
Library/Developer/Xcode/DerivedData/MultiScreen-gstsxmaaiuzazmcmkxnwlwsczybn/SourcePackages/checkouts/swift-nio-transport-services/Sources/NIOTransportServices/NIOFilterEmptyWritesHandler.swift:15:8: error: no such module 'NIO'
import NIO

BUILD FAILED **

xcode 12.3

**Comment by glbrntt** [comment]
Without arguments `xcodebuild` will build a target, I think you need to specify your scheme when you invoke it: `xcodebuild -scheme WhateverYourSchemeIsCalled`
