### ISSUE TITLE
Cocoapods build configuration (Podspec is broken)

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#11]
I've put an initial podspec in `SwiftGRPC.podspec` and put a reference to it in `Examples/Speech/Podfile`. Attempting to build it has a few problems:

1. `#import "internal.h"` needs to be removed from the automatically-generated `SwiftGRPC-umbrella.h`. 
2. The CgRPC code refers to `grpc_slice` and the latest tagged version of gRPC-Core uses the older `gpr_slice`.

**Comment by MrMage** [comment]
Have a look at the `s.public_header_files` line in https://github.com/MrMage/grpc-swift/commit/9f2c674ab52464815a61397b9828bbc4ec8bff93 on how to remove `#import "internal.h"` from the umbrella header. Happy to send a pull request once others have confirmed that spec to be working for them.
