### ISSUE TITLE
Public key pinning support in grpc-swift

### ISSUE THREAD

**Issue by Akanksha-nuclei** [grpc/grpc-swift#1104]
### What are you trying to achieve?

SSL Pinning can be achieved using Certificate pinning or public key pinning. I found there is support for  [certificate pinning](https://medium.com/@ambrose12silveira/ios-swift-grpc-integration-with-tls-client-authentication-f2e2164ed125) in grpc-swift but it has a downside that if the server rotates its certificate on a regular basis, then the application would need to be updated regularly.  

Is there any support for **public key pinning** in grpc-swift?

**Comment by Lukasa** [comment]
Currently there is not, no. What form of public key pinning did you have in mind?

**Comment by Akanksha-nuclei** [comment]
Attaching the code snippet of how we have achieved using rest+swift. We are trying to achieve the same thing using grpc. We do not know how to get certificate from the server and then retrieve the public key from it. Do let me know how i can achieve this in grpc?

func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        
        // if url is exists in ignore list, just disable pinning verification
        if ignorePinningHostList.contains(challenge.protectionSpace.host) {
            completionHandler(.useCredential, nil)
            return
        }
        
        if (challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust) {
            
            if let serverTrust = challenge.protectionSpace.serverTrust {
                
                var secresult = SecTrustResultType.invalid
                let status = SecTrustEvaluate(serverTrust, &secresult)
                
                if(errSecSuccess == status) {
                    // getting certificate from server
                    if let serverCertificate = SecTrustGetCertificateAtIndex(serverTrust, 0) {
                        
                        // Public key pinning
                        if #available(iOS 10.3, *) {
                            let serverPublicKey = SecCertificateCopyPublicKey(serverCertificate)
                            let serverPublicKeyData: NSData = SecKeyCopyExternalRepresentation(serverPublicKey!, nil )!
                            let keyHash = sha256(data: serverPublicKeyData as Data)
                            let publicKeyHashes = URLSessionPinningDelegate.manager.pinnedPublicKeyHashes
                            
                            let pinningSucceeded = publicKeyHashes.contains(keyHash)
                            if pinningSucceeded == true {
                                completionHandler(.useCredential, URLCredential(trust:serverTrust))
                                return
                            } else {
                                // Pinning failed
                                completionHandler(.cancelAuthenticationChallenge, nil)
                                return
                            }
                        }
                    }
                }
            }
        }
        
        // Pinning failed
        completionHandler(.cancelAuthenticationChallenge, nil)
    }

**Comment by Lukasa** [comment]
Ok, so it seems like what you're looking for can likely be done with #1107.
