### ISSUE TITLE
Why I should rename `protoc-gen-grpc-swift` to `protoc-gen-swiftgrpc`

### ISSUE THREAD

**Issue by hamedaakhlaghi** [grpc/grpc-swift#1108]
### What are you trying to achieve?
I want to generate .swift file with this command `protoc api.proto --swiftgrpc_out=.` 

### What have you tried so far?

I ran `make plugins`, the generated file was `protoc-gen-grpc-swift`
I copied this file to `/usr/local/bin`
after running `protoc api.proto --swiftgrpc_out=.` the error is:
``
protoc-gen-swiftgrpc: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
``
with renaming  `protoc-gen-grpc-swift` to `protoc-gen-swiftgrpc` I can generate .swift file!

What is the problem? Is it OK or I should change something?

**Comment by glbrntt** [comment]
In general, the options for protoc follow the name of the plugin that is being used. For example if the plugin is called `protoc-gen-foo` then the output option would be `--foo_out`. Here the plugin is `protoc-gen-grpc-swift` so the output option should be `--grpc-swift_out`.

In your case you're renaming the plugin to match your option, that works, but it's a bit backwards.
