### ISSUE TITLE
failing to build on Simulator - Apple Silicon

### ISSUE THREAD

**Issue by moh-abk** [grpc/grpc-swift#1109]
### Describe the bug

I just switched to M1 and Unable to run my app in Simulator. Runs correctly on apple device.

### To reproduce

Using an Apple M1 mac, attempt to build and run project on simulator.
Installed via cocoapods - `pod 'gRPC-Swift', '1.0.0-alpha.22'`

`could not find module 'GRPC' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator`

### Expected behaviour

App should run correctly on simulator

### Additional information

Runs correctly on Intel Mac

**Comment by Lukasa** [comment]
This project absolutely does work just fine in the iOS simulator on M1 Macs. Can I recommend trying to throw away your derived data and rebuilding?

**Comment by moh-abk** [comment]
> This project absolutely does work just fine in the iOS simulator on M1 Macs. Can I recommend trying to throw away your derived data and rebuilding?

let me try that now

**Comment by moh-abk** [comment]
Still no joy @Lukasa - when I try to navigate to the definition I get this;

![image](https://user-images.githubusercontent.com/7813457/105338937-06c99280-5bd4-11eb-9dcd-af52cd360190.png)

Also how can I add this package via SPM and specify the alpha version?

**Comment by glbrntt** [comment]
> Also how can I add this package via SPM and specify the alpha version?

- File > Swift Packages > Add Package Dependency... > (enter the URL for the repo) 
- Select "Exact" from the drop down

<img width="709" alt="Screenshot 2021-01-21 at 10 51 46" src="https://user-images.githubusercontent.com/5047671/105341202-b7d12c80-5bd6-11eb-8a4e-92426b26594e.png">

**Comment by Davidde94** [comment]
@moh-abk `.package(url: "https://github.com/grpc/grpc-swift.git", from: "1.0.0-alpha.21")`

**Comment by moh-abk** [comment]
Resolved by opening xcode with Rosetta. Seems to be a cocoapod issue.
