### ISSUE TITLE
Unsafe build flags in Package

### ISSUE THREAD

**Issue by alexlaurinmath** [grpc/grpc-swift#1112]
### Describe the bug

MacOS 11.1
Xcode 12.3
Swift 5

Importing swift-grpc as a Package.

On build getting this error: `The package product 'SwiftGRPC' cannot be used as a dependency of this target because it uses unsafe build flags.`

### To reproduce

1. Import swift-grpc as a Package.
2. Build.

**Comment by alexlaurinmath** [comment]
The only funny business I see in the Package declaration that might cause this is
```
    .target(
      name: "CGRPCZlib",
      linkerSettings: [
        .linkedLibrary("z"),
      ]
    ),
```

**Comment by alexlaurinmath** [comment]
Getting this as well on:
MacOS 10.15
Xcode 12.1

**Comment by alexlaurinmath** [comment]
I removed the target mentioned above and I was able to build and run. I have not tested making actual network requests.

**Comment by glbrntt** [comment]
The `SwiftGRPC` product is from the 0.x release series.

This snippet is from the Package.swift of the 1.y release series:

> ```
>     .target(
>       name: "CGRPCZlib",
>       linkerSettings: [
>         .linkedLibrary("z"),
>       ]
>     ),
> ```

You should change your dependency rule to be from `1.0.0-alpha.23`.
