### ISSUE TITLE
 Showing Recent Messages Undefined symbol: _GRPC_SHADOW_SSL_get_secure_renegotiation_support

### ISSUE THREAD

**Issue by helmitaufiqa** [grpc/grpc-swift#1117]
i've tried to install firebase/firestore and getting stuck with this _GRPC_SHADOW_SSL_get_secure_renegotiation_support error. 
Is there anyone who know how to fix it ? Please help me

<img width="690" alt="Screen Shot 2021-01-28 at 13 21 17" src=
<img width="939" alt="Screen Shot 2021-01-28 at 13 21 46" src="https://user-images.githubusercontent.com/51486163/106098575-d6ea3400-616b-11eb-8110-abbd7d4ab2b0.png">
"https://user-images.githubusercontent.com/51486163/106098495-b5894800-616b-11eb-9997-85671aa889e5.png">

**Comment by glbrntt** [comment]
This isn't our code; you should file this against the relevant firebase project, they'll be much better placed to help you: https://github.com/firebase

For what it's worth, this bug looks like it may be related https://github.com/firebase/firebase-ios-sdk/issues/5521
