### ISSUE TITLE
Set ALPN token to h2 by default.

### ISSUE THREAD

**Issue by Lukasa** [grpc/grpc-swift#1124]
It might surprise people to discover that the ALPN tokens aren't set to H2 on some paths (initialising the TLS config from a `TLSConfiguration` directly). Given that we only support the ALPNs we support, we should probably just forcibly set them on all code paths.

**Comment by glbrntt** [comment]
I think it probably makes sense to do this although I'm not 100% sure about doing this for the server. Users _may_ want to only support gRPC-Web, for example. How about only adding the ALPN tokens if none were set in the TLS config. WDYT?
