### ISSUE TITLE
Channel Args support for swift client?

### ISSUE THREAD

**Issue by arnolddrita** [grpc/grpc-swift#113]
We're using gRPC server on GO and our client is written in swift. We've encountered some problems with the message size exceeding the limit, and on our test GO client we were able to solve it by increasing the maximum receive size on the client. 

However I've gone through all of the source generated by the gRPC plugin on swift and I couldn't find a way to pass this parameter as an option, although we were able to easily do this from the GO and PHP client tests.

Does the Swift client support this? 

A temp fix we did was change the code in channel.c to the following:

`
cgrpc_channel *cgrpc_channel_create(const char *address) {
  cgrpc_channel *c = (cgrpc_channel *) malloc(sizeof (cgrpc_channel));
  // create the channel
    grpc_channel_args *channelArgs = gpr_malloc(sizeof(grpc_channel_args));
    channelArgs->num_args = 1;
    channelArgs->args = gpr_malloc(sizeof(grpc_arg));

    grpc_arg *arg = &channelArgs->args[0];
    arg->type = GRPC_ARG_INTEGER;
    arg->key = gpr_strdup("grpc.max_receive_message_length");
    arg->value.integer = -1;

    c->channel = grpc_insecure_channel_create(address, channelArgs, NULL);
    c->completion_queue = grpc_completion_queue_create_for_next(NULL);
  return c;
}
`
Although it would be nice to be able to pass channel arguments from the channel constructor directly on swift (like we do with timeout).

**Comment by timburks** [comment]
Thanks, this seems like a good improvement to make. We'll investigate further.

**Comment by SebastianThiebaud** [comment]
@arnolddrita I think you can close this issue now that `Channel.Argument`s have been added: https://github.com/grpc/grpc-swift/blob/master/Sources/SwiftGRPC/Core/ChannelArgument.swift#L22

Let us know if you still have an issue with this. You might need to open a PR to add a few arguments that would solve your problem, or I'm happy to do so if you can list them.

**Comment by SebastianThiebaud** [comment]
I just created a pull request with a few arguments: https://github.com/grpc/grpc-swift/pull/237

**Comment by timburks** [comment]
Covered by #244

**Comment by mushtaque87** [comment]
Took the latest  
 pod 'SwiftGRPC' 
 pod 'SwiftProtobuf'
version using pod update and it got fixed .

Installing BoringSSL 10.0.6 (was 10.0.5 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing SwiftGRPC 0.5.1 (was 0.4.3 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing gRPC-Core 1.12.0 (was 1.11.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing Realm 3.7.6 (was 3.7.4 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Installing RealmSwift 3.7.6 (was 3.7.4 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)

Then all i need was create the session/service with my certificate.

let certPath = Bundle.main.url(forResource: "XYZ", withExtension: "pem")!
        let certificate = try! String(contentsOf: certPath)
        service = Pronounce_PronounceServiceClient(address: Constants.ServerApi.grpcBaseUrl, certificates: certificate)
