### ISSUE TITLE
Unable to get trailingMetadata 

### ISSUE THREAD

**Issue by piyush97** [grpc/grpc-swift#1135]
### What are you trying to achieve?

I'm trying to retrieve value from trailingMetadata from the result object. 

My trailingMetaData looks like
```swift
trailingMetadata: ["content-security-policy": "default-src \'self\';", "x-permitted-cross-domain-policies": "none", "x-xss-protection": "1; mode=block", "strict-transport-security": "max-age=31536000; includeSubDomains; preload", "x-envoy-upstream-service-time": "281", "grpc-status-details-bin": "\u{08}\r\u{12}\u{16}Please try again later\u{1A}Y\n:type.googleapis.com/com.nuclei.gold.proto.v2.ErrorResponse\u{12}\u{1B}\n\u{01}6\u{12}\u{16}Please try again later", "content-length": "0", "date": "Thu, 11 Feb 2021 13:22:55 GMT", "server": "nginx/1.13.10", "expect-ct": "enforce, max-age=86400, report-uri=https://www.preprod-az-01.gonuclei.com/", "x-content-type-options": "nosniff", "x-frame-options": "DENY", "referrer-policy": "same-origin"]
```

How can I get the value from `grpc-status-details-bin`?

I'm on SwiftGRPC 0.9.0

**Comment by glbrntt** [comment]
You can extract the value with from the metadata by subcripting the metadata, i.e. `callResult.trailingMetadata["grpc-status-details-bin"]` (see https://github.com/grpc/grpc-swift/blob/cgrpc/Sources/SwiftGRPC/Core/Metadata.swift#L121-L131). IIRC by convention "grpc-status-details-bin" is serialized so the `data(forKey:)` API might be what you actually want here (see https://github.com/grpc/grpc-swift/blob/cgrpc/Sources/SwiftGRPC/Core/Metadata.swift#L133-L140)

**Comment by piyush97** [comment]
This is a packed value, how may I unpack it in swift?

**Comment by glbrntt** [comment]
I think it's something along the lines of:

```swift
let bytes = trailingMetadata.data(forKey: "...")
let any = try Google_Protobuf_Any(serializedBytes: bytes)
```
