### ISSUE TITLE
[Flatbuffers] content-type suffix

### ISSUE THREAD

**Issue by mustiikhalil** [grpc/grpc-swift#1137]
Good evening, 

 While working on implementing FlatBuffers support for other programming languages I found out that Go requires the suffix `+flatbuffers` to the `content-type` example: `content-type: application/grpc+flatbuffers`. I was wondering if this is something the library can support? I've dig into the code and found that we might need to change the following enum to support it `ContentType` which won't be a huge issue. since according to the [Https2 protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) the `content-type` should allow any custom suffix if needed.
 
I am willing to implement all the details behind this feature, however I wanted to ask before doing so, since the library might have a different direction and isn't willing to support custom content-type suffix

**Comment by glbrntt** [comment]
I'm okay with adding this.

You're right, adding a case to the `ContentType` is part of this. We also need a way for users to set the value and then tests of course. The easiest way to do this would probably be by using any any value provided in the `customMetadata` and then falling back to "application/grpc" if nothing was provided by the user.

**Comment by mustiikhalil** [comment]
Sounds good to me. I can definitely work on this. This would be the plan:
- [ ] Adding it to the `ContentType` enum.
- [ ] Allowing the user to select the content type they would be sending over the network. 
- [ ] Tests
    - GRPCTests
    - GRPCInteroperabilityTests?

What do you think would be better:

1 - Maybe add a field on the `CallOptions` object itself, and appending it to the `HPACKHeaders` after [init](https://github.com/grpc/grpc-swift/blob/c85a7efe87b6fe5415d95e26f36b05cc5e9bf6f8/Sources/GRPC/CallOptions.swift#L71)
 
```swift
/// example
init(
customMetadata: HPACKHeaders = HPACKHeaders(),
contentType: ContentType = .protoc,
) {
  customMetaData.append((GRPCHeaderName.contentType, contentType.canonicalValue)
}
```

2 - Add it into the `HPACKHeaders`, as in allow the user to append it himself into the `HPACKHeaders` object, then within the code we try to see if there is a `content-type` appended if not, we default to `application/grpc`

**Comment by glbrntt** [comment]
> Sounds good to me. I can definitely work on this. This would be the plan:
> * [ ]  Tests
>   
>   * GRPCTests
>   * GRPCInteroperabilityTests?

Just in `GRPCTests`, the interoperability tests are a standard set of tests described in https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md and don't cover flatbuffers.

> What do you think would be better:
> 
> 1 - Maybe add a field on the `CallOptions` object itself, and appending it to the `HPACKHeaders` after [init](https://github.com/grpc/grpc-swift/blob/c85a7efe87b6fe5415d95e26f36b05cc5e9bf6f8/Sources/GRPC/CallOptions.swift#L71)
> 
> ```swift
> /// example
> init(
> customMetadata: HPACKHeaders = HPACKHeaders(),
> contentType: ContentType = .protoc,
> ) {
>   customMetaData.append((GRPCHeaderName.contentType, contentType.canonicalValue)
> }
> ```
> 
> 2 - Add it into the `HPACKHeaders`, as in allow the user to append it himself into the `HPACKHeaders` object, then within the code we try to see if there is a `content-type` appended if not, we default to `application/grpc`

I think 2.) is fine.

**Comment by mustiikhalil** [comment]
So according to a message I got in the messaging forums for gRPC, it seems that all the languages are actually ignoring the suffix. However, go would be the only language to take that suffix into consideration, so I opened an issue in the [grpc-go](https://github.com/grpc/grpc-go/issues/4213) to see if they can provide a fix by using `content-subtype` that can be appended directly to the custom metadata instead of the `content-type` itself.
