### ISSUE TITLE
Performance of Streaming Calls

### ISSUE THREAD

**Issue by qusc** [grpc/grpc-swift#1138]
### What are you trying to achieve?

I am building a voice call server using gRPC. I'm receiving audio packets (OPUS frames) via a client-side streaming call per call participant and forwarding them on another server-side streaming call per client.
It works well, however, CPU usage is very high. With three participants, I'm seeing about 70% usage both running the server on my MacBook Pro or my AWS EC2 t3a.medium instance. Bandwidth is about 90kbit/s in / out total at about 150 messages per second.

### What have you tried so far?

Just commenting out my 
`context.sendResponse(.with { $0.response = .audioPacket(audioPacket) }, promise: nil)`
call massively reduces my CPU usage to about 17%.
Why does sending 150 messages at about 75 byte each take that much CPU time?

**Comment by weissi** [comment]
@qusc before we start debugging, can you confirm how you compiled your program (and gRPC if compiled separately)? Definitely release mode?

**Comment by qusc** [comment]
I was actually running it in debug configuration, thanks a lot for that hint. CPU usage in the same scenario is now at around 7% on my AWS EC2 t3a.medium instance.

**Comment by weissi** [comment]
@qusc awesome! Does that seem reasonable to you? If yes, please feel free to close this issue.

**Comment by qusc** [comment]
I guess so, don't really have a comparison.
