### ISSUE TITLE
Legacy support : master fails to build

### ISSUE THREAD

**Issue by anighanta** [grpc/grpc-swift#1143]
### What are you trying to achieve?

build fails with `Ambiguous use of 'count'` on line `406` 

`grpc-swift/Sources/GRPC/HTTP1ToGRPCServerCodec.swift:406:75: Ambiguous use of 'count'`

**Comment by glbrntt** [comment]
The `master` branch was renamed to `main` and is no longer supported (I thought it had been removed); switching to `main` should resolve any issues.
