### ISSUE TITLE
Plugin option to generate struct initialisers that require all fields to be initialised

### ISSUE THREAD

**Issue by phlippieb** [grpc/grpc-swift#1144]
### Is your feature request related to a problem? Please describe it.

A powerful effect of using protocol buffers across various platforms is that it can keep all platforms in lockstep in terms of endpoint protocols. If something changes "in the proto", all platforms are to some degree forced to implement the change in their own codebases, to keep it compatible with the generated code (i.t.o. compilation).

However, the way that Swift structs are generated from  Protobuf messages is that all properties are given default values, and an empty public initialiser is added to the struct. For example:

```swift
public struct Aaa_SomeRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var userKey: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}
```

So when we instantiate these generated structs to use in endpoints, we must do property-by-property initialisation. For example:

```swift
// Create and configure a request to send to an endpoint:
var request = Aaa_SomeRequest()
request.userKey = 1
```

If the Protobuf gets extended with a new field, this new field will appear on the updated struct, but there is nothing forcing us to make any changes.

### Describe the solution you'd like

For our needs, it would be better if the generated structs did not contain default values, forcing us to initialise *all* properties of a struct at initialisation. For example, the generated struct could look like this:

```swift
public struct Aaa_SomeRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var userKey: Int64

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init(userKey: Int64) {
    self.userKey = userKey
  }
}
```

So that, if a new field is added in Protobuf, and by extension to the generated Swift struct, our code will fail to build, forcing us to explicitly deal with the change.

My proposal is to add an option to the protc-plugin to toggle between generating structs with and without default values.

I believe this would generally enable developers to write safer code and avoid bugs resulting from things getting out of sync across platforms. I do expect, however, that this would conflict with the generated GRPC code, which probably relies on the default values when populating responses, so I can understand if the cons of this proposal outweigh the pros. Nevertheless, would there be interest in such a feature? I might even attempt to implement it myself.

### Describe alternatives you've considered

I thought that perhaps we could just provide our own initialisers that cover all of the structs' fields, and that this would raise a compile error if a new field gets added that isn't set by our initialiser. However, this doesn't work. When creating a custom initialiser that only inits some of the fields, the project still compiles.

**Comment by glbrntt** [comment]
The `protoc-gen-swift` plugin and message generation is handled by https://github.com/apple/swift-protobuf, this question is much better directed at the folks over there.

**Comment by phlippieb** [comment]
Snap, I didn't even realise that was a separate repo. Looks like there's already been some discussion of the request over on that side. Thanks for pointing me in the right direction 😁
