### ISSUE TITLE
Detect When Client Closes Client-Side Streaming Call

### ISSUE THREAD

**Issue by qusc** [grpc/grpc-swift#1145]
### What are you trying to achieve?

I need to detect server-side inside a client-side streaming call handler function when a client disconnects from the streaming call in order to clean up state / free resources and subscriptions.

### What have you tried so far?

For server-side streaming calls I can subscribe to `context.statusPromise.futureResult` where `context` is a `StreamingResponseCallContext`. This seems to always be called eventually, even if the client (in our case an iOS app) looses connection / is killed. However, for client-side streaming calls the context is of type `UnaryResponseCallContext` which doesn't seem to have a corresponding future that I can subscribe to.

How do I get a callback when the client-side streaming call is closed / connection is lost?

**Comment by glbrntt** [comment]
This isn't possible at the moment. I think we'll have to add some API to the context here so that you can be notified when the RPC is torn down. It'd be best if we add this for all RPC types so there's a clear and consistent way to do this.
