### ISSUE TITLE
How to call send from receive(ClientInterceptor)

### ISSUE THREAD

**Issue by VorobyevS** [grpc/grpc-swift#1154]
### What are you trying to achieve?

Make token auto refresh interceptor

### What have you tried so far?

Is it even possible? Interceptors tutorial is not considering this option. How could i send "again" my request?

``` swift
override func send(_ part: GRPCClientRequestPart<Request>,
                       promise: EventLoopPromise<Void>?,
                       context: ClientInterceptorContext<Request, Response>) {
        switch part {
        case .metadata(var headers):
            let defaultHeaders: [(String, String)] = [
                (HeaderKeys.acceptLanguage.rawValue, Locale.current.languageCode ?? String()),
                (HeaderKeys.authorization.rawValue, keychainStorage.token ?? String())
            ]
            headers.add(contentsOf: defaultHeaders)
            context.send(.metadata(headers), promise: promise)
        default:
            context.send(part, promise: promise)
        }
    }
    
    override func receive(_ part: GRPCClientResponsePart<Response>,
                          context: ClientInterceptorContext<Request, Response>) {
        guard case let GRPCClientResponsePart.end(status, _) = part,
              status.code == .unauthenticated else {
            context.receive(part)
            return
        }
        networkService.refresh {[weak self] response in
            context.eventLoop.execute {
                switch response {
                case .success:
                    self?.send(GRPCClientRequestPart<Request>.metadata(HPACKHeaders()),
                               promise: nil,
                               context: context)
//                    context.send(GRPCClientRequestPart<Request>.metadata(HPACKHeaders()),
//                                 promise: nil)
                case .failure(let err):
                    context.receive(part)
                }
            }
        }
    }
```

**Comment by glbrntt** [comment]
This is possible, it's just a little harder to do!

The main point to know is that using the `context` is tied to a single RPC, so the `self?.send`/`context.send` in your example code would be sending headers on the RPC which has already ended with the `unauthenticated` status. 

Instead you need to start a _new_ RPC within the interceptor and direct any responses back to the original call. This will be a lower level `Call` (as opposed to `UnaryCall`, `ClientStreamingCall` etc) for which the `context` provides enough information to construct. As such the interceptor also needs a connection (something conforming to `GRPCChannel`) to make that call.

There's an interceptor in the tests which is quite similar to what you need and should illustrate what I've described above: https://github.com/grpc/grpc-swift/blob/7a75c81f9a1c2a7800df1a3c861942f5d2f7b796/Tests/GRPCTests/InterceptorsTests.swift#L205-L306

**Comment by glbrntt** [comment]
No problem.
