### ISSUE TITLE
WatchOS guidance + support

### ISSUE THREAD

**Issue by arctouch-lauracarvalho** [grpc/grpc-swift#1170]
### What are you trying to achieve?

We're trying to communicate with a grpc server via a watch app for iOS application.

### What have you tried so far?
We did the setup via CocoaPods:

`pod 'SwiftProtobuf', '~> 1.0'`
`pod 'gRPC-Swift', '~> 1.0.0'`

We generated the client and server code using the `protoc` plugins.
We're working with a secure connection, so we're setting the client connection as
`ClientConnection.secure(group: someLoopGroup)`
and setting custom metadata with auth token to the service call, via CallOptions

Using the exact same code with:

- An iPhone application both simulator and physical device - grpc communication success
- A watchOS simulator - grpc communication success
- A physical watch we are facing 2 issues

1. We got a crash while instantiating the `SocketChannel` in SwiftNIO
   I was able to debug it and the crash is an Int overflow exception happening at line 65 of `RecvByteBufferAllocator.swift`.
   Its running in an infinite loop as the while condition isn't met because at round 54 (or 55) `i` receives a negative value and in the next interaction it becomes `0`.
   
  After adding a local fix to this issue (I've added a `i > 0 ` stop condition to the `while` block), we faced a 2nd issue
  
  2. we kept receiving the following log and the grpc communication never happens
  ```
  2021-05-05T14:00:26-0300 info : grpc_connection_id=205C4DF9-4B9E-4042-A0B3-F8E79A7016A0/0 old_state=connecting new_state=transientFailure connectivity state change
 2021-05-05T14:00:27-0300 info : old_state=transientFailure grpc_connection_id=205C4DF9-4B9E-4042-A0B3-F8E79A7016A0/1 new_state=connecting connectivity state change
   ```
  
So about the SwiftNIO crash, I've looked at the open issue and I haven't found anything related to it or to the watchOS specifically. Do you have any guidance on how to solve it?
   
About the grpc connection status we took a look at the suggestion given at https://github.com/grpc/grpc-swift/issues/853 but our app isn't a media streaming application.
We are asking for some guidance from you:

- are we able to rely on this library to perform gRPC calls on an Apple Watch running Watch OS 7.1+ once a fix for the crash is implemented?
- What would be the correct implementation to solve our problems with the connectivity state in an app that is not intended to support media streaming?

**Comment by Lukasa** [comment]
If your app is not a media streaming application then general purpose networking is not available on watchOS, and grpc-swift cannot function. You require the media streaming exemption to get this to work.

You will need to delegate this functionality to your iOS app and use WatchConnectivity to transfer data between the two apps.

**Comment by Lukasa** [comment]
Regarding the crash, this is to be fixed here: https://github.com/apple/swift-nio/issues/1848.

**Comment by arctouch-lauracarvalho** [comment]
Thank you for the quick response @Lukasa!
Very happy to know that the crash will also be fixed!

**Comment by dannyhertz** [comment]
@arctouch-lauracarvalho hey! Was curious if you ever made progress with getting grpc working on watchOS?

**Comment by arctouch-lauracarvalho** [comment]
Hey @dannyhertz! We end up going with another approach in our project, since it isn't a media streaming app. So we didn't make more progress working with grpc on watchOS.
