### ISSUE TITLE
Forwarding intecepted calls in an async callback

### ISSUE THREAD

**Issue by Pante** [grpc/grpc-swift#1181]
I'm currently trying to attach an authentication token from Firebase to a header in a `ClientInterceptor`. The problem is that Firebase authentication is asynchronous in design and I'm not sure if it's safe to attach headers and forward calls to the next interceptor outside of the `send(...)` method and in an asynchronous callback. I tried reading through the [`Echo`](https://github.com/grpc/grpc-swift/tree/main/Sources/Examples/Echo) example and the issues but I couldn't find anything related. Any advice is appreciated.

**Comment by glbrntt** [comment]
Interceptor context functions (i.e. send/receive) **must** be called on the `eventLoop` that the interceptor is invoked on (i.e. `context.eventLoop`). Doing asynchronous work is fine so long as the resulting headers are forwarded from the right `eventLoop` (you can use `context.eventLoop.execute { ... }`). 

You'll also have to make sure that within your interceptor you appropriately buffer any request parts to ensure that request parts are sent in the correct oder (i.e. you could receive a request message to send before the asynchronous code to fetch a token has completed).

---

See also the client interceptor documentation:

https://github.com/grpc/grpc-swift/blob/680f34ce47e06b9b77e9c27adb9b14b1c3df39f0/Sources/GRPC/Interceptor/ClientInterceptors.swift#L44-L50
