### ISSUE TITLE
Always connectivity.state == .idle, cannot get response

### ISSUE THREAD

**Issue by Derekkaoo** [grpc/grpc-swift#1182]
### What are you trying to achieve?

I am trying to get response from server side which give me proto file.

### What have you tried so far?

**library and protoc plugin versions: libprotoc 3.15.8**

I created a class as below, do not know if something wrong with it, or something I did not achieve.
`

class RPCTest {
    
    private let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
    private var channel: ClientConnection?
    private var client: App_AuthServiceClient?
    
    init(host: String, port: Int) {
        let configuration = ClientConnection.Configuration(target: .hostAndPort(host, port), eventLoopGroup: group)
        let channel = ClientConnection.insecure(group: group).connect(host: host, port: port)
        
        self.channel = channel
    }
    
    func makeRPCCall(with username: String, with password: String) {
        guard let connection = self.channel, channel?.connectivity.state == .ready else {
            print("current state:", channel?.connectivity.state)
            return
        }
        
        if self.client == nil {
            self.client = App_AuthServiceClient(channel: connection)
        }
        guard let client = self.client else {
            print("SERVICE HASN'T BEEN CREATED YET")
            return
        }
        var request = App_LoginReq()
        request.username = username
        request.password = password
        
        print("REQUEST MESSAGE \(request)")
        
        let call = client.login(request)
        call.response.whenSuccess { (response) in
            print("CALL SUCCESS WITH RESPONSE \(response)")
        }
        call.response.whenFailure { (error) in
            print("CALL FAILED WITH ERROR \(error)")
        }
        do {
            let status = try call.status.wait()
            print("CALL STATUS \(status)")
        } catch {
            print("EXAMPLE FAILED WITH ERROR \(error)")
        }
    }
}

`

Here is print out.
`current state: Optional(GRPC.ConnectivityState.idle)`

My step as below:

`cd grpc-swift`
`make plugins`
`sudo cp protoc-gen-grpc-swift protoc-gen-swift /usr/local/bin`
`cd <proto path>`
`protoc --swift_out=. auth_svc.proto`
`protoc --grpc-swift_out=. auth_svc.proto`

Then I just drage grpc.swift and pb.swift in my project.
Is there anything I did not achieve? 

Thanks for advising.

**Comment by Lukasa** [comment]
Don't wait for the channel to become ready before you make an rpc: make an rpc, as that will force the channel to become ready. grpc-swift will manage the channel lifetime for you, and so you are not expected to make decisions based on its state: just try to make the RPC and grpc-swift will handle it for you.

**Comment by Derekkaoo** [comment]
> Don't wait for the channel to become ready before you make an rpc: make an rpc, as that will force the channel to become ready. grpc-swift will manage the channel lifetime for you, and so you are not expected to make decisions based on its state: just try to make the RPC and grpc-swift will handle it for you.

Hi Lukasa,

Thanks for replying.
Could you give me some advice for making an rpc?

Thanks!

**Comment by Lukasa** [comment]
The call to `client.login` is an RPC. Simply delete the section that does:

```
    guard let connection = self.channel, channel?.connectivity.state == .ready else {
        print("current state:", channel?.connectivity.state)
        return
    }
```

**Comment by Derekkaoo** [comment]
> The call to `client.login` is an RPC. Simply delete the section that does:
> 
> ```
>     guard let connection = self.channel, channel?.connectivity.state == .ready else {
>         print("current state:", channel?.connectivity.state)
>         return
>     }
> ```

Hi Lukasa,

Actually, I have tried to do that, but I cannot see anything in log...
I guess it stuck somehow.

**Comment by Lukasa** [comment]
It's not clear to me that you have configured a logger. Can you try configuring a logger? https://github.com/grpc/grpc-swift/blob/main/docs/faqs.md#is-logging-supported.

**Comment by Derekkaoo** [comment]
> It's not clear to me that you have configured a logger. Can you try configuring a logger? https://github.com/grpc/grpc-swift/blob/main/docs/faqs.md#is-logging-supported.

Hi Lukasa, 

This is my first time to use SwiftLog sdk, just do some survey that I need to get 'ClientConnection.Builder.withBackgroundActivityLogger', is it correct?
But do not have idea how to implement it, I install SwiftLog, though.

Thanks for your reply!

**Comment by t089** [comment]
Maybe also check how you use your `RPCTest` class. If you don't wait for the callback, your process might exit before it received a response? You can try to block your test method for now:

```
let call = client.login(request)
let response = try! call.response.wait()
print("CALL SUCCESS WITH RESPONSE \(response)")
```

**Comment by Derekkaoo** [comment]
> let call = client.login(request)
> let response = try! call.response.wait()
> print("CALL SUCCESS WITH RESPONSE \(response)")

Hi t089,

Thanks for your reply!

I use class like this 
`let rpc = RPCTest(host: "bochat-grpc.52g63x.com", port: 443)
  rpc.makeRPCCall(with: "jimtest001", with: "000000")
`

It is not print out anything if I try your method above, does it mean it exit before it received response?
How can I improve it for encountering this issue?

Thanks!

**Comment by glbrntt** [comment]
> This is my first time to use SwiftLog sdk, just do some survey that I need to get 'ClientConnection.Builder.withBackgroundActivityLogger', is it correct?

That's correct. You can also set `logger` in the `CallOptions` for the call (this will log request specific information):

```swift
let logger = ...
let callOptions = CallOptions(logger: logger)
let call = client.login(request, callOptions: callOptions)
```

Note also that you can raise the log level when you create a logger so that more information is logged:

```swift
var logger = Logger(label: "...")
logger.logLevel = .trace
```

---

It also looks like you're expecting TLS (port 443) but you're using an `insecure` (e.g. plaintext) connection. If you're using TLS you'll need to change `ClientConnection.insecure(group: group)` to `ClientConnection.secure(group: group)`.

**Comment by Derekkaoo** [comment]
> insecure

Hi glbrntt,

Thank you so much!

I finally got response after changed to `ClientConnection.secure(group: group)`.

Cheers!
