### ISSUE TITLE
Get the serviceName in Service discovery

### ISSUE THREAD

**Issue by mengxiangyue** [grpc/grpc-swift#1183]
### What are you trying to achieve?
When I am creating the client, I want to use service discovery to get the service name. But I need to create `Client` then I can get the service name, if I want to create `Client` I need to use host/port to create a channel, at here I need to use service name to get host. it become a cycle. could you give a suggestion?

```
// Configure the channel, we're not using TLS so the connection is `insecure`.
let channel = ClientConnection.insecure(group: group)
  .connect(host: "localhost", port: self.port) // I need to use service name to get the host/port

// Provide the connection to the generated client.
let greeter = Helloworld_GreeterClient(channel: channel)
```

**Comment by glbrntt** [comment]
I suspect the correct way of resolving this is to generate some `static` metadata for each service and integrate with [swift-service-discovery](https://github.com/apple/swift-service-discovery). However, that'll take a little bit of time.

---

As a workaround for the meantime you can create a no-op client to get the service name by creating something which conforms to `GRPCChannel`: 

```swift
struct NoOpChannel: GRPCChannel {
  func makeCall<Request: SwiftProtobuf.Message, Response: SwiftProtobuf.Message>(
    path: String,
    type: GRPCCallType,
    callOptions: CallOptions,
    interceptors: [ClientInterceptor<Request, Response>]
  ) -> Call<Request, Response> { 
    fatalError()
  }

  func makeCall<Request: GRPCPayload, Response: GRPCPayload>(
    path: String,
    type: GRPCCallType,
    callOptions: CallOptions,
    interceptors: [ClientInterceptor<Request, Response>]
  ) -> Call<Request, Response> {
    fatalError()
  }

  func close() -> EventLoopFuture<Void> { 
    fatalError()
  }
}
```

Then you can extract the service name for service discovery:

```swift
let noOpGreeter = Helloworld_GreeterClient(channel: NoOpChannel())
let serviceName = noOpGreeter.serviceName
```

I appreciate that it's not the nicest solution but it should at least unblock you!

**Comment by mengxiangyue** [comment]
@glbrntt thanks your response so fast, what do you think if we change the `serviceName` into static property?

**Comment by glbrntt** [comment]
> @glbrntt thanks your response so fast, what do you think if we change the `serviceName` into static property?

Unfortunately we can't just make it `static` since we'd effectively be breaking the API. 

We'd most likely want to generate some static service metadata alongside the protocol and then add a static property with a default implementation to the generated protocol, something like:

```swift
protocol Echo_EchoClientProtocol: GRPCClient {
  // existing
  var serviceName: String { get }
  
  // ... 
  // RPC definitions
  // ...

  // new:
  static var metadata: GRPCServiceMetadata { get }
}

extension Echo_EchoClientProtocol {
  // new, default impl.
  static let metadata = GRPCServiceMetadata(name: "echo.Echo")
}
```

**Comment by weissi** [comment]
@glbrntt couldn't we just add a static one?

**Comment by mengxiangyue** [comment]
agree with you we can't break the api. I also have another question, I don't find the `GRPCServiceMetadata` in current code, will it like this?
```
struct GRPCServiceMetadata {
  let name: String
  let version: String
  ......
}
```

**Comment by glbrntt** [comment]
> @glbrntt couldn't we just add a static one?

We could, but it might just be more useful to have a more complete set of metadata (i.e. include RPCs as well).

**Comment by glbrntt** [comment]
> agree with you we can't break the api. I also have another question, I don't find the `GRPCServiceMetadata` in current code, will it like this?
> 
> ```
> struct GRPCServiceMetadata {
>   let name: String
>   let version: String
>   ......
> }
> ```

It doesn't exist yet! It could look something like that, it could also include other info like RPC metadata (i.e. name, request type, response type, whether the RPC streams requests or responses etc.). I'm just thinking out loud at this point though.

**Comment by glbrntt** [comment]
The 1.8.0 release adds support for this. See https://github.com/grpc/grpc-swift/blob/703d3515458ea39ff32e05362f7eabff1600839c/Sources/Examples/Echo/Model/echo.grpc.swift#L387-L424 as an example.
