### ISSUE TITLE
Codegen is broken by `1ac79549`

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#119]
The commit 1ac7954952cfde9c1468dff64edb1a7f3fd12e27 (from 8 days ago) adds final attributes to many classes, including

`{{ access }} final class {{ .|service:file,service }}Session {`

in `Plugin/Templates/server.swift`. Unfortunately, e.g.

`{{ access }} final class {{ .|session:file,service,method }} : {{ .|service:file,service }}Session {`

in `Plugin/Templates/server-session-unary.swift` inherits from just that session class, which breaks building files generated with the current codegen. I'd suggest removing the `final` attribute from `Plugin/Templates/server.swift` to resolve that.

/cc @takasek

**Comment by vincentmarguerie** [comment]
I made a fix ( pull request #116 ), waiting for merge

**Comment by MrMage** [comment]
Thanks for pointing this out, I forgot to look for existing pull requests.
