### ISSUE TITLE
Echo sample broken (problems building grpc core on MacOS)

### ISSUE THREAD

**Issue by johndpope** [grpc/grpc-swift#12]
SwiftProtobufRuntime
<img width="559" alt="screen shot 2017-01-08 at 19 56 50" src="https://cloud.githubusercontent.com/assets/289994/21755676/8ce9e6ae-d5e5-11e6-86c3-227a70ed7ee2.png">

for the thirdparty/RUNME.sh file in
perhaps some tweaks...

#!/bin/sh
git clone https://github.com/apple/swift-protobuf.git
cd swift-protobuf
make install
cd ..
git clone https://github.com/grpc/grpc.git
cd grpc
git submodule update --init
make install
# TODO - comment out the problematic CPPFLAGS error line.

**Comment by soffes** [comment]
I couldn't figure out how to get it compile either.

Making an empty Xcode project with the following Podfile wouldn't compile either:

```ruby
use_frameworks!

target 'App' do
  pod 'SwiftGRPC', git: 'https://github.com/grpc/grpc-swift'
end
```

**Comment by timburks** [comment]
Sorry about the confusion - the podfile isn't working yet. I've renamed it until its problems are sorted out.
So far, I've been building in two ways:
1. With the Echo sample xcode project
2. With the Swift Package Manager
Both require a separate build and installation of the grpc library.

**Comment by soffes** [comment]
@timburks do you have instructions somewhere? I tried to figure this out for ~30 minutes yesterday without success.

**Comment by timburks** [comment]
@soffes Notes on building grpc are in the main README of this repo. 

I'll write up a full walkthrough of the Swift Package Manager version, but here's a short form:

If you've built the grpc library (in third_party) with `make; make install`, then I would expect that you could go to `Examples/Echo/Swift/SwiftPM` and run "make" to build the executable. Directly running "swift build" will fail because some compiler and linker options are required (see the Makefile for these). Then you'll have a binary in `.build/debug/Echo`. Run it once with `.build/debug/Echo serve &` to start the server and then again with `.build/debug/Echo get`, `.build/debug/Echo expand`, `.build/debug/Echo collect`, and `.build/debug/Echo update` to exercise the different gRPC streaming styles.

**Comment by timburks** [comment]
@johndpope gRPC core is now vendored for building with the Swift Package Manager, and I've generated an Xcode project from `swift package generate-xcode`. The Echo Mac app now uses this project (`SwiftGRPC.xcodeproj`). Does this work for you? Thanks!

**Comment by johndpope** [comment]
seems like the runme.sh branch is out of date. I tried updating to latest master - but now xcode 8.3 is crashing. was going to submit PR.....

fyi - I'm thinking docker would be good candidate to house the go grpc server project with an exposed port. Just need to add

EXPOSE 9000

and fire up the the go sample on boot. 
from there - 
the echo client code can easily hit the docker container by pointing to 0.0.0.0:9000

**Comment by johndpope** [comment]
case in point - https://github.com/thammegowda/tensorflow-grpc-java
(I've always wanted to use this project in conjunction with tensorflow)
When I find time,  I'm going to fire up that service swift class and test that stencil code generation. Presumably - it's all working.

**Comment by johndpope** [comment]
FYI - found this today/ Xgen 
Built for playgrounds code generation / but potentially could be used for wider things.
Need to have a crack at services layer. 
https://github.com/JohnSundell/Xgen/blob/master/Tests/XgenTests/XgenTests.swift

**Comment by johndpope** [comment]
@timburks - fyi https://github.com/SwiftGen/StencilSwiftKit

**Comment by timburks** [comment]
gRPC code is now vendored-into the project and built with Swift Package Manager (or a generated Xcode project). [This commit](https://github.com/grpc/grpc-swift/commit/1f99975087ad74b974ef252c513bc61813c8f6e1) fixed a few remaining problems building the Xcode samples.

**Comment by mosn** [comment]
@timburks could you share some of your findings on the podfile, I'd like to spend some time and try to fix  the pod integration but would be great if I can have some background on the issue. 

Cheers
