### ISSUE TITLE
What's the best practice for testing SwiftGRPC clients/servers?

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#120]
Are there any best practices on how to test SwiftGRPC clients and servers, and mocking the other side, so that we can write hermetic tests? Let's take the `Echo.Update` bidirectional streaming call from https://github.com/grpc/grpc-swift/tree/master/Examples/Echo, for example.

As far as I can tell, my client consumes an object of type `Echo_EchoUpdateCall` and calls that object's methods to send/receive messages. Therefore, it would be nice to mock the `Echo_EchoUpdateCall` to return custom reply messages and record the sent messages, to ensure the correct ones are sent. However, as of #114 (cc @takasek), that class is actually `final`. So, how am I supposed to test that the client sends the correct messages on my RPC? Would it maybe make sense to declare `Echo_EchoUpdateCall` as a protocol instead, and only make the actual implementation a class?

The same applies if I'd like to test the bigger picture, namely that the right RPCs are called on `Echo_EchoService`. That's also a final class — should it maybe be a protocol as well, letting me mock the whole service? (In fact, that class _needs_ to be mock-able if I e.g. wanted to fake that class's `func get(_ request: Echo_EchoRequest) throws -> Echo_EchoResponse` call.)

Same for server-side testing: My server class needs to implement `Echo_EchoProvider`, whose `update` methods gets passed a `Echo_EchoUpdateSession`:

    func update(session : Echo_EchoUpdateSession) throws

Again, it would be nice to be able to fake that class, letting me provide fake requests and ensure the right responses are returned. So, should `Echo_EchoUpdateSession` be a protocol for better testability as well?

By the way, testing the `get` method would in theory be slightly easier, given that it simplay takes in an `Echo_EchoRequest` and returns a `Echo_EchoResponse`:

    func get(request : Echo_EchoRequest, session : Echo_EchoGetSession) throws -> Echo_EchoResponse

However, **even that can't be tested, because it's impossible to fake `Echo_EchoGetSession`**, with that class's initializer being `fileprivate`. So, as far as I can tell, to test these things, at the moment I'd need to wrap everything in another layer of protocols and test fake implementations of those protocols, resulting in a ton of boilerplate. (The "real" implementation of those testable protocols would simply call through to the gRPC methods and wrap the results of those methods in other protocols.)

As far as I can tell, this would actually be similar to [how testing is meant to be done with the C++ gRPC library](https://github.com/grpc/grpc/blob/master/doc/unit_testing.md). Please let me know if I'm missing something here.

Any thoughts on this would be much appreciated.

**Comment by timburks** [comment]
Now that we have support for this in the generated code, could you draft a sample test?

**Comment by MrMage** [comment]
Good idea! I'll try to add two sets of example tests (one set each for testing client and server with the other end stubbed) soon.

**Comment by MrMage** [comment]
Example tests are in https://github.com/grpc/grpc-swift/pull/184.

**Comment by MrMage** [comment]
Done with #184.
