### ISSUE TITLE
Altering context path in interceptor 

### ISSUE THREAD

**Issue by Devinpennings** [grpc/grpc-swift#1202]
### What are you trying to achieve?

I am trying to redirect/change the path of an outgoing call on a client. For example:

`/Service/Method` -> `/Service/OtherMethod`

### What have you tried so far?

I've tried to create a client side interceptor which would alter the context path to something different. However, `ClientInterceptorContext.path` is readonly.

Is there any way to change/alter the path of the outgoing call in an client interceptor? Or is there any other way to do this?

Edit: 

My last resort would be to change the path in every `xxx.grpc.swift` file, however I don't think this is future-proof.

**Comment by glbrntt** [comment]
It's not possible to change the path from an interceptor. However, you should be able to implement a [`GRPCChannel`](https://github.com/grpc/grpc-swift/blob/3f4b315ef7b125bdc82351445b26b89699e93ff7/Sources/GRPC/GRPCChannel/GRPCChannel.swift#L21-L71) which modifies the `path` there as necessary before calling through to the 'real' channel implementation.

**Comment by Devinpennings** [comment]
Alright, thanks for your quick response!
