### ISSUE TITLE
Linking the library and no symbols adds 50MB to the app's binary size

### ISSUE THREAD

**Issue by davisg123** [grpc/grpc-swift#1204]
### Describe the bug

Add grpc-swift 1.1.0 as a dependency using SPM, build app, 50MB have been added to the binary size. This seems like a show stopper for many apps wanting to incorporate components of the grpc-swift library

I would have expected the compiler to remove all symbols from grpc-swift as dead references. Is there a global variable somewhere that is causing the entire dependency tree to be included?

### To reproduce

Steps to reproduce the bug you've found:
1. Download thatsabigapp.xcodeproj
2. Set development team
3. Product -> Archive
4. Note app size

### Expected behaviour

Not referencing an external library should leave it out of the binary

### Additional information

Included link map and thatsabigapp sample project

[thatsabigapp.zip](https://github.com/grpc/grpc-swift/files/6711374/thatsabigapp.zip)

[thatsabigapp-LinkMap-normal-arm64.txt](https://github.com/grpc/grpc-swift/files/6711367/thatsabigapp-LinkMap-normal-arm64.txt)

**Comment by davisg123** [comment]
this might just be a swift bug, but wow how do other apps tolerate a 50MB size increase

https://bugs.swift.org/browse/SR-1021

**Comment by Lukasa** [comment]
Issues with dead code stripping are sadly out of scope for us, but you’ve linked an issue that seems relevant. 

There are a few other steps worth investigating:

1. In the detailed build log, can you investigate the compile of one of the SwiftNIO files and see whether it is compiled with `-O` or `-Oz`?
2. Have you tried stripping debug symbols out? That’s admittedly a big hammer, but in my experience debug symbols are often more than half the binary size.

**Comment by davisg123** [comment]
Sure, understood that problem is well beyond the scope of just this project. I'll investigate how the dependent libraries are getting compiled

**Comment by davisg123** [comment]
This seems to just be a general issue with Swift frameworks linking other frameworks
