### ISSUE TITLE
What is the appropriate value for loopCount?

### ISSUE THREAD

**Issue by shimastripe** [grpc/grpc-swift#1206]
### What are you trying to achieve?

- learn how to set the appropriate value for `PlatformSupport.makeEventLoopGroup(loopCount: N)`
- grpc-swift tutorial suggests eventLoopGroup use `PlatformSupport.makeEventLoopGroup(loopCount: N)` in Apple platforms.
- I don't know the appropriate `loopCount` value for the production application.
  - Tutorial documents set to 1.

Thanks.

**Comment by vitruvvius** [comment]
+1

**Comment by Lukasa** [comment]
There is no one answer to this question: it depends on the architecture of your service and the load it’s under.

If your service has complex business logic, then almost certainly the correct loop count is 1. SwiftNIO is very fast, and it’s capable of serving your compute speedily. You’d be well-served by pushing all of your business logic onto other threads and letting SwiftNIO and grpc-swift run in a single loop.

On the other hand, if you have very little business logic or the business logic mostly consists of doing I/O, then you can get a benefit from having as many loops as you have cores.

Ultimately the best thing to do is to make this configurable and then to benchmark your specific workload and environment.
