### ISSUE TITLE
How to use Private Key (SecKey) from Secured Enclave for mTLS

### ISSUE THREAD

**Issue by aniljha24** [grpc/grpc-swift#1208]
Unable to figure out workaround for using private key stored in secured enclave with secured ClientConnection
let privateKey = try NIOSSLPrivateKey(bytes: keyStore.getSecKey(), format: .der)
ClientConnection.secure(group: group)
                .withTLS(privateKey: NIOSSLPrivateKey)
It's throwing exception.

### What are you trying to achieve?

I want to make mTLS secured connection using private key stored in secured enclave. I am using ClientConnection API, I am passing certificate and rootTrust. but I also need to pass private key to make a connection. 
my private key is stored in secured enclave in iphone, and I am accessing it as SecKey object. when I am trying to create NIOSSLPrivateKey object using SecKey it throws exception.

### What have you tried so far?

I tried to convert SecKey into normal Key but no success.
I tried to find some callbacks where I can use SecKey instead of passing it, but didn't found any callback method.

**Comment by Lukasa** [comment]
Currently this is not possible: NIOSSLPrivateKey cannot be backed by a SecKey, and a private key in the Secure Enclave cannot be extracted.

**Comment by aniljha24** [comment]
Is there any Callback where I can do encryption/decryption from secKey whenever required

**Comment by Lukasa** [comment]
There is not: we don’t support arbitrary key types in NIOSSL and have no plans to do so.
