### ISSUE TITLE
Is it intentional that service names are lowercased?

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#121]
First of all, thank you for all your work, and sorry for creating several issues in a single day! I am a Xoogler in the process of starting to use gRPC in my own application (which I plan to host on Google Cloud) and would like to make sure I understand everything rather than building stuff I'd need to throw away later. This one's actually a fairly minor issue, but I figured it wouldn't hurt to ask. Also, happy to help implementing changes that I propose, assuming that the community approves of them (as evidenced by #118 yesterday).

It appears that the RPC call method names on the client service class are getting lowercased, as seen in e.g. line 70 of [`Plugin/Templates/client.swift`](https://github.com/grpc/grpc-swift/blob/master/Plugin/Templates/client.swift):

    {{ access }} func {{ method|methodDescriptorName|lowercase }}(_ request: {{ method|input }})

This is counter to the C++ codegen (see [here](https://grpc.io/docs/tutorials/basic/c.html#example-code-and-setup) and [here](https://github.com/grpc/grpc/blob/v1.9.x/examples/cpp/route_guide/route_guide_client.cc)) and the Objective-C codegen (see [here](https://grpc.io/docs/tutorials/basic/objective-c.html) , which indicate that service names keep their case. To properly swiftify the name, maybe it would make sense to only lowercase the first group of uppercase letters?

**Comment by timburks** [comment]
Thanks for raising this. I think lowercasing the first character only would be better than what we're currently doing.

**Comment by MrMage** [comment]
Done with #187.
