### ISSUE TITLE
What's the appropriate allocation scheme for Channel

### ISSUE THREAD

**Issue by vitruvvius** [grpc/grpc-swift#1210]
### What are you trying to achieve?

We have a single sidecar proxy that receives and routes all requests; accordingly, the address/port we're targeting remains the same in the eyes of the client.

Should we be recreating a Channel / ClientConnection on every new unary request, or is it okay to use one shared channel across all services through a shared singleton?

**Comment by glbrntt** [comment]
If the address remains the same then one shared `ClientConnection` should be preferred.
