### ISSUE TITLE
Release 1.1.1 to CocoaPods

### ISSUE THREAD

**Issue by vyshane** [grpc/grpc-swift#1217]
### What are you trying to achieve?

I'm updating the gRPC Swift dependency in my podspec to the latest 1.1.1 release, but it appears that this version has not been pushed to CocoaPods yet.

### What have you tried so far?

I've checked https://cocoapods.org/pods/gRPC-Swift, and can't see 1.1.1 there. Latest version on CocoaPods is still 1.1.0.

**Comment by glbrntt** [comment]
1.1.1 is only different from 1.1.0 in that the version range of Swift argument parser was relaxed. Since none of the Cocoapods depend on argument parser we didn't feel it was necessary to release pods for 1.1.1.
