### ISSUE TITLE
Get path property of call

### ISSUE THREAD

**Issue by ialimz** [grpc/grpc-swift#1236]
### What are you trying to achieve?

How can I access `path` property of `call`?
I'd like to setup performance monitoring and need to merge `path` property into `host` in order to have a valid identifier for monitoring

### What have you tried so far?

I see that `Call` property of `UnaryCall` struct has `path` property, but it's private and I can't access it.

**Comment by glbrntt** [comment]
Interceptors might be the way to do this (they make the path available to you but not the host, you'd have to pass that in).

Alternatively I'm not opposed to making the `path` available to the `{Unary,ClientStreaming,...}Call`s.

**Comment by ialimz** [comment]
Thanks @glbrntt.
Since I have not access to interceptors in the performance monitor layer, I prefer to have `path` available in `call` object.
I'll create a PR in next few hours and make these changes.
