### ISSUE TITLE
Combine multiple EventLoopFuture results (initial metadata, response, trailing metadata) in a unary RPC call into a single EventLoopFuture object?

### ISSUE THREAD

**Issue by IrisG33** [grpc/grpc-swift#1254]
Hi,
I want to wait for all initial metadata, response, and trailing metadata eventLoopFuture complete, and then combine into a single object to my response handler.

I saw that EventLoopFuture has method [`whenAllComplete(_:on:)`](https://apple.github.io/swift-nio/docs/current/NIO/Classes/EventLoopFuture.html#/s:3NIO15EventLoopFutureC15whenAllComplete_2onACySays6ResultOyxs5Error_pGGGSayACyxGG_AA0bC0_ptFZ). But I don't have a event loop to pass to the method.

Wonder do you have some recommended way to combine the EventLoopFutures?

**Comment by glbrntt** [comment]
You can use [`and`](https://github.com/apple/swift-nio/blob/f2705f9655ede35399b12040e892cf653126de98/Sources/NIOCore/EventLoopFuture.swift#L789) to combine two `EventLoopFuture` results.

Something like:

```swift
initialMetadata.and(response).and(trailingMetadata).whenComplete { 
  // ...
}
```

**Comment by Lukasa** [comment]
Alternatively, `EventLoopFuture` has an `eventLoop` property, so you can use the event loop of any of your futures.

**Comment by IrisG33** [comment]
Got it. Thanks for the help!
