### ISSUE TITLE
Which property or agent do I need to listen for the connection status of the GRPC

### ISSUE THREAD

**Issue by Sunrisesd** [grpc/grpc-swift#1282]
private func makeClient(host: String, port: Int, jwt: String, group: EventLoopGroup) -> StatusServiceClient {
        let channel = ClientConnection.secure(group: group).connect(host: host, port: port)

        var callOptions = CallOptions()
        callOptions.customMetadata.add(name: "xxxxx", value: "=======")
        callOptions.customMetadata.add(name: "xxxxx", value: "xxx")

        return StatusServiceClient(channel: channel, defaultCallOptions: callOptions, interceptors: nil)
    }

**Comment by glbrntt** [comment]
You can provide a connectivity state delegate when constructing your channel which will be notified about changes in connection state. Note that the channel won't attempt to connect until you make try to make a call.

https://github.com/grpc/grpc-swift/blob/bce5b8df6bf11c7a0eef69e0472e4d894d97e78a/Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift#L275-L286
