### ISSUE TITLE
Go client .Recv() does not unblock until streaming server returns `context.eventLoop.makeSucceededFuture(.ok)`

### ISSUE THREAD

**Issue by AaronCasas** [grpc/grpc-swift#1297]
### What are you trying to achieve?

Set up server side streaming RPC following the example [here](https://github.com/grpc/grpc-swift/blob/main/docs/basic-tutorial.md#server-side-streaming-rpc).

### What have you tried so far?

My Swift code looks like the following:

```
func measurementStream(request: MeasurementRequest, context: StreamingResponseCallContext<MeasurementResponse>) -> EventLoopFuture<GRPCStatus> {
        var meas:MeasurementResponse
        // Writes stream of measurement data.
        for index in 1...1000  {
            do {
                meas = self.getLatestMeasurement()
                _ = context.sendResponse(meas)
                sleep(1)
            } catch {
                // handle
            }
        }
        return context.eventLoop.makeSucceededFuture(.ok)
```

My Swift server is being run in a background thread with:

```
 DispatchQueue.global(qos: .userInteractive).async {
            do {
                _ = try server.flatMap {
                      $0.onClose
                    }.wait()
            } catch {
                    // handle
                }
            }
        }
```

My GRPC client is written in Go. It follows the equivalent Go example [here](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L59-L78): it just runs a loop calling the client stream's `.Recv()` method.

### The Problem
The Go client does not seem to receive any messages (i.e. `.Recv()` just blocks) until after_ `context.eventLoop.makeSucceededFuture(.ok)` is called. I want and expect it to receive a message every time the server calls `.send_response()`. I've confirmed that no messages are being received until `context.eventLoop.makeSucceededFuture(.ok)` is called by varying the size of the for loop in the above code: if I set it to 60, the first message isn't received for a minute, if I set it to 1 the first message is received in one second, etc.

Is my issue on the server side? Is there something I am missing?

**Comment by Lukasa** [comment]
That's what I thought: in that case, you cannot call `sleep`. You're blocking the event loop thread and preventing us from doing I/O. If you want to delay then you can use `EventLoop.schedule` to schedule an operation some time in the future.
