### ISSUE TITLE
User-Agent in Metadata

### ISSUE THREAD

**Issue by SebastianThiebaud** [grpc/grpc-swift#130]
Hello,

I've been looking through the entire project to see what is responsible in overriding the `User-Agent` I'm providing in the service metadata. 

I can see that `fill_common_header()` is setting the user agent, so I forked this repository to remove it for testing, but the user agent sent to the server is still `grpc-c/4.0.0 (ios; chttp2; garcia)`.

Any idea what's going on here? I'd like to be able to change the user agent. Thank you.

**Comment by SebastianThiebaud** [comment]
I've been investigating this "issue" for the last hour and came up with a solution. I forked this repository, updated the `channel.c`, `Channel.swift` and the protoc plugin template to let customize the user agent when initializing a service. It works fine now, but I'd love to see the official support of this.

**Comment by timburks** [comment]
Thanks for raising this. We'll investigate and propose something.

**Comment by SebastianThiebaud** [comment]
This is solved with channel arguments. Closing this issue.

**Comment by MrMage** [comment]
FYI, I’m using Endpoints Service Proxy, which does not forward the user agent field to the backend. My workaround was to simply write the user agent field into a different metadata header and check that one in the request handler.
