### ISSUE TITLE
Is there a way to use ByteBuffer instead of actual Protobuf types?

### ISSUE THREAD

**Issue by wu-hui** [grpc/grpc-swift#1316]
### What are you trying to achieve?

Our produce uses nanopb, so it does not work with grpc-swift by default. One way I am trying to work around this is to send serialized proto in bytes to grpc-swift. The problem is the generated grpc code expects some actual protobuf types (rightfully), there is no way to send raw proto bytes. Is there a way to generate code that takes raw bytes?

FWIW, this is possible to do with grpc-cpp.

Also, other suggestions are welcome!

**Comment by glbrntt** [comment]
We don't support code generation for non-protobuf messages.

The workaround is to create a wrapper type around whatever your input type is which conforms to `GRPCPayload`. The purpose of this is to serialize the bytes into a `NIOCore.ByteBuffer` and deserialize a `NIOCore.ByteBuffer` into your output type. To use these you'll need to construct calls manually using the `make{RPCType}Call(...)` functions on `GRPCChannel`.

There's an example in the tests [here](https://github.com/grpc/grpc-swift/blob/563be35dac4ee5d71091b79ff0f212f007a1adec/Tests/GRPCTests/GRPCCustomPayloadTests.swift#L87-L119) with an example wrapper [here](https://github.com/grpc/grpc-swift/blob/563be35dac4ee5d71091b79ff0f212f007a1adec/Tests/GRPCTests/GRPCCustomPayloadTests.swift#L266-L281).

**Comment by wu-hui** [comment]
Thanks for the tip!

**Comment by wu-hui** [comment]
I am wondering if I can get some more help here, I am trying to follow your advice by doing

``` Swift
extension ByteBuffer: GRPCPayload {
  public init(serializedByteBuffer: inout ByteBuffer) throws {
    self = serializedByteBuffer
  }

  public func serialize(into buffer: inout ByteBuffer) throws {
    var copy = self
    buffer.writeBuffer(&copy)
  }
}
```

Then trying to make the Route_Guide example work:

```Swift
let call : BidirectionalStreamingCall<ByteBuffer, ByteBuffer> =
          client.makeBidirectionalStreamingCall(path: "", handler: { (resp:ByteBuffer) in
            let note = try! Routeguide_RouteNote.init(contiguousBytes: resp.getBytes(at: 0, length: resp.readableBytes)!)
            print(
                    "Got message \"\(note.message)\" at \(note.location.latitude), \(note.location.longitude)"
            )
          })

let buffer = try! ByteBuffer.init(data: note.serializedData())
    call.sendMessage(buffer, promise: nil)
```

Where `note` is `Routeguide_RouteNote` in the example. 

I receive error from server: `RouteChat Failed: unavailable (14): Transport became inactive`

**Comment by glbrntt** [comment]
Can you post a more complete snippet? Unavailable could be handful of things, couldn't connect to the server, shutdown before finishing the call etc.

A couple of things to note:
- the path should be "/routeguide.RouteGuide/RouteChat" (see [here](https://github.com/grpc/grpc-swift/blob/c48b15ec8633272d93393913b3e4bc75d1a27195/Sources/Examples/RouteGuide/Model/route_guide.grpc.swift#L148))
- Use `resp.readBytes(length: resp.readableBytes)!` instead of `resp.getBytes(at: 0, length: resp.readableBytes)!` (for `getBytes` the reader index isn't guaranteed to be 0)
