### ISSUE TITLE
Can not call handler

### ISSUE THREAD

**Issue by anya-sverdlova** [grpc/grpc-swift#1325]
### What are you trying to achieve?

I'm trying to get response from server - it has to be stream. In Proto file it looks like `rpc loadEquipmentMasterData (EquipmentMasterDataRequestGrpc) returns (stream EquipmentMasterDataResponseGrpc).` In my .grpc file it looks like 
`internal func loadEquipmentMasterData(
    _ request: Proto_EquipmentMasterDataRequestGrpc,
    callOptions: CallOptions? = nil,
    handler: @escaping (Proto_EquipmentMasterDataResponseGrpc) -> Void
  ) -> ServerStreamingCall<Proto_EquipmentMasterDataRequestGrpc, Proto_EquipmentMasterDataResponseGrpc> {
    return self.makeServerStreamingCall(
      path: "here the actual path",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeloadEquipmentMasterDataInterceptors() ?? [],
      handler: handler
    )
  }
`

### What have you tried so far?

So far I have this code: 
```swift
let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let configuration = ClientConnection.Configuration(target: .hostAndPort(url1, port1), eventLoopGroup: group, errorDelegate: self, connectivityStateDelegate: self, connectionKeepalive: ClientConnectionKeepalive(timeout: .seconds(3600)), connectionIdleTimeout: .minutes(10))
let clientChannel = ClientConnection.init(configuration: configuration)
        
var requestData = Proto_EquipmentMasterDataRequestGrpc()
var locale = Proto_LocaleGrpc()
if let lang = Bundle.main.preferredLocalizations.first {
    locale.languageTag = lang
    requestData.locale = locale
}

let callOptions = CallOptions(customMetadata: headers, timeLimit: .timeout(.seconds(10)))
let handler: (Proto_EquipmentMasterDataResponseGrpc) -> Void = { (response) in
    print(response)
}
let client = Proto_MobileServiceClient.init(channel: clientChannel)
let request = client.loadEquipmentMasterData(requestData, callOptions: callOptions, handler: handler)
```

When I try request.status, I have a call on .whenSuccess. I added delegate methods to my class so I can see that there are no errors and connection switch to "ready". But still my handler doesn't fire.

**Comment by Lukasa** [comment]
Is this _all_ your code? You will need to call `request.status.wait()` in order to keep the program running long enough to get the response.

**Comment by anya-sverdlova** [comment]
I did do this (like _ = try? request.status.wait()), it changed nothing.

**Comment by Lukasa** [comment]
Are you getting any errors in the error delegate?

**Comment by anya-sverdlova** [comment]
We already realised where were the problem: it was because our server needed plaintext so we need to use insecure connection. Thanks for trying to help!
