### ISSUE TITLE
Should we use `gpr_malloc` in the C shim and/or double-check it for memory leaks?

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#134]
Given that I found a memory leak in `metadata.c` (and fixed it with #133), would it be advisable to do a full review of the entire C shim library for memory leaks?

Also, the GRPC de-initializers that sometimes get called use `gpr_free`. To be consistent with that, should we allocate all memory using `gpr_malloc` instead of `malloc`? I assume the two are currently interchangeable, but it might make sense to be consistent there to avoid trouble down the road.

WDYT?

**Comment by jingtianyilong** [comment]
Found memory leak with caller `gpr_zalloc` in `alloc.c`, when I call server with high frequency. Memory never get freed.

**Comment by MrMage** [comment]
Thanks for the info. Is that an issue specific to SwiftGRPC or in the underlying GRPC library, though?

**Comment by jingtianyilong** [comment]
I'm not sure actually. But the `alloc.c` located in `SwifGRPC.xcodeproj/Sources/CgRPC/src/core/lib/support/`
So I assume it's with SwiftGRPC.
When calling with high frequency, it generates tons of `Malloc 32.0Kib` according to the Profile Tool on XCode.
I've noticed that there is a `free` function in the `alloc.h`. But memory never actually get freed.

**Comment by MrMage** [comment]
I think I fixed most leaks I could find recently; closing this.
