### ISSUE TITLE
protoc-gen-grpc-swift is ignoring options with --grpc-swift_opt

### ISSUE THREAD

**Issue by CarlosNano** [grpc/grpc-swift#1340]
### Describe the bug

`protoc-gen-grpc-swift` is ignoring options with `--grpc-swift_opt`

### To reproduce

I'm using `protoc` to generate the grpc files in swift.

I need to use the option [GRPCModuleName](https://github.com/glbrntt/grpc-swift/blob/979958f242da6bccfa613657d2a4cd31682068a6/docs/plugin.md#grpcmodulename)

So I'm running the following:

`protoc helloworld.proto --grpc-swift_opt=GRPCModuleName=GRPC_Swift --swiftgrpc_out=. --plugin=path_to_plugin/protoc-gen-grpc-swift`

It doesn't complain, but I've noticed `protoc` doesn't take into consideration the `--grpc-swift_opt` I added.

If I compare the file generated with the previous command and the one generated with this one:
`protoc --swiftgrpc_out=. helloworld.proto`

They are exactly the same.

I've tried with other options such as: [Visibility](https://github.com/glbrntt/grpc-swift/blob/979958f242da6bccfa613657d2a4cd31682068a6/docs/plugin.md#visibility) and it does the same thing, no differences.

Then I saw this issue: https://github.com/grpc/grpc-swift/issues/1203 

So I tried with: `--swiftgrpc_opt` instead of `--grpc-swift_opt` but with the Visibility parameter and when I've compared it, I can see the differences.

Unfortunately I can't use `GRPCModuleName` with `--swiftgrpc_opt` because I will get:
`ERROR: unknownParameter(name: "GRPCModuleName")`

#### Versions 

`protoc --version`: `libprotoc 3.19.3`

About getting the version of the plugins (`grpc-swift` and `protoc-gen-grpc-swift` ), not sure how to do it, but I've just cloned the repo and use `make plugins` to build them

### Expected behaviour

Get the swift generated files with the module: `GRPC_Swift` instead of the default option.

**Comment by glbrntt** [comment]
`swiftgrpc_out` and `swiftgrpc_opt` refer to plugin for the 0.x version of grpc-swift; the error you see (`ERROR: unknownParameter(name: "GRPCModuleName")`) is expected: there was no "GRPCModuleName" option in 0.x.

`--grpc-swift_opt` and `--grpc-swift_out` are correct for 1.x. Can you verify that you have the correct path for the plugin for grpc-swift?

**Comment by CarlosNano** [comment]
Thanks for the fast response.

Oh I see what happened, I had in `/usr/local/bin` the old plugin: `protoc-gen-swiftgrpc` as well as the new plugin. 

I guess `protoc` ignores the `plugin` parameter if it finds the plugin in `usr/local/bin`

Thanks for the help.
