### ISSUE TITLE
Is it possible to install the swift grpc plugin on Ubuntu?

### ISSUE THREAD

**Issue by dulataldazharov** [grpc/grpc-swift#1344]
I am using Ubuntu 20.04.
I want to be able to generate service classes from proto services.
Is there any installation guide on how to install this on Ubuntu?

**Comment by glbrntt** [comment]
First you need to grab a copy of `protoc` and then build the plugins from source. There are instructions on how to do this [here](https://github.com/grpc/grpc-swift#getting-the-protoc-plugins).
