### ISSUE TITLE
Why the async support generates code for just iOS 15? Since Xcode 13.2.x async features were backported.

### ISSUE THREAD

**Issue by tiborkiss** [grpc/grpc-swift#1351]
### What are you trying to achieve?

Since Xcode 13.2 release, the async features were backported back until iOS 13. I would like to generate stubs compatible also with iOS 13.

### What have you tried so far?

I don't want to manually edit the generated code. It is evident that once the condition of dependency to iOS 15 is generated in the code, I cannot use the backported async support.

I just would like to let it open the discussion, when will be possible to use for iOS 13 .. < iOS 15?

**Comment by glbrntt** [comment]
There is an open PR for this: https://github.com/grpc/grpc-swift/pull/1346
