### ISSUE TITLE
Is there a way to initialise a client using a file descriptor or an XPC connection?

### ISSUE THREAD

**Issue by jvimal-eg** [grpc/grpc-swift#1353]
### What are you trying to achieve?

There are 3 ways to start a grpc client today: host and port, socket address, and unix domain socket path. Is there a way to start one using a file descriptor?

My use case is that I have a server and client running in two different sandboxes.  For some reason, I am unable to share a unix domain socket across the two, and I've resorted to using a TCP socket, which is insecure as any process can connect to it.  

Ideally, it would be great if grpc client can work over an XPC connection, which offers stronger authentication between client/server using codesign certificates.  Alternatively, I could have the server pass a file descriptor to an authenticated client over XPC and use that file descriptor to start the client.

### What have you tried so far?

I tried looking at the source code to see how else I can create connections.

**Comment by Lukasa** [comment]
grpc-over-xpc is unlikely to be a good design pattern: XPC is not really built for bulk data transfer in this way. Passing an FD over XPC and using that would be better, and grpc could absolutely support that as a design pattern, but I'll defer to @glbrntt as to whether that exists today.

**Comment by jvimal-eg** [comment]
@Lukasa that's great, thank you. I remember reading in Apple dev forums that XPC is pretty fast, even faster than unix domain sockets: https://developer.apple.com/forums/thread/74498. I have't benchmarked it myself, so I'll defer it to the experts.

@glbrntt is there a way to use the grpc-swift library to achieve it today without an additional implementation?

**Comment by glbrntt** [comment]
There's no API in grpc to do this at the moment, but NIO provides a [`withConnectedSocket(_:)`](https://github.com/apple/swift-nio/blob/4f2c6a3e0bf5fd2a855d5821b6b397508e46da86/Sources/NIOPosix/Bootstrap.swift#L662-L694) which we should be able to just wire through the grpc API.

We'd need:
- A new entry on [`ConnectionTarget`](https://github.com/grpc/grpc-swift/blob/f79ef102add7a6a920e559a93a9fb309006f794c/Sources/GRPC/ClientConnection.swift#L264)
- New API on the `ClientConnection` builder [here](https://github.com/grpc/grpc-swift/blob/f79ef102add7a6a920e559a93a9fb309006f794c/Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift#L67) (the channel pool uses `ConnectionTarget` directly so does not need new API)
- Some validation that we're not trying to use this API with a `NIOTSEventLoopGroup` or `NIOTSEventLoop` (as far as I can tell, using a file descriptor directly is not possible with Network.framework)
- Tests

Ideally we would give the server the same treatment.

**Comment by wwang71119** [comment]
hmm, seems to me it is overkill, I think GRPC has it's own authentication. see: https://grpc.io/docs/guides/auth/

**Comment by jvimal-eg** [comment]
@glbrntt Sorry for the delay. I have this implemented in a branch that builds fine, but I am having difficulty writing a unit test that uses the `withConnectedSocket(_:)` API for a unix domain socket.  I looked at existing unit tests, and I couldn't find an example that uses a real unix domain socket. Would you be able to help me flush that out?

Would `EchoTestClientTests.testGetWithRealClientAndServer` be a good candidate to test this out?

**Comment by glbrntt** [comment]
Resolved by #1385
