### ISSUE TITLE
Crash due to signal: SIGTRAP(TRAP_BRKPT) at ConnectionManager.channelError(_:) (ConnectionManager.swift:470 )

### ISSUE THREAD

**Issue by DhemaiedRihab** [grpc/grpc-swift#1382]
I caught this crash on my iOS application with the logs specified in these screenshots : 

![Capture d’écran 2022-03-30 à 12 28 18 PM](https://user-images.githubusercontent.com/99874136/160824613-a98722d0-2f83-4f25-8d72-7a36bd0be0cf.png)
![Capture d’écran 2022-03-30 à 12 28 41 PM](https://user-images.githubusercontent.com/99874136/160824626-45137c62-03db-4659-8349-3addda764baa.png)
![Capture d’écran 2022-03-30 à 12 28 52 PM](https://user-images.githubusercontent.com/99874136/160824631-fcbab91a-2abd-4808-8497-ee8ab57fdaca.png)

To reproduce
Unfortunately I can't tell what the cause of this crash was. I get the crash description from from my crash reporting.

Thanks in advance and waiting for your response

**Comment by glbrntt** [comment]
What version of grpc-swift are you using?

**Comment by glbrntt** [comment]
Does this reproduce if you update to the latest version? I.e. 1.7.3?

**Comment by glbrntt** [comment]
The precondition being hit here does not exist on recent versions. Please re-open if this crash still happens with the latest version.
