### ISSUE TITLE
GRPC.GRPCStatus error 1

### ISSUE THREAD

**Issue by BrunoCerberus** [grpc/grpc-swift#1387]
Getting a lot this error recently `The operation couldn’t be completed. (GRPC.GRPCStatus error 1.)`, and my internet is fiber wire. Any solutions for that?

**Comment by BrunoCerberus** [comment]
This is some snapshots of the implementation

<img width="1076" alt="Screen Shot 2022-04-05 at 19 10 41" src="https://user-images.githubusercontent.com/10541956/161858718-3f09bd42-ae55-424f-9051-787f78167035.png">

<img width="912" alt="Screen Shot 2022-04-05 at 19 11 22" src="https://user-images.githubusercontent.com/10541956/161858905-dcb93315-c707-4846-88d9-73dc7f2c0173.png">

<img width="1026" alt="Screen Shot 2022-04-05 at 19 11 47" src="https://user-images.githubusercontent.com/10541956/161859018-01391104-8a17-405e-8c2e-d54249104017.png">

**Comment by glbrntt** [comment]
The string "The operation couldn't be completed" doesn't appear anywhere in grpc-swift and status code 1 is "cancelled". This leads me to think that the service is failing the RPC rather than the client having a bug.

**Comment by BrunoCerberus** [comment]
@glbrntt so is this a service error?

**Comment by glbrntt** [comment]
Yes, it looks that way.

**Comment by BrunoCerberus** [comment]
@glbrntt Dude check this out https://grpc.github.io/grpc/core/md_doc_statuscodes.html, it is a client problem

**Comment by Lukasa** [comment]
It absolutely could be, but the error is being reported by the service and so we need to understand what it's mad about. Do you control the service? Can we see trace level logging from grpc-swift?

**Comment by BrunoCerberus** [comment]
@Lukasa the service is held by another squad from the company that I'm working for, gonna check this with them right away
