### ISSUE TITLE
Google_Cloud_Speech_V1_SpeechAdaptation is not found

### ISSUE THREAD

**Issue by csdf-ssm** [grpc/grpc-swift#1393]
eg:SpeechToText-gRPC-iOS ,when i get make protos, make generate,and run, it tips  Cannot find type 'Google_Cloud_Speech_V1_SpeechAdaptation' in scope

**Comment by glbrntt** [comment]
Did each of the `make` steps succeed?

**Comment by GoluKumar1** [comment]
Still facing this issue when try to run the speech example also Generated file are not available. Only the references are shown.
