### ISSUE TITLE
Health Check Request on v1.x [SwiftNIO]

### ISSUE THREAD

**Issue by OnurVar** [grpc/grpc-swift#1416]
### What are you trying to achieve?

We're trying to use [GRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) but it seems like it's not available in v1.x which is using SwiftNIO

### What have you tried so far?

We've tried to use v0.x which is using `gRPC C library` and we were able to use `grpc_health_v1_HealthCheckRequest` but question is there any way to achieve similar functionality with v1.x ?

Best regards

**Comment by glbrntt** [comment]
It's not provided out-of-the-box. You have to generate and implement the service yourself.

**Comment by OnurVar** [comment]
Understood, thank you
