### ISSUE TITLE
grpc.swift generation

### ISSUE THREAD

**Issue by namsoila** [grpc/grpc-swift#143]
protoc version 3.5.1
grpc swift 0.3.3
xcode 9.2

When generating a grpc swift file using `protoc <file.proto>   --swift_out=.  --swiftgrpc_out=.`, I received two errors when tying to build project with generated file.

```
/// Common properties available in each service session.
internal class Routeguide_RouteGuideSession {
  fileprivate var handler : gRPC.Handler
  internal var requestMetadata : Metadata { return handler.requestMetadata }

  internal var statusCode : StatusCode = .ok <---------------- here
  internal var statusCode: Int = 0
  internal var statusMessage : String = "OK"
  internal var initialMetadata : Metadata = Metadata()
  internal var trailingMetadata : Metadata = Metadata()

  fileprivate init(handler:gRPC.Handler) {
    self.handler = handler
  }
}
```

In other generated code, the statusCode is set as an Int so we have something like:

`internal var statusCode: Int : 0`

```
/// Start the server.
  internal func start(queue:DispatchQueue = DispatchQueue.global()) {
    guard let provider = self.provider else {
      fatalError() // the server requires a provider
    }
    server.run {(handler) in
      print("Server received request to " + handler.host
        + " calling " + handler.method
        + " from " + handler.caller
        + " with " + String(describing:handler.requestMetadata) )

      do {
        switch handler.method {
        case "/routeguide.RouteGuide/GetFeature":
          try Routeguide_RouteGuideGetFeatureSession(handler:handler, provider:provider).run(queue:queue)
        case "/routeguide.RouteGuide/ListFeatures":
          try Routeguide_RouteGuideListFeaturesSession(handler:handler, provider:provider).run(queue:queue)
        case "/routeguide.RouteGuide/RecordRoute":
          try Routeguide_RouteGuideRecordRouteSession(handler:handler, provider:provider).run(queue:queue)
        case "/routeguide.RouteGuide/RouteChat":
          try Routeguide_RouteGuideRouteChatSession(handler:handler, provider:provider).run(queue:queue)
        default:
          // handle unknown requests
          try handler.receiveMessage(initialMetadata:Metadata()) {(requestData) in
            //fix required
            try handler.sendResponse(statusCode:.unimplemented,
                                     statusMessage:"unknown method " + handler.method,
                                     trailingMetadata:Metadata()) <--------------------- here
          }
        }
      } catch (let error) {
        print("Server error: \(error)")
      }
    }
  }
}
```

The handler method seems to require an explicit status code and has additional field:

`try handler.sendStatus(statusCode: 0, statusMessage: "unknown method " + handler.method, trailingMetadata: Metadata(), completion: {})'

Swift autofix suggests:

```
statusCode:StatusCode(rawValue: self.statusCode)!
```

**Comment by MrMage** [comment]
I see two conflicting declarations of `statusCode` in your generated code. But I only see

    var statusCode : StatusCode = .ok

in https://github.com/grpc/grpc-swift/tree/master/Plugin/Templates.

- What version of the protoc plugin are you using exactly? 0.3.3 or HEAD?
- How did you build and install the plugin?
- What version of the runtime library are you using exactly? 0.3.3 or HEAD? (Plugin and runtime need to match.)
- What exactly are the compilation errors you are getting?

**Comment by timburks** [comment]
This looks like a version inconsistency. PR #152 fixes the examples to build with the same version of gRPC as in the repo - earlier versions of the Swift Package Manager required an explicit tag, which would lead to problems if you generated code with a version of the plugin that didn't match the selected runtime version. I'll close this now but please reopen it if you continue to see consistency problems.
