### ISSUE TITLE
Calls always return OK for streaming RPCs

### ISSUE THREAD

**Issue by cvanderschuere** [grpc/grpc-swift#144]
There appears to be a significant bug with the client implementation of streaming RPCs where the status code is never processed. I have been able to verify that this is a swift-specific problem through a comparison with other clients (python & go).

With some investigation, the problem appears to be with what operations are performed for streaming RPCs:

Server Streaming (Swift):
https://github.com/grpc/grpc-swift/blob/c7a788526044077deb584de05e4dde6dbe8005b3/Sources/gRPC/Call.swift#L232-L237

Server Streaming (Python):
```python
_UNARY_STREAM_INITIAL_DUE = (
    cygrpc.OperationType.send_initial_metadata,
    cygrpc.OperationType.send_message,
    cygrpc.OperationType.send_close_from_client,
    cygrpc.OperationType.receive_initial_metadata,
    cygrpc.OperationType.receive_status_on_client,
)
```

The same appears to be true for client and bi-directional streaming as well, although I haven't explicitly verified those.

Issues:
- Streaming RPCs should process status
- Default status code should not be `OK`

**Comment by timburks** [comment]
@cvanderschuere could you confirm that PR #147 resolves this for you?

**Comment by cvanderschuere** [comment]
Tests confirm this was fixed
