### ISSUE TITLE
Cannot use plugins with the latest version (1.8.0) 

### ISSUE THREAD

**Issue by o15a3d4l11s2** [grpc/grpc-swift#1440]
### Describe the bug

```
pod 'gRPC-Swift', '1.8.0'
pod 'gRPC-Swift-Plugins', '1.8.0'
```

```
protobuf 3.19.4
```

I am using the following command
```
protoc --plugin=protoc-gen-swift=Pods/gRPC-Swift-Plugins/bin/protoc-gen-swift --swift_out=MyProject/Services/Protos/ --proto_path=MyProject/Services/Protos $(find MyProject/Services/Protos -name "*.proto" | sed "s|MyProject/Services/Protos/||")
```

I know... it is a little too much with the `find` command, but bear with me.

I get the error
```
Pods/gRPC-Swift-Plugins/bin/protoc-gen-swift: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--swift_out: protoc-gen-swift: Plugin failed with status code 1.
```

The same command succeeds with Pods set to version 1.7.3. Same result for the `protoc-gen-grpc-swift` plugin.

### To reproduce

Steps to reproduce the bug you've found:
1. Install version 1.8.0 of the projects
2. Generate swift files from photos

### Expected behaviour

Command should execute successfully.

### Additional information

Verified that the plugin exists, moved it also to `/usr/bin` and also to `/usr/local/bin` with no success. Also `chmod`-ed to make executable, same result.

**Comment by glbrntt** [comment]
Hmm, can you try with these plugins? [protoc-grpc-swift-plugins-1.8.0.zip](https://github.com/grpc/grpc-swift/files/8907383/protoc-grpc-swift-plugins-1.8.0.zip)

**Comment by o15a3d4l11s2** [comment]
> Hmm, can you try with these plugins? [protoc-grpc-swift-plugins-1.8.0.zip](https://github.com/grpc/grpc-swift/files/8907383/protoc-grpc-swift-plugins-1.8.0.zip)

It worked properly. What is the difference between these binaries and the ones that are in the plugins pod with the same version (1.8.0)?

**Comment by glbrntt** [comment]
> It worked properly. What is the difference between these binaries and the ones that are in the plugins pod with the same version (1.8.0)?

Great!

> The published ones are for ARM64 (Apple Silicon/M1), these are for x86_64 (Intel).

Exactly this. 

I've just republished the plugins as universal binaries.

**Comment by janosvitok** [comment]
Thank you!
