### ISSUE TITLE
[Version mismatch] 'get()' is only available in iOS 15 or newer

### ISSUE THREAD

**Issue by lmcmz** [grpc/grpc-swift#1443]
### Describe the bug

It seem like there is a version mismatch issue in the latest v1.8.0 version, build as the project was fine.
But when I import it to my own project, it throws other errors, I can see those 2 places iOS version is not consistent.

Here is the version info:
gRPC-swift version `1.8.0`
Xcode version `14-beta`

### To reproduce

Steps to reproduce the bug you've found:
1. Import the lib from SPM
2. Build the project

### Screenshots
<img width="633" alt="Screen Shot 2022-06-23 at 4 44 38 pm" src="https://user-images.githubusercontent.com/9669733/175234082-74bfca3f-bb1f-4371-a94a-8a04d47e8158.png">
<img width="1348" alt="Screen Shot 2022-06-23 at 4 44 59 pm" src="https://user-images.githubusercontent.com/9669733/175234103-8d67ed3b-4961-4e1a-b818-9e861bc3335f.png">

**Comment by Lukasa** [comment]
Please update your package dependency versions: NIO [lowered the availability requirement for `EventLoopFuture.get` in 2.36.0](https://github.com/apple/swift-nio/commit/fa3b2a2e66f8da884186b5f5b2d1ab380b570dbb).
