### ISSUE TITLE
Consider documenting QoS used by default on MultiThreadedEventLoop

### ISSUE THREAD

**Issue by pacu** [grpc/grpc-swift#1446]
grpc-swift and procot-gen 1.8.0

I got this warning from the thread sanitizer

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/484008/176510062-e3963ac9-b960-42f0-8917-ab9a5b7f12b7.png">

this is a reference wallet that can be checked out from here: https://github.com/zcash/zcash-ios-wallet

```
SourcePackages/checkouts/swift-nio/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:121: warning run: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
```

This is the code that initializes the client connection.

````
public init(host: String, port: Int = 9067, secure: Bool = true, singleCallTimeout: Int64 = 10000, streamingCallTimeout: Int64 = 10000) {
        self.connectionManager = ConnectionStatusManager()
        self.queue = DispatchQueue.init(label: "LightWalletGRPCService")
        self.streamingCallTimeout = TimeLimit.timeout(.milliseconds(streamingCallTimeout))
        self.singleCallTimeout = TimeLimit.timeout(.milliseconds(singleCallTimeout))

        let configuration = ClientConnection.Configuration(
            target: .hostAndPort(host, port),
            eventLoopGroup: MultiThreadedEventLoopGroup(numberOfThreads: 1),
            connectivityStateDelegate: connectionManager,
            connectivityStateDelegateQueue: queue,
            tls: secure ? .init() : nil
        )
        let channel = ClientConnection(configuration: configuration)

        self.channel = channel

        compactTxStreamer = CompactTxStreamerClient(
            channel: self.channel,
            defaultCallOptions: Self.callOptions(
                timeLimit: TimeLimit.timeout(.seconds(Int64(singleCallTimeout)))
            )
        )
    }
 ````

This is probably what produces it.

````
 func latestHeight(result: @escaping (Swift.Result<BlockHeight, Error>) -> Void) {
        DispatchQueue.global(qos: .userInitiated).async {
            do {
                result(.success(try self.latestBlockHeight()))
            } catch {
                result(.failure(error))
            }
        }
    }
````

**Comment by pacu** [comment]
I'm sorry this shouldn't be labeled as bug :(

**Comment by glbrntt** [comment]
> I'm sorry this shouldn't be labeled as bug :(

No worries!

--- 

`MultiThreadedEventLoopGroup` is provided by `swift-nio` and backed by pthreads. It doesn't have a QoS explicitly associated with it, which is presumably why the thread sanitizer assumes "default".

If you need to adjust the QoS you can use a `NIOTSEventLoopGroup` from [swift-nio-transport-services](https://github.com/apple/swift-nio-transport-services) which is backed by dispatch queues. You can set the `qos` in the [`init`](https://github.com/apple/swift-nio-transport-services/blob/acb6425a09616ea13cd1b1fab8df8b08100705c7/Sources/NIOTransportServices/NIOTSEventLoopGroup.swift#L53).

**Comment by pacu** [comment]
Thank you clarifying this!

**Comment by pacu** [comment]
Hi! I'm sorry to bother again with this. I think this is probably related to how the API is designed for a server-side appication.


I'm digging a little bit deeper here. It seems that it's the initializer that's causing the thread sanitizer warning.
On SwiftUI the main thread is `.userInitiated` how shall one initialize the SwiftGRPC Stack in order to avoid this problems?

Shall client connections be instantiated in a separate thread async?

**Comment by Lukasa** [comment]
Yes, you should do your networking in a separate thread to your UI programming.
