### ISSUE TITLE
error: unable to rename temporary gRPC-Core.build Operation not permitted'

### ISSUE THREAD

**Issue by Mgutierrez2203** [grpc/grpc-swift#1448]
I'm trying to run an custom schema (to unit test) and i got this error. Do you know what is the reason and how I could fix it?

I have tried to clean cache, delete derived data, update my pods and I couldn't get run the application 

<img width="1371" alt="Screen Shot 2022-06-30 at 3 49 57 PM" src="https://user-images.githubusercontent.com/25779525/176776015-003bc1ba-89ae-46ee-a0ce-a7d2a697ad5c.png">

**Comment by glbrntt** [comment]
Sorry but `gRPC-Core` comes from the https://github.com/grpc/grpc -- it is unrelated to this repository.
