### ISSUE TITLE
Could not find module 'SwiftProtobuf' for target 'arm64-apple-ios-simulator' &  'i386-apple-ios-simulator'

### ISSUE THREAD

**Issue by lokeswarisatyanarayanan** [grpc/grpc-swift#1451]
### What are you trying to achieve?

To install the GRPC library into my current project which also uses Firebase. 

### What have you tried so far?

- Installed both using pods and it failed because of name conflicts. 
- Tried adding Architectures of the above in build settings
- Tried opening using Rosetta.

**Comment by diatonicman** [comment]
I also get this error. The repro steps are

1.) Create new Xcode project.
2.) File -> Add Packages
3.) Enter the gRPC URL and click Add Package
4.) Try to build and get the above error.

Help would me much appreciated.

**Comment by glbrntt** [comment]
Could you provide the complete build logs for this?

**Comment by lokeswarisatyanarayanan** [comment]
I resolved that error by adding grpc-swift as a pod with 1.0.0 version and my Firebase packages as SPM. 

Here's my pod version

`pod 'gRPC-Swift', '~> 1.0.0'`

I generate the pb and grpc files using the following commands. 

`protoc --grpc-swift_out=. presence.proto`
`protoc --swift_out=. presence.proto`

The generated files throw multiple errors for missing types in scope in the presence.grpc.swift file. 

Adding the screenshot below. Any help would be appreciated!



<img width="368" alt="Screenshot 2022-07-11 at 6 37 52 PM" src="https://user-images.githubusercontent.com/24609734/178271875-db60b037-20e1-44c9-b5c4-c8ba9680ee57.png">

**Comment by glbrntt** [comment]
You have a version mismatch between the library version (from cocoapods) and the plugin version. The plugin version is newer and is generating code that the library doesn't know about.

FWIW: Cocoapods is no longer supported and the last version published there was 1.8.0.

**Comment by diatonicman** [comment]
What got swift package manager working for me was not importing the proto executable
<img width="655" alt="Screen Shot 2022-07-15 at 11 57 46 AM" src="https://user-images.githubusercontent.com/13081081/179293310-d28992e2-3edb-4a06-9542-ab92638a9534.png">
