### ISSUE TITLE
Want to change some sources of plugin: --grpc-swift_out: protoc-gen-grpc-swift: Plugin killed by signal 9.

### ISSUE THREAD

**Issue by bimawa** [grpc/grpc-swift#1452]
When I trying change some generator logic and recreate grpc plugin and satart it I got the error:
`--grpc-swift_out: protoc-gen-grpc-swift: Plugin killed by signal 9.`

How I launch the protoc: 
```
$: make plugins; protoc streamlayerTest/load.proto \
                                           --proto_path=streamlayerTest/ \
                                           --plugin=./protoc-gen-swift \
                                           --swift_opt=Visibility=Public \
                                           --swift_out=streamlayerOut/ \
                                           --plugin=./protoc-gen-grpc-swift \
                                           --swift_opt=Visibility=Public \
                                           --grpc-swift_opt=Server=false,GRPCModuleName=GRPC 
```
output: 
```
swift build --build-path=./.build --configuration=release --enable-test-discovery --product protoc-gen-grpc-swift
warning: '--enable-test-discovery' option is deprecated; tests are automatically discovered on all platforms
Building for production...
[2/2] Linking protoc-gen-grpc-swift
Build complete! (3.03s)
cp .build/release/protoc-gen-swift .build/release/protoc-gen-grpc-swift .
--grpc-swift_out: protoc-gen-grpc-swift: Plugin killed by signal 9.
```
If I change Generator.swift back. Its workin. if I change some line, its Exit with error 9
How can I cusomise the grpc generator plugin?

**Comment by glbrntt** [comment]
What did you change in `Generator.swift` that causes it to crash?

**Comment by glbrntt** [comment]
Odd that it works as expected in debug mode though.

**Comment by bimawa** [comment]
![CleanShot 2022-07-11 at 20 11 07@2x](https://user-images.githubusercontent.com/1393809/178297026-e1ed5bf8-1253-42ca-a8be-5d57f51314e1.png)
under verbose mode in release config i got this warnings

**Comment by bimawa** [comment]
hmm ok its worked as expected now.
But. when I execute: `make plugins`
Its make me broken binary of `protoc-gen-grpc-swift`
When I build manualy by: 
```
swift build --build-path=./.build --configuration=release --product protoc-gen-grpc-swift
cp .build/debug/protoc-gen-grpc-swift .
```
Its work as expected.

**Comment by bimawa** [comment]
But with make plugins still not working (
I'll investigate it

**Comment by bimawa** [comment]
@glbrntt George, can you check my PR? Maybe it’ll be useful.

**Comment by glbrntt** [comment]
@bimawa can you detail the exact steps you're doing to hit this? I don't think your `Makefile` changes are necessary so it would be helpful if I can reproduce this and figure out what's going on.
