### ISSUE TITLE
Expose `Server.stop` and `Server.onCompletion` in generated code

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#146]
At the moment, e.g. `Echo_EchoServer` has a `start` method which calls `run()` on its underlying `server` instance variable. However, that instance variable's corresponding `stop` method and the setter for the completion block are not exposed. **Should we either give the `server` property the same visibility as `start` or expose additional `stop` and `setOnCompletion` (or `onCompletion`) methods?**

**Comment by MrMage** [comment]
Okay, it appears that releasing the server also stops it. I think it might still make sense to expose an explicit `stop()` method, and or document this behavior.

**Comment by MrMage** [comment]
On a related note: Is it intentional that server-streaming sessions have no means of closing the session? See e.g. `Echo_EchoExpandSession` in [`Examples/Echo/Generated/echo.grpc.swift`](https://github.com/grpc/grpc-swift/blob/master/Examples/Echo/Generated/echo.grpc.swift).

**Comment by timburks** [comment]
I didn't anticipate it but agree that an explicit stop() method on generated servers would be good.

**Comment by MrMage** [comment]
These properties are now public, so I think we can close this.
