### ISSUE TITLE
Cocoapods doesn't seem to be up to date with latest gRPC-Swift versions

### ISSUE THREAD

**Issue by pacu** [grpc/grpc-swift#1460]
### Describe the bug
I've been trying to update to 1.8.2 but Cocoapods fails when doing a `pod lib lint` because it can't find 1.8.2.

### To reproduce
visit `https://cocoapods.org/` and search for gRPC-Swift ---> Version is 1.8.0

also:
create a project that points to `'gRPC-Swift', '~> 1.8.2'`
try to pod install or lib lint depending on what you've done.

For example if I go to commit `221f3a3b98eec8410dc0c4c97c5034f3fc07cc51` of [ZcashLightClientKit](https://github.com/zcash/ZcashLightClientKit)  and try to run `pod lib lint --allow-warnings`
````
    ZcashLightClientKit (from `/Users/pacu/Repos/ECC/ZcashLightClientKit`) was resolved to 0.16.1-beta, which depends on
      gRPC-Swift (~> 1.8.2)

None of your spec sources contain a spec satisfying the dependency: `gRPC-Swift (~> 1.8.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.) during validation.

[!] ZcashLightClientKit did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
`````

### Expected behaviour
dependency gets pulled without issues.

**Comment by Lukasa** [comment]
This is intentional, see #1447 .

**Comment by pacu** [comment]
Oh Thanks!
