### ISSUE TITLE
I got the error "ERROR: unknownParameter(name: "AsyncClient")" when try manually create stubs

### ISSUE THREAD

**Issue by NMaks07** [grpc/grpc-swift#1464]
I got the error "ERROR: unknownParameter(name: "AsyncClient")" when try manually create stubs.

I did not understand how to make stubs with script, so was trying to make it manually as described in readme. 

```
protoc Gen/moobee.proto \
    --proto_path=Gen \
    --plugin=/usr/local/bin/protoc-gen-swift \
    --swift_opt=Visibility=Public \
    --swift_out=Gen \
    --plugin=/usr/local/bin/protoc-gen-grpc-swift \
    --grpc-swift_opt=Visibility=Public,AsyncClient=True,AsyncServer=True \
    --grpc-swift_out=Gen

```    
But it fails with "ERROR: unknownParameter(name: "AsyncClient")"

**Comment by NMaks07** [comment]
> plugins?

Yesterday i install with brew and got this error, I thought maybe something wrong with brew, and today on another mac I clone this project, make plugins, get protoc executable for osx version on intel and got same error

**Comment by NMaks07** [comment]
I clone last release 1.8.2

**Comment by Lukasa** [comment]
You no longer need to provide `AsyncClient` or `AsyncServer` since 1.8.0, the async clients and servers are generated automatically.
