### ISSUE TITLE
How to invoke a method in the async  await manner 

### ISSUE THREAD

**Issue by NMaks07** [grpc/grpc-swift#1466]
How to invoke in the async  await manner  for example sayHello method. Didn't find something similar to .resume. There is some .response.wait() method but it blocks thread.

**Comment by Lukasa** [comment]
This is a standard pattern in Swift concurrency: you call the method via `await`. The [HelloWorld example code](https://github.com/grpc/grpc-swift/blob/d114c5ec34015bab663b3b7afaa7d6197656e47e/Sources/Examples/HelloWorld/Client/main.swift#L62-L67) demonstrates this:

https://github.com/grpc/grpc-swift/blob/d114c5ec34015bab663b3b7afaa7d6197656e47e/Sources/Examples/HelloWorld/Client/main.swift#L62-L67
