### ISSUE TITLE
How to make .grpc and .pb files only for client.

### ISSUE THREAD

**Issue by NMaks07** [grpc/grpc-swift#1468]
I got .proto file from backend devs. I am trying to make only client code. 
couldn't figure out how to achieve this.  
Can someone show me up to date protoc flag to make only client code?

**Comment by eugeneego** [comment]
```sh
protoc <your proto> --grpc-swift_out=Client=true,Server=false:.
```
from https://github.com/grpc/grpc-swift/blob/main/docs/plugin.md
