### ISSUE TITLE
Identifiable

### ISSUE THREAD

**Issue by bspringston** [grpc/grpc-swift#1484]
Is it possible to have generated structs denote that they conform to the  Identifiable protocol when they have an id ?

currently I have to create an empty extension for all of my structs to denote this.

example:

extension MyStruct: Identifiable {}

**Comment by Lukasa** [comment]
The structs are generated by [swift-protobuf](https://github.com/apple/swift-protobuf), not by this library, so I recommend asking on that project. However, in general I'm going to say that I think this is better handled in your code than automatically by the library.
