### ISSUE TITLE
Make plugins does not work m1 mac 

### ISSUE THREAD

**Issue by zseamgen** [grpc/grpc-swift#1486]
### What are you trying to achieve?

I am just trying to use the library so when I run: 

`protoc --swift_out=. test.proto`

it creates .grpc file. 

### What have you tried so far?

I have gone over the README carefully for a few days now. 

PER THE README: 

To build the plugins, run make plugins in the main directory. This uses the Swift Package Manager to build both of the necessary plugins: protoc-gen-swift, which generates Protocol Buffer support code and protoc-gen-grpc-swift, which generates gRPC interface code.

To build the plugins, run make plugins in the main directory.

in my project directory I am running `make plugins`

I get: 

make: *** No rule to make target `plugins'.  Stop.

I have added the project via SPM: 

<img width="1084" alt="Screen Shot 2022-09-19 at 4 37 26 PM" src="https://user-images.githubusercontent.com/91335927/191137344-33920122-4a22-4b59-8edd-db26c5e23191.png">

Note: checking the box for protoc-gen-grpc-swift does not work for m1 macs. 

Is this the issue? 

Thanks

Note: this is not related to https://github.com/grpc/grpc-swift/issues/1451

**Comment by FranzBusch** [comment]
Hey @zseamgen,

Our documentation could be a little clearer here but when we mean run `make plugins` in the root directory we did not mean that you run it in your project directory. What we meant with this is that you clone this repo here and then run `make plugins` inside the root of the cloned repo. This will then build the plugins for you.

However, I would also like to point you to [this document](https://github.com/grpc/grpc-swift/blob/main/Sources/protoc-gen-grpc-swift/Docs.docc/spm-plugin.md) which allows you to generate the files on the fly by using our new SPM plugin. There are some caveats that are outlined in the doc how to use it and it might also be a possibility for you. If you are going this route you also want to sue the [swift-protobuf plugin](https://github.com/apple/swift-protobuf/blob/main/Sources/protoc-gen-swift/Docs.docc/spm-plugin.md)

**Comment by glbrntt** [comment]
Franz is absolutely right here and using the new SPM plugin he linked is the easiest way forward here. However, I'd like to clear up one thing in case anyone else comes across this:

> ### What are you trying to achieve?
> I am just trying to use the library so when I run:
> 
> `protoc --swift_out=. test.proto`
> 
> it creates .grpc file.

This will _not_ create a .grpc file. 

`protoc --swift_out=. test.proto` will only generate messages using the SwiftProtobuf plugin. The `swift` part of the `--swift_out` option is telling `protoc` to use the `protoc-gen-swift` plugin. 

To generate .grpc files (i.e. client and service code) you will need to use the `--grpc-swift_out` option (which tells `protoc` to use the `protoc-gen-grpc-swift` plugin). This [documentation](https://github.com/grpc/grpc-swift/blob/main/docs/plugin.md) covers the various options for the `protoc-gen-grpc-swift` plugin and includes a few examples of how to invoke `protoc` with it.
