### ISSUE TITLE
gRPC support for watchOS 9?

### ISSUE THREAD

**Issue by martinwennerberg** [grpc/grpc-swift#1491]
Is gRPC deprecated for watchOS 9?

I'm working on an app that's available on watch OS and iOS. gRPC has been working for me until recently on watch devices and still works great on iOS and in the simulator, but after upgrading the device to watchOS 9 the channels don't seem to get any incoming traffic and times out after a couple of minutes. `NIOCore.ChannelError.connectTimeout(NIOCore.TimeAmount(nanoseconds: 20000000000)`

I also started a thread at https://developer.apple.com/forums/thread/715581 which links to a couple of other threads about WebSockets no longer working on watchOS. I guess it might be related?

Should I give up on using gRPC on watchOS or perhaps file a bug? Does it work for anybody else?

**Comment by glbrntt** [comment]
It isn't deprecated, no. But there are limitations to using NIO on watchOS. 

See https://github.com/apple/swift-nio/issues/2255, in particular these comments:

- https://github.com/apple/swift-nio/issues/2255#issuecomment-1247797826
- https://github.com/apple/swift-nio/issues/2255#issuecomment-1249791973

**Comment by martinwennerberg** [comment]
Thanks for the clarification. We had based our hole cloud architecture on gRPC, and it’s not an audio streaming app, but a car remote. Back to the drawing board then…

**Comment by glbrntt** [comment]
It may be worth considering something like [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) and using JSON over HTTP on watchOS and gRPC elsewhere.

**Comment by mwurm293** [comment]
hi @glbrntt - is gRPC / Swift NIO supported by App Clips ? Im running the same 'createAccountRequest' from my App Clip and my App, and the App completes in milliseconds, while the App Clip times out after 30s.

**Comment by NighWish** [comment]
> hi @glbrntt - is gRPC / Swift NIO supported by App Clips ? Im running the same 'createAccountRequest' from my App Clip and my App, and the App completes in milliseconds, while the App Clip times out after 30s.
> 
> Is NIO-TS supported by App Clips? If yes, any recommendations on migrating from NIO > NIO-TS ?

I have the same problem. Have you solved it? Is grpc really no longer usable in App Clip?

**Comment by mwurm293** [comment]
We moved to NIO-TS which worked
