### ISSUE TITLE
ServerStreamingCall: Method cannot be declared public because its parameter uses an internal type

### ISSUE THREAD

**Issue by Amit011121** [grpc/grpc-swift#1494]
### Describe the bug

I'm using `ServerStreamingCall` in my file but i am getting error:
Method cannot be declared public because its parameter uses an internal type

find the attachment

<img width="577" alt="Screenshot 2022-09-29 at 5 31 37 PM" src="https://user-images.githubusercontent.com/93518287/193026050-edb2825b-0b3b-437e-ac30-d0d9bd7fd595.png">

**Comment by glbrntt** [comment]
Can you provide more details? Which method cannot be declared public?

**Comment by Amit011121** [comment]
that was our custom method which not allowing to declare public

**Comment by glbrntt** [comment]
Okay, so your method is using an internal type and this is not a grpc bug.
