### ISSUE TITLE
Generated .pb and .grpc swift files from .proto, getting build errors in .grpc file

### ISSUE THREAD

**Issue by ajdali** [grpc/grpc-swift#1497]
### What are you trying to achieve?

I am trying to generate the swift files from .proto to use as a client. I am trying to make a unary rpc and get the code to compile

### What have you tried so far?

Ran
 protoc example_service.proto --swift_out=Generated/
protoc example_service.proto --grpc-swift_out=Generated/

Getting several errors, many of the type like 
Value of type 'Self' has no member 'makeUnaryCall'
Value of type 'Self' has no member 'defaultCallOptions'
Non-class type 'PersistDotNetLib_BackupAsyncClient' cannot conform to class protocol 'PersistDotNetLib_BackupAsyncClientProtocol'
'PersistDotNetLib_BackupClientProtocol' requires that 'PersistDotNetLib_BackupClient' inherit from 'GRPCClient'
Type 'PersistDotNetLib_BackupClient' does not conform to protocol 'PersistDotNetLib_BackupClientProtocol'

I am thinking there is some interoperability issues as I am using latest Swift 5.7, and XCode 14. Any ideas?

**Comment by Lukasa** [comment]
What version of the grpc-swift and swift-protobuf protoc plugins do you have installed?

**Comment by ajdali** [comment]
@Lukasa thanks for the response. I bumped the version up 1.11.0 and that resolved all errors
