### ISSUE TITLE
How can I set a custom status and message in response?

### ISSUE THREAD

**Issue by bartekpacia** [grpc/grpc-swift#1500]
### What are you trying to achieve?

I want to set a custom _code_ and _description_ in my gRPC server implemented in Swift. Thanks to this my client will be able to present better error messages which are actionable for my users.

### What have you tried so far?

My current workaround is that I have the following function:
```swift
private func runCatching<T>(_ block: () async throws -> T) async throws -> T {
  do {
    return try await block()
  } catch let err {
    // TODO: Try to do this with an Interceptor, like on Android
    throw GRPCError.InvalidState("\(err)")
  }
}
```

and use it like this in my method handlers:

```swift
func pressHome(
  request: Empty,
  context: GRPCAsyncServerCallContext
) async throws -> DefaultResponse {
  return try await runCatching {
    try automation.pressHome()
    return DefaultResponse()
  }
}
func pressBack(
  request: Empty,
  context: GRPCAsyncServerCallContext
) async throws -> DefaultResponse {
  return try await runCatching {
    throw PatrolError.generic("pressBack() is not supported on iOS")
  }
}
```

On Android (where I also have a gRPC server)  I've used interceptors for this, but I had no luck using an interceptor on iOS.

See also:
- [my implementation of interceptor on Android](https://github.com/leancodepl/patrol/blob/master/AutomatorServer/android/app/src/androidTest/java/pl/leancode/automatorserver/LoggerInterceptor.kt). I'd like to have the same functionality on iOS.

**Comment by Lukasa** [comment]
Can you clarify what's not working? Your example generates `internal error (13)` with the message "Invalid state: <your error description>". What are you expecting to happen, and what are you actually seeing?

**Comment by bartekpacia** [comment]
> our example generates internal error (13) with the message "Invalid state: "

Yeah, and I'd like to be able to generate error (=create instance of `GRPCError`) with status `NOT_FOUND` and a fully custom message, not prefixed with "Invalid state: " etc. If there is a way to do this, I haven't found it – I'm still quite new to Swift.

Ideally, I'd like to see generic interceptors implemented. See #1148.

**Comment by Lukasa** [comment]
So you can create any error you like and conform it to `GRPCStatusTransformable`, and have it return the appropriate information. For example:

```swift
struct MyError: GRPCStatusTransformable {
    func makeGRPCStatus() -> GRPCStatus {
        return GRPCStatus(code: .notFound, message: "Whatever message you want")
    }
}
```

**Comment by bartekpacia** [comment]
Thanks for helping me @Lukasa, yours solution works fine!
