### ISSUE TITLE
gRPC client won't connect to server: failed: deadlineExceeded(connectionError: Optional(unavailable (14): Unexpected connection drop))

### ISSUE THREAD

**Issue by tarac99** [grpc/grpc-swift#1501]
### What are you trying to achieve?

My gRPC server is running in vDesk localhost on port 8888. From my Mac M1 running macOS 12.6, SSH port forwarding is setup correctly (verified using `nc -zv 127.0.0.1 8888` that it succeeds). I can use **grpcurl -insecure** to send a request successfully for the same service from my Mac to the remote server. 
But my Swift gRPC insecure client using the same proto wont send the request and keep getting `failed: deadlineExceeded(connectionError: Optional(unavailable (14): Unexpected connection drop))`. No certs involved here to keep things simple for debugging. I spent a lot of time debugging and couldn’t get around even after reading docs and other online posts.

### What have you tried so far?

 **library and protoc plugin versions**
grpc-swift 1.11.0

Client :
```swift
class GRPCServiceManager {
    var grpcService: InventoryManagementServiceNIOClient?

    init(iasServer: String = "127.0.0.1", port: Int = 8888) {
        let eventLoopGroup = PlatformSupport.makeEventLoopGroup(loopCount: 1)
        let channelLogger = Logging.Logger(label: "mac_device_check.Channel")
        do {
            // open a channel to the gPRC server
            // let tlsConfig = GRPCTLSConfiguration.makeClientConfigurationBackedByNIOSSL()
            print("Connecting to \(iasServer):\(port)")
            let channel = try GRPCChannelPool.with(
                target: .host(iasServer, port: port),
                transportSecurity: .plaintext,
                eventLoopGroup: eventLoopGroup
            ) {
                $0.backgroundActivityLogger = channelLogger
            }

            let clientLogger = Logging.Logger(label: "mac_device_check.Client")
            let callOptions = CallOptions(timeLimit: .timeout(.seconds(20)), logger: clientLogger)
            // create a Client
            self.grpcService = InventoryManagementServiceNIOClient(channel: channel, defaultCallOptions:callOptions)
            print("gRPC connection initialized")
        } catch {
            printStderr("Couldn’t setup connection to gRPC server")
        }
    }

```
I am making a client req like:
```swift
// grab the addDevice() method from the gRPC client
let call = self.grpcService!.addDevice(req)

do {
            print("rpc path: \(call.path)")
            resp = try call.response.wait()
        } catch {
            printStderr("RPC method ‘addDevice()’ failed: \(error)")
       }
}
```

Output:
```
rpc path: /InventoryManagementService/AddDevice
RPC method ‘addDevice()’ failed: deadlineExceeded(connectionError: Optional(unavailable (14): Unexpected connection drop))
```

**Full `protoc` invocation** 
`protoc --grpc-swift_out=. api.proto`
`protoc --swift_out=. api.proto` 

I don't see any extra GRPC logging in Console.app.

Network logs:
```
info	13:34:23.761604-0700	mac_device_check	com.apple.network	libnetwork.dylib	nw_endpoint_handler_cancel [C5 127.0.0.1:8888 ready socket-flow (satisfied (Path is satisfied), viable, interface: lo0)]
info	13:34:23.761657-0700	mac_device_check	com.apple.network	libnetwork.dylib	nw_association_schedule_deactivation <nw_association 127.0.0.1:8888> will become dormant after 10000ms of inactivity
default	13:34:23.761682-0700	mac_device_check	com.apple.network	libnetwork.dylib	nw_flow_disconnected [C5 127.0.0.1:8888 cancelled socket-flow ((null))] Output protocol disconnected
default	13:34:23.761730-0700	mac_device_check	com.apple.network	libnetwork.dylib	nw_connection_report_state_with_handler_on_nw_queue [C5] reporting state cancelled
```

I have disabled firewall, allowed App Transport Security to allow local network connections, disabled App Sandbox but of no success.

**Comment by Lukasa** [comment]
grpcurl's option `--insecure` is not equivalent to `transportSecurity: .plaintext`. The setting you've provided grpc-swift attempts to not use TLS at all, but grpcurl `--insecure` simply doesn't validate the certificates presented via TLS. It still does a TLS handshake though.

Change your settings to `transportSecurity: .tls(.makeClientConfigurationBackedByNetworkFramework(verifyCallbackWithQueue: ( { _, _, callback in callback(true) }, DispatchQueue(label: "verify queue"))))`. This should disable certificate verification.

**Comment by tarac99** [comment]
That worked fine. Thanks you so much @Lukasa.

**Comment by SufiHarris** [comment]
i tried this bt its not working in my case
