### ISSUE TITLE
How to access `trailers` if an rpc call is failed?

### ISSUE THREAD

**Issue by NoFearJoe** [grpc/grpc-swift#1502]
Our backend puts a [Google error model](https://cloud.google.com/apis/design/errors#error_model) into `trailers`.
I'm trying to extract `trailers` from an error that I get if an rpc call is failed.
```
do {
    let response = try await service.exampleWithGoogleErrorHandling(.init())
                
    print(response)
} catch {
    if let grpcError = error as? GRPCStatusTransformable {
        print(grpcError.makeGRPCStatus()) // 1
    } else {
         print(error)
    }
}
```
On the line marked with `1` I get a `GRPCStatus`, but it doesn't contain the `trailers` property (but, for example, grpc-java does).

Is there a way to get `trailers`?

**Comment by Lukasa** [comment]
Yes: if you use the `makeCall` interface then you will get back one of the call objects (in your case, probably `GRPCAsyncUnaryCall`). This will let you get any trailing metadata. For example:

```swift
let call = service.makExampleWithGoogleErrorHandlingCall(.init())

do {
    let response = try await call.response
} catch {
    let trailers = try await call.trailingMetadata
    // Do what you want here.
}
```

**Comment by NoFearJoe** [comment]
Thank you!
