### ISSUE TITLE
HelloWorldServer doesn't work from the main branch

### ISSUE THREAD

**Issue by mycroftcanner** [grpc/grpc-swift#1511]
### Describe the bug

The HelloWorldServer doesn't work from the main branch or from 1.9.0:

### To reproduce

Steps to reproduce the bug you've found:
1. git clone -b  1.11.0 https://github.com/grpc/grpc-swift or git clone https://github.com/grpc/grpc-swift
2. cd grpc-swift
3. swift run HelloWorldServer                   

Describe what you expect to happen when the steps above are followed.

We would expect 

```
[973/973] Linking HelloWorldServer
[...]
Building for debugging...
Build complete! (60.57s)
server started on port 1234
```

Instead the command just returns:

```
[973/973] Linking HelloWorldServer
[...]
[1029/1029] Linking HelloWorldServer
Build complete! (30.42s)
```

swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: arm64-apple-macosx13.0

**Comment by mycroftcanner** [comment]
Please that 1.0.0 works fine.

**Comment by Lukasa** [comment]
Thanks for this! Try adding `@main` as shown in #1505. We reverted that temporarily because it broke our Swift 5.5 build, but that’s the correct fix.
