### ISSUE TITLE
[NWOSAddressEndpoint port] when using a unix socket

### ISSUE THREAD

**Issue by mycroftcanner** [grpc/grpc-swift#1514]
### Describe the bug

Using latest grpc-swift, I managed to create a grpc client that talks to a grpc server over a unix domain socket.

It works perfectly however I see about 10 messages saying :

```
-[NWOSAddressEndpoint port] Can't fetch port for address family: 1
```

### To reproduce

Here is the code for the client.

```swift
        let manager = FileManager.default
        let home = manager.currentDirectoryPath
        
        // there is a 108 character limit on unix domain socket path length.
        manager.changeCurrentDirectoryPath(
          manager.temporaryDirectory
            .appendingPathComponent("com.x.y").path
        )
        
        let group = PlatformSupport.makeEventLoopGroup(loopCount: 1)
        
        if let channel = try? GRPCChannelPool.with(
          target: .unixDomainSocket("y.socket"),
          transportSecurity: .plaintext,
          eventLoopGroup: group
        ) {
          let client = Y_HaberdasherAsyncClient(channel: channel)
        
          let hat = try await client.makeHat(.with { $0.inches = 32 })
          print(hat)
                    
          manager.changeCurrentDirectoryPath(home)
          try group.syncShutdownGracefully()
        }
```

### Expected behaviour

There seems to be some verbose debugging somewhere and I can't figure out how to disable and I don't think it should try to get the port number for a unix socket.

### Additional information

Include any information that you think might help us to diagnose and resolve
this more quickly, such as logs, code snippets, or similar cases where the bug
does not reproduce. (Please wrap code snippets and logs in backticks though!)

**Comment by Lukasa** [comment]
I’m afraid we don’t control those logs, they come from Network.framework. Please file an issue using Feedback Assistant: https://feedbackassistant.apple.com/. 

Note that these logs will not appear in terminal, they’re logged to the system logger.
