### ISSUE TITLE
SPM Plugin to generate grpc files

### ISSUE THREAD

**Issue by adriantabirta** [grpc/grpc-swift#1521]
Problem: 

When it comes to build a new app using GRPC it's always this headache to copy proto files, check folders and tune script into Xcode project to be able to generate files for iOS client.

Solution you'd like:

A great solution would be to add a SPM plug-in to Package.swift to be able to use it later in own SPM lib to generate whole swift client.
To current repo in the root should be added a Plugins folder, please check [here](https://betterprogramming.pub/implement-your-first-swift-package-build-plugin-9835a7aded0b) an example. This plugin will recursively go through package folders to find Proto folder and using that to generate GrpcClient at least for iOS.

Could be completed with other plugins such as GrpcServer.

**Comment by Jerry-Carter** [comment]
Have you looked at the current plugins?

`        .target(
            name: "Model",
            dependencies: [
                .product(name: "GRPC", package: "grpc-swift"),
            ],
            exclude: [
                "grpc-swift-config.json",
                "swift-protobuf-config.json",
            ],
            plugins: [
                .plugin(name: "SwiftProtobufPlugin", package: "swift-protobuf"),
                .plugin(name: "GRPCSwiftPlugin", package: "grpc-swift"),
            ]
        ),`

While these don't recursively go through the project file, they nicely build any .proto files specified in 'graph-swift-config.json' and 'swift-protobuf-config.json'.

**Comment by adriantabirta** [comment]
@Jerry-Carter Thank you, do you have any idea where I can find examples for 'graph-swift-config.json' and 'swift-protobuf-config.json'?

**Comment by glbrntt** [comment]
The docs include examples: https://github.com/grpc/grpc-swift/blob/main/Sources/protoc-gen-grpc-swift/Docs.docc/spm-plugin.md

**Comment by adriantabirta** [comment]
@glbrntt thank you for the answer, everything work great, already have files generated into plug-in folder, just want to ask if there is a chance to generate into SPM/Sources/... all grpc files to be able to used them outside?

**Comment by FranzBusch** [comment]
@adriantabirta That‘s not possible with SPM plugins. They strictly allow to generate files into a a directory outside the repo which just the build system uses.

if you want to check them in, you have can do this by manually generating the files with protoc and the gRPC plug-in for it.
