### ISSUE TITLE
Is there any way to use plugin with nested imports?

### ISSUE THREAD

**Issue by adriantabirta** [grpc/grpc-swift#1525]
I would like to separate `services` from `messages` so is tried to add in proto files `import "request.proto";` - does not work.

I know that in command line I could specify full path to files - how can I achieve that using  grpc / swift profotbuf plugin ?

**Comment by glbrntt** [comment]
The import needs to be the _relative_ path of `request.proto` within the target directory, e.g. if you have:

```
.
├── Package.swift
└── Sources
    └── MyTarget
        └── proto
            ├── request.proto
            └── service.proto
```

Then in `service.proto` you will need `import "proto/request.proto";`.

See also: 
- Docs for gRPC plugin: https://github.com/grpc/grpc-swift/blob/main/Sources/protoc-gen-grpc-swift/Docs.docc/spm-plugin.md#adding-the-proto-files-to-your-target
- Docs for protobuf plugin: https://github.com/apple/swift-protobuf/blob/main/Sources/protoc-gen-swift/Docs.docc/spm-plugin.md
