### ISSUE TITLE
Use of ServerQuiescingHelper inadvertently suppresses errors from bind

### ISSUE THREAD

**Issue by Lukasa** [grpc/grpc-swift#1542]
(Sourced from #1540)

When we attempt to bind a socket we create a `ServerQuiescingHelper` and attempt to use it in the bound channel. If the call to `bind` produces an immediate error, however, we will never see the `serverChannelInitializer` get called, and the internal promise will leak. This causes an immediate crash.

We should change the way we hold `ServerQuiescingHelper` to avoid this promise being unresolved, in order to prevent errors being hidden by the crash.

**Comment by glbrntt** [comment]
This is a general problem with the `ServerQuiescingHelper` which the example runs into as well (https://github.com/apple/swift-nio-extras/blob/54def83a52da31c01dfc028ec26927b69a8e9cf8/Sources/NIOExtras/QuiescingHelper.swift#L201-L216):

- We need to hold on to the `ServerQuiescingHelper` to call `initiateShutdown(promise:)`
- The promise being leaked is only ever succeeded by calling `makeServerChannelHandler(channel:)` which requires a `Channel`. 


A few possible solutions:
1. Delay initialising the `ServerQuiescingHelper` until the `serverChannelInitializer` and grab it in a promise (which we would fail if the bind fails).
2. Add API to `ServerQuiescingHelper` (on `deinit`?) which fails its promise which we would call if `bind` fails.

I think the second option is better: it's slightly easier for other users of `ServerQuiescingHelper` to pick up and easy to document via the example.

**Comment by Lukasa** [comment]
Agreed: I think doing number 2 would be interesting.

**Comment by glbrntt** [comment]
This was fixed in NIOExtras 1.17.0 (https://github.com/apple/swift-nio-extras/releases/tag/1.17.0)
