### ISSUE TITLE
Missing required module 'CNIOAtomics'

### ISSUE THREAD

**Issue by jvigneshcs** [grpc/grpc-swift#1551]
### What are you trying to achieve?

I am working on small Xcode Framework project using [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-swift) client.
I have to share the XCFramework with the client app and they will add the opentelemetry-swift dependency using SPM.

### What have you tried so far?

I have set **Build Libraries for Distribution** to **YES**,
so I get the following warning in my Framework project

> Module 'GRPC' was not compiled with library evolution support; using it means binary compatibility for 'OtelWrapper' can't be guaranteed

When I include the XCFramework of the framework project in my Sample iOS app, I get the following errors,

> error: missing required module 'CNIOAtomics'
error: failed to build module 'OtelWrapper' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug

You can find the sample framework project and iOS app project that can reproduce the above errors [here](https://github.com/jvigneshcs/otelwrapper)

#### Related links

[opentelemetry-swift - issue - 364](https://github.com/open-telemetry/opentelemetry-swift/issues/364)
[grpc-swift - issue - 683](https://github.com/grpc/grpc-swift/issues/683)

**Comment by Lukasa** [comment]
grpc-swift does not support being built with BUILD_LIBRARY_FOR_DISTRIBUTION=YES. It must be disabled. See also https://github.com/grpc/grpc-swift/issues/1063#issuecomment-738756876

**Comment by Lukasa** [comment]
Note that you can still depend on grpc-swift from within an ABI-stable library, but you must import grpc-swift (and all its dependencies) using `@_implementationOnly import`.

**Comment by jvigneshcs** [comment]
[Underscored attributes](https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md)
If we use `@_implementationOnly` will we face any issue while submitting our app with Apple App store?
