### ISSUE TITLE
Could not find module 'SwiftProtobuf' for target 'arm64-apple-tvos'; found: arm64-apple-tvos-simulator, x86_64-apple-tvos-simulator.

### ISSUE THREAD

**Issue by akshayiosdeveloper** [grpc/grpc-swift#1554]
I am facing this issue after updating the Xcode 14.2 . I am using Macbook Air M2
Also I have tried to set Build Active Architecture Only true or false both but didn't work for me.
Any idea about how to fix this issue

**Comment by Lukasa** [comment]
I'm afraid this sounds like an Xcode issue. You could try the various usual methods for cleaning your Xcode state, such as deleting derived data, but for support with Xcode I recommend using Apple's developer forums at developer.apple.com.
