### ISSUE TITLE
Client Side NIOSSLCertificates Not Showing Up in TLS Handshake

### ISSUE THREAD

**Issue by WiseNN** [grpc/grpc-swift#1562]
### Describe the bug

I am attaching NIOSSLCertificates (client-side), but they are not showing up in the TLS handshake. I have attached them a few different ways, but have settled on this. I don't think there is much to elaborate on, please let me know if more detail is required. 

### To reproduce
Here is my gRPC TLS Configuration object and client connection object
```swift
        var tlsConfig = TLSConfiguration.makeClientConfiguration()
          ...
        tlsConfig.trustRoots = .certificates([nioCert!])
        
        let clientConfig = GRPCTLSConfiguration.makeClientConfigurationBackedByNIOSSL(configuration: tlsConfig)
         
         clientConnection = ClientConnection.usingTLS(with: clientConfig, on: eventLoopGroup)                                
        }
```

### Expected behaviour
When monitoring the network traffic, I expect to see: 
```
Client Certificates: 1
Server Certificates: 3
```

Instead, I see: 
```
Client Certificates: - 
Server Certificates: 3
```

**Comment by Lukasa** [comment]
The [`.trustRoots`](https://swiftpackageindex.com/apple/swift-nio-ssl/main/documentation/niossl/tlsconfiguration/trustroots) property controls the certificates used to validate the remote peer, not the client certificates. You want to set [`.certificateChain`](https://swiftpackageindex.com/apple/swift-nio-ssl/main/documentation/niossl/tlsconfiguration/certificatechain) and [`.privateKey`](https://swiftpackageindex.com/apple/swift-nio-ssl/main/documentation/niossl/tlsconfiguration/privatekey).
