### ISSUE TITLE
transport became inactive error in specific case

### ISSUE THREAD

**Issue by tedKim5178** [grpc/grpc-swift#1576]
When I request two calls in a row, it always gives me "transport inactive error" on second call.
When I give little delay on second call, it success. 

This is my setting.

```swift
let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
        let keepalive = ClientConnectionKeepalive(
            interval: .seconds(Constants.GRPC_KEEP_ALIVE),
            timeout: .seconds(Constants.GRPC_TIMEOUT),
            permitWithoutCalls: true
        )
        let tls = ClientConnection.Configuration.TLS(
            certificateChain: [],
            privateKey: nil,
            trustRoots: .default,
            certificateVerification: .none,
            hostnameOverride: nil)
        
        let connectionBackoff = ConnectionBackoff()//ConnectionBackoff(retries: .upTo(Constants.GRPC_RETRY_COUNT))
        var configuration = ClientConnection.Configuration(
            target: .hostAndPort(host, port),
            eventLoopGroup: group,
            tls: tls,
            connectionBackoff: connectionBackoff,
            connectionKeepalive: keepalive
        )
        
        configuration.target = .hostAndPort(host, port)
        
        let logger = Logging.Logger(label: "mk. grpc")
        configuration.backgroundActivityLogger = logger
        configuration.connectionIdleTimeout = .zero
        let channel = ClientConnection(configuration: configuration)
        self.client = RiderClient(channel: channel)
```

I know it works when I set connectionIdleTimeout as default or some long time, but I just don't understand it does not work when I set it to .zero.

As I understanding, it should work like this below.

1. request first call (connection open)
2. first call ended (connection idle , and closed (because I connectionIdleTimeout = .zero))
3. (as soon as I get first call response) request second call (connection re-open) 
4. second call ended (connection idle, and closed)

but it gives me an error (works like below)

1. request first call (connection open)
2. first call ended (connection idle , and closed (because I connectionIdleTimeout = .zero))
3. (as soon as I get first call response) request second call (connection should be open but not open and gives me an error)  
4. get error 

why is this happening? Am I missing something?

**Comment by Lukasa** [comment]
I'd recommend using `GRPCChannelPool` instead of `ClientConnection`. `ClientConnection` is prone to these kinds of errors because it doesn't have the ability to set up a second connection while the first one is closing.

I will say that an idle timeout of zero is probably not a good setting, but nonetheless I'd be more inclined to expect that this will work with `GRPCChannelPool`.

**Comment by tedKim5178** [comment]
@Lukasa  thanks for your reply. Just one more question please. 
On same environment as above, When I request UnaryCall which takes about 5 seconds, rarely connection disconnected and give "transport became inactive" error before I get the response. Is this known issue or bug or something? Is there any chance that this situation get better when I use GRPCChannelPool instead of ClientConnection also?

**Comment by Lukasa** [comment]
`GRPCChannelPool` may improve your reliability here. We don't have any known bugs in this area: you'd need to use Wireshark to work out what is happening to the connection to diagnose further.

**Comment by tedKim5178** [comment]
@Lukasa Okay. Thanks. Have a good one.
