### ISSUE TITLE
gRPC-Web Error 

### ISSUE THREAD

**Issue by mannuch** [grpc/grpc-swift#1580]
Hello!
I've been trying out the gRPC-Web support but I keep running into the error response:
```
{
   "code": "unknown",
   "message": "internal: gRPC protocol error: no Grpc-Status trailer"
}
```

As first, I thought it might've been my own application's issue, however, I have confirmed that this still happens using this repo's `Echo` example.

If it helps, I have been using the [Buf curl](https://buf.build/docs/curl/usage/) CLI tool to invoke the RPC endpoints. Here's an example of the  `--verbose` output from the tool, invoking the `Echo` example with the gRPC-Web protocol:
```
~/../grpc-swift/Sources/Examples/Echo

buf curl -v \
--schema Model/echo.proto \
--protocol grpcweb \
http://localhost:8080/echo.Echo/Get
buf: * Invoking RPC echo.Echo.Get
buf: * Dialing (tcp) localhost:8080...
buf: * Connected to [::1]:8080
buf: > (#1) POST /echo.Echo/Get
buf: > (#1) Accept-Encoding: identity
buf: > (#1) Content-Type: application/grpc-web+proto
buf: > (#1) Grpc-Accept-Encoding: gzip
buf: > (#1) Grpc-Timeout: 119994m
buf: > (#1) User-Agent: buf/1.15.1 grpc-go-connect/1.5.2 (go1.19.2)
buf: > (#1)
buf: } (#1) [5 bytes data]
buf: * (#1) Finished upload
buf: < (#1) HTTP/1.1 200 OK
buf: < (#1) Access-Control-Allow-Origin: *
buf: < (#1) Content-Type: application/grpc-web+proto
buf: < (#1)
buf: { (#1) [5 bytes data]
buf: { (#1) [18 bytes data]
buf: < (#1)
buf: < (#1) Grpc-Status: 0
buf: * (#1) Call complete
{
   "code": "unknown",
   "message": "internal: gRPC protocol error: no Grpc-Status trailer"
}
```

Additionally, I have confirmed that the RPC method handlers do, in fact, get called, it's just that the client receives the error message noted above.

I have also tried simply running the `EchoWeb` example, which creates a web client that invokes the `Echo` server, however I don't see any response from the server when running the example.

Any thoughts on what could going on here?

Thank you for all the work on this!

### Versions
grpc-swift 1.14.2
M1 Pro, macOS 13.2.1

**Comment by glbrntt** [comment]
Something odd is going on: the error message "gRPC protocol error: no Grpc-Status trailer" conflicts with the verbose logs:

```
buf: < (#1) Grpc-Status: 0
buf: * (#1) Call complete
```

Could you capture the exchange in wireshark?

**Comment by mannuch** [comment]
Thanks for the quick reply!

Yeah, it's definitely pretty strange that the logs display the `grpc-status` while complaining about no `grpc-status` trailer.

I've just run an example with the `Echo` server, capturing the packets via a `NIOWritePCAPHandler`.

Opening the gRPC response packet, I can see the returned `grpc-status` in the `trailer-part` of the message:

<img width="1530" alt="Screenshot 2023-03-28 at 2 02 46 PM" src="https://user-images.githubusercontent.com/24771225/228367109-20c82701-410e-4100-b995-18c7425c13b8.png">

I'm wondering if the trailers returned by the server are somehow not where the client expects them to be. I am quite unfamiliar with the low-level details of the protocols in question, but maybe the gRPC-Web client expects the trailers to just be in the last part of the response's body or something, as opposed to being in the HTTP/1.1 trailer portion. If it's helpful, I can also share more aspects of the `.pcap` file.

From looking through the `GRPCWebToHTTP2ServerCodec` channel handler, it appears that the trailer encoding is handled differently depending on the `content-type`. With `application/grpc-web-text`, the trailers are attached to the response's body, whereas when encountering `application/grpc-web`, the trailers are added as regular HTTP/1 trailers. Given that in this exchange I'm dealing with `application/grpc-web`, I'm wondering if this difference is where the problem is arising from. 

That being said, I'm not entirely sure if the fault lies with grpc-swift or the client.

Also, I did see that in grpc-swift's `ServerWebTests` there is a `// TODO: Add tests for application/grpc-web as well.` comment so maybe we've just uncovered an untested case.

I appreciate the help on this! Like I said above, I'm really not very familiar with these kinds of details, so if I'm just completely misunderstanding something I apologize.

**Comment by glbrntt** [comment]
I think you're right, looking at the [grpc-web spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md):

> 1. Response status encoded as part of the response body
>   * Key-value pairs encoded as a HTTP/1 headers block (without the terminating newline), per https://tools.ietf.org/html/rfc7230#section-3.2
>   ```
>     key1: foo\r\n
>     key2: bar\r\n
>   ```
> 2. 8th (MSB) bit of the 1st gRPC frame byte
>   * 0: data
>   * 1: trailers
>   ```
>     10000000b: an uncompressed trailer (as part of the body)
>     10000001b: a compressed trailer
>   ```
> 3. Trailers must be the last message of the response, as enforced
> by the implementation

We don't encode the trailers as a part of the response body as a length-prefixed message on this path which I think is the bug here.
