### ISSUE TITLE
Retry the call inside an interceptor

### ISSUE THREAD

**Issue by havebeenfitz** [grpc/grpc-swift#1581]
### What are you trying to achieve?

Hi, I have a certain business flow, and I can't get my head around it using the grpc-swift. I need to make any call and catch a certain error, then I need to "confirm" the call with another one, and when the confirmation call is successful, I need to retry the initial call and modify it with certain headers. So the pipeline will look something like this:

1. Make the initial call 
2. If Intercepted NeedsConfirmation error
    - pause the initial call, or fail it silently
    - make another call to confirm the initial one
3. If the confirmation call is successful  
    - modify the initial call with additional headers
    - retry the initial call with modifications

I see that https://github.com/grpc/grpc-swift/pull/1002 provided some sort of low-level call initialization, but how can I achieve that through interceptors? Should I have a reference to my GRPCChannel in the interceptor? Am I required to handle all of the `call.send(..)` parts as well? I will appreciate some guidance here, cause I didn't find anything in the documentation so far.

### What have you tried so far?

I can catch the initial error through the interceptor, and I'm able to retry the call manually on the call site every time. But is it possible to create a call inside the interceptor to make this solution generic and work for any call?

On the call site so far:

```swift
let result = await SomeService.makeCall(...).response.result // 1. Try to make an unary call

switch result {
   case .error:
        if case let ConfirmationError.needsConfirmation(error) = error { // 2. Catch a specific error
            let result = await confirmRequest() // 3. Handle an error by making another call. Requires a user input, handled separately 
            switch result {
            case .success:
                 let result = await SomeService.makeCall(..., callOptions: additionalCallOptions).response.result // 4. Retry the initial call with some modifications
                 ...
        }
    ...
}
```

P.S. all this is required for a client application, i.e. iOS app if that's helpful. Quite similar to the refresh token mechanism, where we exchange a refresh token for a new auth token and seamlessly try to retry the failed initial call, but it's not quite it

**Comment by glbrntt** [comment]
Is the `NeedsConfirmation` error represented by a gRPC status?

If so I think your flow within an interceptor is very similar to this: https://github.com/grpc/grpc-swift/blob/03b3f1fc38dce26fe405fa894de04bb7aa92f1c3/Tests/GRPCTests/InterceptorsTests.swift#L220-L321

> Should I have a reference to my GRPCChannel in the interceptor? 

Yes, you can use this to construct a new `Call` to replay messages to.

**Comment by havebeenfitz** [comment]
It's represented by the `permissionDenied` status 7 and some headers, but your example is exactly what I need, thanks a lot!
