### ISSUE TITLE
Client/server stream gets stuck after some time on a dead connection

### ISSUE THREAD

**Issue by t089** [grpc/grpc-swift#1590]
Not sure if am missing something, but I am trying to implement a client that "subscribes" to a server stream and then acts on incoming events and sends back a "response" via the client stream.
If an error occurs the client is supposed to just try to restart the "subscribe" call. This mostly works: once the connection dies, the client logs an error, reconnects and continues. But _after a while_ the client does not observe that the connections dies and just sits around without retrying, just waiting for new events on a dead connection. The server reports that the client disconnected, but the client does not show any error. The only way to get out of this state is to restart the whole client process. I am sharing here some code bits, maybe there is an obvious mistake on my part...

```swift

    mutating func run() async throws {
        // ... setup
        
        let elg = MultiThreadedEventLoopGroup(numberOfThreads: 1)

        var channelLogger = Logger(label: "channel")
        channelLogger.logLevel = .debug

        let channel = try GRPCChannelPool.with(target: .host(host, port: port), transportSecurity: transportSecurity, eventLoopGroup: elg) {
            $0.backgroundActivityLogger = channelLogger
        }
        
        let client = AsyncClient(channel: channel)

        let logger = Logger(label: "main")
        
        while true {
            do {
                var streamHandler: StreamHandler!
                
                let stream = AsyncStream<ClientMessage> { continuation in
                    streamHandler = .init(clientStreamContinuation: continuation, logger: logger)
                }
                
                let biStream = client.subscribe(stream)
                
                try await streamHandler.start(serverStream: biStream)
            } catch is CancellationError {
                logger.info("Cancelled")
                break
            } catch {
                logger.error("Error: \(error), will reconnect ...")
                try await Task.sleep(nanoseconds: 2_000_000_000)
            }
        }

        try? await channel.close().get()
        try? await elg.shutdownGracefully()
    }
}


actor StreamHandler {

    let clientStreamContinuation: AsyncStream<ClientMessage>.Continuation
    
    // ...
    
    func start(serverStream: GRPCAsyncResponseStream<ServerMessage>) async throws {
        let registerMessage = ClientMessage.with // ...
        
        self.clientStreamContinuation.yield(registerMessage)
        logger.info("sending register message \(registerMessage)")
        
        for try await message: ServerMessage in serverStream {
            do {
                
                let response = try await someAsyncWorkThatProducesAResponse()
                
                self.clientStreamContinuation.yield(self.requestSuccessMessage(id: message.request.id, response: response))
            } catch {
                logger.info("ERROR: \(error)")
                self.clientStreamContinuation.yield(self.requestFailedMessage(id: message.request.id, error: error))
            }
        }
        logger.info("Server stream finished.")
}
```

Mostly, when the connection dies I see the expected log message "`ERROR: \(error)`" and then the client retries, but sometimes the client just stops outputting anything, the last log message is from GRPC swift and can be hours old. Eg.

```text
2023-04-16T17:07:02+0200 debug channel : connectivity_state=connecting grpc_connection_id=7C9AE5CF-51AB-481C-BB89-32DBA78A0D25/0 poolmanager.id=ObjectIdentifier(0x0000600001708180) [GRPC] activating connection
2023-04-16T17:07:02+0200 debug channel : grpc_connection_id=7C9AE5CF-51AB-481C-BB89-32DBA78A0D25/0 poolmanager.id=ObjectIdentifier(0x0000600001708180) [GRPC] TLS handshake completed, negotiated protocol: h2
2023-04-16T17:07:02+0200 debug channel : alpn=h2 grpc.conn.addr_local=192.168.178.135 grpc.conn.addr_remote=34.*.*.* grpc_connection_id=7C9AE5CF-51AB-481C-BB89-32DBA78A0D25/0 poolmanager.id=ObjectIdentifier(0x0000600001708180) tls_version=tlsv12 [GRPC] TLS handshake completed
2023-04-16T17:07:02+0200 debug channel : grpc.conn.addr_local=192.168.178.135 grpc.conn.addr_remote=34.*.*.* grpc_connection_id=7C9AE5CF-51AB-481C-BB89-32DBA78A0D25/0 h2_settings_initial_window_size=65536 h2_settings_max_concurrent_streams=128 h2_settings_max_frame_size=16777215 poolmanager.id=ObjectIdentifier(0x0000600001708180) [GRPC] HTTP2 settings update
2023-04-16T17:07:02+0200 debug channel : connectivity_state=active grpc_connection_id=7C9AE5CF-51AB-481C-BB89-32DBA78A0D25/0 poolmanager.id=ObjectIdentifier(0x0000600001708180) [GRPC] connection ready
2023-04-16T17:07:02+0200 debug channel : grpc.conn.addr_local=192.168.178.135 grpc.conn.addr_remote=34.*.*.* grpc_connection_id=7C9AE5CF-51AB-481C-BB89-32DBA78A0D25/0 h2_active_streams=1 h2_stream_id=HTTP2StreamID(1) poolmanager.id=ObjectIdentifier(0x0000600001708180) [GRPC] HTTP2 stream created
```

**Comment by glbrntt** [comment]
> But after a while the client does not observe that the connections dies and just sits around without retrying, just waiting for new events on a dead connection. 

Presumably it is waiting at  `for try await message: ServerMessage in serverStream {`?

> The server reports that the client disconnected, but the client does not show any error. The only way to get out of this state is to restart the whole client process. I am sharing here some code bits, maybe there is an obvious mistake on my part...

Your code looks fine, there's nothing obviously wrong there.

> Mostly, when the connection dies I see the expected log message "ERROR: \(error)" and then the client retries, but sometimes the client just stops outputting anything, the last log message is from GRPC swift and can be hours old. Eg.

I think `"ERROR: \(error)"` should only happen if `someAsyncWorkThatProducesAResponse()` throws? If the connection dies and the response stream throws I would expect to see `"Error: \(error), will reconnect ..."`.

**Comment by t089** [comment]
> I think "ERROR: \(error)" should only happen if someAsyncWorkThatProducesAResponse() throws? If the connection dies and the response stream throws I would expect to see "Error: \(error), will reconnect ...".

Yes, you are right, of course.

> Your code looks fine, there's nothing obviously wrong there.

This is already helpful, thanks for taking a look! maybe I am also doing something wrong on the server and don't correctly close the server stream and that's why the client waits indefinitely for the RPC to finish 🤔

**Comment by glbrntt** [comment]
Great, just checking it wasn't something on your end 🙂.

> This is already helpful, thanks for taking a look! maybe I am also doing something wrong on the server and don't correctly close the server stream and that's why the client waits indefinitely for the RPC to finish 🤔

That _shouldn't_ be the case if the client has disconnected. I'll see if I can try to reproduce this today because it sounds like it could be a grpc bug.

**Comment by t089** [comment]
> That shouldn't be the case if the client has disconnected. I'll see if I can try to reproduce this today because it sounds like it could be a grpc bug.

Yeah, I am not sure if it actually _disconnects_, as I don't see any "connection" related logs from the `GRPCChannelPool`. But I definitely see on the server, that the client side stream finished and so the server considers this client "dead" and will not send new events on the server response stream.

**Comment by t089** [comment]
I think I can pretty well reproduce it by letting my client running on a MacBook go to sleep mode for some time ~ 10min while a streaming rpc is ongoing.
After a while the server reports that the client stream completed and will return from the call. But when the Mac wakes up again, it still sits in the RPC and waits for messages. I would expect to see some kind of "channel/rpc closed" error.

**Comment by glbrntt** [comment]
Good point; we don't enable it by default, it's opt-in. Tobias, could you try configuring keepalive on the client?
