### ISSUE TITLE
Assertion Failure in 1.16.0 for code that worked in 1.15.0

### ISSUE THREAD

**Issue by edelabar** [grpc/grpc-swift#1598]
### What are you trying to achieve?

We have a GRPC channel in our iOS app that our load balancer times-out after 2 minutes of inactivity. The following code worked until 1.16.0:

``` swift
let eventsStream = client.readEvents(readEventsRequest)
do {
	for try await grpcEvent in eventsStream {
		delegate?.receivedEvent(grpcEvent)
	}
} catch {
	// Timeout is configured on the load balancer, currently set to 2 min.
	NSLog("Disconnected from GRPC Channel: \(error)")
        // Restart the eventsStream
}
```

The channel is relatively inactive so when the load balancer disconnects, we just reestablish the connection. This worked fine from roughly grpc-swift version 1.8.2 through 1.15.0, but as of 1.16.0 when the exception is caught, the code that closes the connection also [fails an assertion in the GRPC package target](https://github.com/grpc/grpc-swift/blob/main/Sources/GRPC/ConnectionPool/PoolManagerStateMachine%2BPerPoolState.swift#L57) which causes the app to crash.

The assertion failure crash itself doesn't hit our code, it's all in a background thread, but I noticed [this change](https://github.com/grpc/grpc-swift/commit/75b390e901c7d70af9b4c5ca2677e035f00cd1ab#diff-6b6f2e83ee52754ea90920c265817616153a80fc90d77b231754010b39fa6905R382) in 1.16.0 which the assertion failure passes-through, which led me to reverting to 1.15.0. Full commit is here: 75b390e but unfortunately I don't have enough time or understanding to dig into the guts of all this. Any help is greatly appreciated. 

### What have you tried so far?

I've looked through the docs to confirm I'm doing things correctly, and best I can tell I am. Reverting to 1.15.0 solves the problem for now, but I was hoping to figure out if I was doing something wrong or if a regression was introduced in 1.16.0.

**Comment by glbrntt** [comment]
Interesting, we must not be correctly counting streams somehow. We appear to be over-returning streams; we'll need to look into this to understand it better.

**Comment by edelabar** [comment]
If it matters, that log prints: `Disconnected from GRPC Channel: Invalid HTTP response status, but gRPC status was present`. If there is anything I can do to help, or anything I can try please let me know.

**Comment by glbrntt** [comment]
I wasn't able to reproduce this. @edelabar would you be able to run this with a connection pool delegate which logs all the relevant info (something like the snippet below)? This should hopefully provide enough context so we can understand how we reach the assertion failure.

```swift
struct LoggingPoolDelegate: GRPCConnectionPoolDelegate {
  func connectionAdded(id: GRPCConnectionID) {
    print(#function, id)
  }
  
  func connectionRemoved(id: GRPCConnectionID) {
    print(#function, id)
  }
  
  func startedConnecting(id: GRPCConnectionID) {
    print(#function, id)
  }
  
  func connectFailed(id: GRPCConnectionID, error: Error) {
    print(#function, id, error)
  }
  
  func connectSucceeded(id: GRPCConnectionID, streamCapacity: Int) {
    print(#function, id, streamCapacity)
  }
  
  func connectionUtilizationChanged(id: GRPCConnectionID, streamsUsed: Int, streamCapacity: Int) {
    print(#function, id, streamsUsed, streamCapacity)
  }
  
  func connectionQuiescing(id: GRPCConnectionID) {
    print(#function, id)
  }
  
  func connectionClosed(id: GRPCConnectionID, error: Error?) {
    print(#function, String(describing: error))
  }
}
```

**Comment by glbrntt** [comment]
Thanks for providing that. I think I've tracked down the bug and have a fix in #1603.

**Comment by edelabar** [comment]
@glbrntt Sorry for the delay, but I just confirmed against the main branch and it looks like it's working for me. Thanks for the help! ETA on a versioned release?

**Comment by glbrntt** [comment]
Awesome, thanks for confirming. Likely to be end of week / early next week.
