### ISSUE TITLE
Is GRPCStatus guaranteed to always be returned?

### ISSUE THREAD

**Issue by Skoti** [grpc/grpc-swift#1601]
I couldn't find any information on what kind of errors are returned from grpc, apart from a slight mention here:
https://github.com/grpc/grpc-swift/blob/main/docs/basic-tutorial.md#simple-rpc-1
> If an error occurs, it is encoded as a GRPCStatus and thrown whilst await-ing the response.

and a general grpc documentation https://grpc.io/docs/guides/error/ that it should be guaranteed.

However, I've found places where other error type is thrown:
https://github.com/grpc/grpc-swift/blob/4ab02e1ae5b4dfdd723773e955b62f35ccbaa7c7/Sources/GRPC/ConnectionPool/ConnectionPool.swift#L363-L364

although `ConnectionPoolError` does conform to `GRPCStatusTransformable`.

1. Is it correct to assume that grpc only throws error types that conform to `GRPCStatusTransformable`?
1. Is there a reason why there is no typed error api?

**Comment by glbrntt** [comment]
> 1. Is it correct to assume that grpc only throws error types that conform to `GRPCStatusTransformable`?

No; grpc-swift _may_ throw errors which do not conform to `GRPCStatusTransformable`. It tries where possible to throw `GRPCStatus` errors but Swift has no mechanism (beyond the `Result` type) for enforcing typed errors so this is very difficult to enforce.

> 2. Is there a reason why there is no typed error api?

Answered above.

**Comment by Skoti** [comment]
Thanks for clarifying 👍 

> but Swift has no mechanism (beyond the Result type) for enforcing typed errors so this is very difficult to enforce

Agreed, but why is the `Result` type not used? It would be easy to enforce the error type with it. Are there other concerns?
