### ISSUE TITLE
Could maxSendMessageLength argument be supported in main branch?

### ISSUE THREAD

**Issue by windameister** [grpc/grpc-swift#1604]
### Is your feature request related to a problem? Please describe it.

Sending message with long string parameter (over 10KB) through AsyncClient would cause a problem:

Server gets the request with whole message, but client did not get response from server, instead the client got an error with GRPCStatus = 1

```cancelled (1): RPC was cancelled by the client, cause: RPC was cancelled by the client```

Tested sending a string param with no longer than 1KB would be fine.

### Describe the solution you'd like

I guess I may have hit the limit of max send message length and would like to have a argument of maxSendMessageLength to get avoid of this problem.  

I find the old branch support this feature: 

https://github.com/grpc/grpc-swift/pull/237/commits/3cd89dd1ab608d4f74f7c7893a4a385f80964617#

https://github.com/grpc/grpc-swift/blob/81312523d2419ef20b698ddba819d8139bad26e9/Sources/SwiftGRPC/Core/ChannelArgument.swift#LL100C1-L101C1

After searching the code of current main branch, I find there is no such argument to be set in current main branch. 
Hope it could be customized.

### Additional context

I'm using Go as server. 

The same RPC message is tested with Go server & Go client and there is no such problem with long string as message param.

**Comment by glbrntt** [comment]
It's not clear that this would resolve your issue.

As I understand it, you can send a long message from your Go client to your Go server but not from your Swift client to your Go server.

If the Swift client policed the length of the message being sent and it was longer than the max allowed then the RPC would still fail from the Swift client. 

The status you receive also indicates that the length is not an issue here: `cancelled (1): RPC was cancelled by the client`; it seems like the client is cancelling the RPC; is that possible?

**Comment by glbrntt** [comment]
Also 1KB is below the default maximum message length (4MB).

**Comment by windameister** [comment]
> 

Thanks for you reply.

The GRPCStatus error indicates the state is cancelled. But I clearly did not call cancel from my code.

The error is thrown during ```try await``` the async gRPC remote call.

I have other messages with more complex info could be sent successfully. 

Also, when I cut down the message string length (< 1KB),  it could also be sent successfully.

I'm using grpc-swift 1.15.0.

Got into this trouble for a whole day. Still no progress. TAT

> It's not clear that this would resolve your issue.
> 
> As I understand it, you can send a long message from your Go client to your Go server but not from your Swift client to your Go server.
> 
> If the Swift client policed the length of the message being sent and it was longer than the max allowed then the RPC would still fail from the Swift client.
> 
> The status you receive also indicates that the length is not an issue here: `cancelled (1): RPC was cancelled by the client`; it seems like the client is cancelling the RPC; is that possible?

**Comment by glbrntt** [comment]
> Thanks for you reply.
> 
> The GRPCStatus error indicates the state is cancelled. But I clearly did not call cancel from my code.

The error you provided above is only produced in one place; I'd suggest creating a breakpoint [at that point](https://github.com/grpc/grpc-swift/blob/c7d65217d8a5a3cfbb4cb19865daf7ed5a93f25c/Sources/GRPC/Interceptor/ClientTransport.swift#L249) and trying to determine what leads to the cancellation.

**Comment by windameister** [comment]
> 

I finally find the root cause.
The await send is happening on UI thread. And the long message will delay too much which caused an exception.
After moving the send operation to background thread, everything goes fine.
