### ISSUE TITLE
Are there any classes can used to be a grpcProxy like grpc-java's GRPCProxy

### ISSUE THREAD

**Issue by BFELFISH** [grpc/grpc-swift#1628]
I would like a gRPC proxy server that can receive requests from clients within the same application and forward them to the actual server. Once it receives the response, it should forward it back to the original client.
grpc-java has an example for this:https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/grpcproxy/GrpcProxy.java
Are there any example demos available for grpc-swift with similar functionality? Or any available for grpc-swift with similar function  like ServerCallHandler.java

**Comment by glbrntt** [comment]
grpc-swift doesn't have that functionality and I'm not aware of any examples though would provide it either. 

I think the only way to achieve this at the moment would be implementing each service and manually proxying each method using a generated client to the upstream. It should be reasonably straightforward but obviously doesn't scale well as you have to implement each service.
