### ISSUE TITLE
Build Package grpc-swift in Xcode 15 produces warnings

### ISSUE THREAD

**Issue by mylaluna** [grpc/grpc-swift#1630]
### Describe the bug

grpc-swift version: 1.18

I am trying to build my iOS app to target iOS 17 in Xcode 15 beta 4.
I received a lot of warnings for just building it. Following are a list of them related to grpc-swift.

Build target protoc-gen-grpc-swift:
Duplicate -rpath '/Users/username/Library/Developer/Xcode/DerivedData/MyProject-aejxskjjdqsnskbatpjjhiktlaif/Build/Products/Debug-iphonesimulator/PackageFrameworks' ignored

Note: this warning has also been mentioned in the main project build about 30+ times. It feels to me that all the grpc related libraries are trying to add this information to rpath without checking if it is in the rpath already.

All other warnings:
<img width="1137" alt="image" src="https://github.com/grpc/grpc-swift/assets/2162747/06b72e0e-5cb6-4cca-88ca-82770e10a313">

### To reproduce

Steps to reproduce the bug you've found:
1. Open my app in Xcode 15 beta 4
2. Chose iPhone 14 Pro and iOS 17.0 as destination.
3. Build

### Expected behaviour

No warning messages.

**Comment by Lukasa** [comment]
The duplicate rpath issue is not a grpc-swift issue: that is likely to be an xcode issue with SwiftPM. Can you please file that using FeedbackAssistant? The issues regarding shadowing generic parameters are grpc-swift warnings, however, which we can fix.

**Comment by mylaluna** [comment]
No problem.

**Comment by Lukasa** [comment]
Hrm, I'm having trouble reproducing this. Can you attach the portion of the build log containing these warnings? I'd like to get the file-and-line for them.

**Comment by mylaluna** [comment]
I cannot reproduce it myself anymore. The only error I now see under Build target protoc-gen-grpc-swift is that duplicated rpath one. Not sure what happened.

The other warnings are under the swift-nio package but I guess they are beyond the scope of this issue. Thank you for the help.
<img width="598" alt="image" src="https://github.com/grpc/grpc-swift/assets/2162747/4bf1b8e1-ce40-405e-a3f4-20633bf1a67d">

**Comment by glbrntt** [comment]
The shadowing was fixed in https://github.com/grpc/grpc-swift/commit/76ae1e4bdde6c0dbedae5ad79ef51e78afe640d5.
