### ISSUE TITLE
1.19.0 doesn't work in Xcode 14.3

### ISSUE THREAD

**Issue by dufflink** [grpc/grpc-swift#1638]
I updated the dependency version to 1.19.0 and now it doesn't work in Xcode 14.3

<img width="762" alt="Снимок экрана 2023-08-09 в 15 51 26" src="https://github.com/grpc/grpc-swift/assets/29461219/12de935b-b579-4bb9-8f0a-b64a2cb63c43">
<img width="1116" alt="Снимок экрана 2023-08-09 в 19 26 49" src="https://github.com/grpc/grpc-swift/assets/29461219/31b5a7b7-2492-4c98-81a2-c03467bac8c8">
<img width="1118" alt="Снимок экрана 2023-08-09 в 19 28 13" src="https://github.com/grpc/grpc-swift/assets/29461219/89db5127-cd2a-4aad-a7c1-9d8ec81a079a">

**Comment by simonjbeaumont** [comment]
@dufflink FYI this change came in NIO 2.58.0. So, while we are working on a repro, if you don't need the features in the new GRPC release and want to get back to a working dependency tree, you should be OK on NIO 2.57.0. 

You could either revert your resolved package versions to before the upgrade or specify an explicit dependency on swift-nio with an upper bound.

**Comment by simonjbeaumont** [comment]
@dufflink I installed Xcode 14.3 to see if there was some difference, but am still unable to reproduce the error with the above steps.

I'll continue to look at this tomorrow (UK time), but if you have a minimal reproduction project, that would be very helpful.

**Comment by simonjbeaumont** [comment]
@dufflink One more thing (apologies for the firehose of questions)...

Are you building with library evolution mode enabled—i.e. are you trying to build NIO as a framework?

**Comment by simonjbeaumont** [comment]
> I tried to create a new project in Xcode 14.3 as you asked. Added the package dependency on swift-nio. The same as on you, it works.

Great—thanks for trying that out.

> In my error case, I used the [tuist](https://github.com/tuist/tuist) framework in order to integrate your grpc-swift. And there it's built as a framework I guess. Seems like the problem is somewhere there.

Thanks for confirming. NIO doesn't support building in library evolution mode. You can read more about that here: https://github.com/apple/swift-nio/issues/1257.

What _might_ work is using the Xcode setting `Allow Non-modular Includes In Framework Headers`, which might need to be a change in tuist.

> Thank you so much for your quick answer!

No problem, happy to help.
