### ISSUE TITLE
iOS background downloading

### ISSUE THREAD

**Issue by s-atif-jamil** [grpc/grpc-swift#1651]
### What are you trying to achieve?

I am using grpc to download multiple files from server on iOS. It is working on foreground but when I put app on background then it stops. Is there a way to work in background also?

**Comment by Lukasa** [comment]
If the iOS app goes into the background, after a small time interval network requests are terminated. grpc-swift cannot use URLSession today, which is the only supported way to do background networking after the app is suspended. 

Future grpc-swift releases may gain this capability though: see https://forums.swift.org/t/grpc-swift-plans-for-v2/67361 for more.
