### ISSUE TITLE
Keepalive with HTTP2 PING through a reverse proxy

### ISSUE THREAD

**Issue by ericsink** [grpc/grpc-swift#1653]
This is a somewhat high-level question.

I am working on an iOS app which uses gRPC to communicate with a server in the cloud.  We have several calls where the client keeps a stream open on the server so it can listen for notifications.  We have the usual problems with connections in a mobile app, and I've been trying to use the keepalive feature in what I believe to be the usual way.  I believe I am using your very fine library correctly, and in a development environment, things seem to work fine.

But when talking to the server in the cloud, the problem is that our reverse proxy (currently AWS Application Load Balancer) doesn't support HTTP2 PING frames.

https://stackoverflow.com/questions/66818645/http2-ping-frames-over-aws-alb-grpc-keepalive-ping

My experiments confirm this to be true.

So I began to look for ALB alternatives, and I found that nginx doesn't handle this either, and there are remarks there which suggest that this is by design, as if perhaps using HTTP2 PING across multiple hops would not be The Right Way.

https://trac.nginx.org/nginx/ticket/1887

So...  The gRPC wants to deal with keepalive using HTTP2 PING frames, but reverse proxies don't want to support those.  

I lack the depth of knowledge to second guess any of these decisions, but It looks like "not everyone is on the same page"?

The subjective question here is:  Do you folks have any opinions on this?

The more practical question is:  If you were building an app along the lines I have described, how might you deal with this problem?

1.  Don't use a reverse proxy (which would seem kinda weird)
2.  Implement some sort of "ping" like thing at the level of a grpc call (which would seem kinda sad)
3.  Something else?

**Comment by ericsink** [comment]
A couple of followups:

1.  YARP (a reverse proxy in .NET) doesn't pass HTTP2 PING frames through either.  But it *does* respond to them.  (Probably the others do too, but I haven't verified that.)
2. My current line of investigation is that maybe I have been thinking about this the wrong way.  Maybe we don't need those ping frames to get passed through to the backend.  Maybe using gRPC keepalives in the mobile app is useful simply for monitoring the health of the network connection up to the reverse proxy.

**Comment by Lukasa** [comment]
No HTTP/2 frame is required to be passed "end to end". Any HTTP-aware intermediary is entitled to entirely rewrite, remove, or insert any HTTP/2 frames it likes, so long as the overall semantics are upheld and the data isn't unreasonably modified. The intermediaries _are_ required to respond to them however.

Your point 2 is more or less right: gRPC keepalives can only be used to keep the individual connection up. Generally that should also be sufficient to prevent the loadbalancer timing out an individual request, though this is not always true. Loadbalancers that are gRPC aware will handle this the best, as they'll use the keepalives to ensure that long-lived but currently-idle streaming RPCs stay up. ALB is less likely to do this, but I admittedly have not tried to investigate.
