### ISSUE TITLE
Suggestion: Move the examples from `Examples/` to `Sources/`

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#171]
That would avoid having to compile gRPC-Core and dependencies twice, and it would avoid the ugly `../../.., branch HEAD` dependency in the example's `Package.swift` files.

**Comment by timburks** [comment]
I'd like to do this, but I'd also like to be sure that package users don't build the examples just by including the grpc-swift package (one reason is that the examples add dependencies that many applications won't have). That probably requires updating the top-level Package.swift to Swift 4 format. I tried that once and had problems with the tests (I believe `swift test` reported that tests weren't found). We should revisit that.

**Comment by timburks** [comment]
Done - thanks!
