### ISSUE TITLE
How check connection for grcp

### ISSUE THREAD

**Issue by gulivero1773** [grpc/grpc-swift#1736]
How check connection for grcp? I Need check connection for server gRPC, how I can do this?

**Comment by glbrntt** [comment]
Hi @gulivero1773 – could you explain your question some more so we can help you?

**Comment by glbrntt** [comment]
The client creates connections lazily, so it's generally not all that useful to check whether the connection is okay. 

However in your case if you send a request and get a response with an ok status then the _connection_ is fine.

**Comment by gulivero1773** [comment]
Maybe client have any func for check server grpc? Or I need to add func in proto file?

**Comment by glbrntt** [comment]
I _think_ you're asking if there's a built in RPC to effectively ping the server? If so, then no, that doesn't exist.

**Comment by gulivero1773** [comment]
Thank you!
