### ISSUE TITLE
Support alternate proto-over-HTTP1 runtime (aka grpc-web) for constrained environments.

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#174]
Support for [grpc-web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) would make it easier to use grpc-swift in environments where bundling a C library is difficult or undesirable, and it would also allow proto-over-HTTP1 (aka grpc-web) APIs to be called in situations where only system-provided HTTP libraries can be used (such as background downloads on iOS).

With care, this could be swapped in with minimal changes to the existing interfaces.

**Comment by MrMage** [comment]
This will be supported by the NIO branch.
