### ISSUE TITLE
Prepare Docker image for Swift gRPC development

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#18]
It would be useful to have a docker image that includes Swift, protoc, and any other necessary dependencies.

**Comment by timburks** [comment]
A Dockerfile and basic instructions are in the new [Docker](https://github.com/grpc/grpc-swift/tree/master/Docker) directory.

**Comment by johndpope** [comment]
Nice. I was looking to throw together a grpc service in swift for server side but currently only can see path forward using go. I'll keep digging.

**Comment by johndpope** [comment]
I wonder if a list of available grpc demos would be appropriate once you fire up container?
like a prompt.

I found this
https://github.com/culumn/gRPC-Demo-Server/blob/master/Package.swift
