### ISSUE TITLE
pool.id uses `ObjectIdentifier(connection)` as the ID but that's not unique.

### ISSUE THREAD

**Issue by weissi** [grpc/grpc-swift#1849]
`ObjectIdentifier(something)` is not unique. It's only unique at any given point in time. But it is not unique across the lifetime of a program. It prints the allocation address and after freeing one object, it will be available again to the next.

For example see how each of the 100 `Class()` instances has the same address/ObjectIdentifier

```
$ echo 'class Clazz {}; for _ in 0..<100 { print(ObjectIdentifier(Clazz())) }' | swift - | sort | uniq -c
 100 ObjectIdentifier(0x0000600000860bd0)
```

**Comment by glbrntt** [comment]
Point taken but for the connection pool I think it's okay: each sub-pool (i.e. the thing we're identifying) is guaranteed lives for as long as the pool so they will be unique.

**Comment by glbrntt** [comment]
I'm not disagreeing with the premise of the issue. It's just low priority as pools are typically long-lived so IDs should be unique enough.

**Comment by glbrntt** [comment]
Ended up doing this as part of https://github.com/grpc/grpc-swift/pull/1852
