### ISSUE TITLE
Don't return "ok" when an operation group fails.

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#185]
We should fix [this](https://github.com/grpc/grpc-swift/blob/975822c1dc693c36df1a8f02e768bc76c1fd9adc/Sources/SwiftGRPC/Core/Call.swift#L111) to set an appropriate error code, and probably [this too](https://github.com/grpc/grpc-swift/blob/975822c1dc693c36df1a8f02e768bc76c1fd9adc/Sources/SwiftGRPC/Core/Call.swift#L104).

**Comment by cvanderschuere** [comment]
This was partially fixed here https://github.com/grpc/grpc-swift/pull/183/commits/4489716b93746e3ff19f324c42bd07cfa529bcb4

**Comment by MrMage** [comment]
I think this will essentially be fixed by https://github.com/grpc/grpc-swift/pull/184. The status code is only relevant for operation groups that include "receiveStatusFromServer" anyway.

**Comment by MrMage** [comment]
@timburks, do you think this can be closed now?
