### ISSUE TITLE
Thoughts on adding support for connectivity state

### ISSUE THREAD

**Issue by SebastianThiebaud** [grpc/grpc-swift#186]
This Swift library doesn't expose connectivity states and doesn't include an API to watch state changes: https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md

**Comment by dcow** [comment]
+1. We would like to inform a user/client about the state of a channel at any given time (basically build a channel state UI, nothing more).

**Comment by MrMage** [comment]
Agreed. I am also working on improving the library's error reporting. For example, if you try to connect to an endpoint that simply does not exist, the library will let you send data just fine in streaming requests and simply throw an `.endOfStream` error when trying to read responses. It should instead inform the user earlier that the connection failed.

**Comment by MrMage** [comment]
I'm adding a simple API for this in #188 (e68cec0).

**Comment by SebastianThiebaud** [comment]
I've been looking at your PR @MrMage and thanks for being on top of this. I've been working on a different implementation in my fork matching a little bit more what gRPC Python is offering with observers. What are your thoughts on updating the API to use observers?

**Comment by MrMage** [comment]
My concern with adding an observer is that it adds _another_ polling thread. So running that extra thread should at least be optional I think.

**Comment by dcow** [comment]
FWIW `grpc-java` punts on an observation mechanism too for exactly the same rationale as @MrMage. You'd need to "lock the world" to deliver connectivity state information in a way that's guaranteed to be accurate. From what I've gathered the compromise was to have a way to get a callback when a provided state is no longer the current state. You "watch" the provided state and get a callback when it changes. If the channel state has already changed from the provided state, the callback fires immediately, see: https://github.com/grpc/grpc-java/issues/3763

**Comment by MrMage** [comment]
Can you share that code so we can look at it? :-)

**Comment by timburks** [comment]
What would be a good way to verify this (in tests)?

**Comment by SebastianThiebaud** [comment]
Closing this issue since #196 and https://github.com/MrMage/grpc-swift/commit/e68cec0db8b1cd90f319ff99c9a8417a711a0c0a are adding support for this.
