### ISSUE TITLE
Connection with Nest Server

### ISSUE THREAD

**Issue by abdelazizSalah** [grpc/grpc-swift#1862]
## Nest Server Connection
* I am facing a problem, as I am working on my graduation project, and we want to connect swift with the server using the gRPC communication protocol. 
* I have generated the .pb and .grpc files successfully, however, in the .pb file, it gives me an error for using proto version 3. 
<img width="1496" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/54127ebc-88b2-494f-9e6e-4054547e39fc">
* When I comment these lines it works, and I have implemented a small javascript file, and calculator swift client, and they work well together, here are some snippets for the client code
* 
<img width="879" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/c433354a-0655-4272-9f40-066ce514b553">
<img width="1019" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/78d7af2d-8893-4e83-a6c8-f48290bb6781">
<img width="1046" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/005cfcfc-cf49-44d4-a186-e9a2a51d88cc">

and here are some snippets for the javascript server: 
<img width="1078" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/94b1539f-e179-4874-a40d-9d6025c26ba7">
<img width="847" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/5dfc87ba-bf0d-41fa-ada2-f8e37f5e5ab8">
<img width="852" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/f23da420-1273-4b7c-b24b-235d3944ea67">

### What are you trying to achieve?
* I want to do the same job but with nest instead of javascript.
* however, when I connect on the same port, with the same proto files exactly, I don't get any output, and It sounds like there is no connection between the server and the client.
* Here are some snippets from the nest server
<img width="884" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/f58ee680-e2dd-45d0-a92e-4c7c56d9fa85"> 
<img width="1157" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/4391cf99-8815-4901-9d73-7f95fb41158b">
<img width="1064" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/2f4024ec-3bce-4108-89d1-773f01948a95">
<img width="816" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/55fbbd45-7e56-4e69-b462-a72a8e4d59ae">

Describe your problem at a high level. Include code snippets if you think that
would help better illustrate your problem. Without enough information, we will
not be able to help you.

### What have you tried so far?
* I have tried many things, trying to check on the connectivity of the port, and I have reached that I can use the .delegate property to check on the status of the channel, and it gives me that 

<img width="548" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/4d02d25b-a6aa-4d9c-8b00-de2689a8323d">

* The connection is ready, however, the server does not print any thing. 
* also I have made a busy wait while loop to check on the time needed for the channel to change its status from idle to ready, and it takes almost 0.016 seconds for that. 
* and I tried to use wrong ports and hosts, but when I do this the channel never becomes ready.
* So now I am looking for help in this issue as it is very critical for me to finish this connection to continue in my graduation project.
* and this is my email, if anyone is free to go for an online meet to solve this issue. 
* abdelaziz132001@gmail.com

Describe what you've tried to do so far to solve your problem. Include any
relevant information such as the **library and protoc plugin versions**, 
the **full `protoc` invocation** (if the problem is related to code generation), 
and any **logs** or **error messages**.

**Comment by glbrntt** [comment]
> <img alt="image" width="1496" src="https://private-user-images.githubusercontent.com/71516308/324145786-54127ebc-88b2-494f-9e6e-4054547e39fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzA2NTYsIm5iZiI6MTcxMzc3MDM1NiwicGF0aCI6Ii83MTUxNjMwOC8zMjQxNDU3ODYtNTQxMjdlYmMtODhiMi00OTRmLTllNmUtNDA1NDU0N2UzOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA3MTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNTBlZDMxNDY0MzFhOTZmZDkyMmMzZTQ2NWY1ZWFmODBhNzU3MDRhNzJjMzA4MzQ2ZWExN2Y0MzMxMWY3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hqXMEF7g2TCBj2Z7k08Ex_GwKLpff2YqPTehPYHN_aU"> 

How did you generate these files? What version of `protoc-gen-swift` did you use?

**Comment by abdelazizSalah** [comment]
for some reasons, the image you have attached is not displayed well, however, I have installed the latest version 
<img width="1027" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/9cfeb2b9-6e21-4992-bb9f-0a07d0ba0620">
I have cloned the repo, then I have followed the instructions, and whenever I need to convert the proto file to .pb and .grpc, I use this command: 
protoc --swift_out=. --grpc-swift_out=. proto_file_name.proto
<img width="773" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/7e3cda5e-45fb-472d-9a73-6019c51dbd9e">

**Comment by glbrntt** [comment]
What's the output of `protoc-gen-swift --version`?

**Comment by abdelazizSalah** [comment]
protoc-gen-swift 2.0.0

**Comment by glbrntt** [comment]
That might be your problem; Swift Protobuf doesn't have a 2.x version yet, so I assume you built that from `main`. 

Can you build a 1.x version of `protoc-gen-swift` and see if that fixes your issues?

**Comment by abdelazizSalah** [comment]
should I run this command? 
<img width="880" alt="image" src="https://github.com/grpc/grpc-swift/assets/71516308/b67c5a4b-5a42-4f9b-ad3b-ea66d236cc04">
or what should I do to change the version?

**Comment by glbrntt** [comment]
You can run that command from the root of the `grpc-swift` repository.

`protoc-gen-swift` will then be in `/path/to/grpc-swift/.build/release/`. 

`protoc` will look for `protoc-gen-swift` in your `$PATH`, so either you need to add the version of `protoc-gen-swift` you built to your `$PATH` or you can specify it directly to `protoc` using `--plugin=/path/to/protoc-gen-swift`.

**Comment by abdelazizSalah** [comment]
Thank you so much!
