### ISSUE TITLE
Call message queue cannot be closed safely

### ISSUE THREAD

**Issue by gm281** [grpc/grpc-swift#19]
`class Call` maintains a queue of messages to send out, but `close()` could jump the queue (unsynchronised). Since the message queue is internal to `Call`, it cannot be observed from outside (in an effort to delay `close()` until it drains).

https://github.com/grpc/grpc-swift/blob/master/Sources/gRPC/Call.swift#L152

**Comment by timburks** [comment]
Current message queue length is made public in [this commit](https://github.com/grpc/grpc-swift/commit/ee457d8663bcfdfea6e6c41b31c1d3105abf7a20)

**Comment by gmilos** [comment]
Thanks, this can be made to work now, but won't make for the easiest concurrency (as someone outside will have to implement a piece of logic with wraps `Call`, accepts `close()`, rejects further message enqueues, watches queue length [which seems to require polling as I cannot see an API that allows to intercept message send notifications] and eventually completes `close()` once the queue drains). Am I missing something?

**Comment by mosn** [comment]
Bump! 

Would appreciate an update on this

**Comment by MrMage** [comment]
This is now solved by calling `call.waitForSendOperationsToFinish()` before calling `close()`.
