### ISSUE TITLE
Allow client to specify metadata per call

### ISSUE THREAD

**Issue by cvanderschuere** [grpc/grpc-swift#190]
Currently the client is only able to modify the metadata at the service level, but metadata is meant to be per-call.

https://github.com/grpc/grpc-swift/blob/dd4d1cb64d080a60e64f15b80e0090da6f5104f3/Sources/protoc-gen-swiftgrpc/Generator-Client.swift#L189-L194

Changes:
- Allow an optional metadata to be passed per call
- Add `merge` to Metadata
- Merge service metadata and call metadata on `call.start`

**Comment by MrMage** [comment]
Note that we can't really make arguments optional, as that is currently not possible on protocols (and we switched to protocols for better test ability). Although, it might be possible to add protocol extensions with optional arguments; that could be a viable workaround.

Do you need per-call metadata at the moment? I would have supposed it's more of an edge case, with the most common case being per-channel authentication metadata.

**Comment by cvanderschuere** [comment]
Yes we do. The most direct use case is for request tracing which must be via per-rpc metadata.
