### ISSUE TITLE
Configure `CallStartBehavior` on a `GRPCChannelPool`?

### ISSUE THREAD

**Issue by feelingsonice** [grpc/grpc-swift#1902]
### What are you trying to achieve?

I want to set the `CallStartBehavior`, this is possible on a `Connection` type but not a `GRPCChannelPool`? 

(my understanding is that `Channel` types are newer approach where a `Connection` type is older?)

### What have you tried so far?

Looked through all of the config options and doesn't seem possible. Both during channel pool creating and inside `CallOptions`

**Comment by glbrntt** [comment]
That's correct, it's not available on `GRPCChannelPool`. You can however set a max wait time, i.e. how long you're willing to wait for the call to start.

**Comment by feelingsonice** [comment]
Are there plans to add it in the future or this is deliberately left out?

**Comment by glbrntt** [comment]
No plans at the moment. We're currently working on v2 and have added it there.
