### ISSUE TITLE
make clean recursive call when directory does not exist

### ISSUE THREAD

**Issue by lebdron** [grpc/grpc-swift#193]
https://github.com/grpc/grpc-swift/blob/f57b9c3d06ace96be2fcb146eb7b605550be3f1f/Makefile#L37-L38

`cd Examples/Echo/PackageManager; make clean` or `cd Examples/Simple/PackageManager; make clean` result in recursive call if `Examples/Echo/PackageManager` or `Examples/Simple/PackageManager` does not exist, because the result of first command is ignored and `make clean` is called in current directory.

**Comment by MrMage** [comment]
You are right; there should probably be a `&&` instead of the `;`, and we might remove them altogether if the directories no longer exist.
