### ISSUE TITLE
How do I unit test my client?

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc-swift#197]
I am writing a Swift gRPC client, and I want to unit test it. In Java, it is possible to make an "in-process" server and register a fake service to it, as nicely documented [here](https://github.com/grpc/grpc-java/tree/master/examples#unit-test-examples).

So is it possible, and how would I...:

* ...create a server and register a fake service for each unit test?
* ...run the server in-process? Does that transport exist at all in Swift?

**Comment by MrMage** [comment]
If you would like to only stub out the service your clients to connect to in your tests, please see [`ClientTestExample.swift`](https://github.com/grpc/grpc-swift/blob/master/Tests/SwiftGRPCTests/ClientTestExample.swift).

If you'd like to spin up a real gRPC server in your tests, please have a look at [`EchoTests.swift`](https://github.com/grpc/grpc-swift/blob/master/Tests/SwiftGRPCTests/EchoTests.swift) and [`BasicEchoTestCase.swift`](https://github.com/grpc/grpc-swift/blob/master/Tests/SwiftGRPCTests/BasicEchoTestCase.swift) for examples.

**Comment by JonasVautherin** [comment]
Seems like it is exactly what I was looking for! Thanks a lot!

**Comment by JonasVautherin** [comment]
@MrMage: Actually, I don't seem to find how to make `protoc` generate the test code? For instance, there is some test code generated [here](https://github.com/grpc/grpc-swift/blob/master/Sources/Examples/Echo/Generated/echo.grpc.swift#L45) that is used in your examples...

I tried `protoc my.proto --swiftgrpc_out=generate_mock_code=true:.` like in C++, but it doesn't work.

**Comment by MrMage** [comment]
You’ll need to add `--swiftgrpc_opt=TestStubs=true`. Also, please make sure to use the plugin and runtime from `master`, as this code is not in a tagged release yet.
