### ISSUE TITLE
How do I close the connection?

### ISSUE THREAD

**Issue by bigodines** [grpc/grpc-swift#198]
I've a go server and I'm playing around with using this library for my client code. I haven't found anywhere a way to close a  channel connection I don't need anymore. What is the right way to close the channel between my client and server?

**Comment by MrMage** [comment]
Good point! The channel and its completion queue get destroyed and shut down once the channel is deallocated. So once the last remaining reference to your channel or service client is released, the connection should be closed automatically.

**Comment by rebello95** [comment]
Closing this out, it should be addressed by https://github.com/grpc/grpc-swift/pull/384.
