### ISSUE TITLE
Develop code generation for gRPC Services.

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#2]
Currently there is no code generation for gRPC services. This needs to be added either to the swift-proto plugin or to a separate plugin.

**Comment by jcanizales** [comment]
As a separate plugin, per https://github.com/apple/swift-protobuf/issues/118 :)

**Comment by johndpope** [comment]
From the look of objective-c generator / it's intermingled into visual studio at some point. 
(TODO find references)

I found this java class that spits out actionscript service libraries. (probably proto 2 version)
https://github.com/Atry/protoc-gen-as3

`https://github.com/Atry/protoc-gen-as3/blob/6ba56584f44f565804f48eca66ad82aa677c901c/compiler/com/netease/protocGenAs3/Main.java`

There's other code online for generating swift files  -> 

`https://github.com/janyou/ANTLR-Swift-Target/blob/master/org/antlr/v4/codegen/target/SwiftTarget.java`
this is using ANTLR to generate swift lexars / parsers / tokenizers. 


Part 1)
Need to choose language to spit out swift service class
Go Java or .... use swift? c++ (dependency concerns?) 
Does it make most sense to use swift? 
https://github.com/google/protobuf/blob/master/docs/third_party.md
Does it make most sense to cherry pick from this
https://github.com/jcanizales/swift-protobuf-plugin/blob/master/Sources/FileGenerator.swift
Any thoughts on this?

Part 2) 
create a canonical gist with service layer to plug into this library.
https://github.com/grpc/grpc/blob/master/src/objective-c/examples/SwiftSample/ViewController.swift

![screen shot 2016-11-04 at 13 26 48](https://cloud.githubusercontent.com/assets/289994/20015541/3dbf1b7a-a292-11e6-9d6a-64a40126eb6e.png)

**Comment by johndpope** [comment]
I've been looking into different widgets to get job done - 
I'd say we'd need a protobuf parser as first step - which led me to this grammar file 
https://github.com/johndpope/protobuf-parser/blob/master/dsl/ProtoParser.g

so - if we  throw this at antlr-swift 
https://github.com/janyou/ANTLR-Swift-Target
we'd have a protobuf parser/lexar/tokenizer in swift - which would spit out a full AST 
from there we'd expose all the methods / service calls for respective proto file

I think biting the bullet and going Swift is nice scenic route. c++ while it may work - will be hard(er) for future offshoot libraries to hot wire.
The other alternative is to cherry pick Apple's source code.

**Comment by jcanizales** [comment]
Oh, but `protoc` will parse the `.proto` files for us already. The usual setup is `protoc` executes your plugin in a separate process, writes a serialized [`CodeGeneratorRequest`](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/plugin.proto#L57) to its stdin, and then reads a serialized [`CodeGeneratorResponse`](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/plugin.proto#L81) from its stdout.

So the plugin can be written in Swift alright, and just needs to conform to that protocol to get the parsing for free.

**Comment by johndpope** [comment]
then cherry picking Apple's work is best option. 
https://github.com/apple/swift-protobuf/blob/bf53b0b56ca611c8fa634006c846a87bb6f2d079/Sources/protoc-gen-swift/Context.swift

https://github.com/apple/swift-protobuf/blob/bf53b0b56ca611c8fa634006c846a87bb6f2d079/Reference/google/protobuf/compiler/plugin.pb.swift

Then we just need the canonical example.
IF proto file looks like this

```
service MasterService {
  // Creates a session.
  rpc CreateSession(CreateSessionRequest) returns (CreateSessionResponse);

  // Extends a session.
  rpc ExtendSession(ExtendSessionRequest) returns (ExtendSessionResponse);

  // Prepares future partial run calls.
  rpc PartialRunSetup(PartialRunSetupRequest) returns (PartialRunSetupResponse);

  // Drives the graph computation.
  rpc RunStep(RunStepRequest) returns (RunStepResponse);

  // Closes a session.
  rpc CloseSession(CloseSessionRequest) returns (CloseSessionResponse);

  // List the devices usable by the master.
  rpc ListDevices(ListDevicesRequest) returns (ListDevicesResponse);

  // Close all existing sessions.
  rpc Reset(ResetRequest) returns (ResetResponse);
}
```

then .... 

fill in the gaps

 ....

**Comment by johndpope** [comment]
This Edge framework for server side swift seems like nice path forward 
https://github.com/SwiftOnEdge/Edge

**Comment by johndpope** [comment]
So - need to commit to specific interoperable network library. 
https://www.reddit.com/r/swift/comments/57m49o/how_to_make_a_network_request_on_linux/
Presumably - the limitations of urlsession across different platforms is still the case?

it looks like ccurl will get some mileage 
https://github.com/yoshiki/curlsample/blob/master/Sources/main.swift

I found this - a swifty version of libcurl wrapped around IBMs.
https://github.com/dmcyk/SwiftyCurl/blob/master/Sources/SwiftyCurl/cURLConnection.swift

**Comment by jcanizales** [comment]
RxLibrary, like many others, is nicer to use from Swift than ObjC. And it can be used standalone by just depending on the `gRPC-RxLibrary` cocoapod. But Swift's generics can be used to create a still nicer Swift version of the library.

I've had in my mind, for a while, to create a doc comparing proposed surfaces for C gRPC: one using RxSwift, the other ReactiveSwift, and what we have today from importing the ObjC library.

Between RxSwift and ReactiveSwift, I personally think having different types for "hot" and "cold" streams is a better idea. But from the POV of the user, it's best if it matches whatever rx library you're already using in your app. That means that either:

* We pick one of RxSwift or ReactiveSwift, and write or find an adapter library to get one from the other.
* We use RxLibrary (or write a more Swifty version), and write adapter libraries for the other two.

**Comment by johndpope** [comment]
fyi https://github.com/IBM-Swift/CCurl/issues/10
IBM's banking on fully deprecating ccurl as a result of Apple presumably getting around to rewriting nsurlsession for server side (hopefully by swift4?) - we could lock that in and cross fingers it will be future proof (in the future).  
The only reservation I have with using rxlibrary is it's introducing objective-c which we superseded in the design up until this point.  I've heard good things about rxswift.
Whereas reactiveswift has reactivecocoa dependencies (& with carthage it is a bit of pain) 
https://github.com/KevinVitale/ReactiveJSON/issues/7
for the document with pros + cons - you could throw a gist up or share google sheet doc.

**Comment by timburks** [comment]
With [this commit](https://github.com/grpc/grpc-swift/commit/97efdbad11f1c4eba3f6e8b10445dc371f86185a), there's a code generating plugin in the Plugins directory that generates client and server stubs for all four API types (Unary, Server Streaming, Client Streaming, Bidi Streaming). The plugin uses templates in the Plugins/templates directory and currently these must be in the same directory where the plugin is run. Templates use Kyle Fuller's [Stencil](https://github.com/kylef/Stencil) package and will hopefully be easy to modify with improvements or for other calling styles. The current generated code surface closely follows the Go grpc generator.

**Comment by johndpope** [comment]
@timburks - thanks for your efforts here - pleased to say I got the service classes spat out (untested) for tensorflow. https://github.com/nubbel/swift-tensorflow/
