### ISSUE TITLE
More flexible secure channel constructor is needed

### ISSUE THREAD

**Issue by gmilos** [grpc/grpc-swift#20]
[Channel constructor accepts certificate URLs](https://github.com/grpc/grpc-swift/blob/1ac521b87460492da4e2995ebffb3f5717cd5ff0/Sources/gRPC/Channel.swift#L68).

Firstly, it's not clear from the API this in in fact URL, relative to the bundle. Secondly, it prevents server use (where there aren't Bundles). More direct `Data` based API is needed.

**Comment by jcanizales** [comment]
> server use (where there aren't Bundles)

I'm curious: Why aren't there bundles for server libraries? They sound like a nice thing to have.

**Comment by gmilos** [comment]
Bundles have conventional directory layout, with metadata, binaries and resources in appropriate places. This convention doesn't really exist on non-Darwin platforms, so even if we could make it work in theory, it will be unnatural for the platform.

**Comment by timburks** [comment]
Planning to compile roots.pem into the executable since it is common to all uses and can be overridden by passing a value into the constructor.

**Comment by MrMage** [comment]
Should be fixed by now: https://github.com/grpc/grpc-swift/blob/f57b9c3d06ace96be2fcb146eb7b605550be3f1f/Sources/SwiftGRPC/Core/Channel.swift#L60.
