### ISSUE TITLE
Support for Channel specification on ServiceClient.init

### ISSUE THREAD

**Issue by rebello95** [grpc/grpc-swift#200]
Python's gRPC implementation allows for consumers to [specify a channel](https://github.com/grpc/grpc/blob/7542ba6e0caee740f124dc25706287fd62f546d8/examples/python/multiplex/multiplex_client.py#L110) when creating clients, like so:
```
def run():
    channel = grpc.insecure_channel('localhost:50051')
    my_stub = helloworld_pb2_grpc.FirstStub(channel)
    my_other_stub = helloworld_pb2_grpc.SomeOtherStub(channel)
    ...
````

The Objective-C implementation uses a [singleton channel](https://github.com/grpc/grpc/blob/master/src/objective-c/GRPCClient/private/GRPCHost.m#L115), where the current Swift implementation [creates a new one](https://github.com/grpc/grpc-swift/blob/master/Sources/SwiftGRPC/Runtime/ServiceClient.swift#L54) every time.

Ideally, consumers would be able to specify their own `Channel` between multiple clients, which would alleviate the need for creating a new one each time:
```
/// Create a client with a pre-defined channel.
public init(channel: Channel) {
    gRPC.initialize()
    self.channel = channel
    self.metadata = Metadata()
}
```

**Comment by rebello95** [comment]
Makes sense. Do you foresee any complications with the underlying C channel management if we were to implement an initializer like the above (i.e., regarding managing connectivity on a long-living/reused channel)? I have some local changes that seem to work as long as `gRPC` is initialized by the time the `Channel` is created.

**Comment by MrMage** [comment]
I think this should be fine; we could just have `Channel.init()` call `gRPC.initialize()` as well.

**Comment by rebello95** [comment]
Yep, sounds good! Opened https://github.com/grpc/grpc-swift/pull/202
