### ISSUE TITLE
Adding gRPC-Swift 3rdParty Libraries to Xcode Project leads to Live Preview failure

### ISSUE THREAD

**Issue by mylaluna** [grpc/grpc-swift#2030]
### Describe the bug

Tested on Xcode Version 16.0 beta 6 (16A5230g) with gRPC Swift 1.23.0

I just filed an Apple feedback about this issue. I was thinking maybe I need to raise an issue here as well just in case.
Feel free to close the issue if you think Apple Xcode team should take the responsibility to fix this problem.
 
In theory, the gRPC-Swift should have nothing to do with Xcode's preview feature but gRPC-Swift is the only library in my project that crashes my Xcode Live Preview. Any other libraries in my project don't have such a problem.

### To reproduce

1. Create a new iOS project in the latest Xcode 16 beta
2. Select ContentView in the project and verify the live preview is working and fast
3. Go the project’s Package Dependencies tab, add gRPC-Swift (https://github.com/grpc/grpc-swift.git) as a 3rdParty library of this project. 
4. Go the main project target, select General tab.
5. Under Frameworks, Libraries, and Embedded Content section, add “GRPC”
6. Go back to ContentView and verify its live preview rendering now takes very long time and eventually failed.
7. Select Live Preview Diagnostic, verify error message: Failed to launch app ”MyApp.app” in reasonable time…

**Comment by glbrntt** [comment]
Thanks for filing this and the feedback. This sounds very much like an Xcode issue so I'll close this.

**Comment by yuyang-ok** [comment]
I have this issue too, Is this solved???
<img width="789" alt="截屏2024-10-20 17 12 12" src="https://github.com/user-attachments/assets/11140295-d5b5-4bb2-82a8-d682e0a3ab6b">

**Comment by yuyang-ok** [comment]
This is a very annoying bug.😭😩

**Comment by yuyang-ok** [comment]
why this is closed?

**Comment by yuyang-ok** [comment]
<img width="1771" alt="截屏2024-10-20 17 16 11" src="https://github.com/user-attachments/assets/27bfd560-c8d9-4320-b582-8ab0b04746a1">
cause this process use a lot cpu resource.
