### ISSUE TITLE
Add support for protobuf editions

### ISSUE THREAD

**Issue by ehmo** [grpc/grpc-swift#2037]
First of all, thank you for all the great work you are doing. Managing an open source project is a thankless job, so I want to express my gratitude.

### What are you trying to achieve?
The current version 1.23 of `apple/swift` doesn't support editions.

### What have you tried so far?
I see you've already upgraded the version in the [last commit](https://github.com/grpc/grpc-swift/commit/962608aafa25000371b1129f1e4bf1d6204dc924). Any idea when will you make the release? As I am using [buf](https://buf.build) and depend on your library, I can't upgrade my proto files to use editions until this issue is fixed.

**Comment by glbrntt** [comment]
> First of all, thank you for all the great work you are doing. Managing an open source project is a thankless job, so I want to express my gratitude.

You're welcome!

We haven't added support for editions in the gRPC plugin yet (we need to!) so I don't think a release would help you until we've done that?

**Comment by ehmo** [comment]
> We haven't added support for editions in the gRPC plugin yet (we need to!) so I don't think a release would help you until we've done that?

Sadly, I didn't check the library that extensively. Do you have an idea when it could be added? I would be happy to contribute some bounty money if that helps.

**Comment by glbrntt** [comment]
Let me take a look tomorrow as I'm not sure what the extent of this work is yet. As part of it we actually need to migrate to a new interface as the one we're using was recently deprecated which is why this is a bit of an unknown.
