### ISSUE TITLE
--swiftgrpc_opt=Visibility=Public is broken

### ISSUE THREAD

**Issue by bootstraponline** [grpc/grpc-swift#206]
![image](https://user-images.githubusercontent.com/1173057/38625761-3243b08e-3d79-11e8-85f4-e3bb59ad6243.png)
![image](https://user-images.githubusercontent.com/1173057/38625783-3a6647c2-3d79-11e8-90e4-7ed51376501a.png)

The structs aren't generated with the public visibility modifier. I'm using `--swiftgrpc_opt=Visibility=Public`

**Comment by MrMage** [comment]
The corresponding are generated by `swift-protobuf`, a different plugin. Pass the same as a `swift_opt` argument.

**Comment by bootstraponline** [comment]
Thanks. `--swift_opt=Visibility=Public` worked
