### ISSUE TITLE
Failed to archive project using grpc-swift: Missing modules and library evolution issues

### ISSUE THREAD

**Issue by salvatorecasalino** [grpc/grpc-swift#2074]
I am encountering an issue while creating an _**.xcarchive**_ for my Swift project, which uses **grpc-swift** (version 1.23.1) and the **protoc-gen-grpc-swift** plugin. I am running the following command:

`xcodebuild archive -scheme start-grpc-test -destination "generic/platform=iOS" -archivePath ./output/clientsdk.xcarchive SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES`

I get errors related to **CNIOAtomics** missing and a warning about binary compatibility due to **library evolution** not being supported for GRPC.

### To reproduce
1. Set up a Swift project with `grpc-swift`.
2. Run the `xcodebuild archive` command.

### Expected behaviour
I expect the project to archive successfully without errors related to missing modules or binary compatibility issues.

### Additional information

Xcode version **15.4**
Swift version **5.10**

Here is an excerpt from the error logs:
[build_output.txt](https://github.com/user-attachments/files/17166150/build_output.txt)

**Comment by glbrntt** [comment]
gRPC Swift – and some of its dependencies – don't support building for library evolution mode as they don't have a stable ABI.
