### ISSUE TITLE
How to build protoc-gen-grpc-swift from source

### ISSUE THREAD

**Issue by piotrkowalczuk** [grpc/grpc-swift#2075]
### What are you trying to achieve?

I'm unable to find a way how to build `protoc-gen-grpc-swift` from source. The documentation states as following:
<img width="798" alt="image" src="https://github.com/user-attachments/assets/03eefa32-acd8-4675-acdb-e95e277fb047">

The first command works as expected:
```
swift build --product protoc-gen-swift
Building for debugging...
[155/155] Applying protoc-gen-swift
Build of product 'protoc-gen-swift' complete! (15.06s)
```
However the second one fails:
```
swift build --product protoc-gen-grpc-swift
Building for debugging...
error: no product named 'protoc-gen-grpc-swift'
```

### What have you tried so far?

I tried following commands:
```
swift build --product protoc-gen-swift
swift build -c release
```

**Comment by piotrkowalczuk** [comment]
Now I see. I has been moved to  `github.com/grpc/grpc-swift-protobuf`.

**Comment by glbrntt** [comment]
@piotrkowalczuk `grpc/grpc-swift-protobuf` is for grpc-swift 2.x which is still work in progress, you likely want `protoc-gen-grpc-swift` for v1.x which you can still build from the source if this repository on the `release/1.x` branch (there's an open PR updating the docs to explain this).
