### ISSUE TITLE
When upgrading from 1.23.0 to 1.23.1 "protoc-gen-grpc-swift=/${BUILD_DIR}/${CONFIGURATION}" becomes "protoc-gen-grpc-swift=/$%7BBUILD_DIR%7D/$%7BCONFIGURATION%7D" and breaks the build

### ISSUE THREAD

**Issue by Lutzifer** [grpc/grpc-swift#2085]
### Describe the bug

When upgrading from 1.23.0 to 1.23.1 "protoc-gen-grpc-swift=/${BUILD_DIR}/${CONFIGURATION}" becomes "protoc-gen-grpc-swift=/$%7BBUILD_DIR%7D/$%7BCONFIGURATION%7D" and breaks the build.

With 1.23.0, the shell script that is generated during the build is

```
#!/bin/sh
/usr/bin/sandbox-exec -p "(version 1)
(deny default)
(import \"system.sb\")
(allow file-read*)
(allow process*)
(allow mach-lookup (global-name \"com.apple.lsd.mapdb\"))
(allow file-write*
    (subpath \"/private/tmp\")
    (subpath \"/private/var/folders/fl/14_g861101sg0qfb9qrtrhwr0000gn/T\")
)
(deny file-write*
    (subpath \"/Users/admin/dev/Synchronizing/clinic-app-mobile/iOS\")
)
(allow file-write*
    (subpath \"/Users/admin/Library/Developer/Xcode/DerivedData/ClinicApp-aisphxldtrzqiraqscjpzjjuettp/SourcePackages/plugins/ClinicApp.output/API/GRPCSwiftPlugin\")
    (subpath \"/private/var/folders/fl/14_g861101sg0qfb9qrtrhwr0000gn/T/TemporaryItems\")
    (subpath \"/private/var/folders/fl/14_g861101sg0qfb9qrtrhwr0000gn/T/TemporaryItems/NSIRD_Xcode_lhUx2k\")
)
" /opt/homebrew/bin/protoc "--plugin=protoc-gen-grpc-swift=/${BUILD_DIR}/${CONFIGURATION}/protoc-gen-grpc-swift" --grpc-swift_out=/Users/admin/Library/Developer/Xcode/DerivedData/ClinicApp-aisphxldtrzqiraqscjpzjjuettp/SourcePackages/plugins/ClinicApp.output/API/GRPCSwiftPlugin -I /Users/admin/dev/Synchronizing/clinic-app-mobile/iOS/Sources/API/Base --grpc-swift_opt=Visibility=Public --grpc-swift_opt=Client=true --grpc-swift_opt=KeepMethodCasing=false clinic_app/v1/service.proto
```

After upgrading to 1.23.1 it becomes

```
#!/bin/sh
/usr/bin/sandbox-exec -p "(version 1)
(deny default)
(import \"system.sb\")
(allow file-read*)
(allow process*)
(allow mach-lookup (global-name \"com.apple.lsd.mapdb\"))
(allow file-write*
    (subpath \"/private/tmp\")
    (subpath \"/private/var/folders/fl/14_g861101sg0qfb9qrtrhwr0000gn/T\")
)
(deny file-write*
    (subpath \"/Users/admin/dev/Synchronizing/clinic-app-mobile/iOS\")
)
(allow file-write*
    (subpath \"/Users/admin/Library/Developer/Xcode/DerivedData/ClinicApp-aisphxldtrzqiraqscjpzjjuettp/SourcePackages/plugins/ClinicApp.output/API/GRPCSwiftPlugin\")
    (subpath \"/private/var/folders/fl/14_g861101sg0qfb9qrtrhwr0000gn/T/TemporaryItems\")
    (subpath \"/private/var/folders/fl/14_g861101sg0qfb9qrtrhwr0000gn/T/TemporaryItems/NSIRD_Xcode_RrTA3c\")
)
" /opt/homebrew/bin/protoc "--plugin=protoc-gen-grpc-swift=/$%7BBUILD_DIR%7D/$%7BCONFIGURATION%7D/protoc-gen-grpc-swift" --grpc-swift_out=/Users/admin/Library/Developer/Xcode/DerivedData/ClinicApp-aisphxldtrzqiraqscjpzjjuettp/SourcePackages/plugins/ClinicApp.output/API/GRPCSwiftPlugin/ -I /Users/admin/dev/Synchronizing/clinic-app-mobile/iOS/Sources/API/Base/ --grpc-swift_opt=Visibility=Public --grpc-swift_opt=Client=true --grpc-swift_opt=KeepMethodCasing=false clinic_app/v1/service.proto
```

Diff:

<img width="907" alt="Screenshot 2024-10-07 at 17 00 19" src="https://github.com/user-attachments/assets/34fc9998-1a30-4a9b-a0a6-caab4ac5ab69">

### To reproduce

1. use the compiler plugin
2. upgrade from 1.23.0 to 1.23.1

### Expected behaviour

Expected: the build is successful.

Instead I get this error:

<img width="937" alt="Screenshot 2024-10-07 at 17 01 30" src="https://github.com/user-attachments/assets/2b3fefb6-8864-469d-8742-6066f9e84f95">

### Additional information

grpc-swift-config.json

```
{
    "protocPath": "/opt/homebrew/bin/protoc",
    "invocations": [
        {
            "protoFiles": [
	            "clinic_app/v1/service.proto"
            ],
            "visibility": "public",
            "client": true,
            "keepMethodCasing": false
        }
    ]
}

```

I think we have the same error with SwiftProtobuf when upgrading from 1.28.1 to 1.28.2

**Comment by glbrntt** [comment]
Ah, I see what's happened... fix incoming.

**Comment by glbrntt** [comment]
@Lutzifer would you mind verifying your problem is fixed by depending on `branch: "release/1.x"? Once that's confirmed I'll tag a release for you.

**Comment by Lutzifer** [comment]
thanks for the really fast fix, I can confirm branch "release/1.x" fixes the issue.

> I think we have the same error with SwiftProtobuf when upgrading from 1.28.1 to 1.28.2

I can also confirm that there is no additional issue with SwiftProtobuf, should have tested them each on their own before opening the ticket...

**Comment by glbrntt** [comment]
Released in [1.24.0](https://github.com/grpc/grpc-swift/releases/tag/1.24.0)

**Comment by Lutzifer** [comment]
this is suddenly reappearing with 1.27.2

<img width="821" height="127" alt="Image" src="https://github.com/user-attachments/assets/74811b54-750f-48c6-bbe9-7bde24fe1e01" />

**Comment by Lutzifer** [comment]
(we were on an older version, so it was most likely broken again in https://github.com/grpc/grpc-swift/commit/5770e231585cb68388a6ae37ce36c4d8dbd46d90)
