### ISSUE TITLE
Breaking Backward Compatibility in 1.24.0

### ISSUE THREAD

**Issue by sidepelican** [grpc/grpc-swift#2089]
### What are you trying to achieve?

Up to version 1.23.0, the `GRPC` product was exported in Package.swift, but it seems to have been removed starting from 1.24.0.  
https://github.com/grpc/grpc-swift/compare/1.23.1...1.24.0#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eL34
Additionally, it feels that the changes are too significant for a minor update. Is this release correct?
This presents a significant breaking change in backward compatibility, and libraries that were used in the form of:
```swift
.package(url: "https://github.com/grpc/grpc-swift.git", from: "1.0.0"),
```
are likely going to encounter build errors.

### What have you tried so far?

Build https://github.com/slashmo/swift-otel

**Comment by glbrntt** [comment]
Apologies @sidepelican, the wrong branch was targeted in the release. I've just released [1.24.1](https://github.com/grpc/grpc-swift/releases/tag/1.24.1) targeting the correct branch.
