### ISSUE TITLE
protoc-gen-grpc-swift binary not generated when building for Ubuntu 24.04

### ISSUE THREAD

**Issue by adrianosela** [grpc/grpc-swift#2092]
### Describe the bug

Building with `swift build -c release` in this repo's main branch does not produce the binary `protoc-gen-grpc-swift` in `.build/release/` (it doesnt produce *any* binaries there).

Environment description: a docker container based off of Ubuntu 24.04 running on an M1 MacBook Pro (ARM).

- Ubuntu Version: 24.04
- Architecture: aarch64 
- Swift Version: 6.0.1
- Protoc Gen Swift Version: 1.28.2
- Protoc Gen GRPC Swift Version: latest / main branch

### To reproduce

Build the Dockerfile in the [Additional information](#additional-information) section here.

`docker build -t <image name> .`

Get a TTY in the container

`docker run -it <image name> bash`

Try to find the binary in `/app/grpc-swift/.build/release` -- its not there :(

It is there if instead of cloning main, I clone branch `release/1.x`

### Expected behaviour

I expect to find a built `protoc-gen-grpc-swift` binary in the `.build/release/` subdirectory after running `swift build -c release`.

### Additional information

Dockerfile:

```
FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    build-essential \
    clang \
    libssl-dev \
    protobuf-compiler

# install swift
RUN curl https://download.swift.org/swift-6.0.1-release/ubuntu2404-aarch64/swift-6.0.1-RELEASE/swift-6.0.1-RELEASE-ubuntu24.04-aarch64.tar.gz -o swift.tar.gz
RUN tar xzf swift.tar.gz --directory / --strip-components=1 && rm swift.tar.gz

WORKDIR /app

# install swift protobuf
RUN git clone https://github.com/apple/swift-protobuf.git && \
    cd swift-protobuf && \
    swift build -c release && \
    cp .build/release/protoc-gen-swift /usr/local/bin/ && \
    cd .. && \
    rm -rf swift-protobuf

# install swift grpc
RUN git clone https://github.com/grpc/grpc-swift.git && \
    cd grpc-swift && \
    swift build -c release # && \
#    cp .build/release/protoc-gen-grpc-swift /usr/local/bin/ && \
#    cd .. && \
#    rm -rf grpc-swift

# need to download well-known types (e.g. timestamp, struct, ...)
RUN git clone https://github.com/protocolbuffers/protobuf.git && \
    mkdir -p /usr/include && \
    cp -r protobuf/src/* /usr/include/ && \
    rm -rf protobuf
```

**Comment by glbrntt** [comment]
This is expected: per the note in the README the main branch is being used for development of v2. For v1 you need to use the release/1.x branch.

Generally speaking you shouldn't depend on a specific branch, you should depend on a tagged version, so you should clone the grpc-swift repo and checkout the tag you want to use.
