### ISSUE TITLE
ServerInterceptor only called before handling request, not after (2.0.0-alpha.1)

### ISSUE THREAD

**Issue by tweidema** [grpc/grpc-swift#2097]
### ServerInterceptor only called before handling request, not after

This is in 2.0.0-alpha.1. Possible I am doing something wrong or that it's simply not implemented yet, that's why I'm not creating a bug-report. The fact that there is no response in the intercept function also makes me believe it's simply not implemented yet?

### What have you tried so far?

I have created an interceptor:
```
struct grpcServerTracingInterceptor: ServerInterceptor {
    let logger: Logger
    init(logger: Logger) {
        self.logger = logger
    }
    func intercept<Input: Sendable, Output: Sendable>(
        request: StreamingServerRequest<Input>,
        context: ServerContext,
        next: @Sendable (
           _ request: StreamingServerRequest<Input>,
           _ context: ServerContext
        ) async throws -> StreamingServerResponse<Output>
    ) async throws -> StreamingServerResponse<Output> {
        logger.info("Intercepting \(context.descriptor.service):\(context.descriptor.method)")
        // Forward the request.
        return try await next(request, context)
    }
}
```
And added it to the GRPCServer during creation:
```
            let tracingInterceptor = grpcServerTracingInterceptor(logger: logger)

            let server = GRPCServer(
                transport: .http2NIOPosix(
                    address: .ipv4(host: self.host, port: Int(self.port)),
                    config: .defaults(transportSecurity: .plaintext)
                ),
                services: [provider],
                interceptors: [tracingInterceptor]
            )
```
In a gRPC request that is completed normally (eg. the client gets a valid response), the interceptor is called before the call is handled, but not after.

**Comment by gjcairo** [comment]
Hi @tweidema. the `next` closure you call at the end of your interceptor's implementation actually returns the handled response. Instead of returning it immediately, you could do something with it before returning. For example:
```swift
logger.info("Intercepting \(context.descriptor.service):\(context.descriptor.method)")
// Forward the request.
var response = try await next(request, context)
// ... do something with `response`
return response
```

Does this answer your question? Or were you thinking of something else?

**Comment by tweidema** [comment]
@gjcairo Thank you for responding so quickly, and yes, that is exactly what I wanted :-)
My Swift-fu is still somewhat lacking, or I could probably have guessed that based on the declaration of the intercept function.
You can close this issue.
