### ISSUE TITLE
NSCondition.wait()s can wake up spuriously

### ISSUE THREAD

**Issue by gmilos** [grpc/grpc-swift#21]
`NSCondition.wait()` can be woken up spuriously, `done.wait()` must be put in `while(!condition)` loop. https://developer.apple.com/reference/foundation/nscondition

**Comment by timburks** [comment]
Please review this new [CountDownLatch](https://github.com/grpc/grpc-swift/blob/master/Sources/gRPC/CountDownLatch.swift) class. It's currently based on NSCondition, but gRPC Core also includes a condition variable in [include/grpc/support/sync.h](https://github.com/grpc/grpc-swift/blob/master/Sources/CgRPC/grpc/support/sync.h), which we may want to use instead.

**Comment by timburks** [comment]
CountDownLatch was replaced with DispatchSemaphore in [this commit](https://github.com/grpc/grpc-swift/commit/8170253611022ec193fe82aa52ae23dab1b69cdc)
