### ISSUE TITLE
Can we remove the 1.24.0 tag?

### ISSUE THREAD

**Issue by slevin** [grpc/grpc-swift#2102]
### Describe the bug

I see that 1.24.0 was mistakenly placed on the wrong commit.

We indirectly depend on grpc-swift through opentelemetry-swift (https://github.com/open-telemetry/opentelemetry-swift).

However, even though there are newer tags, Swift Package Manager really wants to resolve against this tag sometimes.
And once it fails to find the matching products, it gives up and won't run through a package update to get a newer tag.

Some magic mix of reverting the package.resolved file, restarting xcode, deleting derived data, and inserting a direct dependency on a newer tag than 1.24.0 usually works.
I have to work through these steps with a lot of different developers who keep running into this.
I'm sure other people are running into this as well.

It seems it would just stop happening if 1.24.0 weren't around for SPM to take.
Is there any way we could just remove this broken tag or rename it so it doesn't automatically get picked up by SPM?

### To reproduce

Steps to reproduce the bug you've found:
1. Set compression to ...
2. Make a bidirectional RPC to ...
3. ...

### Expected behaviour

Describe what you expect to happen when the steps above are followed.

### Additional information

Include any information that you think might help us to diagnose and resolve
this more quickly, such as logs, code snippets, or similar cases where the bug
does not reproduce. (Please wrap code snippets and logs in backticks though!)

**Comment by Lukasa** [comment]
Thanks for filing this!

Unfortunately, removing the tag doesn’t affect existing checkouts, including your local caches. That would still require that your team delete caches, which isn’t ideal. 

I think SwiftPM resolving this is a bug, and it’d be worth filing it. In any case though, the easiest fix is to add an explicit gRPC-Swift dependency yourself that sets a minimum version higher than 1.24. This would make it impossible for SwiftPM to resolve that version.
