### ISSUE TITLE
Missing GRPC module (Swift PM + Custom Build Phase)

### ISSUE THREAD

**Issue by sunderee** [grpc/grpc-swift#2103]
### Describe the bug

Current setup: iOS project using SwiftUI, and a `.proto` file located at `PROJECT/PROJECT/Protos/` directory. I have a custom script in Build Phases:

```bash
PROTO_OUT="${SRCROOT}/PROJECT/Generated"
FINAL_OUT="${SRCROOT}/PROJECT/Networking/Generated"

mkdir -p "${PROTO_OUT}"
mkdir -p "${FINAL_OUT}"

# Process proto file
/opt/homebrew/bin/protoc \
  --proto_path="${SRCROOT}/PROJECT" \
  --plugin=/opt/homebrew/bin/protoc-gen-swift \
  --plugin=/opt/homebrew/bin/protoc-gen-grpc-swift \
  --swift_opt=Visibility=Public \
  --swift_out="${PROTO_OUT}" \
  --grpc-swift_opt=Visibility=Public \
  --grpc-swift_out="${PROTO_OUT}" \
  "Protos/MyProto.proto"

mv "${PROTO_OUT}/Protos/"*.swift "${FINAL_OUT}"
rm -rf "${PROTO_OUT}"
```

I have added the `grpc-swift-nio-transport` and `grpc-swift-protobuf` dependencies via Xcode (File -> Add Package Dependencies) and set the dependency rule to use the `release/1.x` branch.

In the `*.grpc.swift` file, there's an import `import GRPC` for which Xcode signals "No such module 'GRPC'".

### To reproduce

Create a blank iOS project in Xcode (16.1), add any `.proto` file to the `PROJECT/PROJECT/Protos` directory, add a new build phase script, and build the project.

### Expected behaviour

In the generated file, GRPC module should be found.

### Additional information

None.

**Comment by glbrntt** [comment]
hi @sunderee – are you trying to use v1 or v2? 

- The `GRPC` module comes from v1, so if you want that then you need to add a dependency on `grpc-swift`, but don't use the `release/1.x` _branch_, set the minimum version to "1.24.1" (which really means "1.24.1" up-to-but-not-including "2.0.0").
- The `grpc-swift-nio-transport` and `grpc-swift-protobuf` packages are for v2, so mustn't be added when using v1.
