### ISSUE TITLE
Service Config, RPC retry policy, load balancing and custom name resolution in v1.x

### ISSUE THREAD

**Issue by maniak-dobrii** [grpc/grpc-swift#2107]
### What are you trying to achieve?
For grpc-swift **1.x** (or v1, can use 1.24.1, the latest at the moment for reference)
1. Is there a way to apply `GRPCChannel` configuration based on [Service Config](https://grpc.io/docs/guides/service-config/)?

    - An RPC (vs connection) [retry policy](https://grpc.io/docs/guides/retry/), load balancing etc.
  
3. Is there a [load balancing](https://grpc.io/docs/guides/custom-load-balancing/) and [custom name resolution](https://grpc.io/docs/guides/custom-name-resolution/) implementation? Maybe, available as a separate package?

### What have you tried so far?

Based on my understanding after reading the documentation, examples and (shallow) investigating v1 and v2 code, all the implementations in question are only available in v2 and not in v1:
* a Service Config based configuration (via `CallOptions` and `ServiceConfig` etc.), 
* load balancing (via `PickFirstLoadBalancer` etc.),
* and custom name resolution (via `NameResolver` etc.) implementations.

The only options to achieve Service Config configuration in v1 are:
* a custom implementation,
    * e.g. a retry policy custom client interceptor implementation,
    * or a custom `GRPCChannel` implementation,
* using pre-release grpc-swift v2.

Thank you.

#### Code examples
While creating the channel via `ClientConnection`:
```
let channel = ClientConnection
    ...
    .connect(host: host, port: port)
```
or a `GRPCChannelPool`:
```
let channel = try GRPCChannelPool.with(
    target: .host(host, port: port)
    ...
)
```

**Comment by glbrntt** [comment]
Apologies for not replying sooner, I missed this. v1 doesn't have support for (and won't get support for) service config or load-balancing. It does have a connection pool which it balances RPCs across.
