### ISSUE TITLE
Unable to configure tls mutual auth with current API

### ISSUE THREAD

**Issue by rlubke** [grpc/grpc-swift#212]
I have three artifacts that our gRPC java client uses

- ca.pem      -> our ca
- client.pem -> client cert
- client.key   -> key

However, the current API doesn't really communicate how to use these entities in concert to make a secure connection.

Using only the client cert, I receive:

> OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

However, I can run:

> openssl s_client -CAfile /certs/ca.pem -cert /certs/client.pem -key /certs/client.key -debug -connect localhost:1408

and properly establish a connection to the remote endpoint.

So, what am I missing in order to get this to properly work with grpc-swift?

**Comment by rlubke** [comment]
I have changes locally that resolve this.  I will clean them up and submit a PR.

**Comment by rlubke** [comment]
It seems that getting legal approval for this will take additional time (don't ask), *sigh*

So, I'll describe, at a high level, what I did and perhaps someone with commits rights and time will resolve the issue.  

**shim/cgrpc.h**

- add two more parameters to **cgrpc_channel_create_secure** to accept the client certificate and key in addition to the existing option for the root pem.

**shim/channel.c**

- Implement header signature change.  Create **grpc_ssl_pem_key_cert_pair struct and store the client certificate and key.
- Pass this struct to the existing call **grpc_ssl_credentials_create**.

**gRPC/Channel.swift**

- Expose arguments for client cert and key along with the existing root pem arguments.
- Update **cgrpc_channel_create_secure call sites to pass the new arguments along

**Comment by bootstraponline** [comment]
It'd be awesome to get mutual auth working for Swift. Hopefully you're able to secure legal approval to contribute the fixes upstream.

**Comment by bootstraponline** [comment]
@rlubke how did you generate the certs? We're seeing cert validation errors after enabling this feature.
