### ISSUE TITLE
Protobuf Generation Failing with examples in the repo

### ISSUE THREAD

**Issue by darvay** [grpc/grpc-swift#2135]
### Describe the bug

Running generate.sh in /grpc-swift/dev/protos/ will regenerate the *.grpc.swift files in the example repo and cause the examples "Echo" to fail to compile

Using generate.sh script to compile protobufs in my local project will generate the new *.grpc.swift, *.pb.swift files that are unable to be used. 

I'm trying to use an older version of `https://github.com/grpc/grpc-swift-protobuf ` to see when this broke.

Here are my build configs, attempting to build off the Echo example. 

let package = Package(
  name: "app",
  platforms: [.macOS("15.0")],
  dependencies: [
    .package(url: "https://github.com/grpc/grpc-swift", exact: "2.0.0-alpha.1"),
    .package(url: "https://github.com/grpc/grpc-swift-protobuf", exact: "1.0.0-alpha.1"),
    .package(url: "https://github.com/grpc/grpc-swift-nio-transport", branch: "1.0.0-alpha.1"),
    .package(url: "https://github.com/apple/swift-argument-parser", from: "1.5.0"),
  ],
  targets: [
    .executableTarget(
      name: "app",
      dependencies: [
        .product(name: "GRPCCore", package: "grpc-swift"),
        .product(name: "GRPCNIOTransportHTTP2", package: "grpc-swift-nio-transport"),
        .product(name: "GRPCProtobuf", package: "grpc-swift-protobuf"),
        .product(name: "ArgumentParser", package: "swift-argument-parser"),
      ]
    )
  ]
)

```
diff --git a/Examples/echo/Sources/Generated/echo.grpc.swift b/Examples/echo/Sources/Generated/echo.grpc.swift
index 88b929b9..26c07524 100644
--- a/Examples/echo/Sources/Generated/echo.grpc.swift
+++ b/Examples/echo/Sources/Generated/echo.grpc.swift
@@ -24,41 +24,63 @@
 import GRPCCore
 import GRPCProtobuf

+// MARK: - echo.Echo
+
+/// Namespace containing generated types for the "echo.Echo" service.
 internal enum Echo_Echo {
-    internal static let descriptor = GRPCCore.ServiceDescriptor.echo_Echo
+    /// Service descriptor for the "echo.Echo" service.
+    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "echo.Echo")
+    /// Namespace for method metadata.
     internal enum Method {
+        /// Namespace for "Get" metadata.
         internal enum Get {
+            /// Request type for "Get".
             internal typealias Input = Echo_EchoRequest
+            /// Response type for "Get".
             internal typealias Output = Echo_EchoResponse
+            /// Descriptor for "Get".
             internal static let descriptor = GRPCCore.MethodDescriptor(
-                service: Echo_Echo.descriptor.fullyQualifiedService,
+                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "echo.Echo"),
                 method: "Get"
             )
         }
+        /// Namespace for "Expand" metadata.
         internal enum Expand {
+            /// Request type for "Expand".
             internal typealias Input = Echo_EchoRequest
+            /// Response type for "Expand".
             internal typealias Output = Echo_EchoResponse
+            /// Descriptor for "Expand".
             internal static let descriptor = GRPCCore.MethodDescriptor(
-                service: Echo_Echo.descriptor.fullyQualifiedService,
+                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "echo.Echo"),
                 method: "Expand"
             )
         }
.....
```

### To reproduce

Steps to reproduce the bug you've found:
1. Checkout latest grpc-swift code
2. Run sh  /grpc-swift/dev/protos/generate.sh
3. Navigate to `/swift/grpc-swift/Examples/echo`
4. run `swift build`

### Expected behaviour

Build will complete

### Additional information

Build fails:

```swift build
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/Users/dave/swift/grpc-swift/Examples/echo/Sources/Generated/echo.grpc.swift:32:88: error: extra argument 'fullyQualifiedService' in call
 30 | internal enum Echo_Echo {
 31 |     /// Service descriptor for the "echo.Echo" service.
 32 |     internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "echo.Echo")
    |                                                                                        `- error: extra argument 'fullyQualifiedService' in call
 33 |     /// Namespace for method metadata.
 34 |     internal enum Method {

/Users/dave/swift/grpc-swift/Examples/echo/Sources/Generated/echo.grpc.swift:32:64: error: missing arguments for parameters 'package', 'service' in call
 30 | internal enum Echo_Echo {
 31 |     /// Service descriptor for the "echo.Echo" service.
 32 |     internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "echo.Echo")
    |                                                                `- error: missing arguments for parameters 'package', 'service' in call
 33 |     /// Namespace for method metadata.
 34 |     internal enum Method {

/Users/dave/swift/grpc-swift/Examples/echo/.build/checkouts/grpc-swift/Sources/GRPCCore/ServiceDescriptor.swift:41:10: note: 'init(package:service:)' declared here
39 |   ///   An empty string means that the service does not belong to any package.
40 |   ///   - service: The name of the service. For example, "Greeter".
41 |   public init(package: String, service: String) {
   |          `- note: 'init(package:service:)' declared here
42 |     self.package = package
43 |     self.service = service
.....
```

Reverting the grpc-swift branch to a state before running generate will cause the builds to succeed.

**Comment by darvay** [comment]
Was actually able to get this working setting the branch on the grpc-swift-protobuf repo in generate.sh

```
# Checkout and build the plugins.
build_dir=$(mktemp -d)
git clone https://github.com/grpc/grpc-swift-protobuf "$build_dir"
cd $build_dir
git fetch --all
git checkout 1.0.0-alpha.1
swift build --package-path "$build_dir" --product protoc-gen-swift
swift build --package-path "$build_dir" --product protoc-gen-grpc-swift
```

**Comment by glbrntt** [comment]
`/dev/protos/generate.sh` is not intended for general purpose use; it's intended for maintainers of this project.

As v2 is in a pre-release state, you must use tagged versions of each of the dependencies to ensure compatibility. This means that to use the examples you must use `protoc-gen-grpc-swift` from `grpc-swift-protobuf` at version `1.0.0-alpha.1`.

**Comment by glbrntt** [comment]
> I seem to have another problem related to this ticket. I can't install `grpc-swift --HEAD` because of an error:
> 
> ## Command
> > brew install grpc-swift --HEAD
> 
> ## Result
> Because of this, I cannot generate code for **v2** with the `GRPCCore` dependency

Only tagged versions of grpc-swift are supported. To build code for v2 you need to build the `protoc-gen-grpc-swift` plugin from the `grpc-swift-protobuf` package at an appropriate version.

**Comment by sheinbergon** [comment]
@glbrntt is there a plan to push v2 formulas into homebrew?

**Comment by glbrntt** [comment]
No; we never maintained the homebrew formulas before. 

We also don't think that using them is a good idea: it's too easy for the generated code to get out of sync with the runtime version of the library which can result in hard to diagnose build failures (usually if the plugin is newer than the runtime).

The recommended approach is to either use the SwiftPM build plugin or build the plugins at the version resolved in your package, e.g. `swift build --product protoc-gen-grpc-swift`. There's ongoing work to make this a little easier as well.

**Comment by sheinbergon** [comment]
That's fair, I guess

A few more questions:

1. Is the previous 1.24.2 production worthy?
2. Should i couple the new plugin with the vanilla swift-protobuf plugin @ 1.29.0?
