### ISSUE TITLE
Support for iOS versions below 18 (GRPC V2)

### ISSUE THREAD

**Issue by NoFearJoe** [grpc/grpc-swift#2147]
Currently, we are using the 1st version of GRPC framework, but we'd like to try the 2nd version.
Unfortunately, it's available only from iOS 18 which is 2 version higher than our minimum target.

My question is will the minimum version be lowered in one of the next releases? I guess, there are a lot of projects with the same problem.

**Comment by glbrntt** [comment]
Thank you for your question. Unfortunately, we won’t be able to lower the minimum version requirement because v2 relies on APIs that were introduced in iOS 18 (primary associated types on AsyncSequences are one example).

**Comment by RockLobster** [comment]
So are you planning on still supporting the 1.x branch of grpc-swift for the foreseeable future?

**Comment by Lutzifer** [comment]
@glbrntt thx, hadn't seen that info before.
