### ISSUE TITLE
Manual integration - does not work for iOS

### ISSUE THREAD

**Issue by JCzz** [grpc/grpc-swift#218]
Hi

I have tried for some days to get this working on iOS - but maybe is is not surpose to work for iOS for now and only for MacOs?

Is that correct?

Note: I have followed the Manual integration hoping it would work for iOS.

Thanks in advance

**Comment by MrMage** [comment]
I haven’t tested this myself on iOS, but I think it should work. What problems are you encountering?

**Comment by JCzz** [comment]
Hi @MrMage

My Setup is:
```
MacOs 10.13.4
Xcode 9.3
```
Getting error: `No such module 'ProtocolBuffers'`
The specific steps I have done:
Install swift-protobuf
1. `brew install swift-protobuf`

Building grpc-swift
1. `git clone https://github.com/grpc/grpc-swift.git`
2.  `cd grpc-swift`
3. `make`
4. `cd third_party`
5 `sh RUNME.sh`
6. `cd ../..`
I had an issue with SwiftGRPC.xcodeproj not showing up in grpc-swift - make did not create the project. Then I did manually:
7. `swift package generate-xcodeproj`

protoc-gen-swift & protoc-gen-swiftgrpc
Plugins need to be in the path.
pwd is root of grpc-swift
8. `export PATH=$PATH:$(pwd)`

Generate Swift files from .proto
Form this: `https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto`
1.`protoc helloworld.proto --swift_out=. --swiftgrpc_out=.

Create a new Swift App in Xcode
1. Create Swift iOS app
After building your project, add the generated SwiftGRPC.xcodeproj to your project, and add build dependencies on BoringSSL, CgRPC, and SwiftGRPC.
2. I added to my target in my project: Build Phases / Target Dependencies
- `BoringSSL`
- `CgRPC`
- `SwiftGRPC`
3. Please also note that your project will need to include the SwiftProtobuf.xcodeproj from Swift Protobuf and the source files that you generate with protoc/plugins.

This gives me the following error in the genereted `rpc.swift` file:
`No such module 'ProtocolBuffers'`

I tried to add `Build Phases / Target Dependencies` to `SwiftProtobuf_iOS` still the same error.

**Comment by MrMage** [comment]
Weird, I can't find any reference to the string `ProtocolBuffers` in my project. Could you try searching for it and see where exactly it is used?

**Comment by JCzz** [comment]
It is the:
`protoc --swiftgrpc_out=. --swift_out=. helloworld.proto`
that generates the `import ProtocolBuffers` and it is in the `.proto.swift`file.

I include the two generated file into my project.

**Comment by MrMage** [comment]
Is it possible that the version of the swift protobuf compiler plugin installed via brew is completely outdated?

**Comment by JCzz** [comment]
Good suggestion - I will try to uninstall and use only the one from the grpc-swift project third_party

**Comment by JCzz** [comment]
Do you know anyone how have this running on iOS?

**Comment by basalphenaar** [comment]
I've been able to get it running successfully in my iOS project using these instructions: https://github.com/KyoheiG3/gRPCExample

It's cumbersome, and it requires you to do this every time when a new Swift gRPC update is out, but it works. I'm keeping my fingers crossed for Carthage support in the future to make the update process easier.

**Comment by JCzz** [comment]
Hi @basalphenaar

That is cool, thanks for sharing!

**Comment by timburks** [comment]
@JCzz I don't know if using Cocoapods is an option for you, but if it is, I just merged a [very simple iOS sample that uses Cocoapods and calls a Google Cloud API](https://github.com/grpc/grpc-swift/tree/master/Examples/Cocoapods/NaturalLanguage).

**Comment by DroidFxGit** [comment]
Hi @basalphenaar I checked your iOS example was very helpful and it runs well, but I haven't found a way to run the command to translate .proto files into its .swift classes. Previously I have installed swift_protobuf homebrew library and I could convert messages from .proto into swift classes but i was not able to convert services. As I've checked you have to use something like: "protoc protofile.proto --swiftgrpc_out=." I don't know if somebody else has had this issue in your projects

**Comment by DroidFxGit** [comment]
if someone had troubles with protoc-gen-swift protoc-gen-swiftgrpc integration this tutorial was very useful for me :) https://qiita.com/tikidunpon/items/9759dc6e65da09986c1f

**Comment by basalphenaar** [comment]
@JonasVautherin Thank you so much for adding Carthage support, manually updating grpc-swift every time was becoming quite a nuisance! This is going to save me a lot of time.

**Comment by MrMage** [comment]
Closing this for now, as [@JonasVautherin's instructions](https://github.com/grpc/grpc-swift/issues/218#issuecomment-412986474) have hopefully resolved the issue.
