### ISSUE TITLE
Unprotected concurrent access to writing flag

### ISSUE THREAD

**Issue by gmilos** [grpc/grpc-swift#22]
`Call.writing` flag must always be protected by `sendMutex`. It's not, e.g. in [sendWithoutBlocking failure branch](https://github.com/grpc/grpc-swift/blob/1ac521b87460492da4e2995ebffb3f5717cd5ff0/Sources/gRPC/Call.swift#L279).

**Comment by MrMage** [comment]
I think this has been fixed by now and can be closed?
