### ISSUE TITLE
`swift-nio-zlib-support` pulls in incompatible version of `ncurses`

### ISSUE THREAD

**Issue by tsabirgaliev** [grpc/grpc-swift#220]
When building on a Mac with Macports, `pkgConfig: "zlib"` in `swift-nio-zlib-support` emits `-I/opt/local/include` flag, because **Macports comes with its own `pkg-config`**.  It potentially breaks the build, because `/opt/local/include` may contain incompatible versions of libraries referred from PlatformSDK.  For example: https://github.com/grpc/grpc-swift/issues/205#issuecomment-384274112

@MrMage probably this commit: https://github.com/grpc/grpc-swift/commit/263e66bad2e6db7853e719d2f271fed0952461ab broke the build

**Comment by MrMage** [comment]
Given that the current implementation does build on clean systems, what would you suggest to fix this on systems with MacPorts installed?

**Comment by moldabekov** [comment]
@MrMage I've opened issue in Apple's repo https://github.com/apple/swift-nio-zlib-support/issues/2.

There are three ways for fellow devs to fix it by themselves described here: https://github.com/grpc/grpc-swift/issues/205#issuecomment-384666911. All of them aren't elegant.

While Apple thinks about the fix, it'd be nice to vendor `swift-nio-zlib-support` by ownself. Still it's a simple wrapper with a few lines `Package.swift` file. This seems to me the most convenient way to fix conflict with MacPorts.

**Comment by MrMage** [comment]
I'm not particularly excited about vendoring that `Package.swift`, but I wouldn't object to it either, especially if it's only temporary.

From my side feel free to prepare a pull request, but the final call will have to be made by @timburks of course.

**Comment by tsabirgaliev** [comment]
@MrMage what about something like this:

```swift
#if os(macOS)
let dependencies: [Package.Dependency] = [
    .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.0.2"),
    .package(url: "https://github.com/kylef/Commander.git", from: "0.8.0")
  ]
#else
let dependencies: [Package.Dependency] = [
    .package(url: "https://github.com/apple/swift-nio-zlib-support.git", from: "1.0.0"),
    .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.0.2"),
    .package(url: "https://github.com/kylef/Commander.git", from: "0.8.0")
  ]
#endif

let package = Package(
  name: "SwiftGRPC",
  ...
  dependencies: dependencies,
```

**Comment by tsabirgaliev** [comment]
@MrMage here https://github.com/grpc/grpc-swift/pull/221

**Comment by rlubke** [comment]
Just wanted to add a note here.  After @MrMage's fix, I was still having the same compilation issue on master as described here.

I was able to resolve it by running `port reclaim`.  This removed all of the cruft no longer used by my current ports which resolved the compilation issue.

**Comment by tsabirgaliev** [comment]
@rlubke I believe `port reclaim` among other things removed `pkg-config`, and that solved your issue there.
