### ISSUE TITLE
Missing implementation after generating grpc files

### ISSUE THREAD

**Issue by chryb** [grpc/grpc-swift#223]
After using the latest stable `protoc-gen-swiftgrpc` plugin, I get this error everywhere in my grpc files.

<img width="772" alt="screen shot 2018-05-01 at 11 16 08" src="https://user-images.githubusercontent.com/1353438/39468040-6c32409a-4d31-11e8-817e-071119a374cb.png">

I'm using XCode 9.3 for iOS 11.3.

**Comment by MrMage** [comment]
Thank you for the info. What protocol stubs is the compiler suggesting? Also, which versions exactly (tag or branch) are you using both to compile the plugin and to include as a dependency?

**Comment by chryb** [comment]
For example this stubs:
![image](https://user-images.githubusercontent.com/1353438/39491212-cdf7f77a-4d8b-11e8-99a8-0a0e39caec2a.png)

![image](https://user-images.githubusercontent.com/1353438/39491244-e9c37c18-4d8b-11e8-8bb0-d553cf21e7ab.png)

I just cloned the latest grpc-swift repo and run `make` and the `RUNME.sh` file in the `third_party` folder. After running the RUNME.sh I already tested both options, the latest stable (I think v1.0.2) and the latest master.

**Comment by chryb** [comment]
Ok, I think I found the problem. I've added the dependencies through Cocoapods some time ago: `pod 'gRPC-Core', :git => 'https://github.com/mrmage/grpc', :branch => 'fix-cocoapods-swift'
    pod 'SwiftGRPC', :git => 'https://github.com/grpc/grpc-swift'`.

The problem was that `SwiftGRPC` was an old version and with the new one I could remove the ´gRPC-Core` dependency. Thank you for your help!
