### ISSUE TITLE
Errors sending messages aren't exposed to the client

### ISSUE THREAD

**Issue by gmilos** [grpc/grpc-swift#23]
https://github.com/grpc/grpc-swift/blob/1ac521b87460492da4e2995ebffb3f5717cd5ff0/Sources/gRPC/Call.swift#L278

**Comment by MrMage** [comment]
Has this been sufficiently addressed by now? Most code should be returning errors when an operation failed now (except for a few cases in e.g. https://github.com/grpc/grpc-swift/blob/master/Sources/SwiftGRPC/Runtime/ServerSessionUnary.swift, but those should get addressed soon as well).
