### ISSUE TITLE
Protoc-generated swift files not compatible with SwiftGrpc (CocoaPods)

### ISSUE THREAD

**Issue by sabiland** [grpc/grpc-swift#231]
1) I have installed in my project SwiftGrpc via CocoaPods
2) Then I generated Swift proxy files via:

```
protoc <your proto files> \
    --swift_out=. \
    --swiftgrpc_out=.
```

3) Then I dragged generated swift files into project, but the project doesn't compile (see screenshot) [ScreenShot](https://i.imgur.com/d8jv0Hp.png)

4) When I checked handleMethod definition (from SwiftGrpc CocoaPods) I see different definition like this:

```
/// Handle the given method. Needs to be overridden by actual implementations.
  /// Returns whether the method was actually handled.
  open func handleMethod(_ method: String, handler: Handler, queue: DispatchQueue) throws -> Bool { fatalError("needs to be overridden") }
```

5) Also **HandleMethodError** enum is not defined inside SwiftGrpc (CocoaPods)

Any ideas?

**Comment by MrMage** [comment]
You are most likely using an outdated version of either the plugin or the codegen. See https://github.com/grpc/grpc-swift/issues/223 for example.

**Comment by sabiland** [comment]
Thx for info. I'll check #223.

**Comment by sabiland** [comment]
@MrMage can you please check this [SwiftGrpc 0.4.2](https://i.imgur.com/OG7aZyZ.png) ?

Is this the latest version (0.4.2)?

**Comment by MrMage** [comment]
Yes, but what version is your protoc plugin? You need to check that out with the same version.

**Comment by sabiland** [comment]
I took protoc-3.5.1-osx-x86_64 from [google/protobuf](https://github.com/google/protobuf/releases)

**Comment by MrMage** [comment]
I mean the SwiftGRPC plugin.

**Comment by sabiland** [comment]
Sorry I don't quite understand what you mean?

I installed SwiftGrpc via CocoaPods:

`pod 'SwiftGRPC'`

**Comment by MrMage** [comment]
You need to compile the SwiftGRPC plugin for the protoc compiler yourself. How did you do that?

**Comment by cepages** [comment]
Same problem here.

I fixed with @eaigner advise. ( Thanks :) )

SwiftGRPC: `0.4.2`
protoc --version `libprotoc 3.5.1`
protoc-gen-swift --version `protoc-gen-swift 1.0.3`
protoc-gen-swiftgrpc --version : It doesn't get the version so I assume it's 1.03 too.

My project is using cocoa pods and this is the pod line in the Podile for SwiftGRPC:

`pod 'SwiftGRPC', '= 0.4.2'`

**Comment by MrMage** [comment]
Could you try connecting to a non-SSL gRPC server? Also, how are you linking with BoringSSL and/or OpenSSL? SwiftGRPC links with BoringSSL by default, and linking with both could be problematic.

**Comment by sabiland** [comment]
Thx for info. Will check.

**Comment by sabiland** [comment]
Yes bingo!

After I used non-secure constructor:

```
let masterService = Asr_AsrServiceServiceClient(
            address: SpeechASRPROXY.HOSTASRPROXY,
            secure: false,
            arguments: []
        )
```

Everything works ok now :)

Thx @MrMage

**Comment by MrMage** [comment]
Note that I do not recommend using non-SSL services in production ;-)

**Comment by jatink-copper** [comment]
Hi Marge i have generated the swift grpc plugin but not able to invoke can you tell me the process.

**Comment by MrMage** [comment]
You need to copy the plugin to your PATH, like you did with the Swift plugin.

**Comment by srksista** [comment]
protoc  sample.proto  --swift_out=. --swiftgrpc_out=.
dyld: Symbol not found: _$SBi32_WV
  Referenced from: /usr/local/bin/protoc-gen-swiftgrpc
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/protoc-gen-swiftgrpc
--swiftgrpc_out: protoc-gen-swiftgrpc: Plugin killed by signal 6.

XCode: 10.2 and its command tool
protoc --version
libprotoc 3.9.0

Anhy suggestions to resolve this issue?

**Comment by srksista** [comment]
Issue resolved ny updating "protoc-gen-swiftgrpc" .
