### ISSUE TITLE
Cannot authenticate via API key

### ISSUE THREAD

**Issue by eaigner** [grpc/grpc-swift#234]
I just cannot get authentication to work using Google Cloud (Speech) API keys. I've checked every example there is, yet my key is always rejected. I set the API key on the service `metadata`.

I've seen examples using...

- `X-Goog-Api-Key`: swift grpc says invalid header. Error:

```
invalidMetadata
E0524 08:35:15.361115000 6176894976 call.cc:935] validate_metadata: {"created":"@1527143715.360978000","description":"Illegal header key","file":"/Users/era/Desktop/SpeechTest/Pods/gRPC-Core/src/core/lib/surface/validate_metadata.cc","file_line":43,"offset":0,"raw_bytes":"58 2d 47 6f 6f 67 2d 41 70 69 2d 4b 65 79 'X-Goog-Api-Key'"}
```

- `Authorization`: `Bearer + Token`, swift grpc says invalid header

```
invalidMetadata
E0524 08:36:53.669556000 6135263232 call.cc:935] validate_metadata: {"created":"@1527143813.669152000","description":"Illegal header key","file":"/Users/era/Desktop/SpeechTest/Pods/gRPC-Core/src/core/lib/surface/validate_metadata.cc","file_line":43,"offset":0,"raw_bytes":"41 75 74 68 6f 72 69 7a 61 74 69 6f 6e 'Authorization'"}
```

- `X-Api-Key`: seems to work as a header

```
successful, status permissionDenied: The request is missing a valid API key.
```

**Comment by MrMage** [comment]
FYI, I think the `Authentication` header should be `authorization`. Also, could you provide more details on the errors SwiftGRPC provides, especially the exact error message?

**Comment by eaigner** [comment]
Ah yes, I meant authorization. Typo.

**Comment by eaigner** [comment]
It also seems that casing matters. `x-api-key` works, `X-Api-Key` doesn't -> invalid header key.

**Comment by MrMage** [comment]
Please paste the full error messages in verbatim and how you are trying to set the headers.

**Comment by eaigner** [comment]
These are the full messages in verbatim.

**Comment by eaigner** [comment]
```
let service = Google_Cloud_Speech_V1p1beta1_SpeechServiceClient(address: "speech.googleapis.com")
service.metadata.add(key: "x-goog-api-key", value: "MY_KEY")
```

**Comment by MrMage** [comment]
What's the error message if you use a lowercase `authorization` header?

**Comment by eaigner** [comment]
`authorization`:

```
successful, status unauthenticated: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
trailingMetadata: www-authenticate:Bearer realm="https://accounts.google.com/", error="invalid_token"
```

But it's an console API key, not an OAuth token, so I guess in this case this is correct. A lowercase `x-goog-api-key` gives no errors, yet I get no streamed results now.

**Comment by MrMage** [comment]
You can't provide an API key as a `Bearer` token. Try generating a proper OAuth token via https://developers.google.com/oauthplayground/ and putting that into the `authorization` header.

Alternatively, if you have service account credentials, you could sign a JWT token yourself as described in https://developers.google.com/identity/protocols/OAuth2ServiceAccount#jwt-auth.

**Comment by eaigner** [comment]
I just wrote this... please read my posts.

```
But it's an console API key, not an OAuth token, so I guess in this case this is correct. A lowercase x-goog-api-key gives no errors, yet I get no streamed results now.
```

**Comment by MrMage** [comment]
Sorry, I misunderstood the last part. If you aren't getting an error, I'd suppose that authentication works, but I have no idea about how that API is supposed to work. How are you trying to use it?

**Comment by MrMage** [comment]
That only waits for the final gRPC status. You'll need to call `call.receive...` to actually receive replies.

**Comment by eaigner** [comment]
I did try that. But `receive` never returns.

**Comment by MrMage** [comment]
Do you have an example of how you tried that? Also, did you try closing the call after sending the last piece of data?

**Comment by MrMage** [comment]
FYI, have a look at https://github.com/grpc/grpc-swift/blob/8941a852aaec9cacf07c6cacc6a6dbbe65c42619/Tests/SwiftGRPCTests/EchoTests.swift#L145 for a full bidirectional-streaming example.

**Comment by eaigner** [comment]
So I need to make a new call for each request? Like

1. Make call
2. Close call
3. Receive from call
4. Make new call
5. etc...

**Comment by eaigner** [comment]
Just a bit confusing, since all other gRPC apis work with a callback (like ObjC). I've never seen receive or something like this invoked manually in other examples.

**Comment by MrMage** [comment]
You can also use the non-blocking variants of `receive` to pass a callback. But the callback passed to the method that creates the call is the one that is only called once that whole call finishes.

**Comment by MrMage** [comment]
> So I need to make a new call for each request? Like
> 
> Make call
> Close call
> Receive from call
> Make new call
> etc...

That depends on the API. Could you please provide a link to the documentation of the call you are trying to use?

**Comment by eaigner** [comment]
https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1p1beta1

**Comment by MrMage** [comment]
From the documentation, it sounds like sending multiple pieces of data should work, but for testing purposes I would start with just one call to try it.
I would try something like the following:

```
private func recognize(pcmData: Data) throws {
    let call = try makeCall()
    
    try call.send(makeConfigRequest())
    try call.send(makeAudioRequest(pcmData: pcmData))
    call.waitForSendOperationsToFinish()
    try call.closeSend { }
    print(try call.receive())
}
```

**Comment by eaigner** [comment]
What worked for me just now was

```
try call.send(makeAudioRequest(pcmData: pcmData))
try call.receive(completion: self.handleResponse)
```

But I'm getting an `tooManyOperations` error from `call.receive` when I don't speak.  Could this be an indicator that nothing new can be received at the moment?

**Comment by MrMage** [comment]
No idea about that, but you could try inserting `call.waitForSendOperationsToFinish()` in between the `send` and `receive` calls.

**Comment by eaigner** [comment]
No, doesn't affect it. I just use a `try?` when using receive and it works fine. Makes sense, since no new results are available. Still a strange error message.

**Comment by MrMage** [comment]
Looks like we've seen the same error before in https://github.com/grpc/grpc-swift/issues/78, but nowadays SwiftGRPC should automatically ensure that only one message is in flight at a time. And `receive` should be blocking until a new message is available. FWIW, I don't even know whether this error is generated in this particular case by the backend or by the client's gRPC library.

@timburks, do you know anything about this? (FYI, he's on California time, so will take several hours to get a response.)

**Comment by eaigner** [comment]
What does work without error is when I use the blocking call in a loop on a separate dispatch queue that I start right after the call gets created, like so:

```
private func callReceiveLoop() {
        defer {
            print("callReceiveLoop exit")
        }
        while true {
            guard let call = call else {
                return
            }
            do {
                handleResponse(try call.receive())
            } catch {
                print("call-rcv: \(error)")
            }
        }
    }
```

**Comment by MrMage** [comment]
Alternatively, you could also use the async `receive` call and in the completion handler of that call, pass the same completion handler block again.

**Comment by MrMage** [comment]
@eaigner are you still encountering issues with this?

**Comment by zhaxylykbayev** [comment]
Hi! 
I'm having same problem, too.
Error message: **successful, status unavailable: Name resolution failure**
 When I print results' metadata: trailingMetadata: [:],  initialMetadata  nil
My code: 
`     let address = "\(grpcUrl):7080"
      self.chanel = Channel(address: address, secure: false, arguments: [])
      self.client = Aether_AetherServiceServiceClient.init(channel: chanel)
      do{
            let meta = Metadata()
            try meta.add(key: "authorization", value: "Basic \(base64LoginString)")
            self.client.metadata = meta
            print("meta data", self.client.metadata.dictionaryRepresentation)
        }catch {
            print("cath meta")
        }
       do{
            var call = try self.client.listen { (result) in
                 //printing result field
            }.receive()
         } catch {
            print("in catch 1")
        }
        
`

**Comment by MrMage** [comment]
That's a different error, sounds like the computer can't find `grpcUrl`.

**Comment by zhaxylykbayev** [comment]
Thank you @MrMage! it helped me.

**Comment by MrMage** [comment]
Closing this as the previous thread was inactive anyway.

**Comment by prasanna-tapzo** [comment]
@MrMage I am getting the following error:

 validate_metadata: {"created":"@1547640570.096726000","description":"Illegal header key","file":"/Users/prasannaaithal/Documents/ProtoBufTest 2/Pods/gRPC-Core/src/core/lib/surface/validate_metadata.cc","file_line":43,"offset":5,"raw_bytes":"67 72 70 73 2d 4d 61 74 63 68 65 73 2d 4b 65 79 'grps-Matches-Key'"}

I have created the stub instance and added meta data like this:
```
let client = Org_Baeldung_Grpc_HelloServiceServiceClient(address: "hello-grpc.172.16.1.0.nip.io", secure: false)
try! client.metadata.add(key: "grps-Matches-Key", value: "grpc2"). 
```
