### ISSUE TITLE
Rule of thumb: no prints

### ISSUE THREAD

**Issue by gmilos** [grpc/grpc-swift#24]
gRPC support is likely to be rather foundational library in apps. `Print`s done from within are going to confuse the client. Also, it's usually a sign of API shortcoming: Example: https://github.com/grpc/grpc-swift/blob/1ac521b87460492da4e2995ebffb3f5717cd5ff0/Sources/gRPC/Call.swift#L269 (I.e. https://github.com/grpc/grpc-swift/issues/23)

**Comment by timburks** [comment]
[This commit](https://github.com/grpc/grpc-swift/commit/1785d231c5316edade4da910b0db5f57801eb906) replaces print() with a call to a passed-in error handler.
