### ISSUE TITLE
Add homebrew formula for plugins

### ISSUE THREAD

**Issue by SebastianThiebaud** [grpc/grpc-swift#240]
I'm planning on creating formulas for the plugins in this tap: https://github.com/grpc/homebrew-grpc

Any thoughts before I start? Good/bad idea?

**Comment by MrMage** [comment]
Which plugins do you mean? `protoc-gen-swift` and `protoc-gen-swiftgrpc`?

**Comment by SebastianThiebaud** [comment]
`protoc-gen-swiftgrpc` since `protoc-gen-swift` is already available.

**Comment by MrMage** [comment]
Sounds good.

**Comment by esttorhe** [comment]
Just started developing my own service in go with `grpc` and after i'm done with that i'll get back to my `iOS` client.

Just wondering if there has been any advance on this front (I would rather use the plugin without `CocoaPods` or `SwiftPM` and instead install it with homebrew).

I went to the `hombrew-grpc` repo but doesn't appear to contain the `Swift` plugin.

I could give it a try and add it myself but don't want to do the same work if someone already started tackling it.

**Comment by esttorhe** [comment]
That's great; thanks @SebastianThiebaud

**Comment by SebastianThiebaud** [comment]
@MrMage I'd assume the best place to host the formula would be this repo: https://github.com/grpc/homebrew-grpc

**Comment by SebastianThiebaud** [comment]
Someone did https://formulae.brew.sh/formula/grpc-swift

**Comment by ajayz7** [comment]
Rahuls-MBP:grpc_note ajaythakur$ protoc --swiftgrpc_out=. dispatcher.proto 
protoc-gen-swiftgrpc: program not found or is not executable
--swiftgrpc_out: protoc-gen-swiftgrpc: Plugin failed with status code 1.

I am getting this error for creating grpc.swift file, can someone help me please 

@MrMage @SebastianThiebaud can you please help me on this ?
