### ISSUE TITLE
Network.framework

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#253]
[This](https://developer.apple.com/documentation/network/implementing_netcat_with_network_framework) looks useful as a possible transport for gRPC.

It will probably be Apple-only for a while, and requires macOS 10.14+ and Xcode 10+ (both currently in prerelease beta). 

More details are in [this WWDC 2018 session](https://developer.apple.com/videos/play/wwdc2018/715/), with "Video Available Soon".

**Comment by MrMage** [comment]
Agreed. However, I suppose it is unlikely that the gRPC-Core team will support this framework in the near future. Luckily, the SwiftNIO team [is excited about this](https://twitter.com/Lukasaoz/status/1004801028875866113) and [plans to release a Network.framework-based version of that soon](https://twitter.com/johannesweiss/status/1004801044268716032). Which brings us to #172 again 😅

**Comment by MrMage** [comment]
This is supported in the NIO branch now.
