### ISSUE TITLE
Metadata error

### ISSUE THREAD

**Issue by SebastianThiebaud** [grpc/grpc-swift#258]
I was wondering if we were planning on supporting https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto

We came across this talk: https://schd.ws/hosted_files/kccncna17/ad/2017%20CloudNativeCon%20-%20Mod%20gRPC%20Services.pdf

**Comment by MrMage** [comment]
How exactly would such support go further than what we have already? We already have `CallResult`/`ServerStatus` fulfilling similar purposes (except that they have Metadata instead of details), and any RPC service can be declared to return a message of type `Status` if desired.

Also, what do you mean with the issue title?

**Comment by SebastianThiebaud** [comment]
`CallResult statusMessage` doesn't seem to work properly on my end. Investigating the issue, I see `observers.c line 129` that the `server_details` used for `statusMessage` is set to be an empty string. Am I wrong here?

**Comment by MrMage** [comment]
How are you using this? My RPCs return custom status messages and my client code receives those messages just fine. Please check eg `ServerThrowingTests` if I remember correctly for an example.

**Comment by MrMage** [comment]
@SebastianThiebaud do you have any updates on this, or can I close the issue?

**Comment by SebastianThiebaud** [comment]
Sorry for the delay. I've been looking at this and the main issue is that as described in the [design guide](https://cloud.google.com/apis/design/errors), `Status` should contain a `details` attribute with a type `Any`. In `grpc-swift`, `details` or `metadata` is designed to be a hashmap. I think we should revisit that and in the world of Protobuf, we should also have a contract for errors.

**Comment by MrMage** [comment]
Do you have any documentation, examples or proposals on how this is supposed to be done with gRPC? I can't find any `details` field in https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/Status.java, for example.

Also, keep in mind that we would need to transfer those details in a standardized way via the gRPC protocol, and I am not aware of any provisions for that in the protocol (the document you are linking to doesn't seem to describe any).

**Comment by parthmehta209** [comment]
golang: 
example of parsing error to a status.proto object: 
https://github.com/grpc/grpc-go/blob/master/status/status.go#L125

example of details being extracted out of the status: 
https://github.com/grpc/grpc-go/blob/master/status/status.go#L162

Example of details being added to a status object: 
https://github.com/grpc/grpc-go/blob/master/status/status.go#L144

This is how golang decodes the header 'grpc-status-details-bin' into a status.proto object: 
https://github.com/grpc/grpc-go/blob/339b6cb107199486c3b352f70db9e977191be8b7/internal/transport/http_util.go#L316

**Comment by MrMage** [comment]
Thanks for the info! I would be open to offering an optional method to extract such a proto out of a `Metadata` object (probably by reading the `grpc-status-details-bin` key you mentioned and serializing it into a proto), but that should not be mandatory nor happen automatically (i.e. without being explicitly requested by the consumer of SwiftGRPC). If you have any proposals on implementing that, happy to take a look :-)

**Comment by SebastianThiebaud** [comment]
Works for me.

**Comment by parthmehta209** [comment]
Hi @MrMage, @SebastianThiebaud any updates on this. Is there a plan on making the changes that @MrMage described earlier?

**Comment by SebastianThiebaud** [comment]
I believe `grpc-swift` shouldn't handle the extraction and conversion to a Protobuf object but instead return `Any` rather than a hashmap. Can we make this tiny change?

**Comment by MrMage** [comment]
@SebastianThiebaud could you please elaborate what you mean with that?

**Comment by SebastianThiebaud** [comment]
@parthmehta209 @MrMage please review https://github.com/grpc/grpc-swift/pull/331

I know it's not perfect but it gets the work done. I don't think hosting the generated Protobuf code of `Status` is an issue as it should not change anytime soon.

**Comment by seletskiy** [comment]
@SebastianThiebaud can you point out a code example where you manage to retrieve `grpc-status-details-bin` and parse it into error details array?

**Comment by AhmedAskar** [comment]
@MrMage My problem is I receive the error from CallResult and then I got it from the trainlingMetaData which is a representative of GoogleRP details object and then got the details with this key "grpc-status-details-bin" and then I tried to create a new Google RPC status object by initialising it with the that formatted string and then I got a format error
