### ISSUE TITLE
Secure Channel with hostname override fails to connect, "invalid host set"

### ISSUE THREAD

**Issue by aleczadikian** [grpc/grpc-swift#259]
Edit: Forgot to say, this is in version 0.4.2 of grpc-swift, from `pod 'SwiftGRPC', '= 0.4.2'` in my Podfile. Seems to be the same as the current `podspec-update` branch but different from master.

I'm connecting to a server with TLS. The server's address doesn't match the cert's hostname, but the client has an override for this situation: `api = Public_PublicServiceClient(address: address, certificates: cert, host: "localhost")`

This causes the following unhandled exception:
```
callError(successful, status unauthenticated: Invalid host [address] set in :authority metadata.
initialMetadata: 
trailingMetadata: )
```
where `[address]` is the address I set above

Looking in the channel it uses in `Channel.swift`, I thought maybe this setting of `self.host = address` was a mistake, so I made this change, and it seems to work. I'm not familiar with the project and not sure if it's right, so I'm wondering if this is obvious for anyone else here:
```@@ -60,7 +60,11 @@ public class Channel {
   /// - Parameter host: an optional hostname override
   public init(address: String, certificates: String, host: String?) {
     gRPC.initialize()
-    self.host = address
+    if let host = host {
+        self.host = host
+    } else {
+        self.host = address
+    }
     underlyingChannel = cgrpc_channel_create_secure(address, certificates, host)
     completionQueue = CompletionQueue(
       underlyingCompletionQueue: cgrpc_channel_completion_queue(underlyingChannel), name: "Client")
```

Thanks

**Comment by MrMage** [comment]
In https://github.com/grpc/grpc-swift/blob/5e7269a8578627021fa9d3b3b0f4fa391ae49092/Tests/SwiftGRPCTests/BasicEchoTestCase.swift#L69, we simply change `host` explicitly after creating the channel. What surprises me is that we need to _both_ provide `, arguments: [.sslTargetNameOverride("example.com")]` _and_ set `client.host = "example.com"`; I am surprised that both variables need to be changed.

Ideally, one would not need to change _two_ parameters to allow overriding the SSL target name, however it's unclear to me how the effects of these two methods differ. I would not object to adding a `host` argument to the constructor (or you could just manually set it as above), but I would like to understand the implications of that vs. `sslTargetNameOverride` first (or at least document that you probably need to set `sslTargetNameOverride` as well).

**Comment by MrMage** [comment]
Closing this now; please open a new issue if the issue persists in Swift gRPC 0.9.0.
