### ISSUE TITLE
Too coarse callMutex.

### ISSUE THREAD

**Issue by gmilos** [grpc/grpc-swift#26]
[`Call.callMutex`](https://github.com/grpc/grpc-swift/blob/1ac521b87460492da4e2995ebffb3f5717cd5ff0/Sources/gRPC/Call.swift#L137) is global, but while [`grpc_call_start_batch`](https://github.com/grpc/grpc-swift/blob/1ac521b87460492da4e2995ebffb3f5717cd5ff0/Sources/CgRPC/grpc/grpc.h#L218) apparently requires locking, a per-`Call` lock should suffice. Better still, use more idiomatic concurrency strategy.

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
