### ISSUE TITLE
Question: Is this production-ready?

### ISSUE THREAD

**Issue by glerchundi** [grpc/grpc-swift#260]
I would like to know if it's safe to use in a project we're about to start. And, if it's not if you have any plan/roadmap to make it happen.

Our idea is to deploy this one on iOS devices and found several issues related but it seems like people finally achieved it.

Thanks!

**Comment by bootstraponline** [comment]
I'm using grpc-swift for https://github.com/instructure/instructure-ios

The maintainers have been great to work with as we find bugs and add required features for our use case.

**Comment by MrMage** [comment]
Hey, sorry for forgetting to chime in! I am using SwiftGRPC in production with a ~10 QPS service now (both server- and client-side) and haven't experienced any SwiftGRPC-related outages (after spending a lot of time improving the codebase to ensure just that). Basic test coverage is also present by now.

That being said, the API is still in flux and we hope to migrate the library to SwiftNIO at some point, which would require a less "synchronous" programming paradigm.

So, you could use this in your app, but experience a bit of weird behavior now and then (for example, many legitimate connection interruptions (e.g. cellular connection dropping, etc.) might just be exposed to you as an "unknown error"), and be prepared to change your client code from time to time.

**Comment by glerchundi** [comment]
I thought already answered this!

Thanks for your detailed answer, as our product is under active development seems feasible for us, we'll be prepared for time to time changes.
