### ISSUE TITLE
Use of undeclared type 'ServiceProvider'

### ISSUE THREAD

**Issue by Oopsjesse** [grpc/grpc-swift#262]
when I compile a proto file to xxx.grpc.swift and xxx.pb.swift ,then add to my project, the xxx.grpc.swift have a warning :"Use of undeclared type 'ServiceProvider'."
How can I fix it , thanks

**Comment by MrMage** [comment]
You probably compiled the protoc plugin with the source in the `master` branch, but used a tagged release as your project dependency. Please compile the protoc plugin with the same tag (`git checkout v0.4.1`) or switch your dependency to the `master` branch as well.

**Comment by Oopsjesse** [comment]
Now I solved the problem 

--swift_out=$generated_path --swiftgrpc_out=Client=true,Server=false:

I add "Client=true,Server=false:" to fix the warning

But there have a lot of new warnings 

like:
Use of undeclared type 'grpc_call_error'
Use of unresolved identifier 'GRPC_CALL_OK'
Use of unresolved identifier 'GRPC_CALL_ERROR'

these waring are in Core file

thanks to help~

**Comment by MrMage** [comment]
Did you try my suggestion? That should work.

**Comment by Oopsjesse** [comment]
That works  
Thank you!
