### ISSUE TITLE
Build errors with Cocoapods

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc-swift#264]
I am trying to use SwiftGRPC in an iOS project using Cocoapods. I tried to run the [corresponding example](https://github.com/grpc/grpc-swift/tree/master/Examples/Cocoapods/NaturalLanguage), but I get build errors like "Use of undeclared type 'ServiceProvider'", "Missing argument for parameter 'queue' in call" and "Use of unresolved identifier 'HandleMethodError'" in `*.grpc.swift` files.

I am using `protoc` from brew, version "libprotoc 3.5.1", and I built the swift and swiftgrpc protoc plugins from this repo (SwiftProtobuf 1.0.3, protoc-gen-swift 1.0.3).

Am I missing something?

Note: it may be related to #231.

**Comment by MrMage** [comment]
Please see #262.

**Comment by JonasVautherin** [comment]
Do you mean that I should `$ git checkout 0.4.2` for compiling the protoc plugins because the latest published SwiftGRPC on Cocoapods is 0.4.2? Because if I checkout on `0.4.2`, then the `NaturalLanguage` example doesn't have a Podfile anymore (and `$ pod init` fails).

**Comment by JonasVautherin** [comment]
Right, so it is actually not very intuitive.

It builds with the following:

1. Build the protoc plugins (protoc-gen-swift and protoc-gen-swiftgrpc) from the branch `0.4.2` (`$ git checkout 0.4.2` and then `make` from the root).
2. Use those protoc plugins with the NaturalLanguage examples in the master version (so `$ git checkout master` after the protoc plugins have been built).

I guess that those will be synchronized in the future.
