### ISSUE TITLE
Empty Optional when calling receive()

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc-swift#265]
With a version of the protoc swift plugins dating from a few months ago, I used to do things like this:

```Swift
let call = try self.service.subscribeValue(valueRequest, completion: nil)
while let response = try? call.receive() {
    // Do something with response
}
```

Back then, `response` was not an Optional. Now generating the code with `0.4.2`, `response` is an Optional. That's fine for me, but now I also seem to receive at least one empty Optional, and I don't understand why. 

Is it the last response of `call.receive()`? Should I just ignore it?

**Comment by MrMage** [comment]
The last call to receive() in streaming calls always returns an optional now, which indicates that the other party had closed their stream (ie. finished sending). So once you receive that, there will be no more data incoming.

I'm on the go right now, but some of the "streaming" tests should illustrate how this is supposed to be used.

**Comment by JonasVautherin** [comment]
Ok. It confirms what I observed, but it's good to have a confirmation.

Thanks!
