### ISSUE TITLE
FR: Add an official swift-grpc image in Docker Cloud

### ISSUE THREAD

**Issue by sergiocampama** [grpc/grpc-swift#268]
The Docker section of the project only mentions on how to push the docker image into Google cloud. By maintaining an official image in Docker cloud you'd make it easier for developers to start developing with Swift gRPC without having to build their own images.

**Comment by MrMage** [comment]
I would assume that most developers actually develop their code on a macOS machine with Xcode installed. In that case, they'd need to install the macOS versions of protoc and the protoc SwiftGRPC plugins themselves, anyway. Under which circumstances would the SwiftGRPC Docker image be beneficial?

(I do use Docker to deploy my finished SwiftGRPC server binaries, but I have a custom Dockerfile based on the `ibmcom/swift-ubuntu:4.1` image to build those anyway, and I don't think this image would make a difference for them.)

**Comment by sergiocampama** [comment]
I'm writing a tutorial on how to build a Swift gRPC server and found that using Docker to avoid installing local development dependencies was beneficial to reduce the setup time and complexity. For example, I've been generating my Swift protos and grpc bindings on my macOS machine with:

```
docker run -i -t -v $PATH_TO_PROTOS:/working_dir -w /working_dir \
    sergiocampama/swift_grpc
    protoc -I . --swift_out=. --swiftgrpc_out=. \
    my_proto.proto my_other.proto
```
`sergiocampama/swift_grpc` is a Docker image built using this project's Dockerfile (the one I updated in that PR) and uploaded into Docker Cloud under my account. If grpc-swift had an official image, I could point to that instead of my own, which would look less sketchy.

**Comment by MrMage** [comment]
Ah, I see. Personally I would rather install two macOS-native binaries rather than having to download (potentially) several hundred Megabytes of Docker images for the same task, but I understand that encapsulating this is desirable.

I personally don't have any of the permissions to publish such an image, but maybe @timburks could :-)

**Comment by timburks** [comment]
There's a [grpc org on Dockerhub](https://hub.docker.com/r/grpc/). I'll check with them to see what it would take to publish a Swift image there.

**Comment by kevmo314** [comment]
Did anything ever come out of this? I'm currently trying to build grpc-swift on Debian and am running into the same problems that @sergiocampama mentioned, namely:

- grpc-swift doesn't provide binary versions
- Swift doesn't have instructions for how to install on Debian
- Not sure which dependent packages are necessary

So I've spent a few hours today trying to figure out how to just compile the code which could've been saved by a Docker container. If anyone runs into this, here's a Dockerfile:

```
FROM swift:5.3

# Install a few needed packages that aren't in swiftdocker/swift
RUN apt-get -q update && \
    apt-get -q install -y libz-dev unzip curl

# Install protoc
RUN curl -O -L https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip && \
    unzip protoc-3.6.1-linux-x86_64.zip -d /usr

# Build and install the swiftgrpc plugin
WORKDIR /tmp/grpc-build
RUN git clone https://github.com/grpc/grpc-swift && \
    cd grpc-swift && \
    make plugins && \
    cp protoc-gen-swift /usr/bin && \
    cp protoc-gen-grpc-swift /usr/bin

WORKDIR /
RUN rm -r /tmp/grpc-build
```

Build the container with

```
docker build -t local-grpc-swift .
```

Then run with

```
docker run -v .:/workspace -w /workspace local-grpc-swift sh -c "protoc --swift_out=. --grpc-swift_out=. *.proto"
```
