### ISSUE TITLE
Error after updating the client

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc-swift#269]
I updated my client to SwiftGRPC 0.4.2, and I receive error messages when contacting the server ever since. The error prints:

```
callError(successful, status unimplemented:
initialMetadata:
trailingMetadata: )
```

Could that be because the server version is too old? If yes, are the clients always supposed to wait for the server before updating, or is there no backward compatibility at all (meaning that the clients must use a version matching the server)?

And how should I understand the message? What does the `successful` mean here?

**Comment by MrMage** [comment]
Unlikely that it's related to a version mismatch as that shouldn't affect th GRPC wire protocol. What method are you trying to call, did you maybe change your service spec? I'm also surprised that the status does not contain any status message, just the "unimplemented" code.

The `successful` flag only indicates whether the operation group was successfully processed by gRPC; it's not very meaningful in general.

**Comment by JonasVautherin** [comment]
Right, thanks for the info. Then I may have broken something on my side when I made the update...

I'll look into that!

**Comment by JonasVautherin** [comment]
Ok, that was on my side. Some caching-induced error (i.e. some changes were not reflected on the server side).

Thanks for the help!

**Comment by MrMage** [comment]
Glad to hear that you figured it out! Out of curiosity, may I ask what your server stack lookse?

**Comment by JonasVautherin** [comment]
Of course!

So actually it is for a drone project. The clients send commands to the drone and receive results/streams. The goal is to have the swift (client) / c++ (server) code autogenerated ([that's work in progress](https://github.com/dronecore/dronecore-proto/tree/grpc_plugins_parse_return_params)), but right now there are some manually-written features, e.g. [here](https://github.com/Dronecode/DronecodeSDK/blob/develop/backend/src/plugins/camera/camera_service_impl.h). The full server implementation is [here](https://github.com/Dronecode/DronecodeSDK/tree/develop/backend) (we call it "backend").
