### ISSUE TITLE
O(n^2) message queue

### ISSUE THREAD

**Issue by gmilos** [grpc/grpc-swift#27]
[Message queue uses `removeFirst()`](https://github.com/grpc/grpc-swift/blob/1ac521b87460492da4e2995ebffb3f5717cd5ff0/Sources/gRPC/Call.swift#L265), which is O(n), making the entire process O(n^2). Needs to be simplified to O(n). Also, `removeFirst()` returns the element, no need to read it off first.

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
