### ISSUE TITLE
Static Pod Library support

### ISSUE THREAD

**Issue by anjmao** [grpc/grpc-swift#270]
Hi, as CocoaPods 1.5.0 supports Static Libraries I'm trying to install SwiftGRPC as a static library, but when I check Pods folder I see all source files and there is no static libraries. My Podfile

```ruby
platform :ios, '8.0'

target 'app' do
  use_modular_headers!

  # Pods for app
  pod 'SwiftGRPC'

  target 'mpostTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

When I run `pod install` I get this response
```
Analyzing dependencies
Downloading dependencies
Using BoringSSL (10.0.5)
Using SwiftGRPC (0.4.3)
Using SwiftProtobuf (1.0.3)
Using gRPC-Core (1.11.0)
Using nanopb (0.3.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 5 total pods installed.
```

Have anyone managed to install SwiftGRPC as static library? Thanks.

**Comment by MrMage** [comment]
CocoaPods' static library support refers only to how the library is _compiled and linked_, not how it is _distributed_. SwiftGRPC is always distributed in source code form, so you'll need to compile it yourself. So if you have set up everything correctly, your Xcode would compile the SwiftGRPC source code from scratch into a static library and link your binary with that. Please check if that is the case for you.

**Comment by MrMage** [comment]
Closing this; please let me know if there are any open questions.
