### ISSUE TITLE
Stream closes prematurely 

### ISSUE THREAD

**Issue by alqa-dash** [grpc/grpc-swift#271]
Hello!

I got ios grpc-client which have to upload file onto the server. Proto excerpt below:

`
service UploadData {
    rpc Upload(stream UploadDataRequest) returns (Status);
}
`

protoc generetes swift code and I can send file to the server correctly. But If I don't call closeAndReceive server is unable to store file because it waits for something. If I run closeAndReceive just after send method, I got RST_STREAM from client prematurely and server doesn't receive data. If I set some timeout (sleep of DispatchQueue.*.asyncAfter) for 2-3 seconds, stream closes correctly and server accepts file. 

Could anybody help me to understand how should I catch end of transmission and close stream properly?

Below is my sample code:

`

        DispatchQueue.global(qos: DispatchQoS.QoSClass.background).async {

            repeat {
                let thisChunkSize = ((length - offset) > chunkSize) ? chunkSize : (length - offset)
                let chunk = data.subdata(in: offset..<offset + thisChunkSize )
                uploadDataRequest.data = chunk

                _ = try? self.call?.send(uploadDataRequest, errorHandler: { (error) in
                    print("upload error:", error.localizedDescription)
                })

                offset += thisChunkSize
            } while (offset < length)

            if offset >= length {
                print("offset = ", offset, "length = ", length)
                DispatchQueue.global(qos: DispatchQoS.QoSClass.background).asyncAfter(deadline: .now() + 2) {
                    _ = try? self.call?.closeAndReceive(completion: { (status, clientError) in
                        if let status = status {
                            print("status: ", status)
                        }
                        if let clientError = clientError {
                            print("clietn error: ", clientError)
                        }
                    })
                }
            }
        }
`

**Comment by MrMage** [comment]
You'll need to call `call.waitForSendOperationsToFinish()` before closing the stream. Please see https://github.com/grpc/grpc-swift/blob/d6ae4637c7ae2f961d38399d29e658927bb8fb98/Tests/SwiftGRPCTests/EchoTests.swift#L75 for an example use case.

**Comment by alqa-dash** [comment]
Thanks for your reply!

Yes, I guess that this function should help me but I can't call it from my client code - it is inaccessible. How can I make visible to my code?

**Comment by MrMage** [comment]
Try adding `import SwiftGRPC` to your code if you haven't already.

**Comment by alqa-dash** [comment]
I did of course. 
I generate *pb.swift and *client.pb.swift files by protoc (version 3.5.1) and add to the project as long as SwiftGRPC sources. But the call object has no reference to waitForSendOperationsToFinish function. In my case call object is overridden by custom call object with limited number of properties (may be some protocol is absent?)

**Comment by MrMage** [comment]
What type does `self.call` have and how do you instantiate it?
What's the call object's superclass and what protocols does it implement?
What properties _are_ present on that object?
Which version of the library and the `protoc` plugin are you using?

**Comment by alqa-dash** [comment]
call is type of Interviewkit_UploadData2UnderwritingUpload2UnderwritingCall

This object was generated as follows:

`
internal class Interviewkit_UploadData2UnderwritingUpload2UnderwritingCall {
  private var call : Call
..
`

guard let call = try! service?.upload2underwriting(completion: { (result) in ...)

I can see only 3 available functions for call object: closeAndreceive blocking and non-blocking, and send. All of these come from custom Interviewkit_UploadData2UnderwritingUpload2UnderwritingCall class.

protoc library version is 3.5.1

**Comment by alqa-dash** [comment]
I can share my proto file if you need one. I generate *swift files as follows:
protoc --swift_out=. --swiftgrpc_out=. my.proto

**Comment by MrMage** [comment]
Sorry, I need to know which version of the SwiftGRPC protoc plugin you are using, not the protoc compiler itself. It looks like both your library and client code are very outdated. The latest version of the protoc plugin should generate call code like this:

`internal protocol Timing_SyncUploadOperationLogCall: ClientCallClientStreaming {`

**Comment by alqa-dash** [comment]
How can I check version of this plugin?

**Comment by MrMage** [comment]
Depends on how you built it and how you are including `SwiftGRPC` as a dependency?

Running `git describe --tags` in your SwiftGRPC directory might help.

**Comment by alqa-dash** [comment]
I get SwiftGRPC from git and the command above returns the following:

`
pwd
/Projects/grpc-swift
$ git describe --tags
0.5.0-6-gd9bea65
`

**Comment by MrMage** [comment]
Hmm, that looks like the current version. Could you please upload your entire `.grpc.swift` file (e.g. as a GitHub gist so I can take a look?

Also, when and how did you build and install the SwiftGRPC protoc plugin?

**Comment by alqa-dash** [comment]
I've download SwiftGRPC sources to my project last week. I upload my swift files in a minute. 
Can you tell my how do you generate swift files (may be there is some env setting or so)?

**Comment by alqa-dash** [comment]
https://gist.github.com/alqa-dash/0ae3ccfc221ea97256da40a03cdddcf2 - here you can find swift files.

**Comment by MrMage** [comment]
Those files are generated with a completely outdated version of the SwiftGRPC protoc plugin. The new version even generates `.grpc.swift` files, not `.pb.swift`. I am very surprised that this compiles at all!

You must have an old version of the SwiftGRPC protoc plugin. Please build it from scratch and install it (don't forget to move the new `protoc-gen-swift` to your `PATH`!) via the instructions at https://github.com/grpc/grpc-swift#usage.

**Comment by alqa-dash** [comment]
Aha, I remember that I was unable to compile whole SwiftGRPC project due to errors while building CgRPC. And this not only my problem - many people complains on the same issue. Do you know how to successfully compile SwiftGRPC project?

**Comment by MrMage** [comment]
It should compile with the current source. What error messages are you getting if you follow the instructions in the Readme?

**Comment by alqa-dash** [comment]
Finally I succeed with compile and new swift files generation! Now I see that I really used pretty old version... Thank you very much!

Current approach to create call and stream slightly differs from that one I've been using?

**Comment by MrMage** [comment]
See the tests for a current example.

**Comment by alqa-dash** [comment]
Thanks a lot! Everything is working now as it should be! 

Just in the case: where could I find description of output format of swift files? I was sure that I used current version on plugin :)

**Comment by MrMage** [comment]
The easiest would be to compare with what https://github.com/grpc/grpc-swift/blob/master/Sources/Examples/Echo/Generated/echo.grpc.swift looks like. Normally you should get a compiler error if the library and generated code mismatch, anyways.

If this has been resolved, please make sure to close this issue when appropriate :-)
