### ISSUE TITLE
Can't install on Mac OS High Sierra 10.13.5

### ISSUE THREAD

**Issue by mandelmonkey** [grpc/grpc-swift#275]
Hi I simply clone the repo cd and run make, however I get the following error,
any ideas?

```
Compile Swift Module 'SwiftProtobufPluginLibrary' (19 sources)
Compile Swift Module 'SwiftGRPC' (32 sources)
Compile Swift Module 'Simple' (1 sources)
Compile Swift Module 'Echo' (4 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/Simple
Undefined symbols for architecture x86_64:
  "_CRYPTO_free", referenced from:
      __ZL35peer_property_from_x509_common_nameP7x509_stP17tsi_peer_property in ssl_transport_security.cc.o
      __ZL40add_subject_alt_names_properties_to_peerP8tsi_peerP21stack_st_GENERAL_NAMEm in ssl_transport_security.cc.o
     (maybe you meant: _CRYPTO_free_ex_data)
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      __ZL12init_opensslv in ssl_transport_security.cc.o
  "_SSL_CTX_callback_ctrl", referenced from:
```

**Comment by MrMage** [comment]
That indicates that you are linking with the wrong version of OpenSSL. Could you please provide the exact commands you ran? And do you maybe have extra copies of OpenSSL installed on your system?

**Comment by mandelmonkey** [comment]
thanks

I ran

`git clone https://github.com/grpc/grpc-swift.git cd grpc-swift; make`

and I checked ssl version by

```
$ openssl version
OpenSSL 1.0.2o  27 Mar 2018
```

**Comment by MrMage** [comment]
How did you install `openssl` in the first place? What does `which openssl` return?

**Comment by mandelmonkey** [comment]
```
$ which openssl
/opt/local/bin/openssl
```

Im not sure, I have xcode command line tools installed and have run brew install openssl in the past

**Comment by MrMage** [comment]
Could you try uninstalling your brew copy of OpenSSL and see if it works then?

**Comment by mandelmonkey** [comment]
yes I tried that and no changes, I noticed that which openssl showed /opt/local/bin/openssl
but mac also has open ssl in /usr/bin/openssl so I removed the former and openssl version shows
```
openssl version
LibreSSL 2.2.7
```

so seems mac uses libressl not open ssl, but still no luck

what version should openssl be?

**Comment by MrMage** [comment]
The problem will actually not be the `openssl` binary, but Xcode linking with the wrong version of `OpenSSL`. Normally, the BoringSSL version that we ship with the library should get linked, but it seems like a version installed in your OS gets linked instead. What is the invocation causing an error when running `swift build -v -Xcc -ISources/BoringSSL/include -Xlinker -lz`?

**Comment by mandelmonkey** [comment]
heres the last of the logs, let me know if you need more

`/x86_64-apple-macosx10.10/debug/SwiftProtobuf.build/type.pb.swift.o /Users/a/grpc-swift/.build/x86_64-apple-macosx10.10/debug/SwiftProtobuf.build/wrappers.pb.swift.o -Xlinker -lz -Xcc -ISources/BoringSSL/include
Undefined symbols for architecture x86_64:
  "_CRYPTO_free", referenced from:
      __ZL35peer_property_from_x509_common_nameP7x509_stP17tsi_peer_property in ssl_transport_security.cc.o
      __ZL40add_subject_alt_names_properties_to_peerP8tsi_peerP21stack_st_GENERAL_NAMEm in ssl_transport_security.cc.o
     (maybe you meant: _CRYPTO_free_ex_data)
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      __ZL12init_opensslv in ssl_transport_security.cc.o
  "_SSL_CTX_callback_ctrl", referenced from:
      __Z53tsi_create_ssl_server_handshaker_factory_with_optionsPK33tsi_ssl_server_handshaker_optionsPP33tsi_ssl_server_handshaker_factory in ssl_transport_security.cc.o
  "_SSL_CTX_ctrl", referenced from:
      __Z53tsi_create_ssl_client_handshaker_factory_with_optionsPK33tsi_ssl_client_handshaker_optionsPP33tsi_ssl_client_handshaker_factory in ssl_transport_security.cc.o
      __ZL20populate_ssl_contextP10ssl_ctx_stPK25tsi_ssl_pem_key_cert_pairPKc in ssl_transport_security.cc.o
      __Z53tsi_create_ssl_server_handshaker_factory_with_optionsPK33tsi_ssl_server_handshaker_optionsPP33tsi_ssl_server_handshaker_factory in ssl_transport_security.cc.o
      __ZL29ssl_ctx_use_certificate_chainP10ssl_ctx_stPKcm in ssl_transport_security.cc.o
  "_SSL_ctrl", referenced from:
      __ZL25create_tsi_ssl_handshakerP10ssl_ctx_stiPKcP26tsi_ssl_handshaker_factoryPP14tsi_handshaker in ssl_transport_security.cc.o
      __ZL27ssl_handshaker_extract_peerP14tsi_handshakerP8tsi_peer in ssl_transport_security.cc.o
ld: symbol(s) not found for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:
  "_CRYPTO_free", referenced from:
      __ZL35peer_property_from_x509_common_nameP7x509_stP17tsi_peer_property in ssl_transport_security.cc.o
      __ZL40add_subject_alt_names_properties_to_peerP8tsi_peerP21stack_st_GENERAL_NAMEm in ssl_transport_security.cc.o
     (maybe you meant: _CRYPTO_free_ex_data)
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      __ZL12init_opensslv in ssl_transport_security.cc.o
  "_SSL_CTX_callback_ctrl", referenced from:
      __Z53tsi_create_ssl_server_handshaker_factory_with_optionsPK33tsi_ssl_server_handshaker_optionsPP33tsi_ssl_server_handshaker_factory in ssl_transport_security.cc.o
  "_SSL_CTX_ctrl", referenced from:
      __Z53tsi_create_ssl_client_handshaker_factory_with_optionsPK33tsi_ssl_client_handshaker_optionsPP33tsi_ssl_client_handshaker_factory in ssl_transport_security.cc.o
      __ZL20populate_ssl_contextP10ssl_ctx_stPK25tsi_ssl_pem_key_cert_pairPKc in ssl_transport_security.cc.o
      __Z53tsi_create_ssl_server_handshaker_factory_with_optionsPK33tsi_ssl_server_handshaker_optionsPP33tsi_ssl_server_handshaker_factory in ssl_transport_security.cc.o
      __ZL29ssl_ctx_use_certificate_chainP10ssl_ctx_stPKcm in ssl_transport_security.cc.o
  "_SSL_ctrl", referenced from:
      __ZL25create_tsi_ssl_handshakerP10ssl_ctx_stiPKcP26tsi_ssl_handshaker_factoryPP14tsi_handshaker in ssl_transport_security.cc.o
      __ZL27ssl_handshaker_extract_peerP14tsi_handshakerP8tsi_peer in ssl_transport_security.cc.o
ld: symbol(s) not found for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/a/grpc-swift/.build/debug.yaml main -v output:
    
`

**Comment by mandelmonkey** [comment]
ah sorry the logs were a lot so heres a txt file
[logs.txt](https://github.com/grpc/grpc-swift/files/2223192/logs.txt)

**Comment by MrMage** [comment]
Hmm, not sure what's wrong. What's happening if you run `make project`, and then try to build the Xcode project instead with one of the binary targets?

**Comment by mandelmonkey** [comment]
like this? 
```
make project
swift package -Xcc -ISources/BoringSSL/include -Xlinker -lz generate-xcodeproj
generated: ./SwiftGRPC.xcodeproj
```

maybe its an xcode issue? I can try and reinstall xcode

**Comment by MrMage** [comment]
Yes, and then double-click Xcode and try to build the individual targets...

**Comment by mandelmonkey** [comment]
xcode project builds fine

**Comment by MrMage** [comment]
Could you just use Xcode for the time being then?

**Comment by mandelmonkey** [comment]
thanks :-)
for the time being I got a coworker to generate the protocs I needed for my project
but can I use xcode tp generate them? basically im trying to generate protocs rpc.pb.swift and rpc.grpc.swift and need the binaries protoc-gen-swift and protoc-gen-swiftgrpc

so in order to get protoc-gen-swiftgrpc I need to make the grpc-swift repo

**Comment by mandelmonkey** [comment]
also is it likely to be a mac os version issue?

**Comment by MrMage** [comment]
I'm fairly certain it's an issue with your specific system and whatever libraries you have installed. If you only need the `protoc` plugin, simply run `test-plugin`; it shouldn't need OpenSSL.

**Comment by mandelmonkey** [comment]
thanks that generated them in debug/, is there a way / or a need to generate a release/ build

**Comment by MrMage** [comment]
Yes, but I'm sure you can figure that out yourself.

**Comment by mandelmonkey** [comment]
thanks will give it ago, if I figure out whats wrong in my system ill let you know

**Comment by mandelmonkey** [comment]
I manged to build finally something to do with brew open ssl and macports open ssl, maybe because my macbook was a timemachine backup from an old macbook with old macports version and open ssl, deleting macports and openssl from brew then installing from macports worked, my openssl version is showing OpenSSL 1.0.2q  20 Nov 2018 now
