### ISSUE TITLE
Implement special_status_message interop test

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-swift#276]
https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#special_status_message

This was added in grpc/grpc#16129

-----

I don't actually know what the status of the interop tests are for swift, but it seemed like it was pretty close, thus this notification a new test has been added.

**Comment by MrMage** [comment]
To be honest, I did not even know of the existence of this comprehensive test spec. Thanks for pointing that out, it gives us a good "target" to shoot for!

**Comment by MrMage** [comment]
Interop tests will only be supported in the NIO branch; @glbrntt do you happen to know if we have implemented that particular test?

**Comment by glbrntt** [comment]
We have implemented it.
