### ISSUE TITLE
There is no 0.5.0 version in Cocoapods' specs

### ISSUE THREAD

**Issue by slavabulgakov** [grpc/grpc-swift#279]
Could you add it?

**Comment by anjmao** [comment]
Hi, any news on this issue?

**Comment by anjmao** [comment]
@slavabulgakov I found a simple way by just forking this repo and making pod to pull from it. In your pod file

```
pod 'SwiftGRPC', :git => 'https://github.com/<yourname>/grpc-swift'
```

**Comment by MrMage** [comment]
I think you can even just use the URL `https://github.com/grpc/grpc-swift` directly; the only thing that's missing is to update the official CocoaPods repo with the new podspec.

**Comment by rebello95** [comment]
I went ahead and pushed 0.5.0 to the CocoaPods repo to help unblock / have parity with GitHub. There's a new warning when running the CocoaPods linter on 0.5.0 that we should probably address in the next release, though:
```
- WARN  | xcodebuild:  SwiftGRPC/Sources/CgRPC/shim/cgrpc.h:202:63: warning: this function declaration is not a prototype [-Wstrict-prototypes]
```

**Comment by MrMage** [comment]
Yes, that one should be addressed (I fixed a ton of those in the past, but I guess a new method was introduced).

Could you document the process of pushing to the CocoaPods repo here for future releases?

**Comment by rebello95** [comment]
Yep, basically run the linter and then push the new spec:
```
$ pod spec lint SwiftGRPC.podspec
$ pod trunk push SwiftGRPC.podspec
```

Note that you'll need to be a contributor for this spec in CocoaPods (@timburks can add you @MrMage).

Ideally we should be pushing the new spec to CocoaPods as soon as we cut a new release tag on GitHub.

**Comment by rebello95** [comment]
For sure! Added to ReadMe: https://github.com/grpc/grpc-swift/pull/286

**Comment by timburks** [comment]
Thanks @rebello95 ! I've added @MrMage to the pod owners.

**Comment by rebello95** [comment]
Awesome! FYI the new warning is fixed by https://github.com/grpc/grpc-swift/issues/294
