### ISSUE TITLE
Missing CFBundleVersion keys cause App Store submission errors

### ISSUE THREAD

**Issue by basalphenaar** [grpc/grpc-swift#291]
First of all, I want to thank @JonasVautherin again for adding Carthage support, it really simplified and cleaned up my project! Unfortunately the built Carthage frameworks introduce an issue with submission to the App Store:

![submissionerrors](https://user-images.githubusercontent.com/312220/44201127-c59e4000-a148-11e8-808a-313028a8472f.png)

I've solved it for now by manually editing the `Info.plist` files within the built Carthage frameworks, but I guess this is not really a long-term solution. I see that the `*.plist` files in `SwiftGRPC-Carthage.xcodeproj` have `$(CURRENT_PROJECT_VERSION)` set for `CFBundleVersion`, but this doesn't seem to work for the Carthage build.

**Comment by MrMage** [comment]
I guess we could set the `CURRENT_PROJECT_VERSION` in the same way other properties are being overridden already as well. @JonasVautherin, what do you think?

(I'm in the process of preparing a PR for this.)

**Comment by MrMage** [comment]
Created #292, would appreciate your feedback.

**Comment by JonasVautherin** [comment]
Building and running for me!
