### ISSUE TITLE
Using SwiftGRPC from the Swift REPL

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc-swift#301]
I can't seem to import SwiftGRPC into the REPL.

Here is how I thought I should proceed:

1. Run `$ swift build` to build the modules.
2. Run `$ swift -I .build/x86_64-apple-macosx10.10/debug/` to start the REPL.
3. Import the SwiftGRPC modules.

Running `$ swift build` gives me the exact same error as #275. But `$ swift build -Xcc -ISources/BoringSSL/include -Xlinker -lz` works, so I guess that I need to specify the OpenSSL lib I want to use otherwise it gets the system one.

Then, when I `import SwiftGRPC` from the REPL, I get the following error:

```
1> import SwiftGRPC
error: repl.swift:1:8: error: missing required module 'CgRPC'
import SwiftGRPC
       ^
```

Which is normal. But when I try to `import CgRPC`, it says:

```
1> import CgRPC
error: repl.swift:1:8: error: no such module 'CgRPC'
import CgRPC
       ^
```

Again, I am not surprised, because CgRPC is not a `.swiftmodule`. But still, it is required by SwiftGRPC. Is there a way to import it into the REPL?

**Comment by MrMage** [comment]
Unfortunately I have no experience with the Swift REPL. Maybe it would make sense to ask this question on the Swift forums, in case someone else had similar problems with other C libraries?

**Comment by JonasVautherin** [comment]
I think I got it: by running the REPL with the following command, I can then `import SwiftGRPC`. That's not enough for me to run my example, but I believe it solves this question.

```
swift -I Sources/CgRPC/include/ -L .build/x86_64-apple-macosx10.10/debug/CgRPC.build/ -I .build/x86_64-apple-macosx10.10/debug/
```
