### ISSUE TITLE
Type 'Foo' does not conform to protocol '_MessageImplementationBase'

### ISSUE THREAD

**Issue by AaronTriplett** [grpc/grpc-swift#302]
Extensions for each message type in my generated pb.swift files do not conform to the _MessageImplementationBase protocol. Looks like they are missing the _protobuf_generated_isEqualTo function.

<img width="869" alt="screen shot 2018-08-31 at 11 52 20 pm" src="https://user-images.githubusercontent.com/31156329/44943350-e1752900-ad79-11e8-9398-e9d9cca23156.png">

I am generating these outside of my project using the following:
protoc 3.5.1
protoc-gen-swift 1.1.1
protoc-gen-swiftgrpc master

**Comment by AaronTriplett** [comment]
Looking into the implementation details a bit more, it looks like this is likely an upstream issue with swift-protobuf. If anyone has any helpful information that would be great, but feel free to close out if this is indeed irrelevant.

**Comment by MrMage** [comment]
Thanks for the heads-up! Given that this is a breaking change, we should indeed cut a new release. I've created #303 now. Once that has been approved by @timburks, I can merge it and update the CocoaPods repo.

**Comment by AaronTriplett** [comment]
Great 👍

**Comment by MrMage** [comment]
I have pushed 0.6.0 to CocoaPods now; please let me know if the issue occurs again.
