### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED with CA signed certificate

### ISSUE THREAD

**Issue by mushtaque87** [grpc/grpc-swift#304]
```
let certPath = Bundle.main.url(forResource: "go_daddy", withExtension: "pem")!
       let certificate = try! String(contentsOf: certPath)
       service = Pronounce_PronounceServiceClient(address: Constants.ServerApi.grpcBaseUrl, certificates: certificate)
```

When i try the above code with self signed certificate in my ios(swift) client app it works fine , but when i try with go_daddy CA Signed certificate it gives an error. 

```
ssl_transport_security.cc:1064] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```

Can anyone help me with what needs to be changed on swift client side .. Do I need to add some channel parameters ?

The tester is trying with Java Client and it works for him with these lines of code. 

```
channel = NettyChannelBuilder.forAddress(host, port).negotiationType(NegotiationType.TLS)
                    .sslContext(GrpcSslContexts.forClient()
                            .sslProvider(SslProvider.OPENSSL)
                            .clientAuth(ClientAuth.REQUIRE)
                            .trustManager(new File("src/main/resources/cert/go_daddy.pem"))
                            .build())
                    .build();
```

How to make secure channel in swift . A two lines of code would be helpful.
I tried this also 

```
service = Pronounce_PronounceServiceClient(address: Constants.ServerApi.grpcBaseUrl, certificates: certificate, clientCertificates: nil, clientKey: nil, arguments: [])
 service?.host = "api.ainfinity.ai"
 ```

**Comment by mushtaque87** [comment]
On debuging I think i am getting SSL_ERROR_SSL .. and sometimes -1 for ssl_result in this line in ssl_transport_security.cc \

int ssl_result = SSL_do_handshake(impl->ssl);

**Comment by MrMage** [comment]
Could you please try including your entire certificate chain (including e.g. the root certificate) in what you pass to SwiftGRPC? Also, try enabling debug logging. See e.g. https://github.com/grpc/grpc-swift/issues/285#issuecomment-412534895.

**Comment by mushtaque87** [comment]
This is something printing in the terminal 

2018-09-03 13:52:24.271757+0400 Pronounce[81494:2386634] XPC connection interrupted
D0903 13:52:24.275788000 4501078848 ev_posix.cc:142]                   Using polling engine: poll
D0903 13:52:24.278303000 4501078848 dns_resolver.cc:339]               Using native dns resolver
2018-09-03 13:52:36.317825+0400 Pronounce[81494:2385944] 317:  ca_debug_string: inPropertyData == NULL
D0903 13:52:40.715578000 4501078848 dns_resolver.cc:280]               Start resolving.
I0903 13:52:44.200520000 123145478537216 subchannel.cc:608]            New connected subchannel at 0x60000063a360 for subchannel 0x7fc8ec797410
D0903 13:52:44.202156000 123145478537216 writing.cc:143]               ipv4:52.221.96.241:8443:0x7fc8ed1b7400 stream 1 stalled by transport [fc:pending=0:pending-compressed=14309:flowed=0:peer_initwin=65535:t_win=0:s_win=0:s_delta=-65535]
D0903 13:52:44.284682000 123145478537216 dns_resolver.cc:280]          Start resolving.
Response : nil
GRPC StatusMessage : Optional("Trying to connect an http1.x server")

**Comment by mushtaque87** [comment]
Yes I tried with root.pem certificate( if thats why you are asking me to do). Same error .. Can you please tell what could be the reason for TSI_PROTOCOL_FAILURE . What type of failure is it about.

**Comment by MrMage** [comment]
No idea; did you try Googling this? Also, did you try adding `, arguments: [.sslTargetNameOverride("api.ainfinity.ai")]`? What if you simply use `secure: true` instead of passing any certificates in?

**Comment by MrMage** [comment]
@mushtaque87 did you figure out what the issue was here?

**Comment by dvaldivia** [comment]
@MrMage is there a way to skip the certificate validation so I can work with self signed certs? similar to InsecureSkipVerify in grpc-go ?

**Comment by MrMage** [comment]
> @MrMage is there a way to skip the certificate validation so I can work with self signed certs? similar to InsecureSkipVerify in grpc-go ?

I don't think this is the right thread to ask such a question.

Skipping the certificate verification process is currently not exposed. However, you should be able to pass in your self-signed certificates to the `ServiceClient` constructor, but I can't walk you through that process.

**Comment by MrMage** [comment]
Closing this now; please open a new issue if the issue persists in Swift gRPC 0.9.0.
