### ISSUE TITLE
No truly asynchronous APIs in generated code

### ISSUE THREAD

**Issue by gmilos** [grpc/grpc-swift#31]
In autogenerated code, no asynchronous API available for Receive(), CloseSend(), but Send is. The [following comment] seems inaccurate: https://github.com/grpc/grpc-swift/blob/master/Examples/Echo/Generated/echo.client.pb.swift#L297.

**Comment by timburks** [comment]
Nonblocking APIs were added in [this commit](https://github.com/grpc/grpc-swift/commit/b450ad32d9c04fdf7faf05e3bd4b871051803637).
