### ISSUE TITLE
Watchos Support

### ISSUE THREAD

**Issue by zoecarver** [grpc/grpc-swift#312]
### Question Checklist

- [X] Updated grpc-swift to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [X] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

Watchos Support.
#### Question Description

It would be really nice to have support for watchos. I am working on a project that requires grpc and this seems like the best library however I cannot use it because it does not support watchos. 

Thanks.

**Comment by MrMage** [comment]
Thank you for the request. What issues are you encountering when trying to use the library on watchOS?

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
