### ISSUE TITLE
How do you guys deal with Provider needing to make a async call before responding to client

### ISSUE THREAD

**Issue by idi888** [grpc/grpc-swift#313]
All the generated code for the Provider is only synchronised code, How do you deal if your server needs to make an API call before responding ?

Is using Semaphores the only way ?

**Comment by MrMage** [comment]
I am afraid the current approach would indeed to block the request handler thread until your asynchronous API call has finished. This will be much improved once we add a variant of the library that uses SwiftNIO; see [here](https://github.com/grpc/grpc-swift/pull/281) for the corresponding pull request.

**Comment by idi888** [comment]
Thanks I thought so, Just wanted to check if I was missing something
