### ISSUE TITLE
Client Certificates

### ISSUE THREAD

**Issue by sgammon** [grpc/grpc-swift#315]
### Question Subject
I'm wondering how to use client certificates with Swift gRPC. I tried to dig into CgRPC, and I can see where certain calls are used to create "secure" channels, but this seems to reference server-side TLS, not mutual TLS. I also can't find docs for CgRPC or I'd be happy to contribute a PR.

If someone knows the answer or could point me in the right direction, I'd be happy to code one up :)

#### Question Description
See above.

### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

**Comment by sgammon** [comment]
Found it ;) https://github.com/grpc/grpc-swift/blob/b2084686f01625f581d19773cc508b8040375ad6/Sources/SwiftGRPC/Core/Channel.swift#L82

**Comment by anuranBarman** [comment]
@sgammon  how can I use self signed certificate by openssl with this? I am getting certificate validation failed error for self signed certificate. Can you help here ? #536
