### ISSUE TITLE
protoc-gen-swiftgrpc: program not found or is not executable

### ISSUE THREAD

**Issue by zhaxylykbayev** [grpc/grpc-swift#322]
HI!
I made everything as in readme.md, but when i run protoc --swiftgrpc_out=. <my proto file> getting this message:
protoc-gen-swiftgrpc: program not found or is not executable
--swiftgrpc_out: protoc-gen-swiftgrpc: Plugin failed with status code 1.
I have already put protoc-gen-swift into my folder with proto file, added this directory to PATH with no result.

Also, Do I have to get 2 files? Because i'm getting only 1 pb.swift file
Additionally, i've checked this example https://github.com/JacopoMangiavacchi/PokemonBot of @JacopoMangiavacchi and he have second file pokemon.grpc.swift which is generated by the protocol buffer compiler. So, i'm assuming that command  protoc --swiftgrpc_out=. <my proto file> should generate this file. 
Please, help. I'm new in grpc and protocol buffers

PS: libprotoc 3.6.1, see attached screen of my proto file
<img width="619" alt="2018-10-21 2 13 28" src="https://user-images.githubusercontent.com/18225576/47260174-ce5c1b00-d4d7-11e8-8e66-5ac3a5337fc5.png">

**Comment by MrMage** [comment]
Hi, thanks for your message! You should indeed get two files and no error message.

Could you double-check that the swiftgrpc protoc plugin is executable and check your PATH with eg `echo $PATH`? You might need to open a new she'll for the path change to take effect.

**Comment by zhaxylykbayev** [comment]
@MrMage Hi! Thank you for reply!
Where I need put my proto file and execute commands? I mean in which folder?
Previously I made it in new folder. How my PATH should look like?

**Comment by MrMage** [comment]
What does it look like now? Did you try putting the SwiftGRPC protoc plugin into the same folder as your SwiftProtobuf plugin, if that one works?

**Comment by zhaxylykbayev** [comment]
Path looks like :
/Users/zhaxylykbayev/projects/grpc2/generated:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

where /Users/zhaxylykbayev/projects/grpc2/generated is my folder with proto
file


Also,screenshot of myfolder's content is in attached files.



пн, 22 окт. 2018 г. в 15:53, Daniel Alm <notifications@github.com>:

**Comment by MrMage** [comment]
I don't see an attachment. What do `echo $PATH` and `ls -la /Users/zhaxylykbayev/projects/grpc2/generated` output in a Terminal window? Please paste the results in three \`backticks\` for better readability.

**Comment by MrMage** [comment]
Doesn't look like there's a protoc-gen-swiftgrpc in that folder?

**Comment by zhaxylykbayev** [comment]
Where I can find it?

**Comment by MrMage** [comment]
Please read this project's Readme again.

**Comment by zhaxylykbayev** [comment]
In usage part it's written: 
> Binary releases of protoc, the Protocol Buffer Compiler, are available on GitHub.

Here [https://github.com/protocolbuffers/protobuf/releases](url) i can't find swift, what language do you recommend to use? Im using mac OS

**Comment by MrMage** [comment]
Read the SwiftGRPC Readme. It tells you how to install the SwiftGRPC plugin manually.

**Comment by zhaxylykbayev** [comment]
I've solved this problem. Thank you! 
However, i have a question. How to add basic authorization token?

**Comment by timburks** [comment]
@zhaxylykbayev Anything that you would pass in HTTP headers (like authorization tokens) is sent as "metadata" in gRPC. [This example](https://github.com/grpc/grpc-swift/blob/ac1939e98bce1717bea6dea890d24ca4d335d7eb/Examples/Google/NaturalLanguage/Sources/main.swift#L36) sets the metadata needed to pass bearer tokens; I haven't tried using basic auth to authenticate with any gRPC server, but expect that the code for sending the token would be similar. 

I hope this helps! If you have further questions, please open a dedicated issue!

**Comment by zhaxylykbayev** [comment]
I have already solved this

сб, 23 февр. 2019 г., 3:11 Tim Burks <notifications@github.com>:

**Comment by ajayz7** [comment]
@zhaxylykbayev @MrMage  Can you help me creating a grpc.swift file. I am facing issue in genrating file.
[dispatcher.proto.zip](https://github.com/grpc/grpc-swift/files/4677455/dispatcher.proto.zip)

**Comment by kamalWam** [comment]
As it says here:

https://github.com/grpc/grpc-swift


0.x gRPC C library  cgrpc protoc-gen-swiftgrpc  No longer developed; security fixes only


So to get that, do this:

$ git clone https://github.com/grpc/grpc-swift.git
$ cd grpc-swift
$ git checkout cgrpc
$ make plugin


It will produce in folder .build/release/

.build/release/protoc-gen-swift
.build/release/protoc-gen-swiftgrpc


Then if you need to:

cp .build/release/protoc-gen-swiftgrpc /usr/local/bin

After that, anything like the following should work:

protoc --swiftgrpc_out=. protofile.proto

**Comment by WangLongONE** [comment]
which protoc-gen-swift
/usr/local/bin/protoc-gen-swift

 protoc --swift_out=. my.proto
zsh: command not found: protoc

in  ~/.zshrc 

export PATH="/usr/local/bin/protoc-gen-swift:$PATH"

but not work
