### ISSUE TITLE
Provider crashes if not polled ??

### ISSUE THREAD

**Issue by idi888** [grpc/grpc-swift#325]
Hi All,

My Provider Server crashes if it is not polled for awhile

In Server.swift it is crashing on this line:

``` 
func run(handleFunction:)

// block while waiting for an incoming request
          let event = self.completionQueue.wait(timeout: 600)
```

I have attached the trace from Xcode not sure where to beginning in trying to find
![screen shot 2018-10-30 at 9 39 59 am](https://user-images.githubusercontent.com/8197402/47684678-d0d11a00-dc27-11e8-8521-85ef4b834f77.png)

**Comment by MrMage** [comment]
Looks like this could be the same issue as https://github.com/grpc/grpc-swift/issues/280.

What platform are you running this on? iOS or Mac?

**Comment by idi888** [comment]
Hey do you know why the timeout was set to 600 for the wait ?? 
```
let event = self.completionQueue.wait(timeout: 600)
```

The default server keepalive is 7200000, I think the timeout should be increased this value or you need to set your Channel.Argument.keepAliveTime(600) when creating the client


Otherwise '-1' just sets the timeout to time in distant future ("the workaround")
