### ISSUE TITLE
Client stops before end of stream

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc-swift#326]
### Question Checklist

- [X] Updated grpc-swift to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [X] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [X] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
What does `call.receive()` return/throw?

#### Question Description

I am wrapping a gRPC server stream in an RxSwift Observable, as can be seen in the code below ([link to repo](https://github.com/Dronecode/DronecodeSDK-Swift/blob/master/Dronecode-SDK-Swift/Telemetry.swift#L381-L400)).

My issue is that after a while (few minutes) of receiving messages (multiple small messages (i.e. a few floats) per second), my stream ends on the client side (but not on the server side).

```
private func createPositionObservable() -> Observable<Position> {
        return Observable.create { observer in
            let positionRequest = DronecodeSdk_Rpc_Telemetry_SubscribePositionRequest()

            do {
                let call = try self.service.subscribePosition(positionRequest, completion: nil)
                while let response = try call.receive() {
                    let position = Position(latitudeDeg: response.position.latitudeDeg, longitudeDeg: response.position.longitudeDeg, absoluteAltitudeM: response.position.absoluteAltitudeM, relativeAltitudeM: response.position.relativeAltitudeM)

                    observer.onNext(position)
                }
            } catch {
                observer.onError("Failed to subscribe to position stream")
            }

            return Disposables.create()
        }
        .subscribeOn(scheduler)
        .observeOn(MainScheduler.instance)
}
```

I feel like the problems comes from the way I handle `while let response = try call.receive()`: I assume that I go out of the `while` loop only when the stream ends. But could it be that it also ends when, say, one message fails?

I know that the network connection is good because this happens also when running locally on the loopback interface.

The question could be: in the above code, why would the `while` loop end other than because the stream ended on the server side? And is there a way to know if the stream ended properly on the server side or if it was something else (in which case maybe the `while` loop should continue trying)?

**Comment by MrMage** [comment]
To my limited knowledge of gRPC, there is no such thing as "one message fails", that should only happen when the gRPC library has somehow decided that the connection has been interrupted and gets shut down. At least I have not seen this in other cases, and I would recommend treating an error in `receive()`, establishing a new connection via a new call if needed. (I might be misunderstanding this, though.)

What error is `receive()` throwing, exactly? Also, what did you set the RPC timeout to? The default `Channel` timeout is set to 600 in SwiftGRPC.

**Comment by JonasVautherin** [comment]
Thanks @MrMage!

What seems to happen is that after a while, `receive()` returns `nil`, and the stream ends on the client side (but not on the server side; it is an infinite stream).

Is `nil` supposed to mean that the stream is finished?

> Also, what did you set the RPC timeout to? The default Channel timeout is set to 600 in SwiftGRPC.

Not setting anything in that regard, so I guess it is the default (600).

**Comment by MrMage** [comment]
> Is `nil` supposed to mean that the stream is finished?

Yes, returning nil indicates that the stream has finished. At that point, the next time the server tries to send a message, it should also receive an error. We should probably have a better way to surface this to the server, but don't have one right now, IIRC.

> Not setting anything in that regard, so I guess it is the default (600).

Try increasing the timeout to see if that changes anything. But as mentioned before, you should be prepared to re-establish the connection as needed.

**Comment by JonasVautherin** [comment]
> But as mentioned before, you should be prepared to re-establish the connection as needed.

I could do that, as a workaround, but that doesn't seem like the right way to do it. I mean, if I ask for a finite stream, I want to know if I received the full stream or if the connection somehow broke, right? How do I know that?

I mean, a grpc stream is supposed to be "reliable". If it says that it worked, it should have worked. In my case it gets interrupted, so I would expect to see an error...

**Comment by JonasVautherin** [comment]
Oh, so there is something I'm doing wrong. I'm sorry I am not yet so familiar with the syntax. So I should somehow check if it is `.ok` or not, and if not, I should restart the connection (here by running `self.service.subscribePosition` again). Correct?

Would you mind guiding me on testing this `.ok`? Not sure how to do that :-/.

**Comment by MrMage** [comment]
> Oh, so there is something I'm doing wrong. I'm sorry I am not yet so familiar with the syntax. So I should somehow check if it is `.ok` or not, and if not, I should restart the connection (here by running `self.service.subscribePosition` again). Correct?

That should work.

> Would you mind guiding me on testing this `.ok`? Not sure how to do that :-/.

Have a look at https://github.com/grpc/grpc-swift/blob/19bd5c67fc409bdcc62cd88f74b95db2bfbb1aaa/Tests/SwiftGRPCTests/EchoTests.swift#L120. Not sure whether the call completion handler would get called _before_ or _after_ the `receive()` call returns nil, though.

**Comment by JonasVautherin** [comment]
That was it! Thanks!
