### ISSUE TITLE
A very unstable error

### ISSUE THREAD

**Issue by AlexLisong** [grpc/grpc-swift#330]
I am having a very strange bug here, my code is as below:

        let request = Rpcpb_GetBlockchainInfoRequest.init()
        _ = try? Rpcpb_RpcServiceServiceClient.init(address: "127.0.0.1:50051", secure: false).rpcGetBlockchainInfo(request, completion: { (response, CallResult) in
            print("RESPONSE:\(String(describing: response?.blockHeight))\(String(describing: response?.tailBlockHash))\(CallResult.statusCode)\(String(describing: CallResult.resultData))")
                print("Result:\(CallResult)")

            })

I sometimes got correct result:
RESPONSE:Optional(861)Optional(32 bytes)okOptional(121 bytes)
Result:successful, status ok: 
resultData: 121 bytes
initialMetadata: [:]
trailingMetadata: [:]

sometimes wrong result:
RESPONSE:nilnilunknownnil
Result:successful, status unknown: Failed to create subchannel
initialMetadata: [:]
trailingMetadata: [:]

Without changing any code, I just re-ran the program, it produced different results, anyone had same issue before, how can I fix it?
Any help would be appreciated!

**Comment by MrMage** [comment]
I had `Failed to create subchannel` errors when there used to be connectivity, but then the connection gets lost. However, that should not be the case unless your gRPC server running on `127.0.0.1:50051` gets restarted while the client is still running?

**Comment by AlexLisong** [comment]
I fixed it by changing the code to:
let response = try? Rpcpb_RpcServiceServiceClient.init(address: "127.0.0.1:50051", secure: false).rpcGetBlockchainInfo(request)
print(response?.blockHeight ?? 0)

any idea why using Closures caused the error?

**Comment by AlexEdunov** [comment]
Getting the same error.

**Comment by MrMage** [comment]
@AlexLisong @AlexEdunov would it be possible that the service client gets released and thus deallocated before the async call ends? You should be able to check that by using it somehow in the completion handler. E.g.

```
var client: Rpcpb_RpcServiceServiceClient? = Rpcpb_RpcServiceServiceClient(address: "127.0.0.1:50051", secure: false)
_ = client.rpcGetBlockchainInfo(request, completion: { (response, CallResult) in
        print("RESPONSE:\(String(describing: response?.blockHeight))\(String(describing: response?.tailBlockHash))\(CallResult.statusCode)\(String(describing: CallResult.resultData))")
            print("Result:\(CallResult)")
            client = nil
        })
```

If that still doesn't work, also try

```
var client: Rpcpb_RpcServiceServiceClient? = Rpcpb_RpcServiceServiceClient(address: "127.0.0.1:50051", secure: false)
var call: Any? = client.rpcGetBlockchainInfo(request, completion: { (response, CallResult) in
        print("RESPONSE:\(String(describing: response?.blockHeight))\(String(describing: response?.tailBlockHash))\(CallResult.statusCode)\(String(describing: CallResult.resultData))")
            print("Result:\(CallResult)")
            call = nil
            client = nil
        })
```

**Comment by AlexEdunov** [comment]
```
import Foundation
import SwiftGRPC
import SwiftProtobuf

enum RoutesClientGRPCError: Error {
    case credentialsNotAvailable
    case requestFailure
}

class RoutesClientGRPC: RoutesAPI {
    let config: ClientConfig
    let credentialsSource: CredentialsSource
    var serviceClient: ServiceClientBase?

    required init(config: ClientConfig, credentialsSource: CredentialsSource) {
        self.config = config
        self.credentialsSource = credentialsSource
    }

    @discardableResult
    func fetchRoute(completion: @escaping (Route?, Error?) -> Void) -> Cancellable? {
        let serviceClient = De_Kenkou_RoutesServiceServiceClient(address: config.url, secure: true)
        self.serviceClient = serviceClient

        guard let jwtToken = credentialsSource.getJWTToken(),
              let firebaseUid = credentialsSource.getFirebaseUid() else {
            completion(nil, RoutesClientGRPCError.credentialsNotAvailable)
            return nil
        }

        do {
            let metadata = try Metadata(["authorization": "Bearer \(jwtToken)"])
            serviceClient.metadata = metadata
        } catch {
            completion(nil, RoutesClientGRPCError.credentialsNotAvailable)
            return nil
        }

        let cancellable = CancellableClientCall(clientCall: try? serviceClient.getWeeks(.with {
            $0.firebaseUid = firebaseUid
            $0.locale = LocaleManager.getLocale()
        }) { (response, result) in
            if result.success {
                if let response = response {
                    completion(Route(proto: response), nil)
                }
            }
        })

        return cancellable
    }
}
```

I've defined `serviceClient` property to prevent deallocating.

**Comment by prasanna-tapzo** [comment]
I am getting "successful, status unavailable: Connect Failed\ninitialMetadata: [:]\ntrailingMetadata: [:]". 
and also connectivityState progress from  "connecting => transientFailure". Does this mean connection established & server failed to send any response?

Any help would be appreciated!

**Comment by cepages** [comment]
I'm getting the same error here too. But in my case it's more random. It seems if I use the same service for multiple rpc methods, I get this error ( but as I said, not always )

@MrMage does that mean I should have one `serviceClient` per rpc method? ( https://github.com/grpc/grpc-swift/issues/330#issuecomment-446880378 )

**Comment by MrMage** [comment]
This behavior will be improved by #631, which keeps the channel active until all requests have finished.
