### ISSUE TITLE
Support TVOS

### ISSUE THREAD

**Issue by bimawa** [grpc/grpc-swift#332]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

General

#### Question Description

Why we not support tvOS? 
Tried connect to tvos project: 

```[!] The platform of the target `StreamLayer tvOS` (tvOS 10.0) is not compatible with `SwiftGRPC (0.6.0)`, which does not support `tvos`.```

**Comment by MrMage** [comment]
How did you include SwiftGRPC into your project? If you are using CocoaPods, you might be able to add support for the tvOS and watchOS platforms. If you do, please file a pull request so everyone can take advantages of your changes.

**Comment by bimawa** [comment]
I think its related with grpc/grpc#14173

**Comment by bimawa** [comment]
```
In file included from Pods/BoringSSL-GRPC/crypto/fipsmodule/cipher/e_aes.c:67:
Pods/BoringSSL-GRPC/include/openssl/arm_arch.h:96:5: error: "unsupported ARM architecture"
#   error "unsupported ARM architecture"
    ^
```
Need's help with compilation instructions for BoringSSL.

**Comment by MrMage** [comment]
tvOS is supported now.
