### ISSUE TITLE
Make call completion thread configurable

### ISSUE THREAD

**Issue by SebastianThiebaud** [grpc/grpc-swift#333]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Completion thread as an option

#### Question Description
Right now, the completion blocks are being called from a background thread. It would be great if we could design `grpc-swift` to support calling completion blocks from the main thread (or any other thread). Most network frameworks and libraries give an option to the consumer so they can specify a thread with which completion blocks of calls are called. 

I'm creating this issue for several purposes: tracking and proposal. I could submit a pull request with some changes but I'd like to know which solution is preferred: 
- Default thread property in the channel or service class
- Call argument defaulting to main thread

**Comment by Banck** [comment]
@glbrntt Hello!
Is it possible currently in grpc with NIO make call all completion blocks(such as whenComplete/whenSuccess etc) on specific thread like Main thread, for example?

**Comment by glbrntt** [comment]
@Banck I'm afraid not; it's an `EventLoopFuture` running on an `EventLoop`. You can dispatch onto a dispatch queue in the completion blocks though.

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now. If you want this functionality for the nio version, please file a new PR.
