### ISSUE TITLE
.swiftversion should maybe not be versioned

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc-swift#334]
Should we really have `.swiftversion` versioned? I was not expecting to find [this](https://github.com/grpc/grpc-swift/blob/master/.swift-version#L1), actually.

I mean, I don't even have swift 4.0 installed on my system, and I'm not expecting the project to set that for me 😅.

@ishkawa Do you have an opinion on that? I see that you last updated this file.

**Comment by MrMage** [comment]
What is that file for, anyway? :-)

**Comment by ishkawa** [comment]
This file is for [swiftenv](https://github.com/kylef/swiftenv), which manages Swift version per project. It seems that this file is not point to the version which this project uses currently. I think we can remove this file because SwiftPM have `swift-tools-version` now.
