### ISSUE TITLE
ServiceTestStub methods not implemented

### ISSUE THREAD

**Issue by cepages** [grpc/grpc-swift#339]
I'm trying to test my grpc layer using `...ServiceTestStub`.

If the rpc has a stream I can create all needed to test it. Also If the rpc doesn't have a stream but only if I use the synchronous method.

If I implement the asynchronous call I get an exception `fatalError("not implemented")`

In the code generated for the stubs seems that there is not implementation for this type of method:

```
  func list_protocols(_ request: Xz_Rpc_Protocol_ListProtocolsRequest, completion: @escaping (Xz_Rpc_Protocol_ListProtocolsResponse?, CallResult) -> Void) throws -> Xz_Rpc_Protocol_ProtocolServicelist_protocolsCall {
    fatalError("not implemented")
  }
```

Do I have to create the stub manually to test this type of rpc's?

**Comment by MrMage** [comment]
I am afraid that we indeed do not currently have an implementation for that. One idea would be to have the default implementation simply call the synchronous implementation and then call the completion handler with the result returned by the synchronous method. Would that work for you, and would you be interested in filing a pull request so we can integrate that into the project?

**Comment by cepages** [comment]
Yeah I could try.

Because the code is generated I guess is not that simple to implement it in the .grpc file.

Could you point me where I can create the implementation so it's generated when the script is run?

**Comment by MrMage** [comment]
Sure, thank you! I think the code should be in `Generator-Client.swift` (try searching for `fatalError`) in the plugin source directory. To test your changes, run `make test-plugin` and copy `/tmp/echo.grpc.swift` (I think) to the repo. I would also suggest adding a test illustrating use of this stub to the existing "ClientTestExamples" (or similar, im on the phone right now) test suite. Let me know if you need any further guidance :-)

**Comment by cepages** [comment]
@MrMage trying to follow your advise of implementing the synchronous call and call back to the completion closure I came across two problelms: the `CallResult` and the object to return the `...Call` object, where can I get those?

**Comment by cepages** [comment]
@MrMage after diving a bit more in the code, I could mock the `ServiceTestStub` method in my test system, I guess I could do something similar in the generated code:

```
class Xz_Rpc_Protocol_ProtocolServiceServiceTestStubFixed: Xz_Rpc_Protocol_ProtocolServiceServiceTestStub {
    
    override func list_protocols(_ request: Xz_Rpc_Protocol_ListProtocolsRequest, completion: @escaping (Xz_Rpc_Protocol_ListProtocolsResponse?, CallResult) -> Void) throws -> Xz_Rpc_Protocol_ProtocolServicelist_protocolsCall {
        
        let response = try self.list_protocols(request)
        
        let channel = Channel(address: "")
        let call = channel.makeCall("")
        let operationGroup = try OperationGroup(call: call, operations: [])
        let callresult = CallResult(operationGroup)

        completion(response,callresult)
        
        return Servicelist_protocolsCall()
    }
}
```

The line `Servicelist_protocolsCall()` creates an object from a class that conforms the protocol`Xz_Rpc_Protocol_ProtocolServicelist_protocolsCall` 

Although I'm pretty sure I could use  in the `Xz_Rpc_Protocol_ProtocolServicelist_protocolsCallBase(channel)` in the generator instead, because that class is implemented as a `fileprivate` in the code generated

If you are happy, I could try to implement this in the generator.

If not, I hope this doesn't seem like a totally atrocity :S

**Comment by MrMage** [comment]
Ouch! Sorry, I had forgotten that `CallResult` was so cumbersome to initialize. I would suggest making this method public:

```
https://github.com/grpc/grpc-swift/blob/c401b44ea81b246b8e7fea191ea1ee11a834ee60/Sources/SwiftGRPC/Core/CallResult.swift#L44
```

And then implement the method as follows:

```
    override func list_protocols(_ request: Xz_Rpc_Protocol_ListProtocolsRequest, completion: @escaping (Xz_Rpc_Protocol_ListProtocolsResponse?, CallResult) -> Void) throws -> Xz_Rpc_Protocol_ProtocolServicelist_protocolsCall {
        let response = try self.list_protocols(request)
        let callResult = CallResult(success: true, statusCode: .ok, statusMessage: "OK", resultData: nil,
                   initialMetadata: nil, trailingMetadata: nil)
        completion(response, callResult)
        return Servicelist_protocolsCall()
    }
```

Hope that makes sense; let me know if you have further questions.

**Comment by cepages** [comment]
@MrMage I totally forgot to finish this, sorry.

I've made the changes and created a test in `ClientTestExample`.

But I can't see any testing target where I can run the test. ( Trying with SwiftGRPC-Carthage.xcodeproj )

**Comment by cepages** [comment]
Ok, I think cleaning the project helped. 

I can get some input with `make test-echo`

**Comment by MrMage** [comment]
You should run `make project`, then use the resulting project to run the tests. If you file a pull request, the tests will also be run on our Continuous Integration server and I can review them. To fix the dependency issue, you can run `brew install nghttp2` if you have homebrew installed. But if you only run the `SwiftGRPCTests` test target, the issue should not even come up.

**Comment by cepages** [comment]
At the end I needed to install `nghhtp2` to run any test. They all pass nicely.
Thanks for your help
