### ISSUE TITLE
Memory Leak in ServiceClientBase.init(address:secure:arguments:)

### ISSUE THREAD

**Issue by crousselle2** [grpc/grpc-swift#340]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
`gpr_malloc` blocks are leaking heavily, when trying to instantiate a class subclassing `ServiceClientBase`.
The object is created as such 
`Services_ProtoActionsServiceClient(address: "server_url_here", secure: true)` where `Services_ProtoActionsServiceClient` is a simple `ServiceClientBase` subclass
Everytime we hit that creation and the server api is hit, a `gpr_malloc`is leaked, of pretty large size (250 to 530 KB)
This eventually adds up and leaks a huge amount memory.

Screenshot of profiling: 
<img width="2544" alt="screen shot 2018-12-05 at 4 56 02 pm" src="https://user-images.githubusercontent.com/45021389/49553892-af122500-f8ae-11e8-87c5-cc4cde501598.png">
Stack trace:
<img width="405" alt="screen shot 2018-12-05 at 4 56 34 pm" src="https://user-images.githubusercontent.com/45021389/49553908-be916e00-f8ae-11e8-8d85-2d73c0e350a4.png">
```
   grpc gpr_malloc Pods/gRPC-Core/src/core/lib/gpr/alloc.cc:57
   grpc gpr_strdup Pods/gRPC-Core/src/core/lib/gpr/string.cc:44
   grpc grpc_ssl_credentials_create Pods/gRPC-Core/src/core/lib/security/credentials/ssl/ssl_credentials.cc:92
   SwiftGRPC cgrpc_channel_create_secure /Pods/SwiftGRPC/Sources/CgRPC/shim/channel.c:59
   SwiftGRPC specialized Channel.init(address:secure:arguments:) /Pods/SwiftGRPC/Sources/SwiftGRPC/Core/Channel.swift:51
   SwiftGRPC Channel.init(address:secure:arguments:) /Pods/SwiftGRPC/Sources/SwiftGRPC/Core/Channel.swift:0
   SwiftGRPC ServiceClientBase.init(address:secure:arguments:) Pods/SwiftGRPC/Sources/SwiftGRPC/Runtime/ServiceClient.swift:44
 ```

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   12.1.0                                                       |
| Swift Version                 |   4.0.0                                                       |
| Xcode Version                 |   10.1                                                       |
| gRPC-Swift Version            |  0.6.0                                                      |
| protoc Version                |  3.6.1                                                       |
| protoc-gen-swift Version      |   1.1.2                                                       |
| protoc-gen-swiftgrpc Version  |   1.1.2                                                      |
  </pre>
</details>

**Comment by MrMage** [comment]
Thanks for the heads-up! Could you please check if the leak goes away if you add a line

```
grpc_channel_credentials_unref(creds);
```

after https://github.com/grpc/grpc-swift/blob/54659b8a7fabd9ed4e778ed1d496cb567721da4f/Sources/CgRPC/shim/channel.c#L61?

**Comment by crousselle2** [comment]
@MrMage thanks for the quick update, it does fix the issue! Want me to create a PR with the fix ?

**Comment by MrMage** [comment]
That would be great, thanks!
