### ISSUE TITLE
Release 0.6.0 Make Error

### ISSUE THREAD

**Issue by namsoila** [grpc/grpc-swift#348]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

Running `make` in order to generate protoc-gen-swift and protoc-gen-swiiftgrpc leads to errors. Had install pkg-config manually on osx in order to resolve some error lines. Error does not occur with 0.5.1 release in same environment.

##### Complete output when running grpc-swift, including the stack trace and command used

<details>
  <pre>[swift build -Xcc -ISources/BoringSSL/include -Xlinker -lz
Compile Swift Module 'NIOHTTP2' (16 sources)
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/CNIONghttp2/include/c_nio_nghttp2.h"
        ^
/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/CNIONghttp2/include/c_nio_nghttp2.h:17:10: error: 'nghttp2/nghttp2.h' file not found
#include <nghttp2/nghttp2.h>
         ^
/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/NIOHTTP2/HTTP2DataProvider.swift:14:8: error: could not build Objective-C module 'CNIONghttp2'
import CNIONghttp2
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/CNIONghttp2/include/c_nio_nghttp2.h"
        ^
/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/CNIONghttp2/include/c_nio_nghttp2.h:17:10: error: 'nghttp2/nghttp2.h' file not found
#include <nghttp2/nghttp2.h>
         ^
/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/NIOHTTP2/HTTP2DataProvider.swift:14:8: error: could not build Objective-C module 'CNIONghttp2'
import CNIONghttp2
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/CNIONghttp2/include/c_nio_nghttp2.h"
        ^
/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/CNIONghttp2/include/c_nio_nghttp2.h:17:10: error: 'nghttp2/nghttp2.h' file not found
#include <nghttp2/nghttp2.h>
         ^
/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/NIOHTTP2/HTTP2DataProvider.swift:14:8: error: could not build Objective-C module 'CNIONghttp2'
import CNIONghttp2
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/CNIONghttp2/include/c_nio_nghttp2.h"
        ^
/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/CNIONghttp2/include/c_nio_nghttp2.h:17:10: error: 'nghttp2/nghttp2.h' file not found
#include <nghttp2/nghttp2.h>
         ^
/grpc-swift-master/.build/checkouts/swift-nio-http2.git-4714885477116340479/Sources/NIOHTTP2/HTTP2DataProvider.swift:14:8: error: could not build Objective-C module 'CNIONghttp2'
import CNIONghttp2
       ^
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /grpc-swift-master/.build/debug.yaml main output:
    

make: *** [all] Error 1]</pre>
</details>

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OSX Version                    |   10.14.2                                                      |
| Swift Version                 |   4.2                                                      |
| Xcode Version                 |   10.1                                                       |
| gRPC-Swift Version            |   0.6.0                                                       |
| protoc Version                |   3.6.1                                                       |
| protoc-gen-swift Version      |   0.6.0                                                       |
| protoc-gen-swiftgrpc Version  |   0.6.0                                                       |
  </pre>
</details>

**Comment by MrMage** [comment]
Thanks! Could you please provide the exact error and what you did to resolve the issue? And did you check out the `master` branch or the `0.6.0` tag?

**Comment by namsoila** [comment]
The details section above aimed to provide the exact error. Was there something additional required? I had checked out the master. Thanks.

**Comment by MrMage** [comment]
Sorry, I had missed that section. Are you sure that you are using the 0.6.0 release; that looks like `master` or 0.7.0? Also, did you try `make plugin` to build only the plugin?

**Comment by namsoila** [comment]
At that point I believe master was `0.6.0`. Will run with `0.7.0` and update. Thanks.

**Comment by rebello95** [comment]
Are you still having this issue @namsoila?

**Comment by namsoila** [comment]
@rebello95 Testing currently and will update.

**Comment by namsoila** [comment]
@rebello95 @MrMage The error no longer occurs with 0.6.0. Thanks.
