### ISSUE TITLE
can't access initial metadata before completion of ClientCallServerStreaming

### ISSUE THREAD

**Issue by ericbuehl** [grpc/grpc-swift#353]
### Question Checklist

- [X] Updated grpc-swift to the latest version
- [X] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [X] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [X] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Can't access initial metadata before completion handler of ClientCallServerStreaming is called

#### Question Description
I see no way of accessing initialMetadata before a server streaming call has completed.  It is included in the CallResult that is passed to the completion hander, but the callback is only executed after the server has completed streaming all messages.  I would expect another callback to be invoked when initial metadata is received by the client and before receiving of messages begins.  Is this a missing feature or am I misunderstanding the intention of initial metadata sent from the server?

**Comment by MrMage** [comment]
I'm afraid you are right; I think this was simply an oversight when designing the current (admittedly clumsy) API. I would be open to exposing the initial metadata earlier if you file a pull request; do you have good suggestions on how that could be done without interfering with the "regular" use-case where that metadata is rarely needed? Also, what is your specific use-case for this metadata?

**Comment by ericbuehl** [comment]
One use case is for the server to give hints to a client (if know) about the message stream count. This would allow for progress indication, letting the client bail early if more data is to be sent than expected, etc

As for how to expose this, perhaps another handler could be provided at calltime to be invoked when initial metadata has been received. It could provide a partially filled CallResult or just the underlying Metadata object

**Comment by MrMage** [comment]
> One use case is for the server to give hints to a client (if know) about the message stream count. This would allow for progress indication, letting the client bail early if more data is to be sent than expected, etc

Makes sense (unless one sends these as part of the first streaming message); thanks for the explanation.

> As for how to expose this, perhaps another handler could be provided at calltime to be invoked when initial metadata has been received. It could provide a partially filled CallResult or just the underlying Metadata object

I was thinking of something similar; my only concern is that this would pollute the method signature of all server-streaming calls. Alternatively, we could add a `func getInitialMetadata(_ work: (Metadata) -> Void)` to the server streaming `Sessions`. That block would then be called when initial metadata arrives, or, if it has already arrived, the block would be called immediately with the cached metadata. What do you think?

**Comment by ericbuehl** [comment]
Either approach works for me.  I won't be able to make a stab at the PR just yet but in the meantime let's leave this issue open for posterity.

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
