### ISSUE TITLE
Add client support for SwiftGRPCNIO

### ISSUE THREAD

**Issue by glbrntt** [grpc/grpc-swift#354]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

SwiftGRPCNIO

#### Question Description

(Not a question as such.) It would be great to have client support for the NIO implementation. I've been playing around this recently and wanted to start a discussion on requirements/ideas for this; particularly around how the API looks.

**Comment by glbrntt** [comment]
Thanks for the insight @MrMage! 

That makes sense. I like the idea of call options; it keeps the generation and client API fairly straightforward. I was thinking returning some kind of `{CallType}Call` object (similar to the `CallBuilder` you described) containing futures for metadata and status as well as a response or request providing method (for client- and bidi-streaming). This could also include a `cancel` method.

The calls would then be something like:

```swift
unary(request: Request, options: UnaryCallOptions) -> UnaryCall<Response>
clientStreaming(options: ClientStreamingCallOptions) -> ClientStreamingCall<Response>
serverStreaming(request: Request, options: ServerStreamingCallOptions, handler: (ResponseOrError<Response>) -> Void) -> ServerStreamingCall<Response>
bidirectionalStreaming(options: BiderctionalStreamingCallOptions, handler: (ResponseOrError<Response>) -> Void) -> BiderctionalStreamingCall<Response>
```

It could make for a more consistent API if unary and server streaming requests were also via a `send` method on the `Call` object:

```swift
unary(options: UnaryCallOptions) -> UnaryCall<Response>
serverStreaming(options: ServerStreamingCallOptions, handler: (ResponseOrError<Response>) -> Void) -> ServerStreamingCall<Response>

client.unary().send(request: request).whenSuccess { ... }
```

That feels a quite Java-esque to me though. I suppose this could be the underlying implementation with an extension provided which allows you to provide the request in the `unary`/`serverStreaming` call.

**Comment by MrMage** [comment]
Love the idea of having futures for {initial/trailing} metadata and status, I didn't think of those!

I understand the idea of consistent API, but for client-unary calls, the client should not be able to send more than one message. I think that's better enforced through just taking the one-and-only request message as a call argument, and makes for much more readable unary calls (which are probably 95%) of the cases. However, not sure how we could attach request metadata to those calls; we could either provide another "Options" argument or have a second method that _does_ return a `Call` object. Then the variant with the "easy" API could simply call through to call `.run()` on the call object (reading through this more, this is probably what you meant with the last paragraph :-) ).

FYI, make sure to take a look at `StreamingResponseCallContext` and `UnaryResponseCallContext`; we might do something similar for sharing logic between streaming and bidirectional calls on the client side :-)
