### ISSUE TITLE
How to add custom meta data

### ISSUE THREAD

**Issue by prasanna-tapzo** [grpc/grpc-swift#359]
I am getting the following error while adding custom meta data (key, value) pair.

 validate_metadata: {"created":"@1547640570.096726000","description":"Illegal header key","file":"/Users/prasannaaithal/Documents/ProtoBufTest 2/Pods/gRPC-Core/src/core/lib/surface/validate_metadata.cc","file_line":43,"offset":5,"raw_bytes":"67 72 70 73 2d 4d 61 74 63 68 65 73 2d 4b 65 79 'grps-Matches-Key'"}

I have created the stub instance and added meta data like this:
```
let client = Org_Baeldung_Grpc_HelloServiceServiceClient(address: "hello-grpc.172.16.1.0.nip.io", secure: false)
try! client.metadata.add(key: "grps-Matches-Key", value: "grpc2")
```

**Comment by MrMage** [comment]
Could you try making the metadata keys lowercase?

**Comment by prasanna-tapzo** [comment]
@MrMage Appreciate the help.  I am not getting **Illegal header key** for now. Making the keys lowercase worked. Meanwhile stub also expecting me to specify the port. For Ex:
```
let client = Org_Baeldung_Grpc_HelloServiceServiceClient(address: "hello-grpc.172.16.1.0.nip.io:80", secure: false)
try! client.metadata.add(key: "grps-matches-key", value: "grpc2")```. 

Is this really required to mention the port inside address?

**Comment by MrMage** [comment]
Yes, setting the port is required, because gRPC could work over any port.

**Comment by prasanna-tapzo** [comment]
@MrMage  Thanks.
