### ISSUE TITLE
Even after 0.7.0 is released Cocoapods still lists 0.6.0

### ISSUE THREAD

**Issue by dvaldivia** [grpc/grpc-swift#361]
I see 0.7.0 was released 22 days ago but Cocoapods still list release 0.6.0

I think this is a similar case to #279

**Comment by MrMage** [comment]
@rebello95 could you please check if the CocoaPods release process needs to be run for that version?

**Comment by rebello95** [comment]
Yep, looks like it wasn't run. Just pushed `0.7.0` to CocoaPods:

```
mrebello$ pod trunk info SwiftGRPC

SwiftGRPC
    - Versions:
      - 0.4.2 (2018-04-19 18:26:35 UTC)
      - 0.4.3 (2018-05-17 03:22:19 UTC)
      - 0.5.0 (2018-08-13 15:59:32 UTC)
      - 0.5.1 (2018-08-19 19:46:23 UTC)
      - 0.6.0 (2018-09-04 14:32:08 UTC)
      - 0.7.0 (2019-01-29 04:25:43 UTC)
```

Going to go ahead and close this, feel free to reopen if you still have issues 😄
