### ISSUE TITLE
Unable to build 0.7.0 on Linux

### ISSUE THREAD

**Issue by bourquep** [grpc/grpc-swift#365]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

Trying to compile v0.7.0 in the official Swift 4 Docker image fails at linking with `error: cannot find -ldispatch`.

Repro steps:

```
docker run --rm -it swift:4.2.1

# within the docker container prompt...

git clone -b 0.7.0 https://github.com/grpc/grpc-swift.git
cd grpc-swift
make plugin
```

Observe that linking fails with `error: cannot find -ldispatch`

Try the same steps, but with `git clone -b 0.6.0` instead, and observe that `make build` succeeds.

**Comment by MrMage** [comment]
Closing this; please re-open if it is still relevant with 0.9.0.
