### ISSUE TITLE
protoc-gen-swiftgrpc avoids writing empty files when .proto files lack service definitions. Should it?

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#374]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Code generation

#### Question Description

With [this test](https://github.com/grpc/grpc-swift/blob/ac1939e98bce1717bea6dea890d24ca4d335d7eb/Sources/protoc-gen-swiftgrpc/main.swift#L108), `protoc-gen-swiftgrpc` avoids writing files for any `.proto` file that contains no `service` definitions. This was intended to avoid polluting developer workspaces with empty files, but in discussion of [this swift-protobuf issue](https://github.com/apple/swift-protobuf/issues/710), @thomasvl pointed out that [some build systems work better if these empty files are generated](https://github.com/apple/swift-protobuf/issues/710#issuecomment-354467863).

I'm happy to make this change if there's consensus to support it. Thoughts?

**Comment by MrMage** [comment]
If one runs `protoc` with both the SwiftProtobuf and SwiftGRPC on all their `.proto` files, `protoc` would generate an empty `.grpc.swift` file _for every model file_. I'd expect there to be way more model files than service files, so this might create a significant amount of noise. And if users are using a build system, I would expect them to only run the SwiftGRPC compiler + plugin on the `.proto` files containing a service definition file, making this a non-issue for them.

Unless anyone is encountering real-world problems with this, I would vote against changing.

**Comment by thomasvl** [comment]
I common see folks using bazel just use a `glob(["*.proto])` for their rules, so they get the ones defining models and services all in one.

Our of curiosity, what do the other grpc plugins do?  It seems like there would be an argument for consistence with them, and they too should have this issue, no?

**Comment by rebello95** [comment]
I tend to agree with @MrMage that we shouldn't generate extra files if they're empty. Maybe we could specify a custom option when running the plugin to change this behavior instead of changing it globally?

To answer @thomasvl's comment, it looks like the Go plugin generates something like this when running `protoc --go_out=plugins=grpc:. foo.proto ` on a proto file that has no RPCs or messages (only a package and language version): 

```go
// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("foo.proto", fileDescriptor_7ce1e2eec643ca48) }

var fileDescriptor_7ce1e2eec643ca48 = []byte{
	// 45 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xcb, 0xcf, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x76, 0xcb, 0xcf, 0x4f, 0x62, 0x03, 0xb3, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xc5, 0x49, 0x7f, 0x18, 0x00, 0x00, 0x00,
}
```

I didn't check other plugins. Since we don't generate descriptors, though, I'm not sure this makes sense for our case.

**Comment by MrMage** [comment]
> I tend to agree with @MrMage that we shouldn't generate extra files if they're empty. Maybe we could specify a custom option when running the plugin to change this behavior instead of changing it globally?

I like the idea of having an option for this. However, I'd still lean towards waiting until someone actually reports issues with this in their setup in the wild. (If it ain't broken, don't fix it.) AFAICT build tools like Bazel are less popular with Swift, anyway, but I might be mistaken there.

**Comment by thomasvl** [comment]
We're trying to write a swift_grpc rule for bazel (https://github.com/bazelbuild/rules_swift) and ran into this.  😄

**Comment by MrMage** [comment]
Fair enough 😅 Would an extra plugin option for `protoc` work for you?

**Comment by thomasvl** [comment]
Yea, we could always enable it.

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
