### ISSUE TITLE
Inconsistency in proto message naming convention, too many underscores

### ISSUE THREAD

**Issue by mickeyreiss** [grpc/grpc-swift#38]
Hi @timburks,

While trying to incorporate grpc-swift into my project, I noticed a minor inconsistency between grpc-swift and swift-protobuf in the naming conventions for messages. This caused my generated code to fail to compile.

You can apply this patch, recompile `echo.proto` and then attempt to build the Echo app to see what I'm talking about:

```diff
diff --git a/Examples/Echo/echo.proto b/Examples/Echo/echo.proto
index 1328b5f..ce418b6 100644
--- a/Examples/Echo/echo.proto
+++ b/Examples/Echo/echo.proto
@@ -14,7 +14,7 @@

 syntax = "proto3";

-package echo;
+package echo_package;

 service Echo {
   // Immediately returns an echo of a request.
```

`swift-protobuf` creates messages with names like `EchoPackage_EchoRequest` while `grpc-swift` assumes `Echo_Package_EchoRequest`.

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
