### ISSUE TITLE
NIOServerWebTests cause a fatal error on Linux CI

### ISSUE THREAD

**Issue by glbrntt** [grpc/grpc-swift#382]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

Running the `NIOServerWebTests` on Linux causes a fatal error: <pre>Fatal error: Trying to remove task, but it's not in the registry.: file Foundation/URLSession/TaskRegistry.swift, line 76</pre>

##### Complete output when running grpc-swift, including the stack trace and command used

From: https://travis-ci.org/grpc/grpc-swift/jobs/498728631#L3096

<details>
  <pre>Test Case 'NIOServerWebTests.testUnaryLotsOfRequests' started at 2019-02-26 13:42:02.497
Fatal error: Trying to remove task, but it's not in the registry.: file Foundation/URLSession/TaskRegistry.swift, line 76
Exited with signal code 4
  </pre>
</details>

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   Ubuntu 14.04                                                       |
| Swift Version                 |   4.1.1                                                       |
| gRPC-Swift Version            |   master                                                       |
| protoc Version                |   3.5.1                                                       | </pre>
</details>

**Comment by MrMage** [comment]
@glbrntt is this still the case?

**Comment by glbrntt** [comment]
Doesn't appear to be: we disabled the test and then it was re-enabled when we started generating LinuxMain, we haven't seen any fatals since so I think this is resolved.
