### ISSUE TITLE
How to debug internalError: GOAWAY

### ISSUE THREAD

**Issue by dvaldivia** [grpc/grpc-swift#388]
I'm seeing a behavior some times when my iOS apps comes back from background that the status of the response is internalError

by doing a `debugPrint(result)` on the `CallResult` I get
```
successful, status internalError: GOAWAY received
initialMetadata: [:]
trailingMetadata: [:]
```

The comment on the code states
```
/// Internal errors. Means some invariants expected by underlying System has
/// been broken. If you see one of these errors, Something is very broken.
  case internalError = 13
```

So I was wondering if there's anyway to debug this problem?

A simple retry fixes the issue, but I'm not sure if I should automatically retry on every .internalError

cheers

**Comment by MrMage** [comment]
Closing this for being stale; might also have improved with the new gRPC-Core version using CFStream.

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
