### ISSUE TITLE
Xcode project configuration issues - modules, headers, etc.

### ISSUE THREAD

**Issue by jacobjennings** [grpc/grpc-swift#44]
It appears that module maps are present for each target but are not referenced by the generated Xcode project targets, and can probably be removed.

In order to "import CgRPC" from my main application, I had to:

- Set "Defines Module" to Yes on CgRPC target
- Add a "Headers" phase to CgRPC target build phases & add CgRPC.h as a public header

I'm not familiar with the Xcode project generation or I'd submit a PR.

Thanks for the continued great work! Happy to see it working in Xcode 8.3.2.

**Comment by johndpope** [comment]
hacking the header search path works too
<img width="891" alt="screen shot 2017-04-26 at 10 41 43 am" src="https://cloud.githubusercontent.com/assets/289994/25440269/f6a2f564-2a6c-11e7-85c2-2670ff20e5a5.png">

**Comment by mtitolo** [comment]
Same issue. Changing `Defines Module` and adding `Headers` didn't fix the issue for me in Xcode 8.2.1. Header search path change works.

**Comment by johndpope** [comment]
hi @timburks 
it maybe possible to add this line when generating xcode  project

swift package generate-xcodeproj --xcconfig-overrides settings.xcconfig

see here
https://github.com/johndpope/tensorflow/blob/swift/tensorflow/swift/Makefile


you can spit out the schemas once corrected - this should resolve the known problem with linking 
https://gist.github.com/johndpope/dd5e5c702077f0a7307384ff2596f85f

cherry pick into a new config file - then simpy append override in the swift makefile to fix linking.

**Comment by msalman86** [comment]
Looks like I'm having an issue related to this. When I try to do `import gRPC` in my main code, it complains `Missing Required module CgRPC`. I am not sure what value to use in header search path. Any help would be appreciated, thank you!

**Comment by thedodd** [comment]
@msalman86 when you set the `Header Search Paths` as referenced above, you will need to be sure that the search paths actually reference the real location of that directory on your filesystem. I encountered the same issue.

My workaround was to:
- add grpc-swift as a git submodule in my repo (checked out at a specific tag).
- run make from that submodule location.
- add the resulting `SwiftGRPC.xcodeproj` to my workspace.
- update the `Header Search Paths` (referenced above) to point to the **EXACT** location on my filesystem using the `${SOURCE_ROOT}` variable.

**Comment by bootstraponline** [comment]
I had the same issue. It'd be nice to fix the xcodeproj generation to output a correct project. The fixes discussed in this issue worked for me on Xcode 8.3.3.

**Comment by dcow** [comment]
Same issue, xcode 9. Updating cgrpc target works

**Comment by bootstraponline** [comment]
same issue in Xcode 9.2 as well.

**Comment by JonasVautherin** [comment]
Changing the `Header Search Paths` in the client app worked for me as well, but is there not a way to fix that directly? I see that `CgRPC` has a `module.modulemap` referring to `cgrpc.h` already...

**Comment by JonasVautherin** [comment]
Just found that issue again. Note that it is currently being investigated into #272.
