### ISSUE TITLE
Proposal to introduce a "PendingCall" type

### ISSUE THREAD

**Issue by aufflick** [grpc/grpc-swift#457]
# Problem

In multiple apps I've observed a desire to extend or isolate helper gRPC functionality in a way that avoids duplication while applying to all gRPC services. With the current gRPC api we cannot do this because each service has a unique generated type, and there is no base type which exposes a fixed rpc calling api.

## Ultimate Goals

1. Be able to write simple generic extensions which bridge all gRPC calls with any given Promise/Observable library
2. Be able to implement a gRPC wrapper that makes sense for any given code base where things like error result parsing can take place and which can insulate an app from gRPC api changes (or even changing to a different RPC mechanism)

# Possible Solutions

## Natively return promise type

I'd be ok with this as an outcome, but there are a number of (non-fatal) problems, off the top of my head:

1. Promises aren't universally loved, resulting in unnecessary <strike>arguments</strike> discussions
2. Foundation has no Promise type so either we'd be adding a dependency or writing our own Promise type
3. Related to 2, many people would want to bridge to different Promise or Observable types

## Generate rpc methods which return a generic type instance instead of accepting a completion closure

In other words, instead of generating something like we do now:

```swift
public protocol EchoServiceEchoCall : ClientCallUnary {}

final public class EchoServiceClient : SwiftGRPC.ServiceClientBase, EchoService {

    public func echo(
      _ request: EchoRequest,
      metadata customMetadata: SwiftGRPC.Metadata,
      completion: @escaping (EchoResponse?, SwiftGRPC.CallResult) -> Void
    ) throws -> EchoServiceEchoCall {
    ...
    }
}

```

Where `EchoServiceEchoCall` is really just a canceller. I propose we could instead have a type that represents a pending call. Eg. (and forgive the type naming :)

```swift
public typealias Canceller = () -> Void

public protocol CallFactory {
  /// Execute the RPC.
  public func call(
    _ request: Request,
    metadata: SwiftGRPC.Metadata,
    callback: (Response?, SwiftGRPC.CallResult) -> Void
  ) throws -> UnaryCall
}
```

The existing funcs would then become merely convenience functions:

```swift
final public class EchoServiceClient : SwiftGRPC.ServiceClientBase, EchoService {

  /// New.
  public func pendingEcho() -> PendingCall<EchoRequest, EchoResponse> { ... }
  
  /// Existing (changed only in that the returned type is a generic UnaryCall, not a specific type).
  public func echo(
    _ request: EchoRequest,
    metadata customMetadata: SwiftGRPC.Metadata,
    completion: @escaping (EchoResponse?, SwiftGRPC.CallResult) -> Void
  ) throws -> UnaryCall {
    return try pendingEcho().call(request, metadata, completion: completion) 
  }
}
```

This is entirely backward compatible, seems to suite the new NIO implementation, and allows client users to achieve the original goals of having a single type `PendingCall` which can be extended or wrapped to bridge to a promise type, or perform any other abstraction desired.

# Anticipated feedback

Here are a few responses I would have if I read the above suggestions without context, along with my response:

## Where is the PR?

I thought it would be better to gauge interest and refine the approach to meet community goals before I invested time in writing code. If there isn't any overwhelming resistance I'll produce a PR in the near future :D

## This doesn't seem very functional

Perhaps a "more functional" way would be to curry our existing functions. We can't directly curry functions in Swift (any more), but an importing codebase could write a specific purpose currying helper:

```swift
public class RPCCaller<Request, Response, Call> {
  public typealias RPCFunc =
    ((Request, SwiftGRPC.Metadata, @escaping (Response?, SwiftGRPC.CallResult) -> Void) throws
    -> Call)

  public typealias Canceller = () -> ()

  var rpcFunc: RPCFunc

  // We don't need the client per se, but it's lifecycle must extend until any call is completed.
  var client: SwiftGRPC.ServiceClientBase

  public init(_ client: SwiftGRPC.ServiceClientBase, rpc rpcFunc: @escaping RPCFunc) {
    self.client = client
    self.rpcFunc = rpcFunc
  }

  /// Execute an RPC call.
  public func call(
    _ request: Request,
    metadata: SwiftGRPC.Metadata,
    callback: @escaping (Response?, SwiftGRPC.CallResult) -> ()
  ) throws -> Canceller {
    let retainedClient = self.client

    let clientCall = try rpcFunc(request, metadata) { response, result in
      // Ensure the client's lifecycle extends until the request is complete.
      withExtendedLifetime(retainedClient) {}
      callback(response, result)
    }

    // We can't constrain the Call type to ClientCall since protocols do not (yet) conform to
    // themselves https://bugs.swift.org/browse/SR-55
    guard let typedClientCall = clientCall as? SwiftGRPC.ClientCall else {
      preconditionFailure()
    }

    return typedClientCall.cancel
  }
}
```

Such a helper would allow simple direct usage eg:

```swift
    let client = EchoClientService(...)
    let caller = RPCCaller(client, rpc: client.echo)
    try caller.call(request, metadata: metadata) { result in
	  ...
    }
```

... while also allowing our original goals to be met, ie. being trivial to bridge to any Promise or Observable implementation with a single central extension, and also allow apps to have a single central place where any future gRPC api changes could be isolated.

This feels like a pretty heavy wrapper to expect many code bases to implement however. Additionally, making this the responsibility of each codebase prohibits easy sharing of extensions and patterns.

**Comment by aufflick** [comment]
Ah, I saw it had been discussed, I didn't realise it had been implemented that way, or that the NIO api was quite so different. On first glance it does look like the changes to `UnaryClientCall` achieve my stated goals in a pretty similar way.

Let me try out the NIO interface in practice to confirm, but it does look like this ticket is somewhat moot :)

For completeness here are concrete examples of where the goals are useful (I tried to make them abstract, but perhaps that was unhelpful):

1. Eg. in an RxSwift heavy app you really want to be able to write something like `echoService.call(request).asObservable()` which can then be merged, flatmapped etc. With the current implementation this is not possible without either writing some boilerplate protocol adoption for every client type, or with a convoluted wrapper as in my OP.
2. A concrete example of this is right now :) I'm integrating gRPC into an app with the current shipping API, but I know NIO is coming and don't want to change every file that uses gRPC clients when that change happens, so I'd like to make a single vendor of gRPC clients that expose an implementation agnostic interface (let's say RxSwift, eg. `let rpc: Observable<ResponseProtoType> = myRPCVendor.makeEchoRPCObservable(request)` so that the implementations can be switched out with only that vendor need changing.

**Comment by MrMage** [comment]
> 1. Eg. in an RxSwift heavy app you really want to be able to write something like `echoService.call(request).asObservable()` which can then be merged, flatmapped etc. With the current implementation this is not possible without either writing some boilerplate protocol adoption for every client type, or with a convoluted wrapper as in my OP.

That makes sense. One of the goals for SwiftGRPC is definitely to be able to use it on a lower level than with the generated code; I hope that the NIO implementation makes that much easier (as evidenced by the fact that it requires [much less generated code](https://github.com/grpc/grpc-swift/blob/nio/Sources/Examples/EchoNIO/Generated/echo.grpc.swift) to be useful).

However, if you start doing method calls "by hand", manually declaring the method name and request/response types, you will lose a few of gRPC's type-safety benefits. Another option would be to fork our `protoc` plugin to create bespoke generated code adapted for e.g. RxSwift.

Thinking about that, the new NIO implementation might make that even easier. For example, you could write something like this:

```
```

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
