### ISSUE TITLE
How I suppose to manage the `channel.timeout` when I get `.deadlineExceeded`

### ISSUE THREAD

**Issue by cepages** [grpc/grpc-swift#464]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

Yes

No

#### Question Description

I'm using a stream rpc method. This rpc method needs to be open for a long time. But it always get close after 10 minutes ( the value in `channel.timeout` by default ) with the `callResult.statusCode` = `.deadlineExceeded`.

I thought about change the `channel.timeout`, but I don't have a maximum time of this stream to be closed. 

Another option, it's when I get the `.deadlineExceeded` statusCode, it's to make another request, but I get a `CallResult` error with the type: `tooManyOperations`

Does the stream suppose to be open for any amount of time until it's closed for one of the ends? Or I'm implementing the stream rpc wrongly:

```swift
    lazy internal var getDataHd5DataService: HD5_DataServiceService = {
        
        let service = HD5_DataServiceServiceClient.init(address: address, secure: false)
        return service
    }()
```

...
```swift
self.getDataHd5DataCall = try self.getDataHd5DataService.get_hd5_data_from_path(request) { [weak self] (callResult:CallResult) in
                
                guard let strongSelf = self else { return }
                strongSelf.getDataHd5DataCall?.cancel()

                switch callResult.statusCode {
                case .unavailable:
                    
                    error("unavailable")
                    connectionStatus(.Disconnected)

                    break;
                case .deadlineExceeded:
                    
                    //If deadline Exceeded we re-stablish the connection
                    strongSelf.makeADataRequest(request: request, connectionStatus, success, error, finished: finished)
                    
                break;
                    
                default:
                    print("------------------> Date finish:\(NSDate())")

                    strongSelf.getDataHd5DataCall?.cancel()

                    guard callResult.statusCode != .cancelled else { return }

                    connectionStatus(.Disconnected)
                    error(NSError(domain: NSStringFromClass(GRPCControllerHD5Data.self), code: -1, userInfo: [NSLocalizedDescriptionKey:callResult.statusMessage ?? "Unknown error"]))
                }
            }
            try self.expandGetHD5DataBlocking(hd5DataReceived: success, error: error,finished: finished)
```

**Comment by MrMage** [comment]
Channels should indeed be open until the connection gets interrupted, it gets closed or cancelled by the clients, or `channel.timeout` has been exceeded, whichever comes first. You could try setting `channel.timeout` to a much larger value (e.g. 86400 seconds = 24 hours), but usually making a new call a `.deadlineExceeded` event should be sufficient to start a new call.

Note that you don't need to (and should not) call `strongSelf.getDataHd5DataCall?.cancel()` in the completion handler. Also note that the completion handler will be called on a different thread, so you will need to make sure to not access variables from two threads at once.

> Another option, it's when I get the `.deadlineExceeded` statusCode, it's to make another request, but I get a `CallResult` error with the type: `tooManyOperations`

No idea about that; are you sure that you are using the new call and not accidentally re-using the old call object?

**Comment by cepages** [comment]
@MrMage thanks for your reply

> Channels should indeed be open until the connection gets interrupted, it gets closed or cancelled by the clients, or channel.timeout has been exceeded, whichever comes first. You could try setting  channel.timeout to a much larger value (e.g. 86400 seconds = 24 hours), but usually making a new call a .deadlineExceeded event should be sufficient to start a new call.

I will try set it up to that value or something similar, but it could happen that the stream should be open for more than 24 hours.

Although, I tried to set it up to: `TimeInterval.greatestFiniteMagnitude` but it returns immediately with `.deadlineExceeded`

> Note that you don't need to (and should not) call strongSelf.getDataHd5DataCall?.cancel() in the completion handler. Also note that the completion handler will be called on a different thread, so you will need to make sure to not access variables from two threads at once.

Thanks for the info.

>>Another option, it's when I get the .deadlineExceeded statusCode, it's to make another request, but I get a CallResult error with the type: tooManyOperations

>No idea about that; are you sure that you are using the new call and not accidentally re-using the old call object?

Not always happens, but I think it related because that stream it's fed with a constant flow of responses. So the client can't cope with all the responses sent by the server. I guess it could be because there are so many responses in the service that it's not possible to create a new request?

**Comment by MrMage** [comment]
> Although, I tried to set it up to: `TimeInterval.greatestFiniteMagnitude` but it returns immediately with `.deadlineExceeded`

I think gRPC allows a maximum of six digits in the timeout parameter. So 999999s might be the maximum. Alternatively, you could try "0" or "-1" to see if that gives an infinite timeout.

**Comment by MrMage** [comment]
You could also try enabling more debug logging in gRPC: https://github.com/grpc/grpc/blob/master/doc/environment_variables.md https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md
