### ISSUE TITLE
Does these libraries support GRPCS .. Secure GRPC connection . How to do it .. Just adding secure certificates enough ?

### ISSUE THREAD

**Issue by mushtaque87** [grpc/grpc-swift#466]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

**Comment by mushtaque87** [comment]
My devops team is asking me to support GRPCS in our client. The GRPC proto files and libraries are working as expected though. What needs to be done on client side to handle grpcs . 

Previously I had made secure:true and added certificates over normal GRPC call and it had worked fine. Is that all required or GRPCS is a different ball game all together.

**Comment by MrMage** [comment]
Sorry, but what exactly is GRPCS? I only know gRPC over SSL, which is what `secure: true` does.
