### ISSUE TITLE
(Tensorflow) Service layer class generation - Method can not be declared public because its result uses an internal type.

### ISSUE THREAD

**Issue by johndpope** [grpc/grpc-swift#47]
May need to tweak the stencil class to fix this. 

https://github.com/nubbel/swift-tensorflow/issues/7

seems like a rename from 
 public func receive() throws -> Tensorflow_Event
fixes things. 
 func receive() throws -> Tensorflow_Event

**Comment by timburks** [comment]
I believe this is related to a permission change in the code generated by swift-proto.

Please try generating your proto structs with the following `protoc` options: 

    protoc <your proto files> \
        --swift_out=. \
        --swift_opt=Visibility=Public \
        --plugin=<pat to protoc-gen-swift>`

That may cause `protoc-gen-swift` to make the necessary types public.

More details are [here](https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md#generation-option-visibility---visibility-of-generated-types).
