### ISSUE TITLE
Capital letters in Metadata

### ISSUE THREAD

**Issue by isaac-weisberg** [grpc/grpc-swift#474]
Can I have capital letters in Metadata's keys?
I am creating the Metadata as such

```swift
let headers = ["Client-Version": "ios \(appVersion).\(appBuild)"]
let metadata = try Metadata(headers)
```

And when I call the async method on a service generated by the `SwiftGRPC` it results in
```
E0527 18:49:09.173287000 7358073664 call.cc:895] validate_metadata: 
{"created":"@1558972149.173199000","description":"Illegal header key",
"file":"/Users/some-usr/Projects/some-proj/Pods/gRPC-Core/src/core/lib/surface/validate_metadata.cc",
"file_line":43,"offset":0,
"raw_bytes":"41 75 74 68 6f 72 69 7a 61 74 69 6f 6e 'Authorization'"}
```
However if I set the key lowercase, as in `authorization`, it works out.

I also do get `SwiftGRPC.CallError` code 10.

Could this have anything to do with configuration of the service and its channels arguments?

**Comment by isaac-weisberg** [comment]
I do believe this is similar to https://github.com/jaegertracing/jaeger-client-python/issues/120

**Comment by isaac-weisberg** [comment]
ugh you know what, I'll just cope, I guess.

**Comment by MrMage** [comment]
According to the HTTP2 spec:

> A request or response containing uppercase header field names MUST be treated as malformed

**Comment by isaac-weisberg** [comment]
Totally. Anyone interested can find proof here https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2
