### ISSUE TITLE
Xcode11Beta:  Import of C++ module 'BoringSSL' appears within extern "C" language linkage specification

### ISSUE THREAD

**Issue by fabstu** [grpc/grpc-swift#478]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

Hello! I wanted to see whether grpc-swift works with the spm integrated inside Xcode11 Beta. I created a new project via File -> New -> Swift Package and added `SwiftGRPC` as a dependency. Is it supposed to work differently or an Xcode11Beta bug?

```
Import of C++ module 'BoringSSL' appears within extern "C" language linkage specification
```

Here is an image of it:
https://imgur.com/a/fKcuk65

My `Package.swift` is:

```
// swift-tools-version:5.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SwiftPackageTryout",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "SwiftPackageTryoutLibrary",
            targets: ["SwiftPackageTryout"]),
    ],
    dependencies: [
        .package(url: "https://github.com/grpc/grpc-swift", .branch("master")),
        .package(url: "https://github.com/apple/swift-protobuf", .branch("master")),
        // Dependencies declare other packages that this package depends on.
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "SwiftPackageTryout",
            dependencies: ["SwiftGRPC"]),
        .testTarget(
            name: "SwiftPackageTryoutTests",
            dependencies: ["SwiftPackageTryout", "SwiftGRPC"]),
    ]
)
```

##### Complete output when running grpc-swift, including the stack trace and command used

<details>
  <pre>Fails at build already</pre>
</details>

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   10.15 Beta (19A471t)                                                      |
| Swift Version                 |   Swift 5.1                                                       |
| Xcode Version                 |  Version 11.0 beta (11M336w)                                                       |
| gRPC-Swift Version            |   master                                                       |
| gRPC-Swift Version            |   master                                                       |
| protoc Version                |   -                                                       |
| protoc-gen-swift Version      |   -                                                       |
| protoc-gen-swiftgrpc Version  |   -                                                       |
  </pre>
</details>

**Comment by glbrntt** [comment]
For what’s it’s worth, you shouldn’t need to make a Package.swift to use a dependency, you should be able to just add the dependency on SwiftGRPC in Xcode (see: https://developer.apple.com/videos/play/wwdc2019/408/). (Your approach should still work, however.)

My hunch (i’m not at my Mac so I can’t verify this right now) is that the real issue here lies with SwiftGRPC since it gets its header paths for BoringSSL from an argument specified in the Makefile and not from Package.swift. If this is the case then running ‘swift build’ on SwiftGRPC should give the same error. 

Fortunately SwiftPM introduced support for specifying header paths in Swift 5 so it should be a pretty straightforward fix.

**Comment by cielo** [comment]
Unrelated to the OP's original question.. but I have a question to @fabstu

If you are using Xcode 11, are you also using macOS 10.15? If so, were you able to compile `.proto` source files with `protoc-gen-swiftgrpc`?

**Comment by MrMage** [comment]
> Unrelated to the OP's original question.. but I have a question to @fabstu
> 
> If you are using Xcode 11, are you also using macOS 10.15? If so, were you able to compile `.proto` source files with `protoc-gen-swiftgrpc`?

Please open a separate issue for that.

**Comment by cielo** [comment]
> > Unrelated to the OP's original question.. but I have a question to @fabstu
> > If you are using Xcode 11, are you also using macOS 10.15? If so, were you able to compile `.proto` source files with `protoc-gen-swiftgrpc`?
> 
> Please open a separate issue for that.

I am Sorry about that. I created a separate issue. https://github.com/grpc/grpc-swift/issues/478

**Comment by fabstu** [comment]
A little update: `swift test` works correctly, just generation (`swift package generate-xcodeproj`) and direct inclusion via `Swift packages/Add Package Dependency ..` both throw still the same errors afterwards.

I added the errors to a [Gist](https://gist.github.com/fabstu/b345f28f22812261f9c7e4244bcce502).

**Comment by Krivoblotsky** [comment]
Hey, @glbrntt.
Are there any suggestions how to use SwiftGRPC with SPM integrated within Xcode 11?
I have exactly same experience and errors @fabstu mentioned above. 
Any help or advice will be very appreciated 🙏

**Comment by saudeoncovr** [comment]
I was able to resolve the above issues by making sure my Swift toolchain was on `5.1` via Xcode. If, for some reason, it was set back to the previous version of the toolchain (usually it is when installing new betas) and it caught me out for a bit.

<img width="912" alt="Screen Shot 2019-07-27 at 1 37 13 PM" src="https://user-images.githubusercontent.com/51338401/61999348-d1da8f00-b073-11e9-9362-e1b2c72c9cc9.png">

**Comment by glbrntt** [comment]
> Hey, @glbrntt.
> Are there any suggestions how to use SwiftGRPC with SPM integrated within Xcode 11?
> I have exactly same experience and errors @fabstu mentioned above.
> Any help or advice will be very appreciated 🙏

It won't work out-of-the-box with `master` since it requires some additional flags as per: https://github.com/grpc/grpc-swift/blob/8eac348c1108e8acbe70e24970dc1fd3c384aad6/Makefile#L5

It _might_ be possible to set these manually in Xcode.

For the `nio` branch this should work out-of-the-box.

**Comment by nakkht** [comment]
@glbrntt do you have any ideas on how it would be possible to pass those additional flags while using SPM with SwiftGrpc on master branch?

**Comment by glbrntt** [comment]
@nakkht are you trying to use it with Xcode? 

Assuming you are, then `Package.swift` will need to be updated to use `swift-tools-version:5.0` and include the flags from the `Makefile`. I think you'll need to update the `CgRPC` target to include `cxxSettings` and `linkerSettings`. 

The relevant SwiftPM documentation is here: https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md#methods-5

**Comment by nakkht** [comment]
@glbrntt yes, Xcode 11 stable (to be specific). 
Wasn't aware of SPM documentation, this is gold. Thank you very much!
By the way, does it mean that cxxSettings and linkerSettings can be passed through my project's Package.swift file or is it only possible through SwiftGrpc Package.swift file?

**Comment by glbrntt** [comment]
@nakkht no problem!

I would assume only via swift-grpc's `Package.swift`.

Would you mind filing a PR for this? We should be able to maintain the current `Package.swift` as `Package@swift-4.2.swift` for those who don't/can't use Swift 5. @MrMage does this sound reasonable?

**Comment by nakkht** [comment]
@glbrntt I don't really follow:
> We should be able to maintain the current Package.swift as Package@swift-4.2.swift for those who don't/can't use Swift 5.

Does this mean there can be several different Package.swift files with different suffix, like @swift-4.2? Also, I thought swift 5 and 4.2 are compatible or is there actual SPM difference based on Swift version?

**Comment by glbrntt** [comment]
> @glbrntt I don't really follow:
> 
> > We should be able to maintain the current Package.swift as [Package@swift-4.2.swift](mailto:Package@swift-4.2.swift) for those who don't/can't use Swift 5.
> 
> Does this mean there can be several different Package.swift files with different suffix, like @swift-4.2? 

That's correct. If you have a swift 4.2 compiler it will used `Package@swift-4.2.swift`, if you have a 5.0/5.1 compiler it will use `Package.swift`. 

There's more documentation here: https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#version-specific-manifest-selection

> Also, I thought swift 5 and 4.2 are compatible or is there actual SPM difference based on Swift version?

Target specific build settings in SPM came with Swift 5 (https://github.com/apple/swift-evolution/blob/master/proposals/0238-package-manager-build-settings.md).

**Comment by nakkht** [comment]
@glbrntt 
> Would you mind filing a PR for this? 
Sure, is it fine forking the repository and creating PR upstream to this repo?
Also, I assume I have to sign [Contributor Licence Agreement](https://identity.linuxfoundation.org/projects/cncf)?

**Comment by glbrntt** [comment]
> @glbrntt
> 
> > Would you mind filing a PR for this?
> 
> Sure, is it fine forking the repository and creating PR upstream to this repo?
> Also, I assume I have to sign [Contributor Licence Agreement](https://identity.linuxfoundation.org/projects/cncf)?

Absolutely! And yes you do :)

**Comment by nakkht** [comment]
@glbrntt 
I would appreciate your input on this: so even if I update CgRPC target description to this:
`.target(name: "CgRPC",
            dependencies: cGRPCDependencies,
            cxxSettings: [.headerSearchPath("../BoringSSL/include",
                                            .when(platforms: [.iOS, .macOS, .tvOS, .watchOS]))],
            linkerSettings: [.linkedLibrary("z")]),`

The same error is still present. 
Swift tool version at the top of the file is set to: `// swift-tools-version:5.1`. 
I've also tried using same values with cSettings rather cxxSettings, but it had no effect.
Do you have any ideas on what is missing? Should BoringSSL contain any linkerSettings/cxxsettings?

**Comment by glbrntt** [comment]
@nakkht hmm I'm really not sure, sorry! I'll try to find time to look into this today.

**Comment by nakkht** [comment]
@glbrntt 
After looking at [SPM C language targets](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#creating-c-language-targets
) it appears that "headerSearchPath" might not event be necessary as C language targets are already supported. From error logs it appears that correct BoringSSL location is used.
My questions: isn't BoringSSL written mostly in C? If so, any ideas why Xcode tells that Boring SSL is C++ module? Can we make it a "C module"?
Was trying to compare build logs between "swift build --verbose -Xcc -ISources/BoringSSL/include -Xlinker -lz" and Xcode log, but was overwhelmed by amount of flags.

**Comment by glbrntt** [comment]
@nakkht sorry for the slow response

> After looking at [SPM C language targets](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#creating-c-language-targets) it appears that "headerSearchPath" might not event be necessary as C language targets are already supported. From error logs it appears that correct BoringSSL location is used.

Great, I assumed it was necessary from the flags passed from make!

> My questions: isn't BoringSSL written mostly in C? If so, any ideas why Xcode tells that Boring SSL is C++ module? Can we make it a "C module"?
> Was trying to compare build logs between "swift build --verbose -Xcc -ISources/BoringSSL/include -Xlinker -lz" and Xcode log, but was overwhelmed by amount of flags.

I'm not sure what to suggest here. The furthest I got was a generated .xcodeproj (without additional flags) which worked fine. I didn't manage to get it working directly with Xcode though.

**Comment by KosukeOhmura** [comment]
I tried to use grpc-swift with SPM integrated within Xcode 11, then I faced the same error. Also I cloned `master` branch and just run `make`, got the same. Changing of `swift-tools-version` on top of Package.swift to `5.1` had no effects for me.

Are there any suggestions to build(with SPM or manually) successfully?

my environment:
- macOS Catalina 10.15.1
- Xcode Version 11.2.1 (11B500)

Thanks,

**Comment by MrMage** [comment]
I am still on Xcode 10.2, so can't comment on this. But did you trying the version of gRPC Swift from the `nio` branch instead?

**Comment by KosukeOhmura** [comment]
@MrMage No, I haven't tried `nio` branch. I want to use gRPC Swift for my existing product, but README says `nio` branch is not production ready yet. That is why I want to build `v0.x` branch. Do you know when will the `nio` be get ready?

**Comment by MrMage** [comment]
Sorry, I will need to update the readme, it has conflicting information. The line at the top of the readme is correct:

> We strongly suggest that new projects use the re-implementation from the nio branch which we consider to be production ready.

**Comment by masatomizuta** [comment]
I managed to compile the master branch with Xcode11 by passing ```-Wno-module-import-in-extern-c``` flag to change the error to the warning. For iOS, the SwiftNIO's products and targets had to be removed for https://github.com/grpc/grpc-swift/issues/542.

```swift
    .target(name: "CgRPC",
            dependencies: cGRPCDependencies,
            cSettings: [
              .headerSearchPath("../BoringSSL/include", .when(platforms: [.iOS, .macOS, .tvOS, .watchOS])),
              .unsafeFlags(["-Wno-module-import-in-extern-c"])],
            linkerSettings: [.linkedLibrary("z")]),
```

**Comment by nakkht** [comment]
@masatomizuta this sounds very promising. Great work!
Will try compiling and checking if it works on runtime.

**Comment by nakkht** [comment]
It seems to work pretty well!
Steps to setup:
- Sync to master branch of grpc-swift
- Replace Package.swift contents with the following:

`// swift-tools-version:5.1

import PackageDescription
import Foundation

var packageDependencies: [Package.Dependency] = [
  .package(url: "https://github.com/apple/swift-protobuf.git", .upToNextMajor(from: "1.5.0")),
  .package(url: "https://github.com/kylef/Commander.git", .upToNextMinor(from: "0.8.0"))
]

var cGRPCDependencies: [Target.Dependency] = []

#if os(Linux)
let isLinux = true
#else
let isLinux = false
#endif

if isLinux || ProcessInfo.processInfo.environment.keys.contains("GRPC_USE_OPENSSL") {
  packageDependencies.append(.package(url: "https://github.com/apple/swift-nio-ssl-support.git", from: "1.0.0"))
} else {
  cGRPCDependencies.append("BoringSSL")
}

let package = Package(
    name: "SwiftGRPC",
    products: [
        .library(name: "SwiftGRPC", targets: ["SwiftGRPC"])
    ],
    dependencies: packageDependencies,
    targets: [
        .target(name: "SwiftGRPC",
                dependencies: ["CgRPC", "SwiftProtobuf"]),
        .target(name: "CgRPC",
                dependencies: cGRPCDependencies,
                cSettings: [
                    .headerSearchPath("../BoringSSL/include", .when(platforms: [.iOS, .macOS, .tvOS, .watchOS])),
                    .unsafeFlags(["-Wno-module-import-in-extern-c"])],
                linkerSettings: [.linkedLibrary("z")]),
        .target(name: "protoc-gen-swiftgrpc",
                dependencies: [
                    "SwiftProtobuf",
                    "SwiftProtobufPluginLibrary",
                    "protoc-gen-swift"]),
        .target(name: "BoringSSL"),
        .testTarget(name: "SwiftGRPCTests", dependencies: ["SwiftGRPC"]),
    ],
    swiftLanguageVersions: [.v4, .v4_2, .version("5")],
    cLanguageStandard: .gnu11,
    cxxLanguageStandard: .cxx11)
`
- Try building
- Success!

Right after committed and referenced local grpc-swift repo with the commit to my project. 
Worked right out of the box (after removing carthage integration)

Is it something we could have with version 0.10.1?

**Comment by glbrntt** [comment]
@fabstu this should now work thanks to @nakkht 👏

**Comment by ibaho** [comment]
I have same problem 
SwiftGRPC 0.9.2 
<img width="554" alt="Снимок экрана 2020-12-17 в 15 04 50" src="https://user-images.githubusercontent.com/43005267/102485916-4d7a1900-4079-11eb-885f-ba413f487281.png">

/Library/Developer/Xcode/DerivedData/MultiScreen-faamzirxtndxisdzlocxxkkbsvia/SourcePackages/checkouts/grpc-swift/Sources/CgRPC/include/src/core/tsi/ssl/session_cache/ssl_session.h:29:1: Import of C++ module 'BoringSSL' appears within extern "C" language linkage specification

Can you help me, please?
