### ISSUE TITLE
Releasing for Carthage

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc-swift#495]
Just realized that the latest releases don't work for me with Carthage, because they point to the system nghttp2 library (and I happen to have a newer version on my macos system).

What I realized was that if I run `make project-carthage` while nghttp2 is installed on my system, then SwiftPM will use that. If I don't have it on my system, it will pull it, which is what I believe we want.

So I realize it is a bit annoying, but I think that the person releasing should uninstall nghttp2 from their system before running `make project-carthage`. 

This said, I have read comments saying that nghttp2 would go away with the new NIOGRPC implementation, if I understood correctly, meaning that this "trick" won't be needed anymore after nghttp2 is removed from the dependencies (but probably may still apply to other deps later).

Does that make sense?

**Comment by weissi** [comment]
> This said, I have read comments saying that nghttp2 would go away with the new NIOGRPC implementation, if I understood correctly, meaning that this "trick" won't be needed anymore after nghttp2 is removed from the dependencies (but probably may still apply to other deps later).

NIO person here with little knowledge about grpc-swift but I can confirm one thing: With the NIO based gRPC implementation you will no longer depend on `nghttp` or `libssl` (OpenSSL) from your system anymore.

**Comment by MrMage** [comment]
All the targets provided by the Carthage project should actually be buildable without any copy of `libnghttp2`; this was added in https://github.com/grpc/grpc-swift/pull/450.

**Comment by JonasVautherin** [comment]
Oh, I guess #450 solved it, sorry for the duplicate!

Thanks!
