### ISSUE TITLE
Trying to connect an http1.x server

### ISSUE THREAD

**Issue by dekpient** [grpc/grpc-swift#497]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Since Friday, we've been getting connection failures _everytime_ when creating Google Speech recognise stream. Nothing has changed in our iOS app (SwiftGRPC 0.8.0 with Carthage), so I tried upgrading to master and now I get a more descriptive result – `Trying to connect an http1.x server`.

What does it mean in the context of SwiftGRPC? Based on our tests, the Objective-C and Java clients still work. What can we do to fix it?

This is an important production issue for us as all our users are affected by this.

#### Question Description
The error on 0.8.0 was `The operation couldn’t be completed. (SwiftGRPC.CallError error 1.)` with an unknown cause. There was nothing more useful so we decided to try master.
Upgrading to master didn't make it work, but the error is now `Trying to connect an http1.x server`. I'm not sure if they are related.

I have a reproducible demo on my fork of Google's sample project here https://github.com/dekpient/ios-docs-samples/tree/swift-grpc/speech/Swift/Speech-gRPC-Streaming

It has the latest proto files and running on SwiftGRPC master. Just run Carthage bootstrap, replace the API key and it should be good to run.

Logs from the demo app when running the speech streaming recognise API.

```
hardware sample rate = 44100.0, using specified rate = 16000
Streaming
Result code: unavailable
Result description: successful, status unavailable: Trying to connect an http1.x server
trailingMetadata: [:]
Metadata: nil
Status message: Trying to connect an http1.x server
Obj description: successful, status unavailable: Trying to connect an http1.x server
trailingMetadata: [:]
=============================
```

I also tried long running recognise speech API and got the same error.

```
hardware sample rate = 44100.0, using specified rate = 16000
2019-07-02 22:14:39.326906+1200 Speech[11777:36618418] 317:  ca_debug_string: inPropertyData == NULL
Recording finished with success: true
Recording finished: true
------- Long Running Recognize --------
Sending audio data
nil
successful, status unavailable: Trying to connect an http1.x server
initialMetadata: [:]
trailingMetadata: [:]
No OP
```

Looking forward to some insights on this.
Cheers!

**Comment by MrMage** [comment]
I am seeing the same `Trying to connect an http1.x server` errors when trying to connect to Google Stackdriver Trace. Unfortunately, I don't know what is causing these issues and do not have time to investigate right now.

**Comment by MrMage** [comment]
If you want to investigate the issue, you could set the `GRPC_VERBOSITY ` environment variable to `debug` and also set `GRPC_TRACE` as mentioned in https://github.com/grpc/grpc/blob/master/doc/environment_variables.md, then compare that to the same output with the Objective-C client. Any findings you get would be appreciated.

**Comment by dekpient** [comment]
I came across those variables. Correct me if I'm wrong but I don't think runtime environment variables is a thing for iOS app.

**Comment by MrMage** [comment]
You can set environment variables in your Xcode scheme when running the app from Xcode.

**Comment by dekpient** [comment]
"Expected SETTINGS frame as the first frame, got frame type 80" from this line seems interesting

```
I0703 00:12:41.649181000 123145377214464 chttp2_transport.cc:2603]     ipv4:216.58.199.74:443: Complete BDP ping err={"created":"@1562069561.637939000","description":"Failed parsing HTTP/2","file":"/Users/dekpient/Documents/Code/ios-docs-samples/speech/Swift/Speech-gRPC-Streaming/Carthage/Checkouts/grpc-swift/Sources/CgRPC/src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2523,"referenced_errors":[{"created":"@1562069561.637660000","description":"Expected SETTINGS frame as the first frame, got frame type 80","file":"/Users/dekpient/Documents/Code/ios-docs-samples/speech/Swift/Speech-gRPC-Streaming/Carthage/Checkouts/grpc-swift/Sources/CgRPC/src/core/ext/transport/chttp2/transport/parsing.cc","file_line":261},{"created":"@1562069561.637744000","description":"Trying to connect an http1.x server","file":"/Users/dekpient/Documents/Code/ios-docs-samples/speech/Swift/Speech-gRPC-Streaming/Carthage/Checkouts/grpc-swift/Sources/CgRPC/src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2479,"grpc_status":14,"http_status":400}]}
```

[trace.log](https://github.com/grpc/grpc-swift/files/3350003/trace.log)

**Comment by KosukeOhmura** [comment]
Facing same issue since last Friday. With not Google Speech but our gRPC server on GCP using L7 load balancer. Our Java client and Golang client still work well. I've got same log as @dekpient 's one.

**Comment by KosukeOhmura** [comment]
It is getting better but still unstable. I sometimes get the same error but I sometimes get successful response. Probably Google is doing something and it affects clients using grpc-swift.

**Comment by MrMage** [comment]
Same here; the issues have suddenly stopped on July 2nd, 9AM UTC for me.

**Comment by dekpient** [comment]
What worries me is the fact that it only affects SwiftGRPC but not other clients. Assuming the server-side changes were not targeting a specific client, what makes this less resilient and more fragile than other clients?

**Comment by MrMage** [comment]
No idea; we are using the same gRPC-Core library as e.g. the Objective-C client, after all.

**Comment by KyoheiG3** [comment]
Although I got the same issue on master branch with Carthage, it didn't appear when installed using cocoapods.

**Comment by timburks** [comment]
@dekpient I haven't tested your sample yet, but I just put a similar sample in PR#516 that seems to be working correctly for me.

**Comment by MrMage** [comment]
I think this was an intermittent error with some of Google's gRPC services. Closing this; let me know if you continue to encounter issues.
