### ISSUE TITLE
Define 1.0 release requirements.

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-swift#5]
Presumably:
1. Pass interoperability tests.
2. Implement service code generation.
3. Support both Darwin (Apple platforms) and Linux.

Also (suggested in comments):
4. Explicit gRPC and Swift Proto version dependencies.
5. Surface stability.
6. Continuous testing set up, with high code coverage.
7. Manual testing in a device under changing networking conditions (e.g. with an app like this one).
8. At least 1 app successfully launched?
9. Samples and tutorials.

Please comment with additional requirements.

**Comment by johndpope** [comment]
Hi Tim, 

Digging through you readme for server side swift. 
You may want to open a swift PR against grpc from your branch to master?
https://github.com/timburks/grpc
that way your swift code could stay up to date.

**Comment by jcanizales** [comment]
These are more process-like things:

- Surface stability.
- Continuous testing set up, with high code coverage.
- Manual testing in a device under changing networking conditions (e.g. with an app like [this one](https://github.com/grpc/grpc/tree/master/src/objective-c/tests/Connectivity)).
- At least 1 app successfully launched?
- Samples and tutorials.

**Comment by johndpope** [comment]
Wish list

How bout a Hello world connection to tensor flow? 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/distributed/index.md

**Comment by mrdonley** [comment]
It looks like the swift-protobuf project has been refactored and now grpc-swift is incompatible with versions of swift-protobuf newer than 0.9.24. I think a good 1.0 goal would be to adopt the swift-protobuf changes into the grpc-swift project so it can be used with newer versions of swift-protobuf.

**Comment by timburks** [comment]
Moving this to [the wiki](https://github.com/grpc/grpc-swift/wiki/1.0-Release-Requirements).

**Comment by MrMage** [comment]
It might make sense to also include some points from https://github.com/grpc/grpc-swift/issues/189 on the Wiki page. Happy to elaborate more if some points in the issue are unclear.
