### ISSUE TITLE
Swift Compiler error: "Method cannot be declared public"

### ISSUE THREAD

**Issue by macwish** [grpc/grpc-swift#50]
Swift Compiler error: Method cannot be declared public because its parameter uses an internal type.

-----------------------------

file: Models.proto
![models proto](https://cloud.githubusercontent.com/assets/1431946/25551780/ddd13ab2-2cbc-11e7-81a0-7dbcd38c95d1.png)

file: RPC.proto
![rpc proto](https://cloud.githubusercontent.com/assets/1431946/25551785/eb2dcacc-2cbc-11e7-89b7-bfe9fb37215e.png)

```
protoc --proto_path=. --swift_out=./swift/ Models.proto
protoc --proto_path=. --swiftgrpc_out=./swift/ RPC.proto
```

```
ls -l ./swift/
  >> RPC.client.pb.swift
  >> RPC.server.pb.swift
  >> Models.pb.swift
```

file: RPC.client.pb.swift
![rpc client pb swift](https://cloud.githubusercontent.com/assets/1431946/25551786/f3303354-2cbc-11e7-9add-26b5623a51dd.png)

file: Models.pb.swift
![models pb swift](https://cloud.githubusercontent.com/assets/1431946/25551788/f93a3592-2cbc-11e7-81fc-a67ab517b3a4.png)

**Comment by timburks** [comment]
Hi, this is probably a result of a permission change in the code generated by swift-proto.

Please try generating your proto structs with the following `protoc` options: 

    protoc <your proto files> \
        --swift_out=. \
        --swift_opt=Visibility=Public \
        --plugin=<path to protoc-gen-swift>`

That may cause `protoc-gen-swift` to make the necessary types public.

More details are [here](https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md#generation-option-visibility---visibility-of-generated-types).

This seems to be a common problem, so I'll also add a note about it in the README.

**Comment by macwish** [comment]
Thanks @timburks . 
With these two arguments "--swift_opt" and "--plugin", the issue gone.

```
$
$ protoc --proto_path=. --swift_out=./swift/ --swift_opt=Visibility=Public --plugin=./protoc-gen-swift Models.proto
$ 
```
