### ISSUE TITLE
0.9.1 fails to build with Carthage

### ISSUE THREAD

**Issue by JonasVautherin** [grpc/grpc-swift#507]
With the following Cartfile:

```
github "grpc/grpc-swift" == 0.9.1
```

Running:

```sh
$ carthage bootstrap --platform iOS
```

I get errors with the SwiftPM dependencies in `.build/checkouts`. The same kind that was supposed to be fixed by @byuarus with `fix-carthage-paths.rb`.

@MrMage: does it work for you?

**Comment by MrMage** [comment]
@JonasVautherin thank you for the report! My assumption had been that we did not have any changes that would have mandated a rebuild of the Carthage project for 0.9.1, so I skipped that test. I did this on the `rebuild-carthage` branch now; could you please check if `github "grpc/grpc-swift" "rebuild-carthage"` works better for you? If yes, I'll file a PR and issue another tag.

**Comment by davidvartan** [comment]
Don't know if it's related, but I'm seeing this (including with the rebuild-carthage branch):

```
Fatal error: 'try!' expression unexpectedly raised an error: Basic.GraphError.unexpectedCycle: file /Library/Caches/com.apple.xbs/Sources/swiftpm/swiftpm-14679.1/Sources/Workspace/Workspace.swift, line 987
/var/folders/nt/3bzvq029501fk4ny60gg9g5r0000gn/T/SchemeScriptAction-chCUZs: line 2: 50498 Illegal instruction: 4  swift package resolve
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from fix-carthage-paths.rb:1:in `<main>'
```

**Comment by JonasVautherin** [comment]
I don't have the same error as @davidvartan, but more "error: Build input files cannot be found: '/path/to/grpc-swift/.build/checkouts/swift-protobuf.git--<tag>/blah'".

Even with `rebuild-carthage`, somehow. Maybe the carthage patch files need to be updated for Swift 5...

@MrMage so `carthage bootstrap --platform iOS` works for you with `github "grpc/grpc-swift" "rebuild-carthage"`, right?

**Comment by MrMage** [comment]
FYI, I ran `make project-carthage` with Swift 4.2 for the `rebuild-carthage` branch.

@JonasVautherin @davidvartan could you guys maybe try fixing the Carthage projects locally for yourself and file a PR if you succeed?

**Comment by JonasVautherin** [comment]
> I ran make project-carthage with Swift 4.2

Somehow I was assuming you were on Swift 5, sorry :sweat_smile:. So I am on Swift 5, and I tried to run the following Cartfile after I ran `make project-carthage` myself:

```
github "jonasvautherin/grpc-swift" "my-0.9.1"
```

@MrMage can you try to build with that one, to see if that is backward compatible (I expect it is not)?

Assuming that it is not, I can maintain a fork where I just run `make project-carthage` from Swift 5 until grpc-swift moves to Swift 5. An alternative would be for grpc-swift to make separate releases for Swift 4 and 5 (e.g. `0.9.1-swift5`), but that seems annoying and I guess everybody will move to Swift 5 in the near future.

**Comment by MrMage** [comment]
Yup, that one fails on Swift 4.2 (see below).

Can anyone still on Swift 4.2 confirm that `github "grpc/grpc-swift" "rebuild-carthage"` works at least for them?

```
$ carthage bootstrap --platform iOS
*** No Cartfile.resolved found, updating dependencies
*** Fetching grpc-swift
*** Checking out grpc-swift at "44344a32399df09f55b27682d6ae84f668ec8684"
*** xcodebuild output can be found in /var/folders/2m/1rc0qztj6qnff96q9bsvrnsm0000gn/T/carthage-xcodebuild.Auo8nh.log
*** Building scheme "SwiftGRPC-Package" in SwiftGRPC-Carthage.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/daniel/Desktop/carthage-test/Carthage/Checkouts/grpc-swift/SwiftGRPC-Carthage.xcodeproj -scheme SwiftGRPC-Package -configuration Release -derivedDataPath /Users/daniel/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/grpc-swift/44344a32399df09f55b27682d6ae84f668ec8684 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2m/1rc0qztj6qnff96q9bsvrnsm0000gn/T/grpc-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/daniel/Desktop/carthage-test/Carthage/Checkouts/grpc-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2m/1rc0qztj6qnff96q9bsvrnsm0000gn/T/carthage-xcodebuild.Auo8nh.log
```

**Comment by JonasVautherin** [comment]
> Can anyone still on Swift 4.2 confirm that `github "grpc/grpc-swift" "rebuild-carthage"` works at least for them?

@byuarus or @douglaswsilva: would you mind trying to run that, and possibly `github "grpc/grpc-swift" == 0.9.1`? Just checking if `carthage bootstrap --platform iOS` fails or not, so that we can move on with this issue :blush:.

**Comment by byuarus** [comment]
@JonasVautherin I've checked `carthage bootstrap --platform iOS` for `github "grpc/grpc-swift" == 0.9.1` with XCode 10.1 and it works. 👍

**Comment by JonasVautherin** [comment]
Thanks a lot @byuarus!

@MrMage: so it seems like it is related to the Swift version. Closing this for now, I'll maintain my own fork for Swift 5 until everybody moves there.

**Comment by MrMage** [comment]
@JonasVautherin @byuarus I am planning to cut a 0.10 release soon, which updates CgRPC to 1.23.0. Would you two mind trying if Carthage still works with the current `master` branch before running that release? Not sure if @tsabirgaliev ran `make project-carthage` with Swift 4.2 or 5, but I think it would be time to switch the Carthage project to Swift 5 now, anyway.

**Comment by tsabirgaliev** [comment]
> Not sure if @tsabirgaliev ran make project-carthage with Swift 4.2 or 5, but I think it would be time to switch the Carthage project to Swift 5 now, anyway.

````
$ swift --version
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.7.0
````

**Comment by sibe7691** [comment]
@JonasVautherin Great work man. Is the "My-0.9.1" branch merged into this repo or does it still not support Swift 5?

**Comment by JonasVautherin** [comment]
@sibe7691: it is not merged, no. And not maintained (latest release here is 0.11.0). Right now I am waiting for SwiftPM 5.3 to bring binary dependencies, so that I can move to SPM and drop Carthage support. I tried very hard, but I could not find a way to make Carthage work with SPM in grpc-swift :confused:.
