### ISSUE TITLE
tiny defect - filename generated for service seem to overwrite each other

### ISSUE THREAD

**Issue by johndpope** [grpc/grpc-swift#51]
this maybe one of those obscure bugs that doesn't cause any problems for some time....
but thought I'd capture it.

I grabbed this proto file
https://github.com/tensorflow/serving/blob/c948af73268c8071fed17a6edcf95b34e40583f2/tensorflow_serving/example/inception_inference.proto

threw it into my tensorflow serving folder

for some reason - the name over lapped with the primary tensorflow serving 
tensorflow.serving.server.pb.swift

so the inception class over wrote the file generated from 
 tensorflow_serving/apis/prediction_service.proto

probably not a bug / but interested to dive deeper into file naming.

**Comment by dcow** [comment]
I think `grpc-swift` should probably support path/naming like `swift-protobuf` does.

**Comment by timburks** [comment]
I pulled some code from swift-protobuf into [0.3.1](https://github.com/grpc/grpc-swift/releases/tag/0.3.1) which allows protoc-gen-swiftgrpc to use the same path-oriented naming that protoco-gen-swift uses by default.
