### ISSUE TITLE
generated files import SwiftGRPC even when depending on SwiftGRPCNIO

### ISSUE THREAD

**Issue by avnerbarr** [grpc/grpc-swift#515]
I'm able to generate the swift GRPC server/client/proto files 
I'd like to use the SwiftGRPCNIO version , but my generated files have these dependencies and I am not clear on how to resolve this

```
import Dispatch
import Foundation
import SwiftGRPC <<<<<<<<<<<< I want to be able to use SwiftGRPCNIO
import SwiftProtobuf
```

Should I just go ahead and replace the generated import?

**Comment by MrMage** [comment]
You should check out the `nio` branch of this project before building the protoc plugin. Also, make sure to use the `nio` branch as the package dependency as well.

**Comment by avnerbarr** [comment]
is there a way to flag the protoc compiler to use the NIO libs?

**Comment by MrMage** [comment]
The NIO implementation in the `master` branch is very outdated; you should use the `nio` branch instead. What are your reasons against doing that?

**Comment by MrMage** [comment]
Closing this pending future responses. You can add a `NIO=true` flag to the `protoc` compiler on `master`, but you should _really_ use the `nio` branch instead.
