### ISSUE TITLE
NIO client declares itself as `.ready` too soon

### ISSUE THREAD

**Issue by glbrntt** [grpc/grpc-swift#519]
### Issue Description

Issue #517 indicated that we can have an infinite reconnection loop if the connection closes immediately after the channel becomes active. We should transition the connection state to `.ready` after we have received e.g. the initial settings frame on the connection.

**Comment by MrMage** [comment]
Should be fixed in https://github.com/grpc/grpc-swift/releases/tag/1.0.0-alpha.2.
