### ISSUE TITLE
SSL Authentication for Google (already have OAauth2 token)

### ISSUE THREAD

**Issue by vanshg** [grpc/grpc-swift#52]
I'm trying to securely connect to a Google API. I have already obtained my OAuth2 token, and am including it in the request by doing `service?.metadata = Metadata(["authorization" : token])`. However, it wasn't working so upon looking at the gRPC website (which doesn't seem to have any documentation about the Swift library, probably because this is experimental right now), I found this in Node.js:

```
var GoogleAuth = require('google-auth-library'); // from https://www.npmjs.com/package/google-auth-library
...
var ssl_creds = grpc.Credentials.createSsl(root_certs); // load_certs typically loads a CA roots file
var scope = 'https://www.googleapis.com/auth/grpc-testing';
(new GoogleAuth()).getApplicationDefault(function(err, auth) {
  if (auth.createScopeRequired()) {
    auth = auth.createScoped(scope);
  }
  var call_creds = grpc.credentials.createFromGoogleCredential(auth);
  var combined_creds = grpc.credentials.combineChannelCredentials(ssl_creds, call_creds);
  var stub = new helloworld.Greeter('greeter.googleapis.com', combined_credentials);
});
```

I'm assuming I want to do something similar, but I can't seem to find any Credential class in the Swift gRPC library, let alone something along the lines of `createFromGoogleCredential`. Is there something that I'm missing, or is it just not implemented yet?

**Comment by vanshg** [comment]
Also just to note, I have tried sending the OAuth token as both "Bearer \(token)" and just the token itself

**Comment by timburks** [comment]
Hi @vanshg, for the time being, please review this [sample code for calling the Google Datastore API](https://github.com/grpc/grpc-swift/tree/master/Examples/Datastore/PackageManager). 

It reads an included "roots.pem" file to load a root certificate and sends the OAuth token in a metadata item named "authorization".

Please let me know if that approach works for you or not.

**Comment by vanshg** [comment]
The `roots.pem` in that sample seemed to work, even though other root certificates I had previously tried did not. Thanks!
