### ISSUE TITLE
Archive failed in Xcode 11 ("nio" package added) with arithmetic operations overflow.

### ISSUE THREAD

**Issue by Krivoblotsky** [grpc/grpc-swift#534]
### New Issue Checklist

- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
I have added Swift Package ("nio" branch) with Xcode 11 intergated SPM. Once I do "archive" with selected iOS-platform, the build fails with "arithmetic operations overflow" in `GRPCTimeoutUnit`.
I suppose this is 32-bit related issue because by default Xcode adds armv7 architecture to the build. 
I'm on 10.15, but I get same results on 10.14.
Archive is ok for macOS builds (i386/x86_64)

<img width="807" alt="Screen Shot 2019-07-29 at 9 59 04 PM" src="https://user-images.githubusercontent.com/1411778/62075371-8f6caa00-b24d-11e9-9381-b2fd888c92a9.png">

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   10.15                                                       |
| Swift Version                 |   5.1                                                       |
| Xcode Version                 |   11.0 beta (11M336w)                                                       |
  </pre>
</details>

**Comment by weissi** [comment]
oh yes, the type for `asNanoseconds` should be `Int64` not `Int`, or else it won't work on 32bit platforms.

**Comment by Krivoblotsky** [comment]
Thanks. I’ll open a PR.

**Comment by Krivoblotsky** [comment]
Please, see the PR https://github.com/grpc/grpc-swift/pull/535

**Comment by MrMage** [comment]
Should be fixed by #535.
