### ISSUE TITLE
How to make self signed certificate work with ios

### ISSUE THREAD

**Issue by anuranBarman** [grpc/grpc-swift#536]
I am trying to get data from my gRPC Java server which has been issued a Let's Encrypt self signed certificate. I am trying to use that for mutual TLS but I am getting error in handshake saying 
```
E0731 15:41:27.621060000 6188068864 ssl_transport_security.cc:1239]    Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```

The way I am using this is like below:

```swift
if let filepath = Bundle.main.path(forResource: "st", ofType: "crt") {
            do {
                let contents = try String(contentsOfFile: filepath)
                let arguments: [Channel.Argument] = [.sslTargetNameOverride("staging.mydomain.com")]
                self.client = Com_Domain_Data_EnergyUsageServiceServiceClient(address: "staging.mydomain.com:6001", certificates: contents,arguments: arguments)
            } catch {
                
            }
} else {
            
}
```

How can I make it work? There is issue #285 saying the error, but I could not understand what it said.

**Comment by MrMage** [comment]
What if you do not pass in any certificates and no arguments, either?

**Comment by anuranBarman** [comment]
same problem occurs in that too. Though this is not totally called mutual TLS I suppose as Server will only accept client request with this certificate and client will blindly say dont validate the CA of server. In the generated Client code I don't see anything which can blindly trust the CA. Do I have to do anything with channel?

**Comment by anuranBarman** [comment]
@MrMage is there workaround for this? We are stuck for this.

**Comment by MrMage** [comment]
No need to spam three different threads, please refrain from doing that.

Our tests demonstrate how to do use self-signed certificates, as well as mutual auth: https://github.com/grpc/grpc-swift/blob/8eac348c1108e8acbe70e24970dc1fd3c384aad6/Tests/SwiftGRPCTests/EchoTests.swift#L40
https://github.com/grpc/grpc-swift/blob/8eac348c1108e8acbe70e24970dc1fd3c384aad6/Tests/SwiftGRPCTests/BasicEchoTestCase.swift#L63
https://github.com/grpc/grpc-swift/blob/8eac348c1108e8acbe70e24970dc1fd3c384aad6/Tests/SwiftGRPCTests/BasicEchoTestCase.swift#L70

However, note that **Let's Encrypt certificates are not self-signed and not meant for doing client auth**.

With the little details you are providing and the confusion between Let's Encrypt, self-signed certs, and mutual TLS auth, I don't think anyone would be able (let alone motivated) to help you.

**Comment by anuranBarman** [comment]
That's a mistake from my side. The certificate I am giving is **not** Let's encrypt. there was some confusion with that. The certificate I am giving is openssl self signed certificate.

**Comment by MrMage** [comment]
Here's the script we use to generate the self-signed certificates: https://github.com/grpc/grpc-swift/blob/master/scripts/makecert

And I already linked to the test code that sets up a server and a client for mutual authentication.

I would start with using _exactly these test certificates_ from our repository first, as they are proven to work. Afterwards, try switching them out for your certs. Maybe even try using your own certificates in these tests and see if the tests still work. (You will need to change the SSL hostname override, of course.)

If that doesn't work, there is something wrong with your certificate setup, but you will need to figure that out yourself.

**Comment by anuranBarman** [comment]
I am already doing things as it is mentioned in the test cases. I am checking my certificate setup for confirmation.

**Comment by anuranBarman** [comment]
what is rootCerts in [this](https://github.com/grpc/grpc-swift/blob/8eac348c1108e8acbe70e24970dc1fd3c384aad6/Tests/SwiftGRPCTests/BasicEchoTestCase.swift#L57)?

**Comment by anuranBarman** [comment]
what I have understood after long hours of going through this repo code, that you need to do the following to make a client
```
self.client = Com_Data_EnergyUsageServiceServiceClient(address: "staging.domain.com:6001", certificates: contents,arguments: arguments)
```
and the `certificated` part in the function has to be root certificate of the CA which I assume is the ca.crt file generated from the `makecert` script you talked about. and I am certainly sure that I am passing the same in here also. But I am still getting the same error.

I downloaded the example EchoXcode project and tried that. First of all did not understand what was happening. After going through the code it seemed that on app launch it opens both secured and unsecured connection. when you toggle the TLS checkbox and provide the localhost:8443 as the server address it is supposed to work. then I wrote the message in the message box. It was giving me error of ERROR VERSION NUMBER first then SAME ERROR AS MINE. I did not change anything and used your `ssl.crt` file only. That was supposed to work you said. What can be wrong in this?

**Comment by anuranBarman** [comment]
![Screenshot of the log from the example project EchoXcode](https://imgur.com/a/GOIdGUA "Screenshot of the log from the example project EchoXcode")

**Comment by MrMage** [comment]
I said that the tests should work, not the EchoXcode example project. Use that as a starting point.

**Comment by anuranBarman** [comment]
Certifiy is correct as java client is able to communicate with the root
certificate.
