### ISSUE TITLE
README doesn't mention the required plugin

### ISSUE THREAD

**Issue by mtitolo** [grpc/grpc-swift#54]
Nothing in the README mentions the fact that the plugin needs to be compiled. The README only mentions the regular swift-protobuf plugin, not the gRPC specific one.

The README should have step by step instructions for getting started that list out all of the required steps.

**Comment by timburks** [comment]
Thanks for pointing this out. A first attempt to address this is in [this commit](https://github.com/grpc/grpc-swift/commit/a8a2c1892b80f961dc2225befccfd1da329a0d4b).

**Comment by mtitolo** [comment]
Much better 👍
