### ISSUE TITLE
SwiftGrpc crashes on iOS simulator

### ISSUE THREAD

**Issue by nakkht** [grpc/grpc-swift#542]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
Trying to run app dependent on SwiftGrpc 0.9.1 on simulator causes app to crash mid launch with the message
![see attached image](https://user-images.githubusercontent.com/2426759/62471303-b3c00d80-b79c-11e9-9030-00e3850fb57b.png)

SwiftGrpc project was integrated manually using instructions in Readme file on master branch. (0.9.1)

In addition, during the build the following warnings are shown:
```
URGENT: building for iOS Simulator simulator, but linking against dylib (/usr/local/Cellar/nghttp2/1.39.1/lib/libnghttp2.dylib) built for macOS. Note: This will be an error in the future.
```
This appears for all 3 frameworks: BoringSSL, CgGRPC and SwiftGrpc

Building and running the same app on physical device works without any issues.

libnghttp2 was installed using homebrew prior executing ```make && make project```.
nghttp nghttp2/1.39.1 

I have found the way to [generate nghttp2](https://github.com/jasonacox/Build-OpenSSL-cURL) for iOS, including simulator, but have no clue on how to link it to be used by SwiftGrpc.

Expected behaviour is that SwiftGrpc should run on physical and simulator.

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   10.14.6                                                       |
| Swift Version                 |   5                                                       |
| Xcode Version                 |   10.3                                                       |
| gRPC-Swift Version            |   0.9.1                                                       |
| protoc Version                |   3.7.1                                                       |
| protoc-gen-swift Version      |   1.6.0                                                      |
  </pre>
</details>

**Comment by glbrntt** [comment]
`master` contains an early version of the `nio` branch using Swift NIO 1.0 which uses `nghttp2`. Presumably you're after the implementation which wraps the gRPC C library here in which case one workaround for now is to remove all targets containing `SwiftGRPCNIO` from Package.swift and any dependencies.

**Comment by glbrntt** [comment]
@MrMage are you still using the NIO 1 version?

**Comment by nakkht** [comment]
@glbrntt that actually might have been the answer. I was after CgRPC but was still including NIO which is not being used. I just tried getting rid of NIO-related packages and it seemed to work, but I'll have to double check it tomorrow.
So from what I understand, CgRPC itself being phased out by Swift NIO within v1.0.0 of SwiftGRPC?

**Comment by MrMage** [comment]
> @MrMage are you still using the NIO 1 version?

Yes, I'm still on the NIO1 version, but only on the server.



> @glbrntt that actually might have been the answer. I was after CgRPC but was still including NIO which is not being used. I just tried getting rid of NIO-related packages and it seemed to work, but I'll have to double check it tomorrow.

Try using the Carthage project on the 0.9 branch; it should have all NIO dependencies stripped out.



> So from what I understand, CgRPC itself being phased out by Swift NIO within v1.0.0 of SwiftGRPC?

Yes, see e.g. https://github.com/grpc/grpc-swift/issues/526.

**Comment by nakkht** [comment]
I've stripped version on a different test project and it worked on simulator as well. 
@MrMage I did't want to resolve to using dependency management as of yet, but I took a look at ```patch-carthage-project.rb``` on what is happening. I'll be keeping eye on #526 

Since this was solved, I'll be closing the issue.
Thanks for the help!
