### ISSUE TITLE
Why is public visibility required for the source generated from the protos?

### ISSUE THREAD

**Issue by thomasvl** [grpc/grpc-swift#55]
The _README.md_ documents the need for `--swift_opt=Visibility=Public` as:

> The `--swift_opt` flag passes an option to `protoc-gen-swift` that makes message classes public, which is necessary to use them with gRPC.

But that explication doesn't make sense.  If the _.pb.swift_ files and grpc files are compiled in the same module, then the default internal visibility would be fine.

The real reason one might need public visibility is if the _.pb.swift_ files (and grpc ones) will be placed in a different module from the code that uses them.

**Comment by timburks** [comment]
The generated gRPC methods are public, and since they use structs generated by swift-proto, those structs need to also be public.

Since the generated gRPC methods might be used in a separate module, "public" access seemed like a safer choice. 

Would you recommend that gRPC also support --swift_opt and make that user-controllable?

**Comment by thomasvl** [comment]
It all depends on how developers want to use it, if the intent was to have grpc as an impl detail within some other library, forcing public can seem debatable.  It also could get in the way of WMO since it might force the compiler/optimizer to keep things exposed incase an external caller is added.

**Comment by timburks** [comment]
Thanks - a simpler alternative would be to completely remove the "public" access specifiers and wait for someone to request a Visibility option.

**Comment by thomasvl** [comment]
>Thanks - a simpler alternative would be to completely remove the "public" access specifiers and wait for someone to request a Visibility option.

Yup, because of the Well Known Types (and exposing the PluginLibrary), we had to add the option to SwiftProtobuf.

**Comment by timburks** [comment]
OK, out they go.
