### ISSUE TITLE
GRPC connecting over Tor

### ISSUE THREAD

**Issue by JimmyMow** [grpc/grpc-swift#550]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
Hi. I am trying to allow users of my application to connect to a server over Tor. From my quick research, it seems that the problem is that the `iCepa Tor` framework is using `NSURLSession` API and this library is using `CFStream` API. I was wondering if anyone has connected over Tor using this library successfully or if anyone had any helpful pointers for me in trying to accomplish this. Would be much appreciated!

**Comment by MrMage** [comment]
I don't know of anyone who has tried this, but I would suspect that you would indeed need to mess with the connection on a fairly low level.

We also offer the `nio` branch which re-implements gRPC on top of SwiftNIO, it _might_ be easier to patch Tor support into that one by e.g. adding channel handlers for it.
