### ISSUE TITLE
Use a bi-directional stream to receive continuous data updates

### ISSUE THREAD

**Issue by phlippieb** [grpc/grpc-swift#552]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

How would I write my code so that I could use a bi-di stream to receive continuous updates from server, possibly over the app's entire life-cycle?

#### Question Description

My app is currently using the Objective-C gRPC library. Since my app is written in Swift (and I'm experiencing some difficult-to-resolve crashes in the ObjC code), I'm investigating the feasibility of switching over to this library.

A core concept in my existing app is to use bi-directional streams to maintain the app's data. Such a stream fulfils multiple purposes. Let's use "open chats" as an example:

- The app displays a list of open chats
- This list is bound to persisted data in Realm
- When the user views this list, the app opens a bi-di stream to server
- The app then sends a 'sync request' to server
- Server responds with the data that the app needs for the local data to be "in sync", and the list is updated
- The user can then mark a chat as read; this request is sent as an update on the same stream
- The result of the update is received on the same stream and results in the local data being updated, and the list being updated as a result
- The user can receive a new chat. If this happens, server sends an update on the same stream, which also results in the required updates

Crucially, the last example is essentially an unsolicited update -- the app did not request anything, but was continuously listening for such an update from server.

Using the ObjC library, this sort of continuous listening is supported very naturally. A bi-di stream is created by passing a request writer (object) and a response handler (closure). The response handler is always invoked when an update is received, so the client doesn't care whether the update resulted from a request or not.

Contrarily, using this Swift library, it seems like each update must be anticipated by calling `receive`. Once an update has been received, the same closure passed to handle the result of `receive` will never be executed again. For example, in the following code block, the handler will only be called once; subsequent updates received from server will be ignored.

```
let client = ChatsServiceClient(address: "bla")
let call = try client.chatGroups(completion: nil)

try call.receive { result in
   // Handle result...
   // (This will only get called once)
}
```

So in order to continue receiving updates, we might do this:

```
let client = ChatsServiceClient(address: "bla")
let call = try client.chatGroups(completion: nil)

// Start listening for updates
DispatchQueue.global(qos: .default).async {
   while true {
      let response = try rpc.receive()
      // Handle response...
   }
}
```

This would just keep on listening forever, so we'd probably just keep looping until some flag indicates that we're done, but that's basically the idea.

Is this how you would envision such a use case being implemented, or is there a more built-in way to keep listening on a bi-di stream until we want to stop?

**Comment by MrMage** [comment]
> Is this how you would envision such a use case being implemented, or is there a more built-in way to keep listening on a bi-di stream until we want to stop?

I am afraid this clunky approach is indeed the way to handle bi-di streams in the current version of the gRPC library. The only improvement might be to use the async variant of `receive` that takes a completion handler, to avoid indefinitely blocking a thread just waiting on the `receive` call.

Even better: use the `nio` branch, which is a complete reimplementation on top of SwiftNIO. That branch will also call the same callback for you upon every event, without the need to call `receive` repeatedly. This will become the new `master` branch soon, so if you are just starting out, it makes sense to start with that one right away.

**Comment by phlippieb** [comment]
Cool, thanks for answering!

Switching to Swift would constitute a massive re-write for us, so I'm not diving into it just yet -- only poking around to see what it would look like. I'll definitely give the NIO implementation a try then.
