### ISSUE TITLE
Docker documentation is stale and inconsistent

### ISSUE THREAD

**Issue by Kirow** [grpc/grpc-swift#574]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Running `protoc` from docker container.

#### Question Description
I've tried to follow [this guide](https://github.com/grpc/grpc-swift/blob/master/DOCKER.md), but it seems that image is outdated (swift version I guess).

Then I tried to build image from [Dockerfile](https://github.com/grpc/grpc-swift/blob/master/Docker/Dockerfile), but it also has missing dependencies (libz, curl, libssl). I've made some changes to let it work.

```bash
ENV PROTOC_VERSION=3.9.1 #updated

RUN apt-get -q update \
    && apt-get install curl \ #new
    && apt-get install libz-dev \ #new
    && apt-get install libssl-dev \ #new
    && apt-get -q install -y unzip libnghttp2-dev \
    && rm -r /var/lib/apt/lists/*
```

Please correct  this.

**Comment by glbrntt** [comment]
@Kirow if the above changes to the Dockerfile fix this would you mind submitting a PR?

**Comment by Kirow** [comment]
@glbrntt ok, I will do PR for Dockerfile. But I'm not sure what to do with [DOCKER.md](https://github.com/grpc/grpc-swift/blob/master/DOCKER.md).  How about to remove it and then update [README.md](https://github.com/grpc/grpc-swift/blob/master/README.md) to reference [Docker/README.md](https://github.com/grpc/grpc-swift/blob/master/Docker/README.md)?

**Comment by glbrntt** [comment]
@Kirow apologies for the delay. 

If I remember correctly the Dockerfile just installs the `protoc` plugins, [DOCKER.md](DOCKER.md) leads you to a built version of `grpc-swift` to play around with. I think we should also update the instructions in [DOCKER.md](DOCKER.md) to include the missing packages.

**Comment by Kirow** [comment]
@glbrntt 

There are few places in the docs about the same:
1) [DOCKER.md](https://github.com/grpc/grpc-swift/blob/master/DOCKER.md) - says to `pull swiftdocker/swift` from [Docker Hub](https://hub.docker.com/r/swiftdocker/swift/dockerfile) and then install `protoc` and swift plugin manually. But `swiftdocker/swift` is outdated (used swift 3.1.1) and will not compile `grpc-swift` master branch.
2) [LINUX.md](https://github.com/grpc/grpc-swift/blob/master/LINUX.md) - says to start with `ubuntu:16.04` then repeat commands from `swiftdocker/swift` and `DOCKER.md` manually. Instructions seems valid and should work, but requires manual work.
3) [Docker/README.md](https://github.com/grpc/grpc-swift/blob/master/Docker/README.md) - says to build image from [Dockerfile](https://github.com/grpc/grpc-swift/blob/master/Docker/Dockerfile). But it was missing few dependencies that I've added in #575.

I'm complaining about duplicated instructions. I think that `DOCKER.md` and `LINUX.md` should be removed. `Docker/Dockerfile` should be updated and finally fix all related references in `README.md`. 
If my logic is correct - I can add these changes to my pull request. 
Also project maintainer may upload `Docker/Dockerfile` to Docker Hub (instead of `swiftdocker/swift` suggested in `DOCKER.md`). 

And if I start writing about cleanup, there is one more thing that made me sad. Before committing any changes I've checked [CONTRIBUTING.md](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md). It says that I need to sign [CLA](https://identity.linuxfoundation.org/projects/cncf) (HelloSign). Ok, I did it...but when I made pull request - bot sent me to sign it again, but to [another service](https://api.lfcla.com/v2/repository-provider/github/sign/1656153/68841963/575) (EasyCLA). I did not sign CLA before, but it seems that there is some mismatch between `CONTRIBUTING.md` and configured workflow.

**Comment by glbrntt** [comment]
> I'm complaining about duplicated instructions. 

It's pretty bad -- sorry about that!

> I think that `DOCKER.md` and `LINUX.md` should be removed. 

I don't agree on this one: I think _one_ of them should be removed. There should still be either instructions (or another Dockerfile) so that users can build/run/develop `grpc-swift` using Docker. This should be separate from the existing Dockerfile which provides just the `protoc` plugin. 

> `Docker/Dockerfile` should be updated

Agreed.

> and finally fix all related references in `README.md`.

100% agree.


> And if I start writing about cleanup, there is one more thing that made me sad. Before committing any changes I've checked [CONTRIBUTING.md](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md). It says that I need to sign [CLA](https://identity.linuxfoundation.org/projects/cncf) (HelloSign). Ok, I did it...but when I made pull request - bot sent me to sign it again, but to [another service](https://api.lfcla.com/v2/repository-provider/github/sign/1656153/68841963/575) (EasyCLA). I did not sign CLA before, but it seems that there is some mismatch between `CONTRIBUTING.md` and configured workflow.

Sorry about that, I think that change has trickled down from `grpc/grpc` but their [CONTRIBUTING.md](https://github.com/grpc/grpc/blob/master/CONTRIBUTING.md) also hasn't been updated. I would _assume_ [EasyCLA](https://api.lfcla.com/v2/repository-provider/github/sign/1656153/68841963/575) is the correct way to sign it. @timburks do you know any more about this?

**Comment by Kirow** [comment]
> I don't agree on this one: I think one of them should be removed. There should still be either instructions (or another Dockerfile) so that users can build/run/develop grpc-swift using Docker. This should be separate from the existing Dockerfile which provides just the protoc plugin.

`Docker/Dockerfile` has all need dependencies for development. In fact it pulls master branch to build plugin from swift sources.

**Comment by glbrntt** [comment]
That's right, but then it removes the `grpc-swift` directory after copying the `protoc` plugin.

**Comment by glbrntt** [comment]
Thanks for fixing the `Dockerfile` @Kirow! Repurposing this issue to fix the documentation inconsistency.

In summary:
- The `Dockerfile` with the `protoc` plugin is now up-to-date #575
- One of DOCKER.md or LINUX.md needs to be removed and the other updated (or another Dockerfile needs to be created).
- README.md needs to point to the fixed instructions.
