### ISSUE TITLE
Does gRPC work on a macOS app?

### ISSUE THREAD

**Issue by PierBover** [grpc/grpc-swift#577]
The docs mention iOS but it's not clear whether gRPC-Swift also works on macOS or in which versions.

**Comment by MrMage** [comment]
Yes, macOS is fully supported.

**Comment by PierBover** [comment]
Thanks @MrMage . Which macOS versions do you support?

**Comment by MrMage** [comment]
Should be the same versions as listed at https://github.com/grpc/grpc/tree/master/src/objective-c.
