### ISSUE TITLE
License statement in READM.md seems incorrect

### ISSUE THREAD

**Issue by mit-mit** [grpc/grpc-swift#58]
README.md says 'grpc-swift is released under the same license as gRPC, repeated in LICENSE.', however https://github.com/grpc/grpc-swift/blob/master/LICENSE is Apache 2.0 and https://github.com/grpc/grpc/blob/master/LICENSE is BSD.

**Comment by mehrdada** [comment]
The license in grpc/grpc repo is since updated to Apache 2.0, which is the new license for grpc/grpc-* repos
