### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by shial4** [grpc/grpc-swift#583]
### Question Checklist
When can we expect swift 5 support?
The pod still specify swift 4.2

**Comment by MrMage** [comment]
You can use the library just fine from your Swift 5 code even with the Pod specifying Swift 4.2.

**Comment by shial4** [comment]
@MrMage I know I can do it. That wasn't my question...

**Comment by MrMage** [comment]
What is your question, then?

**Comment by shial4** [comment]
> What is your question, then?
> […](#)

When can we expect swift 5 support?

**Comment by MrMage** [comment]
It's still not clear what you mean with that, and why you need it.

**Comment by nakkht** [comment]
@shial4 now I am curious as well. As far as I know Swift 5.0 is compatible with 4, 4.1, 4.2, thus if your project is using Swift 5, you should be able use SwiftGrpc without any problems. Do you by any chance mean syntax relates changes or ABI Stability?

**Comment by shial4** [comment]
What is hard to understand here?
Question is simple. **When can we expect swift 5 support?**
Why can't you provide that answer? 

I am not asking how to use it with lower version of swift nor complaining about it. 
I simply want to know when can we expect swift 5 support. However, you are trying to change this topic into some compatibility stuff.

**Comment by MrMage** [comment]
What do you mean with "Swift 5 support"? I do not understand the question, please explain it.

**Comment by shial4** [comment]
By support I mean, migration. When are you planning to move out from older swift version?

**Comment by MrMage** [comment]
Why should we do that? What advantage would it bring?
