### ISSUE TITLE
Product names are not prefixed with GRPC

### ISSUE THREAD

**Issue by kevints** [grpc/grpc-swift#591]
The `nio` branch defines several executable products that are not prefixed in any way. These share a global products namespace, so they should probably be prefixed.

Package.swift contains these products:
```
    .library(name: "GRPC", targets: ["GRPC"]),
    .executable(name: "InteroperabilityTestRunner", targets: ["GRPCInteroperabilityTests"]),
    .executable(name: "ConnectionBackoffInteropTestRunner", targets: ["GRPCConnectionBackoffInteropTest"]),
    .executable(name: "PerformanceTestRunner", targets: ["GRPCPerformanceTests"]),
    .executable(name: "Echo", targets: ["Echo"]),
    .executable(name: "protoc-gen-grpc-swift", targets: ["protoc-gen-grpc-swift"]),
```

While `protoc-gen-grpc-swift` seems reasonably named, the others are generically-named and could conflict with products from other packages. For a more detailed exploration of this issue, see https://forums.swift.org/t/namespacing-of-packages-modules-especially-regarding-swiftnio/24726.

**Comment by weissi** [comment]
+1 here, we had a similar issue in Vapor's nio-websocket-client: https://github.com/vapor/nio-websocket-client/issues/8
