### ISSUE TITLE
gRPC on Docker ubuntu 14.04

### ISSUE THREAD

**Issue by johndpope** [grpc/grpc-swift#6]
I followed  your steps
https://github.com/grpc/grpc-swift/tree/master/Packages

I ran into make not found
 apt-get install make 
resolved this

but then ran into
make: no_c_compiler: Command not found

This doesn't seem to be working 
https://gist.githubusercontent.com/johndpope/503029706ed56d5375d1e9469f0135d4/raw/61c9adb603758e1a0ef2318809a431d6e4bd50df/installCGPC.sh

I get

```

include/grpc++/ext/reflection.pb.h:51:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
include/grpc++/ext/reflection.pb.h:52:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
include/grpc++/ext/reflection.pb.h:53:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
make: *** [/grpc/objs/opt/src/cpp/ext/proto_server_reflection.o] Error 1


```

when I use git cloning https://github.com/grpc/grpc.git it does compile successfully.
https://gist.github.com/johndpope/503029706ed56d5375d1e9469f0135d4/9d3c2126e8ff5c004f9cb00ee326b9b8aa9eb119

**IMPORTANT**
@timburks you need to open pr to master to grpc or fetch latest changes from master to your branch to resolve out of date protoc files.

NB some dependencies are missing from prescribed docker file.
I'm using this one for dev.
https://gist.github.com/johndpope/01a74ffb93921df48e334097117be1b3

This line has trouble / saying no git tag exists.
cd gRPC; make; cd .. 

<img width="1076" alt="screen shot 2016-10-25 at 23 30 39" src="https://cloud.githubusercontent.com/assets/289994/19712342/f22391e8-9b0a-11e6-9199-b1c623eb7e8b.png">

**Comment by timburks** [comment]
Thanks for checking this. I let this slide after adding GCD dependencies but will retest the linux build setup ASAP (hoping today).

**Comment by johndpope** [comment]
no worries. 
You may consider - once the docker image is bedded down - to submit to 
https://hub.docker.com/

My dockerfile simply subclasses 
FROM swiftdocker/swift

rather than fetching swift etc.

**Comment by johndpope** [comment]
@timburks - if you get a chance to look at this any time soon - it would be most appreciated.

**Comment by timburks** [comment]
Hi John, thanks for your patience. I started this yesterday and worked through a bunch of problems. I expect to have something ready to commit late today based on Ubuntu 16.04.

**Comment by timburks** [comment]
I've updated and verified the instructions in Packages/README.md using Ubuntu 16.04.
The "Client" and "Server" build, but don't handle threading well and may have other problems.

Please close this if you're able to build on Ubuntu.

**Comment by timburks** [comment]
I cleaned up the package Makefiles somewhat so that now CgRPC is directly built by "swift build". On Linux you'll need to set LD_LIBRARY_PATH to point to a directory containing libCgRPC.so before running the binaries.
