### ISSUE TITLE
Is it possible update the Metadata values?

### ISSUE THREAD

**Issue by IrvingMg** [grpc/grpc-swift#603]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

 Is it possible update the Metadata values?

#### Question Description

I need to authenticate my swift client using JWT. If I insert the token into metadata in this way, the authentication works.

```
stub.metadata.add(key: "authorization", value: "bearer \(jwt)")
```
However, I need to update the value for the `authorization` key because the JWT expires after a request is made it but if I use the `add` method, when I make a second request (and I update the JWT) the server get the first JWT inserted in the metadata (which is expired) and the client can't be authenticated. I think that is because after the first request, the metadata has multiple values for the `authorization` key, right?

In Java I avoid this problem creating new Metadata and insert it in the stub, in this way

```
Metadata header = new Metadata();
Metadata.Key<String> key =
                Metadata.Key.of("authorization", Metadata.ASCII_STRING_MARSHALLER);
header.put(key, "bearer " + jwt);

stub = MetadataUtils.attachHeaders(stub, header);
```
Is there a way to create new Metadatata and insert it to the stub or a way to update the metadata?

**Comment by MrMage** [comment]
I simply reset the entire `metadata` field:

```swift
var headers: [String: String] = [...]
stub.metadata = try! Metadata(headers)
```

or

```swift
var headers: [String: String] = stub.metadata.dictionaryRepresentation
headers["authorization"] = <new JWT>
stub.metadata = try! Metadata(headers)
```

**Comment by IrvingMg** [comment]
> I simply reset the entire `metadata` field:
> 
> ```swift
> var headers: [String: String] = [...]
> stub.metadata = try! Metadata(headers)
> ```
> 
> or
> 
> ```swift
> var headers: [String: String] = stub.metadata.dictionaryRepresentation
> headers["authorization"] = <new JWT>
> stub.metadata = try! Metadata(headers)
> ```

Great! It works perfectly. Thanks for answering!
