### ISSUE TITLE
EXC_BAD_INSTRUCTION in GRPC.ClientResponseChannelHandler.performTimeout

### ISSUE THREAD

**Issue by ydnar** [grpc/grpc-swift#605]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

grpc-swift on the `nio` branch crashes with an `EXC_BAD_INSTRUCTION` when built with Xcode 11.2 beta, on both iOS 13.1 and 13.2.

`Thread 1: EXC_BAD_INSTRUCTION (code=1, subcode=0x8)` in `GRPC.ClientResponseChannelHandler.performTimeout`

##### Complete output when running grpc-swift, including the stack trace and command used

<details>
  <pre>2019-10-07T14:29:27-0700 info: making EventLoopGroup for best network preference
2019-10-07T14:29:27-0700 info: 'best' NetworkImplementation is .networkFramework
2019-10-07T14:29:27-0700 info: connection_id=8A5017CD-126D-4C09-9149-3E4A38A00F69 attempting to connect to hostAndPort("host.example.com", 8001)
2019-10-07T14:29:27-0700 info: connectivity state change: idle to connecting
2019-10-07T14:29:27-0700 info: making client bootstrap with event loop group of type NIOTSEventLoop
2019-10-07T14:29:27-0700 info: connection_id=8A5017CD-126D-4C09-9149-3E4A38A00F69 setting connect timeout to 20.0 seconds
2019-10-07T14:29:27-0700 info: request_id=99A22272-CD84-4C62-9CE2-9FFE9DCB7AEC making bidirectional streaming call to '/p1.RelayAPI/RelayStream', request type: P1RelayRequest, response type: P1RelayResponse
(lldb) </pre>

<pre>
#0	0x00000001030062c0 in method descriptor for ClientResponseChannelHandler.performTimeout(error:) ()
#1	0x000000010242bbcc in BaseClientCall.init(connection:responseHandler:requestHandler:logger:) at .../Library/Developer/Xcode/DerivedData/p1-dcjnosvwtrwjseaarvxizkaclqbh/SourcePackages/checkouts/grpc-swift/Sources/GRPC/ClientCalls/BaseClientCall.swift:115
#2	0x000000010242f768 in BidirectionalStreamingCall.init(connection:path:callOptions:errorDelegate:handler:) at .../Library/Developer/Xcode/DerivedData/p1-dcjnosvwtrwjseaarvxizkaclqbh/SourcePackages/checkouts/grpc-swift/Sources/GRPC/ClientCalls/BidirectionalStreamingCall.swift:60
#3	0x000000010242ed28 in BidirectionalStreamingCall.__allocating_init(connection:path:callOptions:errorDelegate:handler:) ()
#4	0x000000010245c3b8 in GRPCClient.makeBidirectionalStreamingCall<A, B>(path:callOptions:requestType:responseType:handler:) at .../Library/Developer/Xcode/DerivedData/p1-dcjnosvwtrwjseaarvxizkaclqbh/SourcePackages/checkouts/grpc-swift/Sources/GRPC/GRPCClient.swift:79
#5	0x00000001022641a0 in P1RelayAPIServiceClient.relayStream(callOptions:handler:) at .../packages/Protos/Sources/Protos/relay.grpc.swift:59
</pre>
</details>

### Environment

Key                           | Value                                                         
------------------- | -------------------
OS Version | 13.2 beta (17B5059g)
Swift Version | 5.1.1
Xcode Version | 11.2 beta (11B41)
gRPC-Swift Version | `nio` @ 38db19abbc
`protoc` Version |   3.10.0
`protoc-gen-swift` Version | 1.7.0
`protoc-gen-swiftgrpc` Version | `nio` @ 38db19abbc

**Comment by glbrntt** [comment]
Thanks for filing this @ydnar, it appears to be a Swift bug: https://bugs.swift.org/projects/SR/issues/SR-11564

**Comment by glbrntt** [comment]
@ydnar just merged a workaround.

**Comment by ydnar** [comment]
@glbrntt thank you!

**Comment by ydnar** [comment]
Now it blows up in Swift-NIO `handlerAdded`:

```swift
    fileprivate func invokeHandlerAdded() throws {
        self.eventLoop.assertInEventLoop()

        handler.handlerAdded(context: self)
    }
```

Whack-a-mole!

**Comment by glbrntt** [comment]
> Whack-a-mole!

D'oh. I guess you'll either have to wait for another beta or use Xcode 11.1 for the time being.

**Comment by ydnar** [comment]
I forked this repo last night and added a few more default implementations, but wasn’t successful stopping the crash. Guess we’ll wait!

**Comment by ydnar** [comment]
@glbrntt still crashing with Xcode 11.2 final on iOS 13.2.

**Comment by tcldr** [comment]
I'm the reporter SR-11564 (https://bugs.swift.org/browse/SR-11564). I'm following your issue here as I was hoping your workaround may lead to my workaround.

Unfortunately yes, it still seems at large in Xcode 11.2 GM. I've tweeted one of the Swift core team and he thinks it could be a linker bug with `ld -r` related to SwiftPM. Apparently turning on whole module optimisation may solve problem but I'm yet to have any luck. https://twitter.com/jckarter/status/1190030542944841729?s=21

Could you try and see if that works for you?

**Comment by ydnar** [comment]
@tcldr will give whole-module optimization a shot. Be right back…

**Comment by ydnar** [comment]
…and we’re back. Same crash with whole module optimization. I did a clean build to be sure, and got the same result.

**Comment by ydnar** [comment]
Setting `GENERATE_MASTER_OBJECT_FILE` also did not help.

**Comment by tcldr** [comment]
Same thing with my project. He also mentioned it may be specific to SwiftPM. I may try reverting to Carthage tomorrow to see if that brings some temporary relief.

**Comment by ydnar** [comment]
We’re all in on SPM. Most of the business logic of our app and all non-UI code is in internal Swift Packages, and we’ve moved all CocoaPods dependencies to SPM.

**Comment by tcldr** [comment]
Yeah, it's been great... until now! :)

**Comment by ydnar** [comment]
Update: I forked `grpc-swift` and implemented a handful of `override` methods in subclasses of generics similar to this commit: 

https://github.com/grpc/grpc-swift/commit/af247f79c9865cd81ce7856e2be19b8626fceb86

While this fixed the crash (hooray), it doesn’t seem to work. I’m debugging the new failure (unavailable status from a server-streaming GRPC endpoint on our server).

When compiled on Xcode 11.1, this same code works correctly, retrieving data from the streaming endpoint that fails in my fork.

**Comment by ydnar** [comment]
We found a workaround.

Set `DEAD_CODE_STRIPPING = NO` in the app’s target fixes the crash.
