### ISSUE TITLE
Error in Podspec makes 0.9.1 version to fail when installing through cocoapods

### ISSUE THREAD

**Issue by enricmacias** [grpc/grpc-swift#606]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
When installing 0.9.1 version through cocoapods I get the following error:
```
Pre-downloading: `SwiftGRPC` from `https://github.com/grpc/grpc-swift`, tag `0.9.1`
[!] Failed to load 'SwiftGRPC' podspec: 
[!] Invalid `SwiftGRPC.podspec` file: undefined method `swift_versions=' for #<Pod::Specification name="SwiftGRPC">
Did you mean?  swift_version=
               swift_version.

 #  from /var/folders/85/wdy19j6n493g6clply7q02890qjqr5/T/d20191009-11299-y4i277/SwiftGRPC.podspec:35
 #  -------------------------------------------
 #  
 >    s.swift_versions = [4.2]
 #    s.requires_arc = true
 #  -------------------------------------------
```

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   Mojave                                                       |
| Swift Version                 |   4.2                                                       |
| Xcode Version                 |   11.0                                                       |
| gRPC-Swift Version            |   0.9.1                                                       |
| gRPC-Swift Version            |   0.9.1                                                       |
| protoc Version                |   x.x.x                                                       |
| protoc-gen-swift Version      |   x.x.x                                                       |
| protoc-gen-swiftgrpc Version  |   x.x.x                                                       |
  </pre>
</details>

**Comment by MrMage** [comment]
Which version of CocoaPods are you using?

**Comment by enricmacias** [comment]
I'm using 1.5.3

**Comment by enricmacias** [comment]
Ok, I just updated to the new version of cocoapods and is working without a problem.
Thanks!
