### ISSUE TITLE
Archiving for macOS Catalyst fails

### ISSUE THREAD

**Issue by sabiland** [grpc/grpc-swift#607]
Xcode 11.1.
Latest grpc-swift.

`pod 'SwiftGRPC'`

When archiving for macOS Catalyst, I get this error:

`../Pods/gRPC-Core/src/core/tsi/ssl/session_cache/ssl_session.h:29:10: 'openssl_grpc/ssl.h' file not found`

**Comment by MrMage** [comment]
@sabiland is this still affecting you?

**Comment by sabiland** [comment]
It is working OK, after I updated to latest gRpc-swift !
