### ISSUE TITLE
Add support for case iteration in SwiftProtobuf.Enum 

### ISSUE THREAD

**Issue by azr** [grpc/grpc-swift#61]
Howdy ! It's all in the title. 

here are a few options:
 * generating an array with all values
 * add an  `iterateEnum<T: Hashable>(_: T.Type) -> AnyIterator<T> {` that works
 * may be by just storing the highest enumable value somewhere

All from there : https://stackoverflow.com/questions/24007461/how-to-enumerate-an-enum-with-string-type.

Cheers !!

**Comment by timburks** [comment]
Hi, since this is referring to code [SwiftProtobuf/Enum.swift](https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/Enum.swift), I think this should instead be filed as an issue for [apple/swift-protobuf](https://github.com/apple/swift-protobuf). LMK if I've misunderstood.

**Comment by azr** [comment]
Oh I'm so sorry I commented on the wrong repo >.<. Closing the issue then :).
Have a great day !!!
