### ISSUE TITLE
[nio] Provide support for gzip compression?

### ISSUE THREAD

**Issue by be4rd** [grpc/grpc-swift#611]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
The question is whether you plan to implement support for __gzip__ compression for _nio_ at an upcoming release 1.0.0 or nearest future?

#### Question Description
Currently, the *nio* implementation [does not support gzip](https://github.com/grpc/grpc-swift/blob/nio/Sources/GRPC/CompressionMechanism.swift#L64) compression mechanism. For applications with intense usage of networking (such as messenger) the lack of support of this compression mechanism can result in high Network and CPU consumption, as well as higher battery draining on iOS devices. This prevents _nio_ implementation from being ready for production usage for such applications.

### Implementation notes
I have my guesses on where to look at first:
- [ ] Include __gzip__ in [list of supported mechanisms](https://github.com/grpc/grpc-swift/blob/nio/Sources/GRPC/CompressionMechanism.swift#L60)
- [ ] Switch over `compression` in [LengthPrefixedMessageWriter's](https://github.com/grpc/grpc-swift/blob/nio/Sources/GRPC/LengthPrefixedMessageWriter.swift#L42) `write` function and compress data properly according to algorithm
- [ ] Switch over `compression` in [LengthPrefixedMessageReader's](https://github.com/grpc/grpc-swift/blob/nio/Sources/GRPC/LengthPrefixedMessageReader.swift#L166) and unzip data properly, than append unzipped chunk to `ByteBuffer`

If you guys do not plan to do it in any nearest future, I would like to write implementation of __gzip__ support myself, if you'll support me with a little guidance.

**Comment by MrMage** [comment]
I guess we would be open to a patch that adds gzip compression, provided that is:

1. Compatible to gRPC's compression spec,
2. Well-tested (including support for non-compressed messages on the same stream),
3. Easy to maintain,
4. Does not include our dependency surface area too much. (I guess depending on `zlib` should be fine, but would like to hear @glbrntt and @weissi on that.)

You might want to wait until @glbrntt's [refactorings towards a state machine](https://github.com/grpc/grpc-swift/pull/601) are finished, however.

On a more fundamental note, I would expect a messaging application to have very small payloads in general. For these, `gzip` might actually not improve payload sizes that much; did you verify that?

Also, how would _not_ compressing data use _more_ CPU time (besides slightly increasing the amount of data that might need to be copied from the networking stack).

**Comment by be4rd** [comment]
> On a more fundamental note, I would expect a messaging application to have very small payloads in general. For these, `gzip` might actually not improve payload sizes that much; did you verify that?
In our case there are a lot more data sent over gRPC than just text messages - updates on contacts, search results, updating chat list state etc. So the compression is more of a requirement for us. We are sure that using no compression would increase network load significantly, but may check that in profiling using current (non-nio) SwiftGRPC _identity_ vs _gzip_ compression.

> Also, how would _not_ compressing data use _more_ CPU time (besides slightly increasing the amount of data that might need to be copied from the networking stack).
Yep, mistaken here, as when compressing the CPU time only increases for compression and decompression tasks.

But still, sending and receiving larger chunks of data over network increases battery drain and for an app with a lot of users we must ensure good experience and robust performance for all users, even for ones with slow download/upload speed.

**Comment by glbrntt** [comment]
> If you guys do not plan to do it in any nearest future, I would like to write implementation of gzip support myself, if you'll support me with a little guidance.

This is absolutely something we would like, but it isn't a high priority at the moment. More than happy to give you guidance though!

> I guess we would be open to a patch that adds gzip compression, provided that is:
> 
> 1. Compatible to gRPC's compression spec,
> 2. Well-tested (including support for non-compressed messages on the same stream),
> 3. Easy to maintain,
> 4. Does not include our dependency surface area too much. (I guess depending on `zlib` should be fine, but would like to hear @glbrntt and @weissi on that.)
> 
> You might want to wait until @glbrntt's [refactorings towards a state machine](https://github.com/grpc/grpc-swift/pull/601) are finished, however.

+1 on all of this.

Regarding 4.: [NIO Extras](https://github.com/apple/swift-nio-extras) includes Zlib and has recently grown a [NIOHTTPCompression](https://github.com/apple/swift-nio-extras/tree/master/Sources/NIOHTTPCompression) module. I haven't had a chance to look into this yet but I imagine we can make use of it and it's probably the best place to start.

As a footnote: we'd also want to add the [interoperability test cases](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md) for compression. This can be done at a later date though.

**Comment by glbrntt** [comment]
Hey @be4rd, FYI I just pushed up a PR to support gzip and deflate compression on the client. Hoping to work on the server component of this next week 😄

**Comment by be4rd** [comment]
Very nice, thanks 😎
Waiting for an upcoming release to test out and probably migrate...

**Comment by MrMage** [comment]
@glbrntt do we have this on the server now; i.e. can we close this?

**Comment by glbrntt** [comment]
We do, and it's just been tagged in `1.0.0-alpha.10`
