### ISSUE TITLE
swift grpc Watch OS 6

### ISSUE THREAD

**Issue by cfmaley3** [grpc/grpc-swift#614]
I'm using swift grpc in an ios app and i have been asked to migrate the app to watch 0S 6.   Will grpc-swift work on  watch OS 6?

thanks

chris

**Comment by glbrntt** [comment]
For the upcoming 1.0 release we're built on top of SwiftNIO and we have the same platform support as them. [Network.framework supports watchOS 6](https://developer.apple.com/documentation/network) so it _should_ work but as far as I know no one has tried this out yet. I appreciate that's not a hugely helpful answer; I will try to test this out in the next few weeks though.
