### ISSUE TITLE
0.10.0 build fails using Carthage

### ISSUE THREAD

**Issue by nakkht** [grpc/grpc-swift#615]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

Having `github "grpc/grpc-swift" == "0.10.0"` in `Cartfile` and `github "grpc/grpc-swift" "0.10.0"` in `Cartfile.resolved` and building using `carthage bootstrap --platform iOS` fails and yields the following output:

```
*** Checking out grpc-swift at "0.10.0"
*** xcodebuild output can be found in /var/folders/2y/t66flsfj7dg0bb3zym3d807m0000gn/T/carthage-xcodebuild.qb2r03.log
*** Building scheme "SwiftGRPC-Package" in SwiftGRPC-Carthage.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/.../Carthage/Checkouts/grpc-swift/SwiftGRPC-Carthage.xcodeproj -scheme SwiftGRPC-Package -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/grpc-swift/0.10.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2y/t66flsfj7dg0bb3zym3d807m0000gn/T/grpc-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/.../Carthage/Checkouts/grpc-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2y/t66flsfj7dg0bb3zym3d807m0000gn/T/carthage-xcodebuild.qb2r03.log
```
**Expected result:** 0.10.0 version builds using Carthage

##### Complete output when running grpc-swift, including the stack trace and command used

`carthage-xcodebuild.qb2r03.log` contains the following errors:

<details>
  <pre>
Undefined symbols for architecture armv7:
  "_CFStringCreateWithCString", referenced from:
      CFStreamClientConnect(grpc_closure*, grpc_endpoint**, grpc_pollset_set*, grpc_channel_args const*, grpc_resolved_address const*, long long) in tcp_client_cfstream.o
  "_CFWriteStreamOpen", referenced from:
      CFStreamClientConnect(grpc_closure*, grpc_endpoint**, grpc_pollset_set*, grpc_channel_args const*, grpc_resolved_address const*, long long) in tcp_client_cfstream.o
  "_CFErrorGetCode", referenced from:
      grpc_error_create_from_cferror(char const*, int, void*, char const*) in error_cfstream.o
  "_CFErrorGetDomain", referenced from:
      grpc_error_create_from_cferror(char const*, int, void*, char const*) in error_cfstream.o
  "_CFErrorCopyDescription", referenced from:
      grpc_error_create_from_cferror(char const*, int, void*, char const*) in error_cfstream.o
  "_CFStringGetCString", referenced from:
      grpc_error_create_from_cferror(char const*, int, void*, char const*) in error_cfstream.o
  "_CFStreamCreatePairWithSocketToHost", referenced from:
      CFStreamClientConnect(grpc_closure*, grpc_endpoint**, grpc_pollset_set*, grpc_channel_args const*, grpc_resolved_address const*, long long) in tcp_client_cfstream.o
  "_CFReadStreamOpen", referenced from:
      CFStreamClientConnect(grpc_closure*, grpc_endpoint**, grpc_pollset_set*, grpc_channel_args const*, grpc_resolved_address const*, long long) in tcp_client_cfstream.o
  "_CFWriteStreamWrite", referenced from:
      WriteAction(void*, grpc_error*) in endpoint_cfstream.o
  "_CFRetain", referenced from:
      grpc_cfstream_endpoint_create(__CFReadStream*, __CFWriteStream*, char const*, grpc_resource_quota*, CFStreamHandle*) in endpoint_cfstream.o
  "_CFReadStreamRead", referenced from:
      ReadAction(void*, grpc_error*) in endpoint_cfstream.o
  "_CFReadStreamCopyError", referenced from:
      CFStreamHandle::ReadCallback(__CFReadStream*, unsigned long, void*) in cfstream_handle.o
      ReadAction(void*, grpc_error*) in endpoint_cfstream.o
      OnOpen(void*, grpc_error*) in tcp_client_cfstream.o
  "_CFReadStreamClose", referenced from:
      CFStreamShutdown(grpc_endpoint*, grpc_error*) in endpoint_cfstream.o
  "_CFWriteStreamClose", referenced from:
      CFStreamShutdown(grpc_endpoint*, grpc_error*) in endpoint_cfstream.o
  "_CFWriteStreamSetClient", referenced from:
      CFStreamHandle::CFStreamHandle(__CFReadStream*, __CFWriteStream*) in cfstream_handle.o
  "_CFRelease", referenced from:
      CFStreamHandle::ReadCallback(__CFReadStream*, unsigned long, void*) in cfstream_handle.o
      CFStreamHandle::WriteCallback(__CFWriteStream*, unsigned long, void*) in cfstream_handle.o
      CFStreamUnref(CFStreamEndpoint*, char const*, char const*, int) in endpoint_cfstream.o
      ReadAction(void*, grpc_error*) in endpoint_cfstream.o
      WriteAction(void*, grpc_error*) in endpoint_cfstream.o
      grpc_error_create_from_cferror(char const*, int, void*, char const*) in error_cfstream.o
      CFStreamClientConnect(grpc_closure*, grpc_endpoint**, grpc_pollset_set*, grpc_channel_args const*, grpc_resolved_address const*, long long) in tcp_client_cfstream.o
      ...
  "_CFReadStreamSetDispatchQueue", referenced from:
      CFStreamHandle::CFStreamHandle(__CFReadStream*, __CFWriteStream*) in cfstream_handle.o
  "_CFWriteStreamSetDispatchQueue", referenced from:
      CFStreamHandle::CFStreamHandle(__CFReadStream*, __CFWriteStream*) in cfstream_handle.o
  "_CFReadStreamSetClient", referenced from:
      CFStreamHandle::CFStreamHandle(__CFReadStream*, __CFWriteStream*) in cfstream_handle.o
  "_CFWriteStreamCopyError", referenced from:
      CFStreamHandle::WriteCallback(__CFWriteStream*, unsigned long, void*) in cfstream_handle.o
      WriteAction(void*, grpc_error*) in endpoint_cfstream.o
      OnOpen(void*, grpc_error*) in tcp_client_cfstream.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

The following build commands failed:
	SwiftCodeGeneration normal armv7
	SwiftCodeGeneration normal arm64
	Ld /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/11.1_11A1027/grpc-swift/0.10.0/Build/Intermediates.noindex/ArchiveIntermediates/SwiftGRPC-Package/IntermediateBuildFilesPath/SwiftGRPC-Carthage.build/Release-iphoneos/CgRPC.build/Objects-normal/armv7/Binary/CgRPC normal armv7
(3 failures)

</pre>
</details>

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   10.15                                                       |
| Swift Version                 |   5.1                                                       |
| Xcode Version                 |   11.1                                                       |
| gRPC-Swift Version            |   0.10.0                                                       |
| protoc Version                |   3.10.0                                                      |
| protoc-gen-swift Version      |   1.5.0                                                       |
| protoc-gen-swiftgrpc Version  |   0.9.1                                                       |
| Carthage Version  |   0.34.0                                                       |
  </pre>
</details>

**Comment by MrMage** [comment]
Which Xcode version are you using? The Carthage project only works with Xcode 10, not 11.

**Comment by nakkht** [comment]
@MrMage  Xcode 11.1, it is interesting, as it is working with 0.9.1/Xcode 11.1

**Comment by MrMage** [comment]
Weird, there were reports stating the opposite: https://github.com/grpc/grpc-swift/pull/609

Is it possible that you had used 0.9.1 with old binaries built with Xcode 10?

**Comment by nakkht** [comment]
@MrMage don't think so. While using XCode 10/macOS Mojave, I was doing manual integration. When upgraded to XCode 11/macOS Catalina, I tried Carthage and it worked so continued to use it. Furthermore, circleci was setup (last week) using 11.1.0 image and using Carthage to build grpc-swift and it worked out of the box.

**Comment by MrMage** [comment]
Sorry about that, then. Carthage has been a constant source of pain. If you want, you could try if it works better with https://github.com/grpc/grpc-swift/pull/616, or revert to 0.9.1.

**Comment by nakkht** [comment]
Here are some commits I've tried running against:
It involves running (both using `Cartfile` from external project and then running `carthage bootstrap --platform iOS` and also building by just opening `SwiftGRPC-Carthage.xcodeproj` from grpc-swift clone project)

========= BUILD fails =================
44f194e443a8303b82eb463168bde18850b6e3e0

========= BUILD succeeds =============
5d1f76b60e8dce2b53f67e6b8198a2c2d35f0387
8eac348c1108e8acbe70e24970dc1fd3c384aad6
cf002e0aead35e4515baf27f7c750502bbb50099
7c9a83c424170cca3c5596a78a7eeb4667ac79bb
38b98958d06d3cbf03bb4aff902b41d73876ea21
5c610b032a9231e705356d850c823f11460aa17b
8bc025ea64909f43ca3f2dfb76c5a795eb955b2a
ac1a895fc2555dc74e326b762fdc7e3fc013ab8d
e89e402e6f6a7aa146aeea69254ec164d569df32
79ecfa5dc931646abf8ca963bf6e1d8d2cc2939a
67a5352f179751f6aef4e709c030308722f97073

========= BUILD fails =================
99bf33aa932d798ec3f77c04811a9e2e7a3aad67
d5f0c46e4fd067588d17f57894b8b0630c9daca1

Can anyone confirm that building `SwiftGRPC-Carthage.xcodeproj` from 44f194e443a8303b82eb463168bde18850b6e3e0` does not yield the following error:
```
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
@MrMage Since commit is not available on the remove, I've tried replacing `SwiftGRPC-Carthage.xcodeproj/project.pbxproj` contents, however, it did not help.

**Comment by MrMage** [comment]
Hmm, maybe the upgrade to gRPC-Core 1.23 has broken our Carthage support again. @JonasVautherin @WilliamIzzo83 @byuarus @KyoheiG3 do any of you have time to take a look?

**Comment by nakkht** [comment]
What OS version are you guys running? Did anyone try running on macOS Catalina?
I tried building 0.9.1 using carthage on 2 different machines (both using macOS Catalina/Xcode 11.1) and it built both times. My colleague is still using macOS Mojave/XCode 11.1 and carthage build failed for him. (Used same command `carthage bootstrap --platform iOS`
Would be glad to hear if anyone could replicate that.

**Comment by KosukeOhmura** [comment]
@nakkht I tried to build 0.9.1 on macOS Catalina (10.15.1) and Xcode 11.2.1 (11B500) with Carthage (0.34.0) but it failed for me.

the command is: `carthage update --platform iOS`
the error is:

```
error: Build input files cannot be found: '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/CustomJSONCodable.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/FieldTag.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/ZigZag.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/AnyUnpackError.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/BinaryEncodingError.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/duration.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/wrappers.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/BinaryEncodingSizeVisitor.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Message+BinaryAdditions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/TextFormatScanner.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Decoder.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/BinaryDecodingError.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/BinaryDecoder.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONMapEncodingVisitor.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/TextFormatDecoder.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Google_Protobuf_Timestamp+Extensions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/UnknownStorage.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Varint.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Version.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/api.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/type.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/field_mask.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Google_Protobuf_Wrappers+Extensions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/ExtensionFieldValueSet.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/NameMap.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Message+TextFormatAdditions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONDecodingError.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Google_Protobuf_Any+Extensions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/ProtobufMap.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Google_Protobuf_Value+Extensions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/BinaryEncodingVisitor.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONEncodingOptions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/HashVisitor.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/ExtensibleMessage.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/TextFormatDecodingError.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/SelectiveVisitor.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/SimpleExtensionMap.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/TextFormatEncodingVisitor.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/any.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/TextFormatEncoder.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Data+Extensions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Enum.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/TextFormatEncodingOptions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/ExtensionFields.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Google_Protobuf_Struct+Extensions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONScanner.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/WireFormat.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/source_context.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/StringUtils.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONDecodingOptions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/MessageExtension.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/BinaryDecodingOptions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/TimeUtils.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Google_Protobuf_Duration+Extensions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/struct.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Message.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Visitor.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONEncodingError.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONEncoder.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/MathUtils.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/empty.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Message+AnyAdditions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/ProtoNameProviding.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONEncodingVisitor.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/ExtensionMap.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/DoubleFormatter.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Google_Protobuf_FieldMask+Extensions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/ProtobufAPIVersionCheck.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/timestamp.pb.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/FieldTypes.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Google_Protobuf_Any+Registry.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Message+JSONArrayAdditions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/JSONDecoder.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/BinaryEncoder.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/BinaryDelimited.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Google_Protobuf_ListValue+Extensions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Message+JSONAdditions.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/Internal.swift', '/Users/me/Development/project/Carthage/Checkouts/grpc-swift/.build/checkouts/swift-protobuf.git-2635211014727342512/Sources/SwiftProtobuf/AnyMessageStorage.swift' (in target 'SwiftProtobuf' from project 'SwiftGRPC-Carthage')
```

I also tried 0.10.0 and https://github.com/MrMage/grpc-swift/tree/rebuild-carthage-3 (source branch of https://github.com/grpc/grpc-swift/pull/616 ) but all failed too. the error is almost same.

- Does anyone know how to build successfully `v0.x` with Carthage?
- Is it not of grpc-swift but swift-protobuf issue? The error says some of files of swift-protobuf are missing.

**Comment by MrMage** [comment]
It seems like the Carthage build almost never works with Xcode 11. We strongly recommend using SwiftPM or CocoaPods instead.

**Comment by KosukeOhmura** [comment]
@MrMage Okay, I will try with SwiftPM. Thanks.

**Comment by WilliamIzzo83** [comment]
@KosukeOhmura I have a fork [here](https://github.com/WilliamIzzo83/grpc-swift) at version 0.9.something which I'm using with Carthage.

Anyway like @MrMage says, if you can switch to swiftPM and forget about Carthage I think it's for the better. I'm still using this fork because I have some deadlines and I can't afford the switch over.

**Comment by nakkht** [comment]
> Is it not of grpc-swift but swift-protobuf issue? The error says some of files of swift-protobuf are missing.

@KosukeOhmura you are probably right. If you're still interested in trying to fix this issue, try explicitly adding `SwiftProtobuf` in `Cartfile' without `grpc-swift' and then run `carthage bootstrap --platform iOS`. Once SwiftProtobuf dependency is fetched and built, roll back `Cartfile` to use just `grpc-swift`.

**Comment by KosukeOhmura** [comment]
@WilliamIzzo83 and @nakkht Thank you for your reply. I am going to use the `nio` branch with SwiftPM.

**Comment by nakkht** [comment]
Since #682 fixed SwifPM integration for SwiftGRPC, it can be used instead of Carthage/CocoaPods.
