### ISSUE TITLE
[feature] HTTP/JSON Transcoding

### ISSUE THREAD

**Issue by pvzig** [grpc/grpc-swift#617]
It would be great if grpc-swift could parse protobuf annotations and generate the HTTP handlers for them, for example:

```
// Returns a specific bookstore shelf.
rpc GetShelf(GetShelfRequest) returns (Shelf) {
  option (google.api.http) = { get: "/v1/shelves/{shelf}" };
}
```

from: https://cloud.google.com/endpoints/docs/grpc/transcoding#deploying_a_service_using_transcoding

**Comment by MrMage** [comment]
This is definitely out of scope for gRPC Swift — not even gRPC-Core supports it. Please use a transcoding proxy (like the Cloud Endpoints proxy you linked to, or Envoy) instead.

**Comment by adam-rocska** [comment]
@MrMage is it still the case?

**Comment by glbrntt** [comment]
> @MrMage is it still the case?

Yes, this is still the case.
