### ISSUE TITLE
Getting memory crashes in NSOperationQueue  (QOS: UNSPECIFIED) EXC_BAD_ACCESS 0x0000000000000000

### ISSUE THREAD

**Issue by tikekar** [grpc/grpc-swift#619]
I am trying to understand following two memory crashes. 
Has anyone else seen those or can you give some suggestions regarding how we can resolve those?

During our debugging we haven't seen those, but in our production crash logs we do see them pretty often.

<img width="636" alt="Screen Shot 2019-11-01 at 2 07 26 PM" src="https://user-images.githubusercontent.com/8505549/68056772-362f6f00-fcb1-11e9-85ab-c556ac55cedb.png">

<img width="535" alt="Screen Shot 2019-11-01 at 2 07 10 PM" src="https://user-images.githubusercontent.com/8505549/68056798-47787b80-fcb1-11e9-999f-6200aaa277c1.png">

**Comment by ydnar** [comment]
Related: #605 https://bugs.swift.org/browse/SR-11564

**Comment by ydnar** [comment]
We found a workaround.

Set `DEAD_CODE_STRIPPING = NO` in the app’s target fixes the crash.

**Comment by tikekar** [comment]
Thanks for the reply. I will try the DEAD_CODE_STRIPPING = No. But can you explain what can be the probable reason of this crash? Will there be any consequences of setting this flag to No?

**Comment by ydnar** [comment]
The Swift 5.1.1 compiler has a regression in Xcode 11.2 that breaks certain generic superclass symbols.

See here for more context: https://bugs.swift.org/browse/SR-11564

**Comment by MrMage** [comment]
Closing this as it is a compiler issue.

**Comment by tikekar** [comment]
@MrMage @ydnar This issue is still seen by our users. It is not fixed by the suggested DEAD_CODE_STRIPPING = No fix. Please reopen this to further investigate
