### ISSUE TITLE
[nio] at least under TSan, flaky test GRPCTests.FunctionalTestsAnonymousClientNIOTS testBidirectionalStreamingLotsOfMessagesBatched

### ISSUE THREAD

**Issue by weissi** [grpc/grpc-swift#621]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

```
$ swift test --sanitize=thread --disable-index-store
[...]
Test Case '-[GRPCTests.FunctionalTestsAnonymousClientNIOTS testBidirectionalStreamingLotsOfMessagesBatched]' started.
/private/tmp/.nio-release-tools_N0Glvg/grpc-swift/Tests/GRPCTests/FunctionalTests.swift:189: error: -[GRPCTests.FunctionalTestsAnonymousClientNIOTS testBidirectionalStreamingLotsOfMessagesBatched] : Asynchronous wait failed: Exceeded timeout of 15 seconds, with unfulfilled expectations: "Expecting 5000 response(s)", "Expecting status received".
/private/tmp/.nio-release-tools_N0Glvg/grpc-swift/Tests/GRPCTests/FunctionalTests.swift:202: error: -[GRPCTests.FunctionalTestsAnonymousClientNIOTS testBidirectionalStreamingLotsOfMessagesBatched] : XCTAssertEqual failed: ("ok") is not equal to ("unavailable")
Test Case '-[GRPCTests.FunctionalTestsAnonymousClientNIOTS testBidirectionalStreamingLotsOfMessagesBatched]' failed (15.596 seconds).
```

the OS was macOS Catalina

- NIO: fbe0c8a6b8a968e449f1d4facd825e4069120efb
- grpc swift: 2cd9ea7008312db794cb62d805f5ace043496ead

**Comment by glbrntt** [comment]
It _looks_ like this is just timing out. Maybe we finally need to do #437 @MrMage / or increase the timeouts?

**Comment by MrMage** [comment]
I agree that we should probably have an option to exclude time sensitive tests; do you have a suggestion on how to best implement that?

**Comment by glbrntt** [comment]
We can have an environment variable and then just check whether it's set or not. I'd think a computed property on `GRPCTestCase` (which is needed for log handler setup) and then just add something like: `guard self.enableTimeSensitiveTests else return` in each of the tests we care about.

**Comment by MrMage** [comment]
> We can have an environment variable and then just check whether it's set or not. I'd think a computed property on `GRPCTestCase` (which is needed for log handler setup) and then just add something like: `guard self.enableTimeSensitiveTests else return` in each of the tests we care about.

👍

**Comment by weissi** [comment]
@MrMage & @glbrntt that sounds perfect, in the NIO release tools we use `export ENABLE_TIMING_TESTS=false` to disable them as a few projects have used that syntax. If you don't mind it'd be great if you went for that one, if you choose some other syntax, please let me know and I'll add the respective environment variable to the release tools.
