### ISSUE TITLE
[nio] Crash within swift-nio causing issues.

### ISSUE THREAD

**Issue by saudeoncovr** [grpc/grpc-swift#623]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

After updating to the latest version, we started to receive issues occurring within the nio module itself. This is documented [here](https://github.com/apple/swift-nio/issues/1227) as I also think this may be an issue in Swift-NIO itself.

Everything connects appropriately, we get the TLS handshake completed log but then a crash occurs on the line documented in the above issue.

##### Complete output when running grpc-swift, including the stack trace and command used

<details>
  <pre>2019-11-08T17:03:14-0800 info: making EventLoopGroup for best network preference
2019-11-08T17:03:14-0800 info: 'best' NetworkImplementation is .networkFramework
2019-11-08T17:03:14-0800 info: connection_id=F4CBAE33-87B1-41C1-A249-33C683720EC9 attempting to connect to hostAndPort("REDACTED", 443)
2019-11-08T17:03:14-0800 info: connectivity state change: idle to connecting
2019-11-08T17:03:14-0800 info: making client bootstrap with event loop group of type NIOTSEventLoop
2019-11-08T17:03:14-0800 info: connection_id=F4CBAE33-87B1-41C1-A249-33C683720EC9 setting connect timeout to 20.0 seconds
2019-11-08T17:03:14-0800 info: request_id=A8D8560B-886D-470B-9A6F-F41F0AB4AE42 making unary call to '/covr.grpc.cash.Cash/DeliveryInfo', request type: DeliveryInfoRequest, response type: DeliveryInfoResponse
2019-11-08T17:03:15-0800 info: TLS handshake completed, negotiated protocol: Optional("h2")</pre>
</details>

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   13.2.0                                                       |
| Swift Version                 |   5.1.2                                                       |
| Xcode Version                 |   11.2                                                       |
| protoc Version                |   3.7.1                                                       |
| protoc-gen-swift Version      |   1.0.0-alpha.6                                                       |
| protoc-gen-grpc-swift Version  |  1.0.0-alpha.6                                                       |
  </pre>
</details>

**Comment by weissi** [comment]
same as https://github.com/apple/swift-nio/issues/1227

**Comment by saudeoncovr** [comment]
I have provided comments to [apple/swift-nio#1227](https://github.com/apple/swift-nio/issues/1227) @weissi

**Comment by saudeoncovr** [comment]
It seems the resolution to this was to do what has been described in [SR-11564](https://bugs.swift.org/projects/SR/issues/SR-11564).

This involved setting `DEAD_CODE_STRIPPING` to `NO` in the build settings of the application. It will still break the unit tests per package but that can be dealt with separately. 

Going to close this out as it seems to be a larger swift team issue.
