### ISSUE TITLE
Client Streaming response handling when server calls onComplete by itself

### ISSUE THREAD

**Issue by ahmetaa** [grpc/grpc-swift#624]
We have gRPC Java server and a Swift client. We use a **unidirectional** client streaming rpc. This is our scenario:

- Client calls streaming rpc indefinite amount of times. 
- In some cases, without onComplete() ( closeAndReceive ) is called from client side, server may return the response (In the java side, calling onComplete() by itself). 

In Java client we could handle this. However we could not figure out how to handle this in Swift code.

**Comment by MrMage** [comment]
The call's completion handler should be called with the response from the server; see https://github.com/grpc/grpc-swift/blob/e3d8af46a21d957901e70f9c4d3b1630d835d64f/Sources/Examples/Echo/main.swift#L130 for an example. Is that what you are looking for?

The API for this is definitely a bit clumsy; we strongly recommend using the `nio` branch which has a much nicer API.

**Comment by ahmetaa** [comment]
Thanks for the response. We tried but it did not fit to our scenario. However, we experimented with bidirectional streaming and it seems to work. My question on the nio branch is, is it stable enough to use in production code? We are mostly interested in the client side usage.

**Comment by MrMage** [comment]
Yes, `nio` should be stable enough for production use. If you end up encountering any issues with the `nio` branch, please let us know.
