### ISSUE TITLE
Delete the Examples folder?

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#627]
I think https://github.com/grpc/grpc-swift/tree/nio/Examples has been replaced with `Sources/Examples`. @glbrntt, would https://github.com/grpc/grpc-swift/tree/nio/Examples be safe to delete?

**Comment by glbrntt** [comment]
Not quite: the `Google/NaturalLanguage` example uses NIO so we'd need to move that across first. The rest are all CgRPC based though, I think, so can be deleted.

When we add some GUI based examples we should keep them out of source and have only their generated gRPC code in `Source/Examples`.

**Comment by glbrntt** [comment]
I think there's some other stuff left over from the CgRPC branch too. I'll do some ~spring~ autumn cleaning soon.

**Comment by MrMage** [comment]
@glbrntt I think this has all been cleaned up now; shall we close this issue?

**Comment by glbrntt** [comment]
Yup!
