### ISSUE TITLE
Bazel Support

### ISSUE THREAD

**Issue by perezd** [grpc/grpc-swift#63]
It'd be nice to be able to compile this cleaning with bazel.build. Has anyone attempted? Any pointers?

**Comment by JonNRb** [comment]
I just threw something together since I couldn't find anything either: [JonNRb/bazel_grpc_swift](https://github.com/JonNRb/rules_grpc_swift)

**Comment by keith** [comment]
@timburks any chance you could add whatever Google uses internally for this to this repo? // @allevato

**Comment by allevato** [comment]
The `swift_grpc_library` rule that we use internally is part of rules_swift because it shares logic with `swift_proto_library`, so when we open-source it it will live in that repo, not here.

It’s on my to-do list, but as usual, we’re resource-constrained.

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
