### ISSUE TITLE
Add an configuration option to switch between HTTP & HPACK headers

### ISSUE THREAD

**Issue by layoutSubviews** [grpc/grpc-swift#635]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description

I just updated GRPC on an internal project from 1.0.0-alpha6 to 1.0.0-alpha7, and noticed that request headers were switched from plain HTTP headers to HPACK headers. This sounds like a great enhancement, however:
- This significant change was not mentioned in the Release Notes for the version, therefore it took us a while to find out that:
- HPACK headers may not be compatible (yet) with existing API gateways & services, unfortunately. Quite some time may be required for this software to support them fully.

Therefore I would like to propose that the use of HPACK be optionally disabled, through a `ClientConnection.Configuration` item or similar.

Cheers,

**Comment by layoutSubviews** [comment]
I think I misunderstood our problem. I will close this issue for now, and reopen if necessary.
Sorry for the noise.

**Comment by glbrntt** [comment]
@layoutSubviews The breaking change in the generated code is mentioned at the top of the release notes but it certainly could have been clearer, sorry about that!
