### ISSUE TITLE
[nio] Provide option to return additional trailing metadata in ServerErrorDelegate.transformRequestHandlerError

### ISSUE THREAD

**Issue by dinhhungle** [grpc/grpc-swift#636]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Unable to return additional trailing metadata in ServerErrorDelegate.transformRequestHandlerError

#### Question Description
We would like to use swift services along with our golang services. We handle our errors by using 
https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto
which uses the `grpc-status-details-bin` key  in metadata

It would be nice being able to handle this error transformation in the error delegate.
 
The current signature for transformRequestHandlerError
https://github.com/grpc/grpc-swift/blob/062b341d63a324699ac7b4d5f2eb6656d61a5158/Sources/GRPC/ServerErrorDelegate.swift#L64-L70
I believe it was possible to add trailing metadata prior to #572 and would suggest to restore that functionality.

**Comment by glbrntt** [comment]
Thanks for raising this @ledinhhu  -- I wasn't aware of `grpc-status-details-bin`, it's not mentioned in the spec but it is implemented as an experimental feature in a number of languages (e.g. [Python](https://github.com/grpc/grpc/blob/b0c9849393da9ec4d4e6e1910f67e94e6a1834b0/src/python/grpcio_status/grpc_status/rpc_status.py#L40), [Go](https://github.com/grpc/grpc-go/blob/40ed2eb467471df2bd3c59e66cc5357159062d48/internal/transport/http_util.go#L366), etc.). 

This seems like a useful feature that we should support. I think the correct way to achieve this would be to add `var details: [Any]` (the Protobuf `Any`, not the Swift `Any`) to our `GRPCStatus` and internally do the first level of encoding/decoding, the user would then have to decode the `Any` into the appropriate type on the client side.

Would this solve your problem @ledinhhu?

@MrMage how do you feel about supporting an experimental feature? Any other suggestions?

**Comment by ledinhhu** [comment]
@glbrntt Thank you for the suggestion. This would in principle solve our problem.
But `grpc-status-details-bin` contains a serialized google.rpc.Status proto, not the details directly.
Therefore it would probably require the status proto file and its compiled form to be vendored.
I believe this was previously rejected for the non-nio branch #331 by @MrMage . 

For our case encoding the status proto and adding it to metadata ourselves would be sufficient. It would be less error-prone to handle this in the error delegate.

**Comment by MrMage** [comment]
Still not a huge fan of having to vendor and maintain that proto ourselves, but less opposed than I used to be. I wouldn't make it a priority for 1.0, but we could add it as an experimental feature (not covered by SemVer) later on.

It sounds like @ledinhu's original idea of the server error delegate functionality would be more universally useful. Happy to at least look at a PR and hopefully an example use case implementation — I don't think we would get around to adding this before 1.0. @glbrntt, WDYT?

**Comment by glbrntt** [comment]
I don't think it would necessarily be a maintenance burden: we don't see many changes in SwiftProtobuf and any SemVer major changes will require work on our behalf anyway.

That said I'm open to returning headers from the delegate as well. I.e. returning `(GRPCStatus, HTTPHeaders?)?` instead of `GRPCStatus?`:

```
 protocol ServerErrorDelegate { 
   func transformLibraryError(_ error: Error) -> (GRPCStatus, HTTPHeaders?)?
   func transformRequestHandlerError(_ error: Error, request: HTTPRequestHead) -> (GRPCStatus, HTTPHeaders?)?
 }
```

I _think_ this would actually be a relatively small change. @ledinhhu would you be open to making this change?

**Comment by ledinhhu** [comment]
I will take a look at it and provide a PR later

**Comment by dinhhungle** [comment]
Hey, I am very sorry for the lack of update. Due to changes at my workplace, I am currently unable to spend time on this.
If this feature is still desired, feel free to pick this up.
