### ISSUE TITLE
Examples/Google/NaturalLanguage does not compile

### ISSUE THREAD

**Issue by sroche27r** [grpc/grpc-swift#642]
### New Issue Checklist

- [x ] Updated grpc-swift to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x ] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
Trying to compile Examples/Google/NaturalLanguage and I am getting compile errors.  _(I attempted to fix the errors, but could not get a functional example)_ 

Here is what I did:

1. downloaded the latest 'nio' branch
2. ran make plugins _(success)_
3. downloaded the latest protoc compiler 
4. ran Examples/Google/NaturalLanguage/RUNME _(success, compiled Proto files)_   
5. attempted to compile the example by running make _(failed with compile errors)_

<details>
  <pre>
Roche-MBP:NaturalLanguage sroche$ make
swift build -c release
/Volumes/work/DocsAndTutorials/gRPC/test_2019.11.29/grpc-swift-nio/proto_build/grpc-swift/Examples/Google/NaturalLanguage/Sources/main.swift:102:49: error: cannot convert value of type 'HTTPHeaders' to expected argument type 'HPACKHeaders'
  let callOptions = CallOptions(customMetadata: headers, timeout: timeout)
                                                ^~~~~~~
/Volumes/work/DocsAndTutorials/gRPC/test_2019.11.29/grpc-swift-nio/proto_build/grpc-swift/Examples/Google/NaturalLanguage/Sources/main.swift:40:28: error: extra argument 'tlsConfiguration' in call
        tlsConfiguration: .init(sslContext: try makeClientTLS()))
                          ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
</details>

NOTE: I have tried this on the nio branch, 1.0.0-alpha.7, 1.0.0-alpha.6. all with similar issues

I attached a script that will execute every step that I tried. Just copy it into an empty directory and run it.  [build_natural_language_example.sh.txt](https://github.com/grpc/grpc-swift/files/3906805/build_natural_language_example.sh.txt)

### Environment

<details>
  <pre>
  
| Key                           | Value                         

                                |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   10.14.6                                                       |
| Swift Version                 |   5.1.2                                                       |
| Xcode Version                 |   11.2.1                                                       |
| gRPC-Swift Version            |   nio/1.0.0-alpha.7                                                      |
| protoc Version                |   3.11.0                                                       |
| protoc-gen-swift Version      |   nio/1.0.0-alpha.7                                                       |
| protoc-gen-swiftgrpc Version  |  nio/1.0.0-alpha.7                                                       |
  </pre>
</details>

**Comment by glbrntt** [comment]
Thanks for the report! I think this is just from API breaking changes between pre-release versions of the nio branch. These went unnoticed because they're out-of-source so they're not built in CI. I just pushed up a PR to fix the compilation issues: #643

**Comment by sroche27r** [comment]
@glbrntt Thanks for the quick fix.  It now compiles, but it fails to successfully make the rpc call.  I can get the 0.10 example code working, so I know that I am using valid tokens and that I have the Natural Language API's enabled in google cloud.

Here is the output from the example:

```
2019-12-02T08:55:01-0800 info: connectivity state change: idle to connecting
CALL OPTIONS
CallOptions(customMetadata: [([], "authorization", "Bearer ya29.c.Kl6zB0529FphCy01aeAiNf_NefXXP3tuXitZUff0gJxKXOvhLy8ISAkxdLDyM2C8_WeqIB4KIna6LqSE5dI2I0VpnxC-GPvSzzCBZxLVTtSsh4w6aGBVslZ_wCkjJzSU")], timeout: 30S, cacheable: false, requestIDProvider: GRPC.CallOptions.RequestIDProvider.autogenerated, requestIDHeader: nil)

REQUEST MESSAGE
GRPC_Swift_NIO_test_ios.Google_Cloud_Language_V1_AnnotateTextRequest:
document {
  type: PLAIN_TEXT
  content: "The Caterpillar and Alice looked at each other for some time in silence: at last the Caterpillar took the hookah out of its mouth, and addressed her in a languid, sleepy voice. `Who are you?' said the Caterpillar."
}
features {
  extract_syntax: true
  extract_entities: true
  extract_document_sentiment: true
  extract_entity_sentiment: true
  classify_text: true
}

2019-12-02T08:55:01-0800 info: path=/google.cloud.language.v1.LanguageService/AnnotateText request_id=ED2ECDB0-C7D5-4EBB-8A45-983F78EF5B70 starting rpc
2019-12-02T08:55:01-0800 info: TLS handshake completed, negotiated protocol: Optional("h2")
2019-12-02T08:55:01-0800 info: connectivity state change: connecting to ready
2019-12-02T08:55:01-0800 error: error=invalidHTTPStatus(Optional(NIOHTTP1.HTTPResponseStatus.notFound)) client error
2019-12-02T08:55:01-0800 info: request_id=ED2ECDB0-C7D5-4EBB-8A45-983F78EF5B70 duration_ms=51 status_code=12 rpc call finished
CALL STATUS
unimplemented (12): invalid HTTP status: Not Found
CALL FAILED WITH ERROR
unimplemented (12): invalid HTTP status: Not Found
2019-12-02T08:55:01-0800 error: error=StreamClosed(streamID: HTTP2StreamID(1), errorCode: HTTP2ErrorCode<0x8 Cancel>) client error
```

It looks like the rpc call is getting started before the connection is 'ready'.  I did a quick test and didn't make the call until the connection was in the 'ready' state, but I still got the same results.  If you don't have time to look into this, any insight would be greatly appreciated, as I would love to use this library in our project.  Thanks

**Comment by glbrntt** [comment]
Ah sorry about that, I didn't have time to do the due diligence here and setup an account etc. (I didn't create this example). The connection readiness shouldn't be an issue here: we manage to do the TLS handshake and negotiate "h2' before sending off the request headers but then we get a 404 back from the server:

> ... invalidHTTPStatus(Optional(NIOHTTP1.HTTPResponseStatus.notFound)) 

I'm not sure what this is but I'll look into this first thing tomorrow (not being able to talk to a service is a bit a pretty bad bug!).

Out of curiosity have you tried any other services?

**Comment by sroche27r** [comment]
@glbrntt Thanks.  Yes, I have tried with the DialogFlow apis, same error.

**Comment by glbrntt** [comment]
@sroche27r got to the bottom of the problem: we were sending the content-type as "application/grpc+proto" (which is permitted by the gRPC spec) but the service was rejecting it and sending a 404 in response. I just updated #643 to use "application/grpc" instead which works.

**Comment by sroche27r** [comment]
Thanks @glbrntt the Natural Language calls are working now.  I will try more services tomorrow.
