### ISSUE TITLE
Metadata binary value support

### ISSUE THREAD

**Issue by kmarcell** [grpc/grpc-swift#648]
### Question Checklist

- [*] Updated grpc-swift to the latest version
- [*] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [*] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [*] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Are you planning to add binary `Data` support for values on `Metadata` class?

#### Question Description

On Android it is possible to add `Data` as a key-value pair.
Link: https://grpc.github.io/grpc-java/javadoc/io/grpc/Metadata.Key.html

We would need something similar like:
```
func add(key: String, data: Data) throws
```

**Comment by MrMage** [comment]
We are not planning any new features for the gRPC-Core version of gRPC Swift. However, this might be an option for the `nio` branch, provided the NIO-HTTP2 developers are open to adding this (https://github.com/apple/swift-nio-http2/blob/master/Sources/NIOHPACK/HPACKHeader.swift). /cc @lukasa

Alternatively, you could always resort to base64-encoding your headers.

**Comment by Lukasa** [comment]
As I understand the gRPC specification, binary metadata fields _are_ base64-encoded. Certainly [the spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests) implies this:

> **Binary-Header** → {Header-Name "-bin" } _{base64 encoded value}_

> Note that HTTP2 does not allow arbitrary octet sequences for header values so binary header values must be encoded using Base64 as per https://tools.ietf.org/html/rfc4648#section-4. Implementations MUST accept padded and un-padded values and should emit un-padded values. Applications define binary headers by having their names end with "-bin". Runtime libraries use this suffix to detect binary headers and properly apply base64 encoding & decoding as headers are sent and received.

So I don't think swift-nio-http2 requires any additional support, this would be a purely grpc-swift feature.

**Comment by kmarcell** [comment]
Indeed it seems we were able to use `public func serializedData(partial: Bool = false) throws -> Data` on `SwiftProtobuf.Message` and `Data.base64EncodedString()`
