### ISSUE TITLE
included shim incompatible with current gRPC head

### ISSUE THREAD

**Issue by perezd** [grpc/grpc-swift#65]
Seeing errors like this:

```
external/swift_grpc/Sources/CgRPC/shim/channel.c:32:58: error: too few arguments to function call, expected 3, have 1
  c->completion_queue = grpc_completion_queue_create(NULL);
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~     ^
external/grpc/include/grpc/grpc.h:98:9: note: 'grpc_completion_queue_create' declared here
GRPCAPI grpc_completion_queue *grpc_completion_queue_create(
        ^
external/swift_grpc/Sources/CgRPC/shim/channel.c:64:58: error: too few arguments to function call, expected 3, have 1
  c->completion_queue = grpc_completion_queue_create(NULL);
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~     ^
external/grpc/include/grpc/grpc.h:98:9: note: 'grpc_completion_queue_create' declared here
GRPCAPI grpc_completion_queue *grpc_completion_queue_create(
        ^
external/swift_grpc/Sources/CgRPC/shim/channel.c:89:54: error: passing 'const char *' to parameter of incompatible type 'grpc_slice' (aka 'struct grpc_slice')
                                                     method,
                                                     ^~~~~~
external/grpc/include/grpc/grpc.h:190:57: note: passing argument to parameter 'method' here
    grpc_completion_queue *completion_queue, grpc_slice method,
                                                        ^
```

Using this release:
https://github.com/grpc/grpc/tree/a39d9fa040efa1aaec8140b5999352c490a1c817

**Comment by perezd** [comment]
Also looks like APIs have changed to favor grpc_slice over char *.

Looks like it might be easy to refactor, however:
https://github.com/grpc/grpc/blob/5253c8f9a899450397a5e46e4923d01ac9a66a27/include/grpc/slice.h#L86

**Comment by dhavalcue** [comment]
@perezd: Did you do any more work here?

**Comment by perezd** [comment]
Not yet, working with @timburks to get this up to par with HEAD.

**Comment by dhavalcue** [comment]
Thanks @perezd, I filed a related issue: https://github.com/grpc/grpc-swift/issues/66 Will be great to have this updated!

**Comment by timburks** [comment]
I have an update in the grpc-1.4.5 branch that builds and runs the Simple and Echo examples when they are built with the package manager. There are still a few problems: the top level unit test fails (will be fixed soon), Xcode crashes upon opening the generated Xcode project, and Swift 4 builds are unable to find the CgRPC library.

**Comment by timburks** [comment]
Top-level tests pass now for the [grpc-1.4.5](https://travis-ci.org/grpc/grpc-swift/builds/270538555?utm_source=email&utm_medium=notification) branch.

**Comment by timburks** [comment]
Updated to 1.6.0 with [this release](https://github.com/grpc/grpc-swift/releases/tag/0.2.1).
