### ISSUE TITLE
Attempt to build a maintain request, but just receive response once

### ISSUE THREAD

**Issue by TheyCallMeTank** [grpc/grpc-swift#656]
I attempt to build a maintain request, the server side continue send data to our client, but receive response just once, did I miss something?

    let call = try client.subscribe(request, metadata: self.generateHeader()) { (result) in
        // not called
        TLOG.info("[grpc push] call complete: \(result)")
    }
    try call.receive { (response) in
        // called just once
        switch response {
        case .result(let response):
            switch type {
                case .order:
                    self.orderData.accept(response?.payload.toJSON())
                }
        case .error(let error):
            // not called
            TLOG.info("[grpc push] call error: \(error)")
        }
    }

**Comment by MrMage** [comment]
You need to call `receive` again for each time you would like to receive a message. Would that explain it?
