### ISSUE TITLE
SPM question

### ISSUE THREAD

**Issue by WilliamIzzo83** [grpc/grpc-swift#667]
So, I'm trying to set up a swift package using grpc-swift as a dependency. I'm pointing to the latest beta (1.0.0-alpha.8).

I'm on macOS Catalina (10.15.1), running xcode 11.3 (11C29)

What I want is to build for iOS, therefore I use spm to create the xcodeproject and then I launch

```xcodebuild build -sdk iphoneos13.2 -target my_target -quiet```

As a result I get
```
/Users/William/Documents/work/clients/perceptolab/safehome/ios_sdk/spm/.build/checkouts/grpc-swift/Sources/GRPC/CallHandlers/BaseCallHandler.swift:17:8: error: could not find module 'SwiftProtobuf' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios
import SwiftProtobuf
       ^
/Users/William/Documents/work/clients/perceptolab/safehome/ios_sdk/spm/.build/checkouts/grpc-swift/Sources/GRPC/CallHandlers/BaseCallHandler.swift:17:8: error: compiling for iOS 8.0, but module 'SwiftProtobuf' has a minimum deployment target of iOS 13.2: /Users/William/Documents/work/clients/perceptolab/safehome/ios_sdk/spm/build/Release-iphoneos/SwiftProtobuf.framework/Modules/SwiftProtobuf.swiftmodule/arm64-apple-ios.swiftmodule
import SwiftProtobuf
```

I can work around to the first error by passing only the architecture I'm interested (arm64 etc), but for the second error I can't find a solution (as per command line I'm specifing the latest sdk. I get the same error if I don't specify it)
 
I'm kinda stuck here. If I try to use swift build instead, so as to generate a macos package, it seems to work fine.

**Comment by glbrntt** [comment]
Did you try setting the [supported platforms](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md#supportedplatform) in `Package.swift`?

It's also not clear to me what you're doing here, is this just a Swift Package, or a macOS/iOS app which depends on grpc-swift?

**Comment by WilliamIzzo83** [comment]
Sorry I missed some infos. What I'm trying to do is to make a swift package which depends on grpc-swift. Then I'd like to link this package to an iOS app.

Those are the contents of my current Package.swift
```swift
// swift-tools-version:5.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "MyPackage",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "MyPackage",
            targets: ["MyPackage"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/grpc/grpc-swift.git", from: "1.0.0-alpha.8")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "MyPackage",
            dependencies: [
              "GRPC"
        ]),
        .testTarget(
            name: "MyPackageTests",
            dependencies: ["MyPackage"]),
    ]
)
```

I'll try to look into supported platform

**Comment by WilliamIzzo83** [comment]
Ok it seems I got everything wrong :D
The problem arises when I try to generate an xcodeproject from my package. If I open the generated xcodeproject I get the errors.

Instead of doing this I should have looked better into how swift package are meant to be used (just reference them from the main app project). By doing so everything works as intended.

Problem solved.
Sorry guys!

**Comment by glbrntt** [comment]
No problem!
