### ISSUE TITLE
Delayed error response when network connection is not available

### ISSUE THREAD

**Issue by codingrhythm** [grpc/grpc-swift#67]
When the device is offline ( flight mode), there are 2 issues:

1. When making a request, it takes ~20 seconds to receive error response (error code 14)
2. The streaming channel never get any error response, thus no way to reconnect. (If I quit my gRPC server, I can receive endOfStream error from client instantly, but not for flight mode)

I am comparing with objective-c grpc lib which works as expected. Also I have tested this on my local machine using iPhone to talk to my server over LAN as well as an external cloud server.

**Comment by dhavalcue** [comment]
@codingrhythm: Seeing the same issues on our end. Do you have any workarounds for this?

**Comment by MrMage** [comment]
Could you please check if this got fixed in #184? Callbacks should now always be called even when an error is encountered.
