### ISSUE TITLE
migrating from .0.10 to 1.0.0-alpha.6

### ISSUE THREAD

**Issue by chris-speebly** [grpc/grpc-swift#679]
I am in the process of migrating to version 1.0.0-alpha.8

when i run the protoc command to generate my swift code from my .proto file should "imports swiftgrpc"  be replaced with "imports grpc"?

thanks

Chris

**Comment by saltyskip** [comment]
@chris-speebly How were you able to resolve this?

**Comment by chris-speebly** [comment]
The new import is grpc

What helped me was when I found the examples under sources in 1.0.0-alpha.6
branch
