### ISSUE TITLE
Unable to find library gRPC when linking [Swift 4]

### ISSUE THREAD

**Issue by Allezxandre** [grpc/grpc-swift#68]
Using Swift 4.0 and Xcode 9 Beta 5, the linker is unable to find the gRPC library. 

I've tried every single combination I can think of and it fails when doing one of the following from a fresh copy of `origin/master`:

* Building from Xcode after the following steps:
  - `cd $(REPO)`
  - `make`
  - open the project in Xcode
  - add `libz.tbd` to the 'Linked frameworks and libraries' of the 'CgRPC' target
  - build `SwiftGRPC-Package` for 'My Mac' from Xcode
* Launching the tests from Swift using `make test`

The error is as follows:

```
ld: library not found for -lCgRPC for architecture x86_64
clang: error: link command failed with exit code 1 (use -v to see invocation)
```

Running `swift build -Xcc -ISources/BoringSSL/include` before does not help.

From the Xcode project I also tried fiddling with any setting I could think about, like adding everything as a dependency or adding to the Library Search Paths, but to no avail, `ld` cannot find the library. Does anyone have this issue as well? My internet connection has been too intermittent to download Xcode 8.x or upgrade to Xcode 9b6 so please forgive me if this is an issue related to my version of Xcode/Swift.

**Comment by timburks** [comment]
Yes, I'm seeing this also.

**Comment by Allezxandre** [comment]
I still haven't found a solution or workaround unfortunately.

**Comment by timburks** [comment]
There seems to be a solution in [this blog post](https://hackernoon.com/migrating-perfect-project-to-swift-4-3ada7b4a3c1a), which reports a similar problem. I'm investigating further now.

**Comment by timburks** [comment]
The change proposed in the blog post fixes the builds for the samples, but there's still a failure when running `swift test`:
```
xcrun xctest /Users/timburks/Desktop/grpc-swift/.build/debug/SwiftGRPCPackageTests.xctest
2017-09-02 13:13:48.789 xctest[95502:17325014] The bundle “SwiftGRPCPackageTests.xctest” couldn’t be loaded. Try reinstalling the bundle.
2017-09-02 13:13:48.789 xctest[95502:17325014] (dlopen(/Users/timburks/Desktop/grpc-swift/.build/debug/SwiftGRPCPackageTests.xctest/Contents/MacOS/SwiftGRPCPackageTests, 265): Symbol not found: _XCTActivityTypeUserCreated
  Referenced from: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftXCTest.dylib
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Agents/../../Frameworks/XCTest.framework/Versions/A/XCTest
 in /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftXCTest.dylib)
make: *** [test] Error 1
```
It appears that _XCTActivityTypeUserCreated is undefined, and there doesn't appear to be a definition of it in the [Swift sources](https://github.com/apple/swift/search?utf8=%E2%9C%93&q=XCTActivityTypeUserCreated&type=).

**Comment by Allezxandre** [comment]
Thank you. It works in Xcode at least. I'll look into the remaining `swift test` issue but do you want me to start a pull request with this fix in the meantime?

For others, for reference, just removing `link "CgRPC"` in `Sources/CgRPC/include/module.modulemap` made the build work in Xcode.

**Comment by timburks** [comment]
I tested the September 1 releases of Swift 4 for Ubuntu 14.04 and Mac OS and the tests worked for both, so it appears that the missing symbol problem is fixed.

I'll update this within the next day and document that we're switching from Swift 3 to Swift 4. I don't see a good way to support both.

**Comment by timburks** [comment]
OK, we've [moved to Swift 4](https://github.com/grpc/grpc-swift/releases/tag/0.2.3).
