### ISSUE TITLE
[tls] negotiating application protocol invalid

### ISSUE THREAD

**Issue by WilliamIzzo83** [grpc/grpc-swift#680]
Hello

I'm working on an iOS app from some time now, and I've decided to switch to the new nio branch. I've got some problems with tls though. 

Some background first: we use tls for secure connection. The code that is using grpc-swift master branch does something like this

```swift
let client = MyClient(address: configuration.backendHostName, secure: configuration.needsSecureConnection)
```

And this works as intended.

With the new api exposed on the nio branch, things have changed a little. Therefore now I've got:

```swift
let eloop = PlatformSupport.makeEventLoopGroup(
    loopCount: 1,
    networkPreference: .best)

let target = ConnectionTarget.hostAndPort(configuration.backendHostName, configuration.port)
let conf = ClientConnection.Configuration(
      target: target,
      eventLoopGroup: eloop,
      errorDelegate: nil,
      connectivityStateDelegate: nil,
      tls: configuration.needsSecureConnection ? ClientConnection.Configuration.TLS() : nil,
      connectionBackoff: nil)
    
let conn = ClientConnection(configuration: conf)
let callOpts = CallOptions(customMetadata: [:],
    timeout: try! .minutes(10),
    cacheable: false,
    requestIDProvider: .autogenerated, requestIDHeader: nil)

let client = MyClient(connection: conn, defaultCallOptions: callOpts)
```

Unfortunately I'm getting the following

```
2019-12-20T12:34:41+0100 error: negotiated application protocol is invalid: nil
2019-12-20T12:34:41+0100 warning: error=GRPCError(wrappedError: GRPC.GRPCClientError.applicationLevelProtocolNegotiationFailed, origin: GRPC.GRPCError.Origin.client, file: "/Users/William/Library/Developer/Xcode/DerivedData/sphere-dmhvcadfhsxqgbglhgytyjsalwoi/SourcePackages/checkouts/grpc-swift/Sources/GRPC/TLSVerificationHandler.swift", line: 94) connection_id=6EB998B5-81A8-416E-AF24-D472437A012E client connection shutdown failed
```

I guess I need some guidance to understand what is going on

Thank you

**Comment by glbrntt** [comment]
During the TLS handshake the application layer protocol that the client and server will communicate using will also be negotiated. This has the unsurprising name of application layer protocol negotiation (ALPN) https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation.

For gRPC this protocol they negotiation should be "grpc-exp" or "h2". (Turns out our client has a typo in "grpc-exp" which I will fix shortly!)

However, we fail to negotiate ALPN: the negotiated protocol is not present. Even with the typo in `grpc-exp` they should be able to negotiated `h2`. So this _seems_ like a server bug. 

Can you provide more details on the service you're trying to connect to?

**Comment by WilliamIzzo83** [comment]
Yes of course: basically we've got a grpc service behind an nginx ingress, with tls termination. 
Other things that comes to mind are:
- We've got a test client written in go that works with this service, using the default tls configuration of the crypt/tls package.
- Also we use grpcurl and we don't have any problems.

Another thing: by trying a curl toward the service we got this
```
*   Trying 54.72.162.170:443...
* TCP_NODELAY set
* Connected to development.sphere.perceptolab.cloud (54.72.162.170) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=development.sphere.perceptolab.cloud
*  start date: Aug 13 00:00:00 2019 GMT
*  expire date: Sep 13 12:00:00 2020 GMT
*  subjectAltName: host "development.sphere.perceptolab.cloud" matched cert's "development.sphere.perceptolab.cloud"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: development.sphere.perceptolab.cloud
> User-Agent: curl/7.67.0
> Accept: */*
>
* Received HTTP/0.9 when not allowed

* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (1) Received HTTP/0.9 when not allowed
```

So it seems h2 is being offered by the service. I noticed something else though: if I do the same curl call from macos (using catalina at the moment) the h2 offering is not logged. I don't know exactly what this could mean though

**Comment by glbrntt** [comment]
> ```
> * Connected to development.sphere.perceptolab.cloud (54.72.162.170) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> ...
> * ALPN, server did not agree to a protocol
> ```
> 
> So it seems h2 is being offered by the service.

From the output it above this doesn't seem to be the case!


What I suspect is happening is that the other implementations also fail the ALPN negotiation and then proceed as if h2 was negotiated anyway. If this is correct then we it shouldn't be too difficult for us to adopt this behaviour as well.

**Comment by WilliamIzzo83** [comment]
@glbrntt I've been a little sloppy and I published ip and hostname of our services, could you please remove them? :o

**Comment by glbrntt** [comment]
Oops, updated!

**Comment by WilliamIzzo83** [comment]
Hey @glbrntt, can I contribute to this in any way? (sorry for the delay, I've been on holiday break!)

**Comment by glbrntt** [comment]
No problem, I was also away! I can probably look into this today or I can provide some guidance if you'd rather take this on?

**Comment by WilliamIzzo83** [comment]
I'd like to give it a shot!

**Comment by glbrntt** [comment]
Awesome!

When the TLS handshake is completed an event is fired which is caught and checked in `TLSVerificationHandler.swift`. This event carries with it the negotiated protocol, which may be `nil`. At the moment we pass this check if the protocol is not `nil` _and_ is one of the valid protocols, the desired semantics should be that the negotiated protocol is `nil` _or_ one of the valid protocols.

We also need a test case for this. We don't have any that target just that specific handler but it shouldn't be too hard to do: 
1. Use an `EmbeddedChannel` with just one handler, the `TLSVerificationHandler`
2. Fire a `TLSUserEvent.handshakeCompleted` event into the channel using `fireUserInboundEventTriggered`
3. Verify that future on the handler is as expected.

You can look at `DelegatingErrorHandlerTests.testUncleanShutdownIsIgnored` for a similar test.

Let me know if any of that isn't clear or you need some more pointers.

**Comment by WilliamIzzo83** [comment]
At the moment I've changed the implementation of ```TLSVerificationHandler.userInboundEventTriggered``` so that it implements the following semantic

> pass the check if the negotiated protocol is nil **or** one of the valid protocols

But from what I can see here the negotiated protocol will always be nil unless it is *h2* or *grpc-exp*. In fact when I run the test ```ClientTLFailureTests.testClientConnectionFailsWhenProtocolCanNotBeNegotiated``` I expect it to still pass, instead it fails for the reasons stated before.

Maybe I am missing something here.

Here's the modified code of ```TLSVerificationHandler.userInboundEventTriggered```, just for reference:

```swift
func userInboundEventTriggered(context: ChannelHandlerContext, event: Any) {
    precondition(self.verificationPromise != nil, "handler has not been added to the pipeline")

    guard let tlsEvent = event as? TLSUserEvent,
      case .handshakeCompleted(negotiatedProtocol: let negotiatedProtocol) = tlsEvent else {
        context.fireUserInboundEventTriggered(event)
        return
    }

    self.logger.debug("TLS handshake completed, negotiated protocol: \(String(describing: negotiatedProtocol))")
    guard let proto = negotiatedProtocol else {
      self.logger.debug("cannot agree to application protocol, proceeding as valid")
      self.verificationPromise.succeed(())
      return
    }
    
    if GRPCApplicationProtocolIdentifier(rawValue: proto) != nil {
      self.logger.debug("negotiated application protocol is valid")
      self.verificationPromise.succeed(())
    } else {
      self.logger.error("negotiated application protocol is invalid: \(String(describing: negotiatedProtocol))")
      let error = GRPCError.client(.applicationLevelProtocolNegotiationFailed)
      self.verificationPromise.fail(error)
    }
  }
```

**Comment by glbrntt** [comment]
> But from what I can see here the negotiated protocol will always be nil unless it is h2 or grpc-exp. 

Yes, you're correct here, with one caveat explained below.

In fact I think the check against `GRPCApplicationProtocolIdentifier` is incorrect: the user can actually override which protocols to negotiate (i.e. they could choose something other than `h2` or `grpc-exp` if they desire, which would actually lead to this failing unnecessarily, although this seems unlikely).

> In fact when I run the test `ClientTLFailureTests.testClientConnectionFailsWhenProtocolCanNotBeNegotiated` I expect it to still pass, instead it fails for the reasons stated before.

I would expect this to test to now _fail_ because now we hit the case where no protocol is negotiated and we continue regardless. This will now need to check that it can connect when the protocol can't be negotiated.


The above code looks good, although in light of this comment, the final if-else block can just be reduced to a log message including the negotiated protocol `proto` and just succeeding the promise.
