### ISSUE TITLE
Cant find protoc-gen-grpc-swift when upgrading to NIO branch.

### ISSUE THREAD

**Issue by saltyskip** [grpc/grpc-swift#684]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

#### Question Description

Hello I'm attempting to upgrade my SwiftGRPC version from the deprecated version to the new NIO version. Previously I was using cocoapods, but Im now attempting to install it via the Swift Package Manager in xcode without success.

Screen shots follow
![image](https://user-images.githubusercontent.com/14796429/71802053-0b420c80-30a0-11ea-883a-297ee8878c97.png)

Adding dependency to xcode

![image](https://user-images.githubusercontent.com/14796429/71802089-2280fa00-30a0-11ea-9230-a7b53106ecd9.png)

NOTE: I cannot select the protoc-gen-grpc here

After this i am not quite sure how to proceed, I cannot find how to add the protoc-gen-grpc as it appears to not have been downloaded anywhere. 

I've read through the documentation as well as this thread
https://github.com/grpc/grpc-swift/issues/526

and it appears as if it should "just work", but I've run into a wall. Does anyone have any insights on what might be the issue

**Comment by saltyskip** [comment]
Was able to eventually find and make the project by looking in the derived data where the the swift package manager had put all related files in case this helps anyone out

**Comment by glbrntt** [comment]
Hi @saltyskip, unfortunately you can only add library dependencies. 

Another option is to just clone grpc-swift and build the plugins yourself (`make plugins` should do). While it doesn't solve the problem directly making the protoc plugin available via e.g. homebrew would make this slightly easier. (There's already a formula for the 0.x release series which we should update when we tag 1.0.)

Let us know if you hit any more issues with the upgrade!

**Comment by saltyskip** [comment]
Hi @glbrntt

**Comment by saltyskip** [comment]
Updated the script to 
```
#!/bin/bash

## Build the plugins
if [ ! -d grpc-swift ]; then
        git clone -b nio https://github.com/grpc/grpc-swift.git
        cd grpc-swift
        make plugins
        cp protoc-gen-grpc-swift* ./Protofiles/
        cp protoc-gen-swift* ./Protofiles/
        cd ../Protofiles
else
        cp ./grpc-swift/protoc-gen-grpc-swift* ./Protofiles/
        cp ./grpc-swift/protoc-gen-swift* ./Protofiles/
        cd ./Protofiles
fi



## Generate your Swift code from proto files
# Add the path in your PATH
export PATH=:$pwd:$PATH
protoc *.proto --swift_out=../Generated/GRPC/ --grpc-swift_out=Client=true,Server=false,TestStubs=true:../Generated/GRPC/
```

However the GRPC files aren't getting generated at all now, although I think this is a step in the right direction

**Comment by saltyskip** [comment]
Ive resolved the issue and posted a potential solution for anyone that  is upgrading. The naming conventions changing tripped me up a bit.

**Comment by demistry** [comment]
Having the issue of the grpc.swift files not generated with the current import
