### ISSUE TITLE
NIO: example for using secure connection (cert from string, adding metadata)

### ISSUE THREAD

**Issue by ealymbaev** [grpc/grpc-swift#697]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

#### Question Description

I am trying to use new `nio` branch of `grpc-swift` repo for communicating with `LND` and have encountered several issues:

- I could not find a way to set TLS certificate from a string (not from file). Apple Nio SSL has `NIOSSLCertificate` class, but is is able to init with file path and byte array only. In old implementation of `grpc-swift` we could init client with `certificates` string argument.

- In old implementation of `grpc-swift` I could also set `Metadata` to connection. I need it to set `macaroons` headers for authentication. In new `nio` branch I could not find a way to set metadata.

It would be great if you could provide some examples for setting options described above.

**Comment by glbrntt** [comment]
> * I could not find a way to set TLS certificate from a string (not from file). Apple Nio SSL has `NIOSSLCertificate` class, but is is able to init with file path and byte array only. In old implementation of `grpc-swift` we could init client with `certificates` string argument.

You can use the `bytes` initializer for `NIOSSLCertificate` by taking the `utf8` view of the string to get the bytes:

```swift
let certificateString: String = ...
let certificateBytes: [UInt8] = Array(certificateString.utf8)
let certificate = try NIOSSLCertificate(bytes: certificateBytes, ...)
```

> * In old implementation of `grpc-swift` I could also set `Metadata` to connection. I need it to set `macaroons` headers for authentication. In new `nio` branch I could not find a way to set metadata.

The `NaturalLanguage` example shows how set metadata [here](https://github.com/grpc/grpc-swift/blob/nio/Examples/Google/NaturalLanguage/Sources/main.swift#L92-L93). Note that you can set default `callOptions` on a generated clien, i.e. `SomeGeneratedClient(connection: connection, defaultCallOptions: callOptions)` or at the RPC level (as in the example).

I agree that we need to pad out the documentation here though.

**Comment by ealymbaev** [comment]
Thank you for your response. We were able to connect using NIO branch. The only issue left is that IP address host does not work yet, but we have created a PR:

https://github.com/grpc/grpc-swift/pull/702
