### ISSUE TITLE
How to suspend receiving from ServerStreamingCall on iOS app?

### ISSUE THREAD

**Issue by KosukeOhmura** [grpc/grpc-swift#705]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
I am making an iOS app using grpc-swift (`nio` branch). My app subscribes Server-Streaming gRPC.

When the app goes to background, I think it is better to cancel the Server-Streaming gRPC for reducing the computing cost of our server. Also when the app come back to foreground, call the Server-Streaming gRPC again.

Is my thinking correct? If so, is there any way to do it easier?

#### Question Description

Here is my implementing plan:

- My app receives from server-side streaming like this:
```swift
let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let connectionConfig = ClientConnection.Configuration(target: .hostAndPort("example.com", 443), eventLoopGroup: eventLoopGroup)
let connection = ClientConnection(configuration: connectionConfig)
let service = MyServiceClient(connection: connection)
let request = MyRequest()
let call = service.listSomething(request) { response in
    print("received: \(response)")
}
call.status.whenComplete { result in
    print("call completed with result: \(result)")
}
```

- When the app goes to background (on `appDidEnterBackground`):
```swift
// 1. cancel the Server-side Streaming call
call.cancel().whenComplete { result in
    print("call canceled with result: \(result)")
    
    // 2. Close the connection
    connection.close().whenComplete { result in
        print("connection closed with result: \(result)")
        
        // 3. Shutdown the EventLoopGroup
        eventLoopGroup.shutdownGracefully { errorOrNil in
            print("eventLoopGroup is shutted down with error: \(errorOrNil)")
        }
    }
}
```

- When the app come back to foreground (on `appWillEnterForeground`):
```swift
//  Create all again from the beginning.
let newEventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let newConnectionConfig = ClientConnection.Configuration(target: .hostAndPort("example.com", 443), eventLoopGroup: newEventLoopGroup)
let newConnection = ClientConnection(configuration: newConnectionConfig)
let newService = MyServiceClient(connection: newConnection)
let newCall = newService.listSomething(request) { response in
    print("received: \(response)")
}
```

**Comment by glbrntt** [comment]
Hey @KosukeOhmura,

That sounds like a reasonable plan, although I don't think shutting down the event loop group is necessary here.

One thing that would improve this is support for the connection to be closed when it becomes idle after 5 minutes of inactivity (for example), and then automatically connect again once a new RPC has been started, i.e. the flow you described above would be:

- start an RPC
- app enters the background
- cancel the RPCs
- after some time the connection becomes idle and disconnects
- app enters the foreground
- start an RPC, the connection is automatically re-established with the server

This is something we'd like to add (I've just created #706 to track it) but don't have at the moment.

**Comment by KosukeOhmura** [comment]
Hi @glbrntt , thanks for the reply.

I understand there is no function that supports suspending but I can do it manually. #706 sounds great!
