### ISSUE TITLE
Close client connection when it becomes idle

### ISSUE THREAD

**Issue by glbrntt** [grpc/grpc-swift#706]
At the moment the client will persist a connection to the server even if there is no active RPCs. Ideally the client should disconnect when the connection becomes idle after 5 minutes of inactivity, for example. On starting an RPC the client should re-establish a connection to the server.

**Comment by MrMage** [comment]
We could also consider adding on option for this to the _server_, to have it enforce conserving of server-side resources.

**Comment by audio-algorithms** [comment]
this is so stupid. managing a connection is the responsibility of the application.
