### ISSUE TITLE
Support for Cronet in grpc-swift

### ISSUE THREAD

**Issue by ypyu2000** [grpc/grpc-swift#715]
Hi, We would like to know if we can have [Cronet](https://chromium.googlesource.com/chromium/src/+/master/components/cronet/) support for grpc-swift, especially as it moves to support swift NIO. Cronet has various advantages, including QUIC support that ensures much better performance in terms of network latencies and error rates.

Thanks

James

**Comment by MrMage** [comment]
We use NIO's underlying transport mechanism. That pretty much excludes the possibility of using Cronet in the NIO version.
