### ISSUE TITLE
TLS handshake completed, no protocol negotiated

### ISSUE THREAD

**Issue by gitrema** [grpc/grpc-swift#716]
# Question Checklist
[x] Updated grpc-swift to the latest version
[x] I read the Contribution Guidelines
[x] I read README
[x] I searched for existing GitHub issues (especially, there are many resolved issues related to SSL)

## Question Subject
version: 1.0.0-alpha.9

I use gRPC Swift for developing an iOS app. When I call unary RPC I get a grpc client error with the description `UnableToParseFrame()`

Can I get some help in identifying the issue?

## Question Description

Here the relevant logs
```
request_id=9F6FB145-D6A6-4C02-B0F3-9D8B515E048F starting rpc
2020-02-06T10:06:24+0100 debug: TLS handshake completed, no protocol negotiated
2020-02-06T10:06:29+0100 error: error=UnableToParseFrame() grpc client error
```
Trying to narrow it down it seems the error is a wrong frame size received on the http/2 pipeline.
 I have no idea how this can happen, what smells to me is the `no protocol negotiated` that can lead the server to not switch to http/2 and thus sending text data that can can be wrongly interpreted by swiftNIO-http2 library.

This is the server response using `curl`
```
*   Trying 35.186.224.0...
* TCP_NODELAY set
* Connected to xxxxxxxxxx (xxx.xxx.xxx.xxx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: *omissis*
*  start date: May 16 00:00:00 2017 GMT
*  expire date: Jul 29 12:00:00 2020 GMT
*  subjectAltName: host "*omissis*" matched cert's "*omissis*"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fbccb001200)
> GET / HTTP/2
> Host: *omissis*
> User-Agent: curl/7.64.1
> Accept: */*
```

**Comment by glbrntt** [comment]
@gitrema how are you creating your TLS configuration?

If you're using [the preferred `init`](https://github.com/grpc/grpc-swift/blob/86c421efdcc5a5ff27c33ed9ca887d748ac5482d/Sources/GRPC/TLSConfiguration.swift#L86) then the `grpc-exp` and `h2` protocols will be offered for ALPN.

If you use the [`init` where you provide `NIO.TLSConfiguration`](https://github.com/grpc/grpc-swift/blob/86c421efdcc5a5ff27c33ed9ca887d748ac5482d/Sources/GRPC/TLSConfiguration.swift#L105) then it's up to you to ensure that the correct protocols are set in the `NIO.TLSConfiguration`.

**Comment by gitrema** [comment]
Hey @glbrntt thanks a lot for your advice.

I had

```
 tls: ClientConnection.Configuration.TLS.init(
                    configuration: TLSConfiguration.forClient()
                        )
```

using the preferred `init` as you suggested fix the protocol negotiation and now I get `grpc-exp` and everything works as expected.

Thanks again for your help

**Comment by glbrntt** [comment]
No problem!
