### ISSUE TITLE
Certificate pinning with NIO?

### ISSUE THREAD

**Issue by phlippieb** [grpc/grpc-swift#723]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

Does the NIO implementation of Swift GRPC support certificate pinning? If so, how do I use it?

#### Question Description

I should preface this by saying I only have a basic grasp on certificate pinning and TSL in general. My understanding of it is as follows: instead of trusting any certificate signed by any of the default trust roots provided by my OS, certificate pinning means that I specify which specific certificate I want to trust, and any connection signed by any other certificate should fail to authenticate.

I have tried the following in order to use this:

**1. Got the certificate from our server**

I ran
```
openssl s_client -servername <servername> -host <hostname> -port <port> -showcerts < /dev/null
```

which yielded 2 certificates.

**2. Instantiated the certificates in code**

```
let certificateString1 = """
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
        """

let certificateString2 = """
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
        """

func getCertificate(for certificateString: String) -> NIOSSLCertificate? {
        do {
            let bytes: [Byte] = certificateString.utf8.map { $0 }
            let certificate = try NIOSSLCertificate(bytes: bytes, format: .pem)
            return certificate
        } catch let error {
            print(error)
            return nil
        }
}

let certificate1 = getCertificate(for: certificateString1)!
let certificate2 = getCertificate(for: certificateString2)!
let certificates = [certificate1, certificate2]

let certificateSource1 = NIOSSLCertificateSource.certificate(certificate1)
let certificateSource2 = NIOSSLCertificateSource.certificate(certificate2)
let certificateSources = [certificateSource1, certificateSource2]
```

**3. Created some different TLS configurations**

Configuration A:
- My certificates given as the chain
- Empty trust roots

```
let tlsA = ClientConnection.Configuration.TLS(
        certificateChain: certificateSources,
        trustRoots: .certificates([]))
```

Configuration B:
- Empty certificate chain
- My certificates given as the trust roots

```
let tlsB = ClientConnection.Configuration.TLS(
        certificateChain: [],
        trustRoots: .certificates(self.certificates))
```

Configuration C:
- My certificates given as the chain
- My certificates given as the trust roots

```
let tlsC = ClientConnection.Configuration.TLS(
        certificateChain: certificateSources,
        trustRoots: .certificates(self.certificates))
```

Configuration D:
- Using the default certificate chain
- My certificates given as the trust roots

```
let tlsD = ClientConnection.Configuration.TLS(
        trustRoots: .certificates(self.certificates))
```

Configuration E:
- Using my certificates as the chain
- Using the default trust roots

```
let tlsE = ClientConnection.Configuration.TLS(
        certificateChain: certificateSources)
```

**4. Created and used a client connection with each of these TLS configurations.**

I won't post the code here, but I will note that this part works fine if I do not attempt to set up certificate pinning; when I just pass `tls: .init()` to my client connection configuration, my endpoint calls authenticate correctly and everything. Things only start breaking once I use one of the configurations above.

**5. Results**

With configurations A-D, I get errors like these:

Errors:
```
2020-02-14T09:07:46+0200 error: error=handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268435581 error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED])) error caught before TLS was verified
2020-02-14T09:07:46+0200 error: error=handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268435581 error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED])) grpc client error
2020-02-14T09:07:46+0200 notice: connection_id=21C06D0C-1C94-4903-BCDF-8BE8B6DD86D2 error=handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268435581 error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED])) connection attempt failed
```

When I use configuration E, the call succeeds; however, when I change the certificate (by substituting some of the caracters with `0`s), the call *still* succeeds, which indicates that my certificates are not being used for authentication at all. This makes sense; the certificates are signed by trusted CAs, so using the default trust roots would cause my connection to succeed.

**Overview**

My own inexperience with TLS makes it difficult for to pinpoint whether my problems originate from my own code, the Swift GRPC / NIO SSL libraries, or the server. So it would be extremely helpful if someone could tell me whether Swift GRPC supports certificate pinning, and if so, how to use it.

**Comment by weissi** [comment]
CC @lukasa

**Comment by Lukasa** [comment]
Without seeing your certificates it’s hard to know whether you can successfully pin them with the APIs we have today. In particular, NIOSSL only lets you set trust _roots_: these must be self-signed, and the root of the certificate chain. We don’t support pinning of the form “we require that this certificate be the leaf”. Given that you say your certificates are signed by trusted roots, that suggests that they are not self-signed, which means the current support doesn’t work.

The way to implement certificate pinning today _with NIOSSL_ is:

1. Create NIOSSL certificates for the certificates you want to pin.
2. Create a custom certificate callback.
3. Check whether the certificates in the certificate chain are equal to the certificate you want (probably just the leaf).

grpc-swift may not have the API for this today, in which case grpc-swift could add it. We could also consider adding a convenience helper for NIOSSL.

Note that Network.framework uses a totally different TLS API, so even if we add support in NIOSSL grpc-swift would need to be able to handle this with Network.framework’s NWProtocolTLS as well.

**Comment by jcgonlop** [comment]
Hi everyone, is there any progress on this issue?

**Comment by Lukasa** [comment]
@jcgonlop What is the specific functionality you are missing from the above list? I believe I outlined the current state of affairs, so it'd be good to know what is failing you there.

**Comment by jcgonlop** [comment]
@Lukasa is this feature scheduled to be added to grpc-swift anytime soon?
