### ISSUE TITLE
TCP connection seems closed after one successful GRPC call

### ISSUE THREAD

**Issue by manyoo** [grpc/grpc-swift#725]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

#### Question Description

We've been using grpc-swift for a few months in our iOS app.  We were using the old cGRPC based version and creating new channels whenever user switches between wifi and cellular.

We decided to switch to the new nio based version recently and I'm really glad with the new steaming API.  But I incorrectly used the MultiThreadEventLoopGroup at first, the app works pretty good except the connection drop after switching from wifi to LTE. (But it works switching from LTE to wifi).

Now, I switched to use this:

```
let group = PlatformSupport.makeEventLoopGroup(loopCount: 1, networkPreference: .best)
let config = ClientConnection.Configuration(target: .hostAndPort(url, port), eventLoopGroup: group)
connection = ClientConnection(configuration: config)
```

to create the connection on iOS 13, which should handle the connectivity issue automatically, right?  Then the connection is shared by all generated ServiceClient objects.

With NIOTSEventLoopGroup, the app can call the first GRPC call correctly. But subsequent calls will do nothing (no error/success response) and it seems the TCP connection is closed after the first call.

Am I doing things wrong or is it a bug? 

Thanks.

**Comment by glbrntt** [comment]
Hmm, that doesn't sound right at all! Could you enable trace logging and attach the logs when you do this? You can enable trace logging with the following (you'll need to import `Logging` and ensure this only runs once per process): 

```swift
LoggingSystem.bootstrap {
  var handler = StreamLogHandler.standardOutput(label: $0)
  handler.logLevel = .trace
  return handler
}
```

**Comment by MrMage** [comment]
Closing this for being stale; please provide more info if this is still relevant.
