### ISSUE TITLE
Using `nio` branch: `module 'SwiftProtobuf' has a minimum deployment target of iOS 13.2`

### ISSUE THREAD

**Issue by khairilushan** [grpc/grpc-swift#732]
So I'm trying to use new GRPC (`nio`) into my project. I imported the GRPC.xcodeproj that I got from `swift package generate-xcodeproj`into my project.
When I try to build the project I got this error message

```
Compiling for iOS 10.0, but module 'SwiftProtobuf' has a minimum deployment target of iOS 13.2: /Path/To/My/Project/Project_name-baptfxahalvegoenxukxxrnugwha/Build/Products/Release-iphonesimulator/SwiftProtobuf.framework/Modules/SwiftProtobuf.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

and

```
Could not find module 'SwiftProtobuf' for target 'i386-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64
```

Is it not possible to use the `nio` branch in app that still target iOS version below 13.x ?

**Comment by glbrntt** [comment]
It's possible to use the `nio` branch for iOS 10.0 and newer. The minimum platforms supported are also listed in [`Package.swift`](https://github.com/grpc/grpc-swift/blob/38484c0b0eb5726dc61d570c0c378a2cc2af56c8/Package.swift#L24).

It sounds like you need to set the minimum deployment versions of various targets in your project. Can you try setting them to the minimum version of iOS you support?

As a side note, with Xcode 11+ you can add a Swift package directly to a project without having to check out the source code and generate the project yourself (File > Swift Packages > Add Package Dependency).

**Comment by khairilushan** [comment]
Hi @glbrntt thank you so much for your response.

So I tried using Swift GRPC via SPM. To give more context here is the architect of the app

App -- depends on --> My Cocoa touch Framework -- depens on --> Swift GRPC

I added the SwiftGRPC to my framework. But when I ran the app I got error `No such module 'GRPC'`

Should I also add Swift GRPC into my app (via SPM) ?

**Comment by glbrntt** [comment]
> I added the SwiftGRPC to my framework. But when I ran the app I got error `No such module 'GRPC'`

Is this _after_ setting the minimum deployment versions?

**Comment by khairilushan** [comment]
My deployment target is set to `iOS 10` from the beginning. It's the same for app and my framework. 

Btw that's happen when I am using Swift package manager to add swift-grpc to app and my framework.

**Comment by glbrntt** [comment]
Sorry, I'm not sure what your problem is at the moment. Is it the `Compiling for iOS 10.0, but module 'SwiftProtobuf' has a minimum deployment target of iOS 13.2` error or the `No such module 'GRPC'`?

**Comment by khairilushan** [comment]
When I tried to build and import the Swift GRPC project manually I got this `Compiling for iOS 10.0, but module 'SwiftProtobuf' has a minimum deployment target of iOS 13.2`.

But now, I am using Swift package manager, I got this `No such module 'GRPC'`. So that's my issue right now.

**Comment by glbrntt** [comment]
Is `GRPC` missing from "Link Binary With Libraries" for the target you're trying to build (or any dependencies that depend on gRPC Swift)?

**Comment by khairilushan** [comment]
GRPC is there. In my App target and my framework target. 
![Screen Shot 2020-03-02 at 19 18 51](https://user-images.githubusercontent.com/1143117/75675942-ceb71980-5cba-11ea-9b2a-0bf1568839ed.png)

**Comment by glbrntt** [comment]
Hmm... could you create and share a minimal project which reproduces this?

**Comment by JanC** [comment]
I'm jumping into to conversation to try to help ..
@khairilushan could you maybe provide a small sample project to reproduce it?

**Comment by khairilushan** [comment]
> Hmm... could you create and share a minimal project which reproduces this?

When trying to create minimal project to help reproduce this, I got it work on that sample project. with the same setup:

App -- depends on --> My Cocoa touch Framework -- depens on --> Swift GRPC

> in that case you need to link `My Cocoa touch Framework` to `GRPC` (not the main app)

Thank you for your help. But I've tried this. And still got the same result

**Comment by khairilushan** [comment]
> Hmm... could you create and share a minimal project which reproduces this?

After change the build configuration from `Debug/Release` to `Dev/Staging/Production` I succeed to reproduced the issue

[GRPCSample.zip](https://github.com/grpc/grpc-swift/files/4275469/GRPCSample.zip)

**Comment by glbrntt** [comment]
@khairilushan it seems like the build configuration must be present in both `.xcodeproj`s. In the sample you uploaded I created a "Staging" build configuration for the "Data" project and then I was able to compile it.

**Comment by khairilushan** [comment]
@glbrntt aaah haven't tried that. I'm on train right now. Will definately try it when arrive at home. 😅
Thank you so much. 🙏🙏

**Comment by glbrntt** [comment]
No problem! Closing this for now, feel free to re-open if this doesn't solve your problem.

**Comment by khairilushan** [comment]
> No problem! Closing this for now, feel free to re-open if this doesn't solve your problem.

Yeah, it's work. THANK YOU!!
