### ISSUE TITLE
Remove init() method from generated struts from message

### ISSUE THREAD

**Issue by Banck** [grpc/grpc-swift#737]
Hello!
As I noticed, you add init() method for all structs, which were generated from messages from proto.
That's why we can't init our models with default swift structs init method with all params.
Example:
```
struct GetLocalizationsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var platform: String = String()

  var appName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}
```
If you remove init() then we will can init GetLocalizationsRequest like:
`GetLocalizationsRequest(platform: "iOS", appName: "client")
`

**Comment by glbrntt** [comment]
Hey @Banck, the message generation is handled by SwiftProtobuf: https://github.com/apple/swift-protobuf please redirect your question there. 

FWIW, the generated messages have a `.with` constructor: 

```swift
let request = GetLocalizationsRequest.with {
  $0.platform = "iOS"
  $0.appName = "client"
}
```
