### ISSUE TITLE
GRPCProtobufPayload issue with import proto in another proto

### ISSUE THREAD

**Issue by Banck** [grpc/grpc-swift#738]
Hello!
Let's imagine we have 2 (or more) protos. And in one proto we imported another one.
In this case, in every *.grpc.swift will be generated extensions for the same messages with conform GRPCProtobufPayload protocol.
For example:
Devices has RegisterRequest and ResponseRequest.
And Video looks like:
```
syntax = "proto3";

option java_package = "*";

import "google/protobuf/empty.proto";
import "devices_services.proto";

service Videos {
    rpc test (RegisterRequest) returns (RegisterResponse);
}
```

Then in `devices_services.grpc` will be 
```
/// Provides conformance to `GRPCPayload` for the request and response messages
extension RegisterRequest: GRPCProtobufPayload {}
extension RegisterResponse: GRPCProtobufPayload {}

```

and in videos_services.grpc will be the same lines:
```
/// Provides conformance to `GRPCPayload` for the request and response messages
extension RegisterRequest: GRPCProtobufPayload {}
extension RegisterResponse: GRPCProtobufPayload {}
```

**Comment by glbrntt** [comment]
Hey @Banck -- thanks for the report; I'm aware of this and will look into it. 

As a precautionary note: as the grpc-swift API hasn't fully stabilised yet you should prefer pinning to a tagged version, i.e. `1.0.0-alpha.9`, and build the protoc plugin at that same tag. (I say this as the issue you mention here hasn't yet been tagged.)
