### ISSUE TITLE
Using `*.crt` file as Certificate using `nio` branch

### ISSUE THREAD

**Issue by khairilushan** [grpc/grpc-swift#739]
I just migrated to the `nio` branch and kinda confuse with the way to use `*.crt` file that I used to pass on the `Client` class constructor.

```
let resourceName = "crt.filename.here"
let bundle = Bundle(for: self)
		
if let certificateURL = bundle.url(forResource: resourceName, withExtension: "crt"),    
   let certificate = try? String(contentsOf: certificateURL) else {
	client = Protobuf_OrderServiceServiceClient(address: address, certificates: certificate)
} else {
	client = Protobuf_OrderServiceServiceClient(address: address)
}	
```

What is the new way of doing this?

**Comment by glbrntt** [comment]
We defer to [SwiftNIO SSL](https://github.com/apple/swift-nio-ssl) for our SSL; to load your certificate chain from file you can use the `fromPEMFile(_:)` method on `NIOSSLCertificate`.

You can then provide the certificates to your TLS configuration and then to your client configuration:

```swift
```

**Comment by glbrntt** [comment]
We defer to [SwiftNIO SSL](https://github.com/apple/swift-nio-ssl) for our SSL; to load your root certificates from file you can use the `fromPEMFile(_:)` method on `NIOSSLCertificate`.

You can then provide the certificates to your TLS configuration and then to your client configuration:

```swift
let certs = try NIIOSSLCertificate.fromPEMFile("foo.crt")
let tls = ClientConnection.Configuration.TLS(trustRoots: .certificates(certs))
let configuration = ClientConnection.Configuration(..., tls: tls)
```

There is also some documentation [here](https://github.com/grpc/grpc-swift/blob/nio/docs/tls.md).

**Comment by khairilushan** [comment]
Thank you so much for that code sample. Is there any relation between this TLS config with error `ioOnClosedChannel` ? I keep getting this error now.

**Comment by khairilushan** [comment]
> Thank you so much for that code sample. Is there any relation between this TLS config with error `ioOnClosedChannel` ? I keep getting this error now.

Yep, this one due to incorrect certificate setup. I am able to stream the data from my gRPC server. Thank you so much @glbrntt !
