### ISSUE TITLE
Pause and resume streaming?

### ISSUE THREAD

**Issue by khairilushan** [grpc/grpc-swift#741]
Hi, is there any way to pause and resume `BidirectionalStreamingCall` or `ServerStreamingCall` ?

**Comment by glbrntt** [comment]
Not at the moment I'm afraid. There's currently no manual flow control for client calls with response streams; this is something we plan on adding soon, however.

If you're not interested in this from a flow control standpoint then it should be fairly straightforward to just write into a buffer and read from it whenever you want to read responses.
