### ISSUE TITLE
Q about syncShutdownGracefully

### ISSUE THREAD

**Issue by Banck** [grpc/grpc-swift#742]
Hello!
Sorry, if it's not the best place for question.
But I want to ask about the best approach for syncShutdownGracefully.

I have a Managers - it's structs with static methods where I make grpc calls.
Here it is:
```
struct DeviceManager {
    static func getConfig() -> EventLoopFuture<GetConfigResponse> {
        let group = PlatformSupport.makeEventLoopGroup(loopCount: 1)
        let config = ClientConnection.Configuration(
            target:  .hostAndPort("...", 443),
            eventLoopGroup: group,
            tls: ClientConnection.Configuration.TLS.init(configuration: .forClient(applicationProtocols: ["h2"]))
        )
        let connection = ClientConnection(configuration: config)
        let client = DevicesServiceClient(channel: connection)
        let future = client.getConfig(Google_Protobuf_Empty()).response
        return future
    }
    
    static func updateDevice() -> EventLoopFuture<Google_Protobuf_Empty> {
        let group = PlatformSupport.makeEventLoopGroup(loopCount: 1)
        let config = ClientConnection.Configuration(
            target:  .hostAndPort("...", 443),
            eventLoopGroup: group,
            tls: ClientConnection.Configuration.TLS.init(configuration: .forClient(applicationProtocols: ["h2"]))
        )
        let connection = ClientConnection(configuration: config)
        let client = DevicesServiceClient(channel: connection)
        let request = UpdateRequest()
        let future = client.update(request).response
        return future
    }
}
```
And call it like: `DeviceManager.updateDevice()` etc.

In the example I saw, that we should call syncShutdownGracefully like that:
 ```
   let group = PlatformSupport.makeEventLoopGroup(loopCount: 1)
   defer {
     try! group.syncShutdownGracefully()
   }
```
but if I call like this, grpc call will shutdown immediately.

What should I add to my methods or everything is fine? Thanks!

**Comment by glbrntt** [comment]
Hey @Banck,

Generally speaking your connection should be longer lived than a single RPC otherwise you pay the cost of spinning up a connection each time. This is especially bad when you're using TLS since you have the extra round-trips from the handshake.

The event loop group should live at least as long as your connection; note that they may also be shared across different connections.

I would suggest _not_ having static methods here for `updateDevice` and `getConfig` since they rely on objects - the connection and event loop group - which must be setup and shutdown at appropriate times.

One additional note about your TLS configuration:

```swift
let configuration = ClientConnection.Configuration(
  ...
  tls: ClientConnection.Configuration.TLS.init(configuration: .forClient(applicationProtocols: ["h2"]))
)
```

You should prefer the other `TLS` init over the `TLS(configuration:)`; it sets a number of defaults (including the application protocols to offer for ALPN) in accordance with the gRPC spec. You should be able to just set `tls: .init()` within `Configuration`.

**Comment by Banck** [comment]
@glbrntt thanks for your help. 
So if I understood correctly, at least I have to call `group.syncShutdownGracefully()` when call will be completed(or with error), in `.whenComplete()` block, for example. 
Right?

**Comment by Banck** [comment]
Or I have to init client only once and use it in whole app and call shutdown when app is closing..?

**Comment by glbrntt** [comment]
@Banck no problem. You *should not* call `group.syncShutdownGracefully()` in `whenComplete()`: the group that you're shutting down provides the event loop on which `whenComplete()` is running. You _can_ shutdown the group when the app is closing.

**Comment by Banck** [comment]
And use one group in all rpc calls, right? So it will looks something like that:
```
var defaultConnection: ClientConnection = {
    let group = PlatformSupport.makeEventLoopGroup(loopCount: 1)
    let config = ClientConnection.Configuration(
        target:  .hostAndPort("mobile-dev.ozzitv.com", 443),
        eventLoopGroup: group,
        tls: .init()//ClientConnection.Configuration.TLS.init(configuration: .forClient(applicationProtocols: ["h2"]))
    )
    let connection = ClientConnection(configuration: config)
    return connection
}()
```
 ```
let client = SomeClient(channel: defaultConnection)
 var request = SomeRequest()
 let future = client.getSomethig(request).response
```

**Comment by glbrntt** [comment]
Yup, that's right! :)

**Comment by Banck** [comment]
Thanks a lot for your help
