### ISSUE TITLE
[nio] Initialize generic GRPCClient

### ISSUE THREAD

**Issue by jongarate** [grpc/grpc-swift#747]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

My backend team generated `NIO` aware client code for a gRPC API service. Here's a sanitized example of this code:

```
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf

internal protocol Generated_Service {
  func domainAction(_ request: Generated_Request, callOptions: CallOptions?) -> UnaryCall<Generated_Request, Domain_Data>
}

internal final class Domain_DataServiceServiceClient: GRPCClient, Generated_Service {
  internal let connection: ClientConnection
  internal var defaultCallOptions: CallOptions

  internal init(connection: ClientConnection, defaultCallOptions: CallOptions = CallOptions()) {
    self.connection = connection
    self.defaultCallOptions = defaultCallOptions
  }

  internal func domainAction(_ request: Generated_Request, callOptions: CallOptions? = nil) -> UnaryCall<Generated_Request, Domain_Data> {
    return self.makeUnaryCall(path: "/Domain.Service/DomainAction",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }
}
```

#### Question Description

Since there are many similar cases of API calls to be performed, I'm thinking of extracting a general "getter" of sorts to centralize timeout and authorization establishment:

```
public func get(token: String, service: GRPCClient.Type) -> GRPCClient {
    let configuration = ClientConnection.Configuration(target: .hostAndPort("api.example.com", 443),
                                                       eventLoopGroup: MultiThreadedEventLoopGroup(numberOfThreads: 1),
                                                       tls: .init())
    let connection = ClientConnection(configuration: configuration)
    var headers = HPACKHeaders()
    headers.add(name: "authorization", value: "Bearer \(token)")
    let callOpts = CallOptions(customMetadata: headers,
                               timeout: .seconds(rounding: 5))
                               
    return service.init(connection: connection, defaultCallOptions: callOpts)
}
```

However, I see in the library that `GRPCClient` doesn't define an `init()` method (kind of expected since it's just a `protocol`). What I find surprising is that all generated code defines it the same way, even `AnyServiceClient`:

```
/// A client which has no generated stubs and may be used to create gRPC calls manually.
/// See `GRPCClient` for details.
public final class AnyServiceClient: GRPCClient {
  public let connection: ClientConnection
  public var defaultCallOptions: CallOptions

  /// Creates a client which may be used to call any service.
  ///
  /// - Parameters:
  ///   - connection: `ClientConnection` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(connection: ClientConnection, defaultCallOptions: CallOptions = CallOptions()) {
    self.connection = connection
    self.defaultCallOptions = defaultCallOptions
  }
}
```

Anybody got experience working around this?

**Comment by glbrntt** [comment]
Hey @jongarate, 

It's not clear to me what problem you're trying to solve here. Is it that you have many generated clients and you want a factory that provides them with an active connection and some default call options?

**Comment by jongarate** [comment]
Hi @glbrntt,

You could say so. The main motivation here is to define all general connectivity settings in a single place and make all clients use it with the least possible boilerplate.

**Comment by glbrntt** [comment]
If the `host` for all of your services is the same you really should avoid creating a connection for each client, you can re use it for different services. As such your factory should really be parameterised with the connection as well as the service type and token.

We updated the `GRPCClient` protocol recently to include an `init`. I'm hoping to tag a release next week in which case you should be a able to define something similar to what you have now:

```swift
func make<Client: GRPCClient>(_ client: Client.Type, channel: GRPCChannel, ...) -> Client {
  // ...
}
```

Note that `ClientConnection` conforms to `GRPCChannel` (similar story: not yet tagged in a release).

**Comment by jongarate** [comment]
You're right regarding the connection instance. Since the whole scheme is more about adding the latest authorization header to each call (which fits in `CallOptions`), it doesn't make sense create a brand new connection each time. I'll have a look into that.

Regarding the `GRPCClient`, it's good to know that at least it's on the roadmap. For now I simply resorted to centralizing a `Context` struct that I then feed to each instance:

```
public struct Context {
    public let connection: ClientConnection
    public let callOptions: CallOptions
}
```
like so:
```
let context = getContext()
Domain_DataServiceServiceClient(connection: context.connection, defaultCallOptions: context.callOptions)
```

For now, it's keeping the boilerplate within a manageable scale.

Thanks for the quick support @glbrntt 🙏

**Comment by glbrntt** [comment]
No problem!
