### ISSUE TITLE
No ability to provide  pem_root_cert, pem_private_key and pem_cert_chain 

### ISSUE THREAD

**Issue by punitpawarapple** [grpc/grpc-swift#75]
Hello
I am trying to do a GRPC Call and I require to provide 3 parameters  rootcert, privateKey and the certChain 

I am using Swift3 and Swift-Grpc Release# 0.1.12
I have not upgraded to Swift4 yet since most of us are still dependent on using Swift3

The channel support section in https://github.com/grpc/grpc-swift/blob/master/Sources/CgRPC/include/CgRPC.h  does not have this ability any more

did something change ?
How can we go about providing all the three parameters ?

This functionality below  existed in Swft-Grpc  0.1.9 Release , but does not seem to exist in the later release  0.1.12

// Adding support for private key and cert chain
cgrpc_channel *cgrpc_channel_create_securev2(const char *address,
                                           const char *pem_root_certs,
                                           const char *pem_private_key,
                                           const char *pem_cert_chain);

IS there a different way now to pass in all the three parameters?

your response will be appreciated..

**Comment by timburks** [comment]
I don't see that function declaration in the [0.1.9-tagged version of CgRPC.h](https://github.com/grpc/grpc-swift/blob/0.1.9/Sources/CgRPC/include/CgRPC.h). Could it have been added to a local copy that you have?

I believe that the root certificates can be passed by concatenating them with pem_cert_chain.

**Comment by punitpawarapple** [comment]
hmm , let me check if it was added to the local copy that I have. ( You might be right )
So your recommendation is to try to concatenate root certificate with pem_cert_chain ?
Is there a way this concatenation needs to be done ? 

And as far as your understanding goes , at the moment there is no ability to pass all the above three parameters separately correct ?

Thanks Again for replying

**Comment by Gurpartap** [comment]
Concatenating (cert chaining) is an acceptable way of bundling the CA certs together, from the otherwise unrecognized root CA, leading up to the intermediate that signed yours.

```swift
let certs = [certa, certb].join("\n")
```

Pass it to [secure Server.init()](https://github.com/grpc/grpc-swift/blob/1ef3b54deacccf9c683cf17a0d442b0b29c7fe66/Sources/gRPC/Server.swift#L55). Should work.

**Comment by MrMage** [comment]
Should be obsolete, as we do support e.g. client authentication & co. by now.
