### ISSUE TITLE
How to get the error status with details

### ISSUE THREAD

**Issue by AhmedAskar** [grpc/grpc-swift#759]
There doesn't seem to be any support for deserialising error status details, as implemented in the grpc library. The Status Object type here only supports details as a string.

The status details binary can be found in the Call Result object in trailing metadata by key "grpc-status-details-bin". I've tried to create a new Status object by intializing it with this formatted string and then I got an error. 

Is there any way to get this status object directly or how I can get the status object from the call result.

@MrMage Would you please advice?

**Comment by MrMage** [comment]
`grpc-status-details-bin` is not an official part of the gRPC spec. You should be able to access that header field via the metadata, base-64 decode it, and then deserialize a Proto from it. Implementing that would be up to you; it is not directly related to this project.

**Comment by FranzBusch** [comment]
@glbrntt I understand that `grpc-status-details-bin` is not part of the official spec but at least the [Go](https://github.com/grpc/grpc-go/blob/ca62c6b92c334f52c7e48b7cbf624f3b877fb092/internal/transport/http_util.go#L317) and the [Java](https://github.com/grpc/grpc-java/blob/eda5e2e32c1f80af8631db6fecf0341b40b09692/protobuf/src/main/java/io/grpc/protobuf/StatusProto.java#L37) implementation of grpc both support this. Is this enough to make the case to add this functionality to grpc-swift?

**Comment by MrMage** [comment]
@FranzBusch you should be able to implement this yourself with roughly 5 lines of code, no change to this library needed. Is that not sufficient?

**Comment by FranzBusch** [comment]
@MrMage I totally understand the point you are making and also know that it is quite trivial to implement the `grpc-status-details-bin` logic in a couple of lines. The only reason why I was asking is because of the disparity between the `grpc-go` & `grpc-java` implementation and the `grpc-swift` one. I just want to grasp if it makes sense to add this or it is generally not desired. I would also be willing to open a PR for this.

My current approach was to simply do this (disregard the force try and unwraps):
```swift
// Server
let localizedMessage = Google_Rpc_LocalizedMessage.with {
    $0.locale = "de"
    $0.message = "Es ist ein unerwarteter Fehler aufgetreten."
}
let anyLocalizedMessage = try! Google_Protobuf_Any(message: localizedMessage)
let status = Google_Rpc_Status.with {
    $0.code = Int32(Google_Rpc_Code.unauthenticated.rawValue)
    $0.message = "This is an error"
    $0.details = [anyLocalizedMessage]
}
let data = try! status.serializedData()
let string = data.base64EncodedString()
context.trailingMetadata = ["grpc-status-details-bin": string]

// Client
update.trailingMetadata.whenComplete { result in
    guard case let .success(value) = result else { return }
    guard let statusDetails = value.first(name: "grpc-status-details-bin") else { return }
    guard let data = Data(base64Encoded: statusDetails) else { return }

    let status = try! Google_Rpc_Status(serializedData: data)
    let first = status.details.first!
    let message = try! Google_Rpc_LocalizedMessage(serializedData: first.value)
}
```

This can definitely be implemented smarter and better to use.

**Comment by MrMage** [comment]
Thanks! I would be open to reviewing a PR this as long as it does not violate our goal of also supporting other message formats such as Flatbuffers.

@glbrntt, what do you think?

**Comment by glbrntt** [comment]
I think that would be fine as long as the changes are framed as getting/setting binary metadata as opposed to just "grpc-status-details-bin".
