### ISSUE TITLE
Question: Integrating Performance Monitoring & Request Timing

### ISSUE THREAD

**Issue by orj** [grpc/grpc-swift#766]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Timing Requests

#### Question Description
I'm looking at trying to integrate a vendor library (Dynatrace) into our application that uses swift-grpc. Dynatrace already automatically instrument (and provide timing data) for URLSession based requests.  I'm trying to implement the same sort of request timing for our gRPC based calls.

I have a few challenges:

1. There doesn't appear to be an easy way to observe the state of a call in progress other than wrapping it in code like the following:

```
func getAccounts(promise: @escaping (Result<AccountsAPI_GetAccountListResponse, Error>) -> Void) {
  let url = ... // ⁉️ There doesn't seem to be a way of getting a "URL" like string from a UnaryCall even though all the data I need appears to be in the _GRPCRequestHead.
  let timer = startRequestTimer(url)

  var options = accountsService.defaultCallOptions
  if let serviceHeader = timer.serviceHeader {
    options.customMetadata.add(name: serviceHeader.key, value: serviceHeader.value)
  }

  let call = accountsService.getAccountList(AccountsAPI_GetAccountListRequest(), callOptions: options)

  call.status.whenComplete { timer.stop(status: try! $0.get()) }
  call.response.whenComplete(promise)
```

Ideally it would be nicer if there was some sort of `UnaryCallMonitoringDelegate` (or something) on `GRPCClient` that was invoked for each call request/response.  Then I could create a generic delegate handler that recorded metrics for each call.  I could just maintain a set of timers in the delegate against requestIDs.

2. As noted above there doesn't seem to be a way to get something "URL-ish" from the GRPC service or UnaryCall once constructed, the library I'm using needs that for constructing request timers.

I would appreciate any guidance on how to proceed.

**Comment by glbrntt** [comment]
Hey @orj, 

I'm absolutely onboard with exposing a way to time requests. 

I think the easiest way to resolve this would be via [swift-metrics](https://github.com/apple/swift-metrics) rather than building out an interceptor layer for the RPCs (which is something we'd like to have but it's not a priority at the moment). In this approach gRPC would emit metrics to the metrics system and the system would emit them to a metrics backend which you would provide. Would this approach using the APIs that Dynatrace provide work for you?

**Comment by orj** [comment]
I'm not sure. Maybe on the backend, but the use case I have is client side.  Their SDK client side is pretty targeted to patterns established by `URLSession`.  Their docs for measuring requests are [here](https://www.dynatrace.com/support/help/technology-support/operating-systems/ios/customization/oneagent-sdk-for-ios/#expand-1114measure-web-requests).

One thing I don't think SwiftMetrics would help with is that Dynatrace want you to include a header in each request sent to the server (I assume for correlation/tracing purposes).

I believe Dynatrace is joining the [OpenTelemetry](https://www.dynatrace.com/news/blog/dynatrace-joins-the-opentelemetry-project/) project. So perhaps if SwiftGRPC (or SwiftMetrics) supported OpenTelemetry then all of this would be moot.

**Comment by MrMage** [comment]
FYI, I am also a fan of request tracing. My current approach is to "wrap" all request handler implementations in a call that does some "middleware processing", including request tracing.

**Comment by orj** [comment]
@MrMage Can you share an example of what you are doing?

**Comment by orj** [comment]
I think most of what I want to do could be achieved if `ClientConnection` was open and I just overloaded `makeUnaryCall` (if that is even possible with generics).

**Comment by glbrntt** [comment]
> I'm not sure. Maybe on the backend, but the use case I have is client side. Their SDK client side is pretty targeted to patterns established by `URLSession`. Their docs for measuring requests are [here](https://www.dynatrace.com/support/help/technology-support/operating-systems/ios/customization/oneagent-sdk-for-ios/#expand-1114measure-web-requests).

Their documentation doesn't fill me with hope that using swift-metrics is a workable solution!

 > I think most of what I want to do could be achieved if `ClientConnection` was open and I just overloaded `makeUnaryCall` (if that is even possible with generics).

This should be possible actually, although not by overloading. Generated clients require a `GRPCChannel` so you could also implement a wrapper which conforms to `GRPCChannel` but delegates the actual work to `ClientConnection`.

**Comment by orj** [comment]
@glbrntt Right. I hadn't thought specifically of doing that. I'll give that a go! See how I fair.

**Comment by orj** [comment]
@glbrntt In my codebase I went with wrapping `ClientConnection` in a decorator that implemented `GRPCChannel`.  At least for `UnaryCall`s it has worked out well. Thanks for the suggestion.

**Comment by glbrntt** [comment]
No problem!
