### ISSUE TITLE
Contribution for CocoaPods Support on NIO implementation

### ISSUE THREAD

**Issue by pacu** [grpc/grpc-swift#767]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
CocoaPods Support for NIO implementation
#### Question Description
Hi! I thought this might have been asked before but issue search said 'not really'. 
GRPC-swift is the main dependency on a project I'm maintaining [Zcash iOS SDK](https://github.com/zcash/ZcashLightClientKit)

we serve static assets, which is not supported by SPM and most of our users have reported using cocoapods as their dependency manager of choice. 

I'm wrapping my head around contributing with such support, on this project but it is unclear to me the tasks involved, because it's not evident to me which dependencies of this new implementations already have cocoapods support and which do not. I assume that main contributors like @MrMage might already have an idea of the effort and tasks needed for doing this.

**Comment by MrMage** [comment]
I think we already have a PR pending for CocoaPods support, courtesy of @Jake-Prickett: https://github.com/grpc/grpc-swift/pull/764

**Comment by pacu** [comment]
Thank you @MrMage for your quick response.

**Comment by pacu** [comment]
closing since it's already addressed
