### ISSUE TITLE
Support for custom ChannelHandlers

### ISSUE THREAD

**Issue by lschmierer** [grpc/grpc-swift#770]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

Support for custom `ChannelHandler`s

#### Question Description

I am working on a project that uses GRPC in a LAN setting. As using TLS is too verbose (I want to transmit public keys by scanning a QR codes; self-singed SSL certificates are simply too big for that), I need to roll my own channel encryption.
Therefore it would be convenient to plug in my own `ChannelHandler`s instead of the TLS Handlers.

I think it would be the easiest to add a field like `customHandlers` to the Configuration structs and add them right after the (optional) TLS handler (and before any HTTP handlers) in bootstrapping.

I am willing to implement it and open a PR if that change would be accepted and I can get some feedback on how the API should look.

**Comment by MrMage** [comment]
Independent of the wish for custom `ChannelHandler`s, would it be possible to use TLS in a different way?

For example:

- Why would the entire TLS certificate need to be stored inside the QR code — would it be possible to just provide a _link_ to the certificate instead, e.g. with an ID in the URL that is too long to be guessable and/or an extra encryption key as part of the link?
- Also, why does the QR code need to contain the cert at all, given that it is transmitted upon each connection anyway? Or does the QR code contain the _client_ certificate instead?

Background: implementing your own crypto is always hard to get right and potentially more susceptible than repurposing an off-the-shelf solution.

**Comment by Lukasa** [comment]
I know I'm not addressing the substance of your question yet, but before I do, I want to call out some options other than replacing TLS. TLS is extremely well understood and well implemented. Rolling your own is a highly risky endeavour, and I want to make sure you've absolutely considered all possibilities that would avoid needing to replace it:

> As using TLS is too verbose (I want to transmit public keys by scanning a QR codes; self-singed SSL certificates are simply too big for that), I need to roll my own channel encryption.

I don't think this is accurate. A QR code can store 2,953 bytes in the largest form, and but even a 101x101 QR code can do it if you're willing to use ECDSA certificates. For example, consider this ECDSA certificate:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7f:43:e9:6e:2c:6e:ce:28:ee:99:8c:94:ba:43:1d:d0:c6:aa:be:bc
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN=myhost.local
        Validity
            Not Before: Apr  6 11:46:16 2020 GMT
            Not After : Apr 16 11:46:16 2020 GMT
        Subject: CN=myhost.local
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:80:c0:14:0b:09:2d:a1:87:10:b4:8a:25:7f:8f:
                    6f:4a:17:d5:b4:d3:21:66:fb:2c:17:16:ce:da:78:
                    bb:d2:ab:7a:b8:3d:73:bb:07:fa:2e:31:eb:98:a7:
                    33:73:e4:ba:d6:02:f4:77:b2:76:ec:4d:75:9f:e9:
                    dd:d5:3b:a4:b6
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:myhost.local
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:94:46:57:2b:e1:28:d4:84:2b:62:88:fd:51:
         64:5f:96:20:34:c3:ac:d4:95:0f:79:62:d7:20:57:71:d3:44:
         eb:02:21:00:e5:84:ba:1c:86:b4:35:7d:ac:ae:41:d0:d8:6f:
         0b:5c:9f:1a:4f:42:88:f1:f5:29:3a:b4:8c:34:f2:6a:c3:2f
```

This certificate is 335 bytes in DER format.

I strongly encourage you to consider whether or not you can continue to do this using TLS before you abandon this.

**Comment by lschmierer** [comment]
Thank you very much for your responses. As I thought about it, I think I have overcomplicated things in the process of designing my system.
For context, I am prototyping a concept I have developed for my Master thesis. It is basically about  storing personal medical records encrypted on patients devices, while not transferring data over the internet. I therefore do not want to depend on an internet connection. Data is directly transferred between a practitioner terminal and the users device (using Wifi).

The first idea was to establish a dedicated PKI. That would allow a central authority to govern over to whom user devices could connect. However, as the user hast to trust the local IT infrastructure anyway that would not serve no purpose as data can still be tapped after transmission anyway.
At the end I need encryption only to protect against an attacker trying to tamper with the Wifi connection. I do not want to rely on the Wifi security. macOS APIs for example only allow creation for WEP encrypted network.

It turns out, instead of rolling my own PKI or implementing transport encryption myself, I can simply stick to the existing global PKI infrastructure every system works with anyway (how to call it, does "the big PKI" habe a specific name?).

I am sorry for taking your time. But your input helped a lot straighten my thoughts.

The issue can probably be closed.

@Lukasa Btw, I experimented with 101x101 QR codes. While they work quite good when printed out, my phone had trouble detecting them on glossy computer screens.

**Comment by Lukasa** [comment]
“The big PKI” is usually called the Web PKI, as it’s mostly associated with the HTTP infrastructure. Sounds like you landed in a good place, I’m glad we could help clarify!

For now I’m closing this, but I’m sure we’ll get this request again: please do not read this closure as a “no”, consider it a “not yet” instead.
