### ISSUE TITLE
CocoaPods validation failure

### ISSUE THREAD

**Issue by SebastianThiebaud** [grpc/grpc-swift#771]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
Publishing a private CocoaPods spec with `grpc-swift` as dependency fails.

When lint runs, it fails and prints out this:
```
    - ERROR | [iOS] xcodebuild:  gRPC-Swift/Sources/GRPC/GRPCProtobufPayload.swift:24:14: error: argument labels '(contiguousBytes:)' do not match any available overloads
    - NOTE  | [iOS] xcodebuild:  gRPC-Swift/Sources/GRPC/GRPCProtobufPayload.swift:24:14: note: expected an argument list of type '(serializedByteBuffer: inout ByteBuffer)'
```

I'm using the library in a sample project (using SPM) and didn't run into this problem. I'm unsure why the CocoaPods linter fails.

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |   macOS 10.15.3                  |
| Swift Version                 |   Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15) Target: x86_64-apple-darwin19.3.0  |
| Xcode Version                 |   11.4 (11E146)                                                       |
| gRPC-Swift Version            |   1.0.0-alpha.11                                                       |
  </pre>
</details>

**Comment by MrMage** [comment]
For posterity, would you mind sharing how you added the Pod as a dependency?

**Comment by SebastianThiebaud** [comment]
Of course, here is the podspec I’m using:
(I removed some information in what I pasted here {{ }})

```
#
# Be sure to run `pod lib lint SwiftVariants.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see https://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = '{{ name }}'
  s.version          = '0.4.0'
  s.summary          = '{{ summary }}.'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  s.description      = <<-DESC
{{ description }}
                       DESC

  s.homepage         = 'https://github.com/{{ repo }}’
  s.author           = 'Postmates Inc'
  s.license          = 'Copyright'
  s.source           = { :git => 'git@github.com:{{ repo }}', :tag => "v#{s.version}" }

  s.ios.deployment_target = '10.0'

  s.source_files = 'Sources/*.swift'

  s.dependency 'gRPC-Swift', '1.0.0-alpha.11'
end
```

**Comment by glbrntt** [comment]
That's very strange. 

The error refers to this line:
 https://github.com/grpc/grpc-swift/blob/944c70aff5b282edc1112e614fbe5375a262aac2/Sources/GRPC/GRPCProtobufPayload.swift#L24

Which is the [`contiguousBytes` initializer in SwiftProtobuf](https://github.com/apple/swift-protobuf/blob/88a61789f856675437fe52a795274f0b51c78b14/Sources/SwiftProtobuf/Message%2BBinaryAdditions.swift#L89-L114) which (added in 1.8.0; which we depend on in the gRPC-Swift podspec).

What I did notice though is that the initializer only compiled for Swift>=5.0; that isn't a problem for gRPC Swift since we require Swift 5.0 as well. I wonder if this information is lost by Cocoapods though; does the error persist if you set the Swift version appropriately in your podspec?

**Comment by SebastianThiebaud** [comment]
> What I did notice though is that the initializer only compiled for Swift>=5.0; that isn't a problem for gRPC Swift since we require Swift 5.0 as well. I wonder if this information is lost by Cocoapods though; does the error persist if you set the Swift version appropriately in your podspec?

Good catch, this is it. Setting up the Swift version in my podspec fixed this. Interesting that CocoaPods doesn't propagate the dependencies version requirements.

Thank you very much @glbrntt :) 

For people searching this issue in the future, please add 
```
  s.swift_version = '5.0'
```
in your `.podspec` file.
