### ISSUE TITLE
Using NIOTSEventLoopGroup results in connection error

### ISSUE THREAD

**Issue by kmarcell** [grpc/grpc-swift#777]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
Using `NIOTSEventLoopGroup` instead of `MultiThreadedEventLoopGroup` results in connection error `ConnectivityState.transientFailure`. This error is reported via `ConnectivityStateDelegate` of the `ClientConnection.Configuration` `var connectivityStateDelegate` which is passed to the `connectivity: ConnectivityStateMonitor` property of `ClientConnection`.

``` 
let configuration = ClientConnection.Configuration(
    target: .hostAndPort(host, port), 
    eventLoopGroup: PlatformSupport.makeEventLoopGroup(loopCount: 1),
    connectivityStateDelegate: connectivityStateDelegate, 
    tls: tls
)
let channel = ClientConnection(configuration: configuration)
```
The connection is not set-up and I don't see any specific errors on what the problem is. While using the `posix` `MultiThreadedEventLoopGroup` results in a successful connection.

##### Complete output when running grpc-swift, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |  10.15.3                                                       |
| Swift Version                 |   Swift 5                                                      |
| Xcode Version                 |   11.1                                                       |
| gRPC-Swift Version            |   alpha-11                                                       |
| protoc Version                |   3.10.0                                                       |
| protoc-gen-swift Version      |   1.8.0                                                       |
| protoc-gen-swiftgrpc Version  |   x.x.x                                                       |
  </pre>
</details>

**Comment by Lukasa** [comment]
When you say it results in connection error `ConnectivityState.transientFailure`, where is that error reported from? A quick check suggests that that error is associated with the C implementation, and would presumably be unrelated to NIO/NIOTS.

**Comment by kmarcell** [comment]
This error is reported via `ConnectivityStateDelegate` of the `ClientConnection.Configuration` `var connectivityStateDelegate` which is passed to the `connectivity: ConnectivityStateMonitor` property of `ClientConnection`.

**Comment by Lukasa** [comment]
Ok, that sounds like a 20 second connection timeout. That's a surprise to me. Do you have pcaps of the connection attempts?

**Comment by kmarcell** [comment]
Also the `self.tlsOptions` is `nil` on the `NIOTSConnectionBootstrap` instance where we do use TLS and we set it to `ClientConnection.Configuration`

**Comment by kmarcell** [comment]
> Ok, that sounds like a 20 second connection timeout. That's a surprise to me. Do you have pcaps of the connection attempts?

Can you explain what is pcaps and how do I check it? The grpc-swift or NIO does retry the connection and always fails.

**Comment by Lukasa** [comment]
A pcap is a packet capture log: a log of the network traffic. You can obtain one using `tcpdump`: for example, `tcpdump -i en0 host google.com` would capture all traffic on your machine heading to `google.com` that used interface `en0`.

**Comment by Lukasa** [comment]
Currently gRPC does not use NIOTS TLS configuration but instead unconditionally uses NIOSSL, so we'd expect to see `self.tlsOptions` equal to `nil`.

**Comment by glbrntt** [comment]
> Also the `self.tlsOptions` is `nil` on the `NIOTSConnectionBootstrap` instance where we do use TLS and we set it to `ClientConnection.Configuration`

This is expected: we use the channel handlers provided by `NIOSSL` to provide TLS for the Network.framework implementation _instead_ of setting the `tlsOptions` on the `NIOTSConnectionBootstrap`. This makes it _much_ simpler to have a one way to setup either a connection using NIO or NIO Transport Services.

**Comment by Lukasa** [comment]
So right now it's very difficult to know exactly why the connection attempt is timing out. The best guess I have is that Network.framework thinks that for some reason the host is not reachable, and it's waiting for that to change. We would expect to see that in packet captures by not seeing any outbound connection attempts. `Console.app` may also have useful logs in the NIOTS case, so I'd consider investigating in there as well.

**Comment by kmarcell** [comment]
@Lukasa ,

So what I found so far is that if Charles is running (even if I wasn't able to capture the output) the connection does succeed, but if I exit Charles the connection does fail. I think this might be an issue on my machine. Please note I was not running Charles in the couple of months!

**Comment by Lukasa** [comment]
This is in line with the idea that Network.framework is waiting for something, but the fact that regular NIO can connect suggests that whatever Network.framework is waiting for is in error. I'd still like to see output from Console.app if you can get it.

**Comment by kmarcell** [comment]
I've followed the guide here: https://developer.apple.com/documentation/network/recording_a_packet_trace as well as used Charles to capture. Even enabled CFNETWORK_DIAGNOSTICS=3. It seems when the issue happens with the timeout, the packets are not even sent from the Simulator to the server.

We'll try to attach rvictl to a device.

**Comment by kmarcell** [comment]
With our security setup we're unable to connect `rvictl` to our test devices and we're not sure what's causing `NIOTSEventLoopGroup` to fail on the Simulator, but it has to do with the SSL setup on our side. I'm closing the issue. :) Thank you guys.
