### ISSUE TITLE
Streaming rate drops, ByteBuffer reallocs increases

### ISSUE THREAD

**Issue by johnkassebaum** [grpc/grpc-swift#779]
### Question Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject

What should we be doing differently?

#### Question Description

Our server streams to an iOS client 1000s of data bundles of size 20...100KB. Consistently we observe that as the stream runs throughput drops to 500KB/sec and application memory increases.  To verify, we've created the simplest of apps, just creating a client connection and making one call that accepts the data and drops it on the floor. If we limit the call to streaming ~200 bundles, we get throughput of 6-8MB/sec.

Instruments shows that `static func allocateAndPrepareRawMemory(bytes:allocator:)` is called dozens of times/sec and that the `_Capacity` arg grows quickly from `4096` to `524288` and then continues upward to `67108864`.  Only once have we observed the value drop briefly but it quickly returned to the large value.  

We've tried increasing the `targetWindowSize` in `HTTP2StreamMultiplexer`, tried increasing threads in the `EventLoopGroup`, and tried inserting `autoreleasepool {...}` in our client call handler.  

If we observe the Debug Session stats in Xcode while running on device, we see a consistent correlation between application memory size and throughput.  Our simple app starts small at ~15MB and 6-8MB/sec throughput.  As app memory jumps quickly to 30MB, throughput begins to drop.  Eventually app memory exceeds 70-100MB and throughput is down to 300-500KB/sec.   As mentioned above, the app is doing nothing but opening a connection and triggering one call that does nothing with the streamed data bundles. 

For example, in one repeatable case in which the server streams 1730 bundles comprising 47929724 total bytes, we measure an average throughput of <1MB/sec, far lower than the device and its connection can support. 

If we cancel the call after every 200 bundles then make a new call with the last received cursor, we measure 6-6MB/sec over the span of 1730 bundles.

Is there something we are missing? Thanks so much for your help.

**Comment by Lukasa** [comment]
Do you happen to have the call stacks for the large calls to `allocateAndPrepareRawMemory`? I think this is us growing a byte buffer without bound.

**Comment by johnkassebaum** [comment]
Of course. I set a breakpoint in `@usableFromInline mutating func _copyStorageAndRebase(extraCapacity: _Capacity = 0, resetIndices: Bool = false)`

At this point, 1272 bundles totalling 34540717 bytes had been streamed. 
`_copyStorageAndRebase` had been called 2383 times.

State:
```
extraCapacity	NIO.ByteBuffer._Capacity	0
resetIndices	Bool	false	
self	NIO.ByteBuffer	
toCapacity	NIO.ByteBuffer._Capacity	67108864
```
Stacktrace:
```   
NIO-ELT-0-#0 (9)#0	0x0000000102126b04 in ByteBuffer._copyStorageAndRebase(extraCapacity:resetIndices:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ByteBuffer-core.swift:300
#1	0x0000000102127b18 in ByteBuffer._setBytes(_:at:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ByteBuffer-core.swift:362
#2	0x000000010212c174 in ByteBuffer.setBytes(_:at:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ByteBuffer-core.swift:764
#3	0x0000000102121d0c in closure #1 in ByteBuffer.setBuffer(_:at:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ByteBuffer-aux.swift:333
#4	0x0000000102120e0c in thunk for @callee_guaranteed (@unowned UnsafeRawBufferPointer) -> (@unowned Int, @error @owned Error) ()
#5	0x0000000102121d48 in thunk for @callee_guaranteed (@unowned UnsafeRawBufferPointer) -> (@unowned Int, @error @owned Error)partial apply ()
#6	0x000000010212a350 in ByteBuffer.withUnsafeReadableBytes<A>(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ByteBuffer-core.swift:572
#7	0x0000000102121c38 in ByteBuffer.setBuffer(_:at:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ByteBuffer-aux.swift:332
#8	0x0000000102121ed4 in ByteBuffer.writeBuffer(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ByteBuffer-aux.swift:345
#9	0x00000001020afdac in LengthPrefixedMessageReader.append(buffer:) at /Users/jkassebaum/gRPC/grpc-swift/Sources/GRPC/LengthPrefixedMessageReader.swift:102
#10	0x00000001020ba7dc in ReadState.readMessages<A>(_:as:) at /Users/jkassebaum/gRPC/grpc-swift/Sources/GRPC/ReadWriteStates.swift:153
#11	0x000000010207925c in GRPCClientStateMachine.State.receiveResponseBuffer(_:) at /Users/jkassebaum/gRPC/grpc-swift/Sources/GRPC/GRPCClientStateMachine.swift:451
#12	0x0000000102078eec in GRPCClientStateMachine.receiveResponseBuffer(_:) at /Users/jkassebaum/gRPC/grpc-swift/Sources/GRPC/GRPCClientStateMachine.swift:299
#13	0x00000001020db598 in _GRPCClientChannelHandler.readData(content:context:) at /Users/jkassebaum/gRPC/grpc-swift/Sources/GRPC/_GRPCClientChannelHandler.swift:371
#14	0x00000001020da968 in _GRPCClientChannelHandler.channelRead(context:data:) at /Users/jkassebaum/gRPC/grpc-swift/Sources/GRPC/_GRPCClientChannelHandler.swift:274
#15	0x00000001020dc5ec in protocol witness for _ChannelInboundHandler.channelRead(context:data:) in conformance _GRPCClientChannelHandler<A, B> ()
#16	0x00000001021534fc in ChannelHandlerContext.invokeChannelRead(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ChannelPipeline.swift:1339
#17	0x000000010214eb14 in ChannelPipeline.fireChannelRead0(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ChannelPipeline.swift:829
#18	0x000000010214e964 in ChannelPipeline.fireChannelRead(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ChannelPipeline.swift:587
#19	0x00000001023f5858 in HTTP2StreamChannel.receiveInboundFrame(_:) at /Users/jkassebaum/gRPC/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamChannel.swift:620
#20	0x00000001023f87e4 in HTTP2StreamMultiplexer.channelRead(context:data:) at /Users/jkassebaum/gRPC/swift-nio-http2/Sources/NIOHTTP2/HTTP2StreamMultiplexer.swift:72
#21	0x00000001023fa85c in protocol witness for _ChannelInboundHandler.channelRead(context:data:) in conformance HTTP2StreamMultiplexer ()
#22	0x00000001021534fc in ChannelHandlerContext.invokeChannelRead(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ChannelPipeline.swift:1339
#23	0x0000000102157548 in ChannelHandlerContext.fireChannelRead(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ChannelPipeline.swift:1152
#24	0x000000010239baa4 in NIOHTTP2Handler.processFrame(_:flowControlledLength:context:) at /Users/jkassebaum/gRPC/swift-nio-http2/Sources/NIOHTTP2/HTTP2ChannelHandler.swift:300
#25	0x0000000102398a30 in NIOHTTP2Handler.frameDecodeLoop(context:) at /Users/jkassebaum/gRPC/swift-nio-http2/Sources/NIOHTTP2/HTTP2ChannelHandler.swift:196
#26	0x000000010239870c in NIOHTTP2Handler.channelRead(context:data:) at /Users/jkassebaum/gRPC/swift-nio-http2/Sources/NIOHTTP2/HTTP2ChannelHandler.swift:160
#27	0x0000000102399f48 in protocol witness for _ChannelInboundHandler.channelRead(context:data:) in conformance NIOHTTP2Handler ()
#28	0x00000001021534fc in ChannelHandlerContext.invokeChannelRead(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ChannelPipeline.swift:1339
#29	0x0000000102157548 in ChannelHandlerContext.fireChannelRead(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ChannelPipeline.swift:1152
#30	0x000000010245bf80 in NIOSSLHandler.doFlushReadData(context:receiveBuffer:readOnEmptyBuffer:) at /Users/jkassebaum/gRPC/swift-nio-ssl/Sources/NIOSSL/NIOSSLHandler.swift:415
#31	0x0000000102458b10 in NIOSSLHandler.channelReadComplete(context:) at /Users/jkassebaum/gRPC/swift-nio-ssl/Sources/NIOSSL/NIOSSLHandler.swift:153
#32	0x000000010245dc70 in protocol witness for _ChannelInboundHandler.channelReadComplete(context:) in conformance NIOSSLHandler ()
#33	0x00000001021536b8 in ChannelHandlerContext.invokeChannelReadComplete() at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ChannelPipeline.swift:1349
#34	0x000000010214ed64 in ChannelPipeline.fireChannelReadComplete0() at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ChannelPipeline.swift:835
#35	0x00000001021014d0 in BaseSocketChannel.readable0() at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/BaseSocketChannel.swift:1104
#36	0x00000001021029b4 in BaseSocketChannel.readable() at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/BaseSocketChannel.swift:1048
#37	0x0000000102103ce8 in protocol witness for SelectableChannel.readable() in conformance BaseSocketChannel<A> ()
#38	0x000000010220a314 in SelectableEventLoop.handleEvent<A>(_:channel:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/SelectableEventLoop.swift:321
#39	0x000000010220b638 in closure #1 in closure #1 in SelectableEventLoop.run() at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/SelectableEventLoop.swift:381
#40	0x000000010220b948 in thunk for @callee_guaranteed (@guaranteed SelectorEvent<NIORegistration>) -> (@error @owned Error) ()
#41	0x000000010220fc1c in partial apply for thunk for @callee_guaranteed (@guaranteed SelectorEvent<NIORegistration>) -> (@error @owned Error) ()
#42	0x000000010221ea58 in Selector.whenReady(strategy:_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/Selector.swift:561
#43	0x000000010220b404 in closure #1 in SelectableEventLoop.run() at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/SelectableEventLoop.swift:376
#44	0x000000010220e9c0 in partial apply for closure #1 in SelectableEventLoop.run() ()
#45	0x00000001020f2804 in thunk for @callee_guaranteed () -> (@error @owned Error) ()
#46	0x000000010220e9e4 in thunk for @callee_guaranteed () -> (@error @owned Error)partial apply ()
#47	0x000000010220669c in closure #1 in withAutoReleasePool<A>(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/SelectableEventLoop.swift:23
#48	0x000000010220670c in partial apply for closure #1 in withAutoReleasePool<A>(_:) ()
#49	0x00000001b98fdbbc in autoreleasepool<A>(invoking:) ()
#50	0x0000000102206624 in withAutoReleasePool<A>(_:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/SelectableEventLoop.swift:22
#51	0x000000010220a73c in SelectableEventLoop.run() at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/SelectableEventLoop.swift:375
#52	0x0000000102190610 in closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:selectorFactory:initializer:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/EventLoop.swift:753
#53	0x00000001021977cc in partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:selectorFactory:initializer:) ()
#54	0x0000000102190f18 in thunk for @escaping @callee_guaranteed (@guaranteed NIOThread) -> () ()
#55	0x0000000102254edc in closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) at /Users/jkassebaum/gRPC/swift-nio/Sources/NIO/ThreadPosix.swift:105
#56	0x0000000102255058 in @objc closure #1 in static ThreadOpsPosix.run(handle:args:detachThread:) ()
#57	0x0000000183ae2d98 in _pthread_start ()
```

**Comment by johnkassebaum** [comment]
Time profiling. 
<img width="2134" alt="image" src="https://user-images.githubusercontent.com/39099029/80884972-46310700-8c72-11ea-87c6-4339ca332434.png">

**Comment by Lukasa** [comment]
Hmm, interesting. A quick look at the code rules out the trivial bug of never freeing the accumulator buffer under any circumstances. However, there are definitely two wrinkles in here that we should address:

1. `LengthPrefixedMessageReader.buffer` is only cleared if it has consumed _all_ bytes. In streaming scenarios, if the remote peer is always streaming the next message, it’s possible that this criterion will never be hit. This will lead to what has been seen here, with ever increasing copies of dead data.
2. When `LenghPrefixedMessageReader.buffer` is cleared, it is freed. There’s no need to do that: we should keep the buffer around and just scrub it, potentially capping it at some reasonable message size.

I think part (1) is the bigger perf problem, and should be addressed. `LengthPrefixedMessageReader` will need a heuristic for when it may choose to “shuffle” the bytes in the buffer down. My gut instinct for what this heuristic should be will be at any point where the number of bytes prior to the reader instinct is greater than 1kB _and_ more than half the size of the buffer. That should prevent us wasting our time. We can do this check at the end of the call to `nextMessage`.

This will need a method I’ve wanted in `ByteBuffer` for a while: `compact`. We can write it here first and upstream it into NIO.

**Comment by Lukasa** [comment]
I’ll work on this patch tomorrow, I should have something fairly quickly.

**Comment by johnkassebaum** [comment]
Thanks so much. I can test your changes in your branch if that would be helpful.

**Comment by Lukasa** [comment]
Thanks @johnkassebaum, would you like to try with the patch available at https://github.com/Lukasa/grpc-swift called `cb-discard-bytes`?

**Comment by Lukasa** [comment]
Or alternatively now with the master branch here.

**Comment by glbrntt** [comment]
GH closed this when the PR was merged: please re-open if it doesn't help!
