### ISSUE TITLE
Stream does not stream. (tooManyOperations | GRPC_CALL_ERROR_TOO_MANY_OPERATIONS).

### ISSUE THREAD

**Issue by enzomd** [grpc/grpc-swift#78]
Regarding the server streaming ```rpc Expand(EchoRequest) returns (stream EchoResponse) {}  ```.

When the server ```session.send(response)``` 3 or more times in a row without any pause, you get a tooManyOperations error. This does not happen in the example as there is a ```sleep(1)``` between each send.

I think this is related to this issue https://github.com/grpc/grpc/issues/4628#issuecomment-169357969; differing state between GRPC C and Swift code.

**Version**
https://github.com/grpc/grpc-swift/tree/0.2.3

**To replicate:**
- Add 3 x "try session.send(response)" into expand() handler.
   - https://github.com/grpc/grpc-swift/blob/0.2.3/Examples/Echo/EchoProvider.swift#L28
- cd grpc-swift/Examples/Echo/PackageManager;
- swift build
- Run server/client from CLI.

Ideally I think that there should be a blocking version of ```send```, or a async completion handler to get a notification of when ```response``` has been sent.

**Comment by timburks** [comment]
Agreed. I think adding a completion handler would be best (most flexible). I'll change the generated send() method to look like this:
```
  /// Send a message. Nonblocking.
  internal func send(_ response: Echo_EchoResponse,
                     completion: @escaping ()->()) throws {
    try handler.sendResponse(message:response.serializedData()) {completion()}
  }
```

**Comment by timburks** [comment]
Please see [this commit](https://github.com/grpc/grpc-swift/commit/a26794eaf0ad5984e14a6de6b05c8959d6de1078) for the above change.
