### ISSUE TITLE
Call Interceptor functionality

### ISSUE THREAD

**Issue by adriantabirta** [grpc/grpc-swift#785]
On client side I need an interceptor, would be great if we do have one like in go

**Comment by glbrntt** [comment]
@adriantabirta what's your specific use case? It might be something we can solve without interceptors. I agree though, interceptors would be helpful!

**Comment by adriantabirta** [comment]
I would use Interceptors for:
* auth - (server side check auth token, client side to get a token)
* metrics - (server side)
* stream filter/validation - (probably most for server side)

**Comment by whilesoftware** [comment]
@glbrntt is this on the roadmap?

I'd love to take a stab at implementing it. I was thinking of creating a mechanism to specify additional ChannelHandlers per-Server and/or per-CallHandlerProvider to be injected into the Pipeline between GRPCServerRequestRoutingHandler and BaseCallHandler.

The API would look something like:
```swift
extension CallHandlerProvider {
  public var prefixedHandlers: [ChannelHandler]? { get }
}

extension Server {
  public var prefixedHandlers: [ChannelHandler]? { get }
}
```

Does that sound right?

This would work nicely for my needs, where I want to validate JWT on a subset of my GRPC api. I can currently implement that validation inside a CallHandlerProvider, but that gets ugly quick. The JWT validation is an async operation, but I need to respond synchronously with either a FailedFuture or SucceededFuture, so I'm forced to mark every request as Succeeded and move error handling into my proto service/message layer.

**Comment by whilesoftware** [comment]
Actually now I realize the async part of my JWT auth procedure can be factored out... so I suppose this isn't nearly as dire as I was making out.

Still up for contributing if this approach is sane :)

**Comment by glbrntt** [comment]
It's certainly on the roadmap. It's not clear to me that a `ChannelHandler` is the right abstraction here though. We need to explore this space some more before deciding on a solution.

**Comment by glbrntt** [comment]
This is available as of 1.0.0-alpha.21

**Comment by upday7** [comment]
how can I use the ClientInterceptor? any documentations?

**Comment by glbrntt** [comment]
I have an example/tutorial which needs tidying up, I'll try to post it in the next couple of days. In the meantime I'd suggesting looking at some of the tests as a starting point: https://github.com/grpc/grpc-swift/blob/main/Tests/GRPCTests/InterceptorsTests.swift#L298-#L325

**Comment by upday7** [comment]
> I have an example/tutorial which needs tidying up, I'll try to post it in the next couple of days. In the meantime I'd suggesting looking at some of the tests as a starting point: https://github.com/grpc/grpc-swift/blob/main/Tests/GRPCTests/InterceptorsTests.swift#L298-#L325

thanks.

**Comment by glbrntt** [comment]
fyi, there is now a tutorial/example: https://github.com/grpc/grpc-swift/blob/main/docs/interceptors-tutorial.md
