### ISSUE TITLE
Cannot connect to bidirectional stream 

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc-swift#788]
Copying over from https://github.com/grpc/grpc/issues/22120
@slavabulgakov 

What version of gRPC and what language are you using?
1.24.2, swift

What operating system (Linux, Windows,...) and version?
iOS 12.4

What did you do?
There is bidirectional stream service:

service TypingService {
   rpc TypingStream (stream OutgoingTyping) returns (stream IncomingTyping);
}
I try to connect to it by following code:

let headers = ...
let callOptions = GRPCMutableCallOptions()
callOptions.flowControlEnabled = true
callOptions.setHeaders(headers)
callOptions.keepaliveInterval = 5
callOptions.keepaliveTimeout = 2
callOptions.userAgentPrefix = "MyUserAgent"
callOptions.retryEnabled = true
let path = "/com.example.messages.TypingService/TypingStream"
let requestOptions = GRPCRequestOptions(host: "...", path: path, safety: .default)
call = GRPCCall2(requestOptions: requestOptions, responseHandler: responseHandler, callOptions: callOptions)
call?.start()
call?.receiveNextMessages(1)
What did you expect to see?
A started stream without any errors

What did you see instead?
I instantly get callback in the method func didClose(withTrailingMetadata trailingMetadata: [AnyHashable: Any]?, error: Error?) in class which conforms to GRPCResponseHandler with error "grpc_status":2, unknown, No status received:

Error Domain=io.grpc Code=2 "{"created":"@1582558092.202200000","description":"No status received","file":".../src/Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1080,"grpc_status":2}" UserInfo= {io.grpc.HeadersKey={
}, io.grpc.TrailersKey={
    "content-length" = 0;
    date = "Mon, 24 Feb 2020 15:28:12 GMT";
    server = nginx;
}, NSDebugDescription={"created":"@1582558092.202200000","description":"No status received","file":".../src/Pods/gRPC-Core/src/core/lib/surface/call.cc","file_line":1080,"grpc_status":2}, NSLocalizedDescription=No status received}
Anything else we should know about your project / environment?
However the same service perfectly works with grpc-java.

**Comment by glbrntt** [comment]
@slavabulgakov this was just copied over from grpc/grpc: I see the original issue is a few months old. Are you still having problems?

**Comment by slavabulgakov** [comment]
@glbrntt An issue occurred using objective-c grpc framework, not grpc swift. I cannot check this issue out again, because developing the feature which should use bidirectional stream was paused.

**Comment by glbrntt** [comment]
Okay, no problem. If it's Objective-C you should re-open the issue in grpc/grpc if it becomes a problem again!
