### ISSUE TITLE
How can we use this on iOS?

### ISSUE THREAD

**Issue by KyoheiG3** [grpc/grpc-swift#79]
I have cloned the repository and maked the `SwiftGRPC.xcodeproj` then added it for MyProject and added __BoringSSL__, __CgRPC__, __gRPC__ and __Czlib__ frameworks to `Link Binary With Liblaries` . But I got build errors.

```
ld: framework not found BoringSSL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is this only for Mac?

**Comment by ishkawa** [comment]
Hi @KyoheiG3.

I could build an iOS app with gRPC Swift. The example project is available [here](https://github.com/ishkawa/grpc-swift/tree/ios-example-79) (`Examples/Echo/iOS/Echo.xcodeproj`). If it doesn't help you, could you push an example project somewhere? I think it is very useful to find out the problem.

**Comment by KyoheiG3** [comment]
@ishkawa Thank you for your example. I will try it.

**Comment by KyoheiG3** [comment]
I was also able to build for iOS using gRPC with reference to your repository!

When I tried to build the project, I couldn't find __BoringSSL__, __CgRPC__ and __gRPC__. Because I created `MyProject.xcworkspace` to use `cocoapods`. So I built `SwiftGRPC-Package` before build MyProject.

<img width="293" alt="2017-10-06 16 08 09" src="https://user-images.githubusercontent.com/5707132/31267247-642eefd2-aab2-11e7-9e00-9abf6400fbf7.png">

And then, I got build error of `zlib-example` so I removed from target it tentatively.

<img width="1121" alt="2017-10-06 16 06 26" src="https://user-images.githubusercontent.com/5707132/31267370-d11c5af8-aab2-11e7-9a67-76726e36a876.png">

I could build at this point, but I couldn't import `gRPC` so I added `CgRPC` headers to `Header Search Paths`

I would like to solve a dependency for `.xcworkspace` to build.

**Comment by KyoheiG3** [comment]
It needed to change Base SDK and Deployment Target to iOS. I published the example.
https://github.com/KyoheiG3/gRPCExample
It can also build on the `xcworkspace`.

Thank you.

**Comment by dcow** [comment]
Can you please reopen this until fixes are merged?

**Comment by dcow** [comment]
Removing the `zlib-example` target resolves the product-type error. It looks like we still need some Info.plist for the other targets.

**Comment by dcow** [comment]
>  It looks like we still need some Info.plists for the other targets.

`false`

Alright. Is there any preference on resolving this issue? I am happy to groom up the build but not familiar with `swift build`. Is there a way to have the generated xcodeproject specify a platform?

I found this article which is remarkably similar to how SwiftProtobuf organizes their project to support multiple platforms: https://medium.com/@ataibarkai/create-a-universal-swift-framework-for-ios-os-x-watchos-and-tvos-2aa26a8190dc

**Comment by KyoheiG3** [comment]
@dcow Hi. I have added [README](https://github.com/KyoheiG3/gRPCExample/blob/master/README.md#how-to-build-grpc-swift) how to build it.
I can not resolve `zlib-example` issue yet.

**Comment by dcow** [comment]
Thank you! It's good to compare notes. A few questions/comments: 

1. why did you need to disable bitcode?
2. Alternatively to setting header search path, you can add the CgRPC header to the CgRPC target.
3. (aside) when integrating into an actual app, all the frameworks must be embedded top-level which makes it hard to bundle grpc+protobufs into a "comms-level" framework.

**Comment by KyoheiG3** [comment]
1. To shut down when I exported ipa. I don't know why.
2. I tried it but didn't work. How to set it?
3. What does it mean? All the frameworks must be embedded when I tried to build.
