### ISSUE TITLE
Release missing on CocoaPods

### ISSUE THREAD

**Issue by SebastianThiebaud** [grpc/grpc-swift#793]
### New Issue Checklist

- [x] Updated grpc-swift to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues)(especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Issue Description
A new gRPC-Swift release has been published `1.0.0-alpha.12` but is not available on CocoaPods.

It looks like the version/release wasn't successfully pushed to CocoaPods. 
https://github.com/CocoaPods/Specs/tree/master/Specs/f/7/4/gRPC-Swift
Only `1.0.0-alpha.11` is available at this time.

**Comment by Jake-Prickett** [comment]
Currently pushing `1.0.0-alpha.12`. Will let you know when it's completed.

**Comment by Jake-Prickett** [comment]
Release `1.0.0-alpha.12` should now be available via CocoaPods: https://cocoapods.org/pods/gRPC-Swift 👍

**Comment by SebastianThiebaud** [comment]
Awesome, thank you! :)

**Comment by glbrntt** [comment]
thanks @Jake-Prickett!

**Comment by MrMage** [comment]
Sorry, I had meant to push the new release yesterday. That succeeded for `CGRPCzlib`, but failed for the main library (because the just-updated `CGRPCzlib` dependency had not propagated to the CocoaPods repo, I assume). I later forgot to try re-running that script.
