### ISSUE TITLE
gen-grpc-swift: allow generating code in different modules

### ISSUE THREAD

**Issue by jagobagascon** [grpc/grpc-swift#795]
The protobuf swift generator has an option ([ProtoPathModuleMappings](https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md#generation-option-protopathmodulemappings---swift-module-names-for-proto-paths)) that lets us define the module for each proto in a single file. This automatically adds the required imports for every generated swift class.

We have a decent amount of protos, and we are splitting our generated code into modules. **Are there any plans to add a similar mechanism into `grpc-swift`?**

I'm aware that we can use `ExtraModuleImports` to add extra imports, and we could somehow automate the calculation of the extra modules, but I still think the current mechanism is not powerful enough. It would be much easier to use the same module mapping file as `swift` generator does.

**Comment by glbrntt** [comment]
This would definitely be useful and worth having. 

Since we use SwiftProtobuf's plugin library I'm hoping that this shouldn't be too difficult to do. Is this something you want to try adding @jagobagascon?

**Comment by jagobagascon** [comment]
Using `ProtoPathModuleMappings` in 'grpc-swift' is actually creating the imports, but it is also adding its own module:
a.proto (uses b.proto)
```swift
import A // this is not required
import B

...
```

So it may in fact be an easy fix. I'll try to fix it when I have some time later today 😃

**Comment by glbrntt** [comment]
Oh, interesting! I wasn't aware we even had broken support for this 😅

**Comment by jagobagascon** [comment]
I added a PR to fix the problem mentioned above.  I wasn't aware that we could use `ProtoPathModuleMappings` with `grpc-swift`, so I guess this issue should be closed? Or maybe `ProtoPathModuleMappings` option should be added to the [documentation](https://github.com/grpc/grpc-swift/blob/master/docs/plugin.md)?

**Comment by glbrntt** [comment]
Documentation would be great, if you don't mind adding it :)
