### ISSUE TITLE
Error in imports in the generated files (iOS).

### ISSUE THREAD

**Issue by OhhhThatVarun** [grpc/grpc-swift#805]
### Question Checklist

- [X] Updated grpc-swift to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [X] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [X] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
Import error in generated filed.

#### Question Description
I build my `.proto` files with the compiler but after copying the`.grpc.swift` and `.pb.swift` files to the project it is showing the error in the import statement of the `.grpc.swift` file `No such module 'GRPC'`. I replaced it with `SwiftGRPC` but now it's showing import error for `NIO` `No such module 'NIO'`. I'm not sure how to fix this.
I used these commands to generate the files
`protoc --swift_out=. StudentService.proto`
`protoc --swiftgrpc_out=. StudentService.proto`

In my `podfile` I have `pod 'SwiftProtobuf'` and `pod 'SwiftGRPC'`

Is it something I'm doing wrong?

**Comment by MrMage** [comment]
When creating an issue like this, please fill out the issue template.

**Comment by OhhhThatVarun** [comment]
So, now should I create a new issue or edit this one?

**Comment by MrMage** [comment]
Feel free to edit the issue and comment again afterwards. And make sure to fill out the "versions" section completely.

**Comment by OhhhThatVarun** [comment]
Issue updated.

**Comment by MrMage** [comment]
Which version of the protoc compiler Plugin are you using?

**Comment by OhhhThatVarun** [comment]
When I did `protoc --version` I got `libprotoc 3.5.1`

**Comment by MrMage** [comment]
That's the version of `protoc`, not of the plugin.

Anyway, did you try running `pod update`?

**Comment by glbrntt** [comment]
`--swiftgrpc_out` relates to the plugin (`protoc-gen-swiftgrpc`) for the `0.x` version which you're trying to use with the `1.x` version of the library.

You need use `protoc-gen-grpc-swift`, see instructions for getting it here: https://github.com/grpc/grpc-swift#getting-the-protoc-plugins

**Comment by OhhhThatVarun** [comment]
So, I saw there is a new release so removed everything and reinstalled everything. These are the things I did in order.
1) Clone the grpc-swift repo.
2) Ran `make` command in the root then `make plugins`
3) Copied `protoc-gen-grpc-swift` and `protoc-gen-swift` to the path.
4) Ran `protoc --grpc-swift_out=. StudentService.proto` and `protoc --swift_out=. StudentService.proto` command.
5) Copied the generated filed to my iOS project.

The error I'm getting in Code is `No such module 'GRPC'`.

Do I need to change something in the `podfile`?

**Comment by MrMage** [comment]
Did you run `pod update`? What does your `Podfile.lock` file look like?

**Comment by MrMage** [comment]
Also, you might need to replace the `pod 'SwiftGRPC'` with `pod 'gRPC-Swift'`, please try that, then run `pod update`.

**Comment by OhhhThatVarun** [comment]
My `podfile.lock`

`
PODS:
  - CGRPCZlib (1.0.0-alpha.11)
  - CNIOAtomics (2.15.0)
  - CNIOBoringSSL (2.7.1)
  - CNIOBoringSSLShims (2.7.1):
    - CNIOBoringSSL (= 2.7.1)
  - CNIODarwin (2.15.0)
  - CNIOHTTPParser (2.15.0)
  - CNIOLinux (2.15.0)
  - CNIOSHA1 (2.15.0)
  - gRPC-Swift (1.0.0-alpha.11):
    - CGRPCZlib (= 1.0.0-alpha.11)
    - Logging (= 1.2.0)
    - SwiftNIO (= 2.15.0)
    - SwiftNIOHTTP2 (= 1.11.0)
    - SwiftNIOSSL (= 2.7.1)
    - SwiftNIOTransportServices (= 1.3.0)
    - SwiftProtobuf (= 1.8.0)
  - Logging (1.2.0)
  - Stripe (19.2.0)
  - SwiftNIO (2.15.0):
    - CNIOAtomics (= 2.15.0)
    - CNIODarwin (= 2.15.0)
    - CNIOLinux (= 2.15.0)
    - CNIOSHA1 (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
  - SwiftNIOConcurrencyHelpers (2.15.0):
    - CNIOAtomics (= 2.15.0)
  - SwiftNIOFoundationCompat (2.15.0):
    - SwiftNIO (= 2.15.0)
  - SwiftNIOHPACK (1.11.0):
    - SwiftNIO (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
    - SwiftNIOHTTP1 (= 2.15.0)
  - SwiftNIOHTTP1 (2.15.0):
    - CNIOHTTPParser (= 2.15.0)
    - SwiftNIO (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
  - SwiftNIOHTTP2 (1.11.0):
    - SwiftNIO (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
    - SwiftNIOHPACK (= 1.11.0)
    - SwiftNIOHTTP1 (= 2.15.0)
    - SwiftNIOTLS (= 2.15.0)
  - SwiftNIOSSL (2.7.1):
    - CNIOBoringSSL (= 2.7.1)
    - CNIOBoringSSLShims (= 2.7.1)
    - SwiftNIO (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
    - SwiftNIOTLS (= 2.15.0)
  - SwiftNIOTLS (2.15.0):
    - SwiftNIO (= 2.15.0)
  - SwiftNIOTransportServices (1.3.0):
    - SwiftNIO (~> 2.0)
    - SwiftNIOConcurrencyHelpers (~> 2.0)
    - SwiftNIOFoundationCompat (~> 2.0)
    - SwiftNIOTLS (~> 2.0)
  - SwiftProtobuf (1.8.0)

DEPENDENCIES:
  - gRPC-Swift (= 1.0.0-alpha.11)
  - Stripe
  - SwiftProtobuf (= 1.8.0)

SPEC REPOS:
  trunk:
    - CGRPCZlib
    - CNIOAtomics
    - CNIOBoringSSL
    - CNIOBoringSSLShims
    - CNIODarwin
    - CNIOHTTPParser
    - CNIOLinux
    - CNIOSHA1
    - gRPC-Swift
    - Logging
    - Stripe
    - SwiftNIO
    - SwiftNIOConcurrencyHelpers
    - SwiftNIOFoundationCompat
    - SwiftNIOHPACK
    - SwiftNIOHTTP1
    - SwiftNIOHTTP2
    - SwiftNIOSSL
    - SwiftNIOTLS
    - SwiftNIOTransportServices
    - SwiftProtobuf

SPEC CHECKSUMS:
  CGRPCZlib: e595387378d0601be796e858dd30c505458c4b1f
  CNIOAtomics: ba49b1c86f281e1ecfd84c9205fbc27a81826847
  CNIOBoringSSL: e4766830ab6d7c7fcd3618331f05fcb11638314d
  CNIOBoringSSLShims: c3f3c6f05b7ce9b576521328a5b1b566d8f4665b
  CNIODarwin: 2e341dd283fa3972706568b12925366145a8e2cd
  CNIOHTTPParser: 25e1d1bc84c0612cbbbd6baedc4be05d77a17e01
  CNIOLinux: 61598a8e49510207acb74c87f8fc11f762f76b5a
  CNIOSHA1: 7b1dcceef9682aef4c6578b9fc67f87a03f0c48e
  gRPC-Swift: 79f04da038f9a62005271d5b638611ce1bb31304
  Logging: 7838d379d234d7e5ae1265fa02804a9084caf04c
  Stripe: d481c2dab9a892fd923f097f854661217f70dc7f
  SwiftNIO: c9889dcd8aed2655af9163b42fc11ebd4ce94252
  SwiftNIOConcurrencyHelpers: 2357037a16e9c51880c01b896a5ac3cd41066044
  SwiftNIOFoundationCompat: f09ee499a8a9c636ec9007f73c5a1cedc23dcad3
  SwiftNIOHPACK: 906596511ff9d1e095b7a72a0011351591bcae03
  SwiftNIOHTTP1: b05f4061ba18482006a264a5aa087bbcd35d153c
  SwiftNIOHTTP2: 3a52499594c6ec073af2a2801cf3c5d3d1c8700f
  SwiftNIOSSL: 7c82b8393a6b69a3ef9b12fe74240e92c2bd7add
  SwiftNIOTLS: 51580e51240d1a4d51efb2d317e92cf243181042
  SwiftNIOTransportServices: 26d40c589fc8fe667af51b06ef0aa49fbc9ae7f2
  SwiftProtobuf: 2cbd9409689b7df170d82a92a33443c8e3e14a70

PODFILE CHECKSUM: 01951009c68906256d7a507388865e4edba49f67

COCOAPODS: 1.9.1

`

**Comment by MrMage** [comment]
@OhhhThatVarun that Podfile looks correct. Did you try compiling with that again?

Also, please make sure to put multi-line code snippets in triple backticks to make them render correctly.

**Comment by OhhhThatVarun** [comment]
Now it's not showing any error in the generated filed after I restarted my mac. Thank you!

**Comment by cs145442** [comment]
> Now it's not showing any error in the generated filed after I restarted my mac. Thank you!

Running on the same issue. Let my try that . :D
