### ISSUE TITLE
Should we document "moving from CgRPC to NIO" in the README?

### ISSUE THREAD

**Issue by MrMage** [grpc/grpc-swift#808]
Maybe we should have a brief section on the differences. For example:

- different threading model might require a substantial rewrite (referring to the new examples)
- the CocoaPod was renamed from `SwiftGRPC` to `grpc-Swift` (this one tripped a few people up)
- the protoc plugin needs to be updated and re-run to get the new generated code
- etc.

**Comment by Lutzifer** [comment]
having done this migration last week: yes, documentation on this would be much of a help

**Comment by MrMage** [comment]
> having done this migration last week: yes, documentation on this would be much of a help

Makes sense! Were there any things you stumbled upon besides the ones mentioned in the list above? It would be good to know about them so that we can include them in the documentation :-)

**Comment by Lutzifer** [comment]
- I found it hard to find the examples (as there is a second folder)
- I did not find an easy to understand example on how to use NIO based grpc in an iOS app (I found the SpeechToText example, but even now I find this one a bit confusing). It took me some time to use the group correctly (the defer block from the example triggered too early in the iOS app, thus destroying the connection before I could use it) [https://github.com/grpc/grpc-swift/blob/9a41c8efdad71274e676ec735565dd16b241efb9/Sources/Examples/RouteGuide/Client/main.swift#L206].
- Having examples of "in cGRPC you might have done X, so do Y now" would be cool
- It took me some time to update the protoc plugins correctly and make sure the right version is used
- overall, I think, having a simpler iOS example App (Bonus Points if it is Rx 😂) would have been a lot of help. But maybe I had a different case to implement (chunking and sending a binaray file using streaming) than most of the people.
- I think we need a better overview over the examples and how to run them.
- https://github.com/grpc/grpc-swift/blob/9a41c8efdad71274e676ec735565dd16b241efb9/Examples/Google/SpeechToText/Sources/SpeechService.swift#L41 is what I would have needed most in hindsight, but I landed at [https://github.com/grpc/grpc-swift/blob/9a41c8efdad71274e676ec735565dd16b241efb9/Sources/Examples/RouteGuide/Client/main.swift#L196]. A combination of both did it for me (with some trial and error).

Hope this helps a bit.

**Comment by glbrntt** [comment]
Thanks @Lutzifer - that's really helpful!

Looks like we have a few things to do:

- [x] Explain difference between examples (#814)
- [x] Explain high-level difference between versions  (#814)
- [ ] Simple iOS example
- [ ] Better documentation for existing examples
- [ ] Transition guide and explanation of different threading models

**Comment by MrMage** [comment]
This is probably obsolete by now.
