### ISSUE TITLE
ld: framework not found GRPCClient

### ISSUE THREAD

**Issue by MitchDart** [grpc/grpc-swift#809]
### Question Checklist

- [x] Updated grpc-swift *and protoc-gen-swiftgrpc* to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [x] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [x] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
ld: framework not found GRPCClient linking error after switching to Cocoapods

#### Question Description
I used to use swift package manager for this project on the nio branch.  I see everything is merged in now and I wanted to switch to Cocoa pods (since I use this for my other dependencies). After adding it I get this error:

ld: framework not found GRPCClient 

Things I have tried

- pod install
- pod update
- remove Pod and Podfile.lock and running above
- Cleaning build and rebuilding
- Rebooting XCode

I can't see where GRPCClient comes from. There is very clearly only GRPC.framework product from the pod but my project is trying to link GRPCClient.framework with:
-framework GRPCClient

Here is my Podfile.lock

`PODS:
  - Alamofire (5.2.0)
  - AlamofireImage (4.1.0):
    - Alamofire (~> 5.1)
  - CGRPCZlib (1.0.0-alpha.12)
  - CNIOAtomics (2.15.0)
  - CNIOBoringSSL (2.7.1)
  - CNIOBoringSSLShims (2.7.1):
    - CNIOBoringSSL (= 2.7.1)
  - CNIODarwin (2.15.0)
  - CNIOHTTPParser (2.15.0)
  - CNIOLinux (2.15.0)
  - CNIOSHA1 (2.15.0)
  - gRPC-Swift (1.0.0-alpha.12):
    - CGRPCZlib (= 1.0.0-alpha.12)
    - Logging (= 1.2.0)
    - SwiftNIO (= 2.15.0)
    - SwiftNIOHTTP2 (= 1.11.0)
    - SwiftNIOSSL (= 2.7.1)
    - SwiftNIOTransportServices (= 1.3.0)
    - SwiftProtobuf (= 1.8.0)
  - Logging (1.2.0)
  - MaterialComponents/AnimationTiming (107.4.0)
  - MaterialComponents/Availability (107.4.0)
  - MaterialComponents/Buttons (107.4.0):
    - MaterialComponents/Elevation
    - MaterialComponents/Ink
    - MaterialComponents/private/Math
    - MaterialComponents/Ripple
    - MaterialComponents/ShadowElevations
    - MaterialComponents/ShadowLayer
    - MaterialComponents/Shapes
    - MaterialComponents/Typography
    - MDFInternationalization
    - MDFTextAccessibility
  - "MaterialComponents/Buttons+ColorThemer (107.4.0)":
    - MaterialComponents/Buttons
    - MaterialComponents/schemes/Color
  - "MaterialComponents/Buttons+ShapeThemer (107.4.0)":
    - MaterialComponents/Buttons
    - MaterialComponents/schemes/Shape
  - "MaterialComponents/Buttons+Theming (107.4.0)":
    - MaterialComponents/Buttons
    - "MaterialComponents/Buttons+ColorThemer"
    - "MaterialComponents/Buttons+ShapeThemer"
    - "MaterialComponents/Buttons+TypographyThemer"
    - MaterialComponents/schemes/Container
    - MaterialComponents/ShadowElevations
  - "MaterialComponents/Buttons+TypographyThemer (107.4.0)":
    - MaterialComponents/Buttons
    - MaterialComponents/schemes/Typography
  - MaterialComponents/Elevation (107.4.0):
    - MaterialComponents/Availability
    - MaterialComponents/private/Color
    - MaterialComponents/private/Math
  - MaterialComponents/Ink (107.4.0):
    - MaterialComponents/Availability
    - MaterialComponents/private/Color
    - MaterialComponents/private/Math
  - MaterialComponents/Palettes (107.4.0)
  - MaterialComponents/private/Application (107.4.0)
  - MaterialComponents/private/Color (107.4.0):
    - MaterialComponents/Availability
  - MaterialComponents/private/Math (107.4.0)
  - MaterialComponents/Ripple (107.4.0):
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Availability
    - MaterialComponents/private/Color
    - MaterialComponents/private/Math
  - MaterialComponents/schemes/Color (107.4.0):
    - MaterialComponents/Availability
    - MaterialComponents/private/Color
  - MaterialComponents/schemes/Container (107.4.0):
    - MaterialComponents/schemes/Color
    - MaterialComponents/schemes/Shape
    - MaterialComponents/schemes/Typography
  - MaterialComponents/schemes/Shape (107.4.0):
    - MaterialComponents/ShapeLibrary
    - MaterialComponents/Shapes
  - MaterialComponents/schemes/Typography (107.4.0):
    - "MaterialComponents/schemes/Typography+BasicFontScheme"
    - "MaterialComponents/schemes/Typography+Scheming"
    - MaterialComponents/Typography
  - "MaterialComponents/schemes/Typography+BasicFontScheme (107.4.0)"
  - "MaterialComponents/schemes/Typography+Scheming (107.4.0)"
  - MaterialComponents/ShadowElevations (107.4.0)
  - MaterialComponents/ShadowLayer (107.4.0):
    - MaterialComponents/ShadowElevations
  - MaterialComponents/ShapeLibrary (107.4.0):
    - MaterialComponents/private/Math
    - MaterialComponents/Shapes
  - MaterialComponents/Shapes (107.4.0):
    - MaterialComponents/private/Color
    - MaterialComponents/private/Math
    - MaterialComponents/ShadowLayer
  - MaterialComponents/TextFields (107.4.0):
    - MaterialComponents/AnimationTiming
    - MaterialComponents/Buttons
    - MaterialComponents/Elevation
    - MaterialComponents/Palettes
    - MaterialComponents/private/Math
    - MaterialComponents/Typography
    - MDFInternationalization
  - "MaterialComponents/TextFields+ColorThemer (107.4.0)":
    - MaterialComponents/TextFields
    - MaterialComponents/Themes
  - "MaterialComponents/TextFields+Theming (107.4.0)":
    - MaterialComponents/schemes/Container
    - MaterialComponents/TextFields
    - "MaterialComponents/TextFields+ColorThemer"
  - MaterialComponents/Themes (107.4.0):
    - MaterialComponents/schemes/Color
    - MaterialComponents/schemes/Typography
  - MaterialComponents/Typography (107.4.0):
    - MaterialComponents/private/Application
    - MaterialComponents/private/Math
  - MDFInternationalization (2.0.0)
  - MDFTextAccessibility (2.0.0)
  - OTPFieldView (1.0.1)
  - PromisesObjC (1.2.8)
  - PromisesSwift (1.2.8):
    - PromisesObjC (= 1.2.8)
  - SticittSSO (0.1.2):
    - Alamofire (~> 5.0)
    - "MaterialComponents/Buttons+Theming (~> 107.4.0)"
    - "MaterialComponents/TextFields+Theming (~> 107.4.0)"
    - OTPFieldView (~> 1.0.1)
    - PromisesSwift (~> 1.2.8)
  - SwiftNIO (2.15.0):
    - CNIOAtomics (= 2.15.0)
    - CNIODarwin (= 2.15.0)
    - CNIOLinux (= 2.15.0)
    - CNIOSHA1 (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
  - SwiftNIOConcurrencyHelpers (2.15.0):
    - CNIOAtomics (= 2.15.0)
  - SwiftNIOFoundationCompat (2.15.0):
    - SwiftNIO (= 2.15.0)
  - SwiftNIOHPACK (1.11.0):
    - SwiftNIO (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
    - SwiftNIOHTTP1 (= 2.15.0)
  - SwiftNIOHTTP1 (2.15.0):
    - CNIOHTTPParser (= 2.15.0)
    - SwiftNIO (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
  - SwiftNIOHTTP2 (1.11.0):
    - SwiftNIO (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
    - SwiftNIOHPACK (= 1.11.0)
    - SwiftNIOHTTP1 (= 2.15.0)
    - SwiftNIOTLS (= 2.15.0)
  - SwiftNIOSSL (2.7.1):
    - CNIOBoringSSL (= 2.7.1)
    - CNIOBoringSSLShims (= 2.7.1)
    - SwiftNIO (= 2.15.0)
    - SwiftNIOConcurrencyHelpers (= 2.15.0)
    - SwiftNIOTLS (= 2.15.0)
  - SwiftNIOTLS (2.15.0):
    - SwiftNIO (= 2.15.0)
  - SwiftNIOTransportServices (1.3.0):
    - SwiftNIO (~> 2.0)
    - SwiftNIOConcurrencyHelpers (~> 2.0)
    - SwiftNIOFoundationCompat (~> 2.0)
    - SwiftNIOTLS (~> 2.0)
  - SwiftProtobuf (1.8.0)

DEPENDENCIES:
  - AlamofireImage (~> 4.1)
  - gRPC-Swift (= 1.0.0-alpha.12)
  - MaterialComponents/Ripple (~> 107.4.0)
  - PromisesSwift (~> 1.2.8)
  - SticittSSO

SPEC REPOS:
  "sticitt@vs-ssh.visualstudio.com:v3/sticitt/Pay/CocoaPods":
    - SticittSSO
  trunk:
    - Alamofire
    - AlamofireImage
    - CGRPCZlib
    - CNIOAtomics
    - CNIOBoringSSL
    - CNIOBoringSSLShims
    - CNIODarwin
    - CNIOHTTPParser
    - CNIOLinux
    - CNIOSHA1
    - gRPC-Swift
    - Logging
    - MaterialComponents
    - MDFInternationalization
    - MDFTextAccessibility
    - OTPFieldView
    - PromisesObjC
    - PromisesSwift
    - SwiftNIO
    - SwiftNIOConcurrencyHelpers
    - SwiftNIOFoundationCompat
    - SwiftNIOHPACK
    - SwiftNIOHTTP1
    - SwiftNIOHTTP2
    - SwiftNIOSSL
    - SwiftNIOTLS
    - SwiftNIOTransportServices
    - SwiftProtobuf

SPEC CHECKSUMS:
  Alamofire: c1ca147559e730bfb2182c8c7aafbdd90a867987
  AlamofireImage: c4a2ba349885fb3064feb74d2e547bd42ce9be10
  CGRPCZlib: a53e43fb0567e720e753dd172911b96baa3910d7
  CNIOAtomics: ba49b1c86f281e1ecfd84c9205fbc27a81826847
  CNIOBoringSSL: e4766830ab6d7c7fcd3618331f05fcb11638314d
  CNIOBoringSSLShims: c3f3c6f05b7ce9b576521328a5b1b566d8f4665b
  CNIODarwin: 2e341dd283fa3972706568b12925366145a8e2cd
  CNIOHTTPParser: 25e1d1bc84c0612cbbbd6baedc4be05d77a17e01
  CNIOLinux: 61598a8e49510207acb74c87f8fc11f762f76b5a
  CNIOSHA1: 7b1dcceef9682aef4c6578b9fc67f87a03f0c48e
  gRPC-Swift: d4432e8659f1d075b9d07963c18e6791c8b159c3
  Logging: 7838d379d234d7e5ae1265fa02804a9084caf04c
  MaterialComponents: 52e2ade4684e3017eff7f62587b37522d217ea50
  MDFInternationalization: 010097556d6b09d2c4ea38e0820ea6d37be6a314
  MDFTextAccessibility: 85c09a1bd9c321f494348e632a25063bcda35a53
  OTPFieldView: 700a752fe62c41d1c4914c78aa500fb30d97c255
  PromisesObjC: c119f3cd559f50b7ae681fa59dc1acd19173b7e6
  PromisesSwift: 37bad6f4daddb02f7c9c531efe91e8b21c13ee2f
  SticittSSO: c5ed8d1611e344f3ba7d2e2e49e77212161ef948
  SwiftNIO: c9889dcd8aed2655af9163b42fc11ebd4ce94252
  SwiftNIOConcurrencyHelpers: 2357037a16e9c51880c01b896a5ac3cd41066044
  SwiftNIOFoundationCompat: f09ee499a8a9c636ec9007f73c5a1cedc23dcad3
  SwiftNIOHPACK: 906596511ff9d1e095b7a72a0011351591bcae03
  SwiftNIOHTTP1: b05f4061ba18482006a264a5aa087bbcd35d153c
  SwiftNIOHTTP2: 3a52499594c6ec073af2a2801cf3c5d3d1c8700f
  SwiftNIOSSL: 7c82b8393a6b69a3ef9b12fe74240e92c2bd7add
  SwiftNIOTLS: 51580e51240d1a4d51efb2d317e92cf243181042
  SwiftNIOTransportServices: 26d40c589fc8fe667af51b06ef0aa49fbc9ae7f2
  SwiftProtobuf: 2cbd9409689b7df170d82a92a33443c8e3e14a70

PODFILE CHECKSUM: 90fa65c595f55714672acdf1903da22eb98115b2

COCOAPODS: 1.8.4`

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |  Catalina 10.15.4                                                       |
| Swift Version                 |  5.0                                                       |
| Xcode Version                 |   11.4.1                                                       |
| gRPC-Swift Version            |   1.0.0-alpha.12                                                 |
| protoc Version                |   3.11.2                                                       |
| protoc-gen-swift Version      |   1.0.0-alpha.12                                                       |
| protoc-gen-swiftgrpc Version  |   1.0.0-alpha.12                                                       |
  </pre>
</details>

**Comment by MrMage** [comment]
`GRPCClient` is part of the [Objective-C version of gRPC](https://github.com/grpc/grpc/tree/master/src/objective-c/GRPCClient). You are posting on the gRPC-Swift repository.

Try using `pod GRPCClient` instead, or post your issue to https://github.com/grpc/grpc/issues.

**Comment by MrMage** [comment]
Sorry, I misread your initial post. However, `GRPCClient` still sounds like the Objective-C library for gRPC. As far as I remember, our library was never called like that.

Do you still accidentally have some reference to `GRPCClient` in your code somewhere? Or did you e.g. use in the past a Google/Firebase SDK in your app, which might depend on the ObjC version of gRPC?

**Comment by MitchDart** [comment]
Hi MrMage

I might have included objc version of GRPC back in the day when I was trying it out and maybe just forgot about it. Strange that its been working all this time with Swift package manager. Turns out there was a -framework "GRPCClient" and a few others in Target -> Linking -> Other Linker Flags. After removing them it's working now. Sorry about that I had no idea to think about the objc version.

**Comment by MrMage** [comment]
No worries! Thanks for the quick feedback. Closing this for now; let us know if you encounter any other issues!
