### ISSUE TITLE
How do you get a status code from an error?

### ISSUE THREAD

**Issue by OhhhThatVarun** [grpc/grpc-swift#813]
### Question Checklist

- [X] Updated grpc-swift *and protoc-gen-swiftgrpc* to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [X] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [X] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
This is a question about reading the error code value from the response.

#### Question Description
So, when I'm trying to call my server like this 
```
func signIn(student: Proto_Student,completion: @escaping (Proto_SignInResponse?, GRPCStatus.Code?)-> Void) {
        let response = client!.signIn(student).response
        response.whenSuccess { (SignInResponse) in
            DispatchQueue.main.async {
                completion(SignInResponse, nil)
            }
        }
        response.whenFailure { (Error) in
            DispatchQueue.main.async {
                self.printError(error: Error)
                print(Error)
                completion(nil, GRPCStatus.Code(rawValue: Error._code))
            }
        }
    }
```
`printError` is printing `The operation couldn’t be completed. (GRPC.GRPCStatus error 1.)`
and `print(Error)` is printing `notFound (5): No user found!` <-- This is the correct one

So how to get the code `.notFound`? I saw in the debugger there is a variable `code` with the correct value but "Error._code" is always returning 1.

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |  10.15.4                                                      |
| Swift Version                 |   5.2.4                                                       |
| Xcode Version                 |   11.5                                                       |
| gRPC-Swift Version            |   0.11.0                                                       |
| protoc Version                |   libprotoc 3.5.1                                                       |
| protoc-gen-swift Version      |   1.8.0                                                       |
| protoc-gen-swiftgrpc Version  |   x.x.x                                                       |
  </pre>
</details>

**Comment by glbrntt** [comment]
I think you might be using gRPC Swift `1.0.0-alpha.X` and not `0.11.0` as stated in the environment details: `response.whenSuccess` and `response.whenFailure` look highly suspicious here. If that _is_ the case then you should be able to just cast the error in the `whenFailure` block to a `GRPCStatus`:

```swift
response.whenFailure { error in
  if let status = error as? GRPCStatus {
    let code = status.code
    // ...
  } else {
    // handle other error types
  }
}
```

**Comment by OhhhThatVarun** [comment]
Hey @glbrntt , thank you for your response! It did work and yeah I'm sorry I'm using the old version. But how to migrate it to the latest release? I did put `pod 'gRPC-Swift', '0.11.0'` in m pod file and it's showing me an error. 

```
[!] CocoaPods could not find compatible versions for pod "gRPC-Swift":
  In Podfile:
    gRPC-Swift (= 0.11.0)

None of your spec sources contain a spec satisfying the dependency: `gRPC-Swift (= 0.11.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by glbrntt** [comment]
> Hey @glbrntt , thank you for your response! It did work and yeah I'm sorry I'm using the old version. 

`GRPCStatus` only exists in the 1.x releases: you can't be using the old version.

There are two major versions of gRPC Swift:

1. The `0.x` releases are based on a the gRPC C core library. We refer to this version as "cgrpc". We no longer actively support this release series (apart from for security patches and major bug fixes).
2. The `1.x` releases, of which `1.0.0-alpha.12` is the most recent. This implementation is based on [SwiftNIO](https://github.com/apple/swift-nio) instead of the gRPC C core library, we often refer to this as the "nio" version. This is the version you are using. 

> I did put pod 'gRPC-Swift', '0.11.0' in m pod file and it's showing me an error.
>
> ```
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> ```

The `gRPC-Swift` pod is for the `1.x` releases; the version you should depend should be `1.0.0-alpha.12` and not `0.11.0` which is for the `0.x` series.

**Comment by OhhhThatVarun** [comment]
Thank you for your wonderful explanation.
