### ISSUE TITLE
How to set metadata to a service?

### ISSUE THREAD

**Issue by Nickev123** [grpc/grpc-swift#816]
### Question Checklist

- [X] Updated grpc-swift and protoc-gen-swiftgrpc to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/grpc/grpc-swift/blob/master/CONTRIBUTING.md)
- [X] I read [README](https://github.com/grpc/grpc-swift/blob/master/README.md)
- [X] I searched for [existing GitHub issues](https://github.com/grpc/grpc-swift/issues) (especially, there are many [resolved issues related to SSL](https://github.com/grpc/grpc-swift/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+ssl))

### Question Subject
This is a question about metadata.

#### Question Description
So, when I'm trying set metadata to a client

```
var callOptions = CallOptions()
        let hasToken = callOptions.customMetadata.contains(name: "access_token")
        if !hasToken {
            callOptions.customMetadata.add(name: "acess_token", value: AppUserDefaults.getAccessToken()!)
        }
 self.client = Proto_HitchServiceClient.init(channel: getChannel(),defaultCallOptions: callOptions);
```

It's not working. Server is keep sending me "`No authentication token found`"
How to set metadata to a client? 

### Environment

<details>
  <pre>
  
| Key                           | Value                                                         |
| ----------------------------- | --------------------------------------------------------------|
| OS Version                    |  10.15.4                                                      |
| Swift Version                 |   5.2.4                                                       |
| Xcode Version                 |   11.5                                                       |
| gRPC-Swift Version            |   1.0.0-alpha.12                                                       |
| protoc Version                |   libprotoc 3.5.1                                                       |
| protoc-gen-swift Version      |   1.8.0                                                       |
| protoc-gen-swiftgrpc Version  |   x.x.x                                                       |
  </pre>
</details>

**Comment by glbrntt** [comment]
That's the correct way to set metadata.

Are you setting the right key? When you `add` the token the key above is "acess_token" not "access_token".

You have set _default_ call options: is it possible you are overriding these when you call the RPC?

**Comment by Nickev123** [comment]
Thank you!! Not sure how I missed that.. appreciate it!
