### ISSUE TITLE
Call dropped by load balancing policy

### ISSUE THREAD

**Issue by chemidy** [grpc/grpc-swift#82]
Hello,

I am trying to do a GRPC Call on Google Cloud Platform and i have a **Call dropped by load balancing policy Error**

On My local network  it works, with a grpc server in golang.
On Google Cloud Platform we are using, TCP Load Balancer in front of gRPC Google endpoint and our golang backend is deployed with Google Container Engine. 

With a Go Client on GCP it works.
With grpcc a NodeJS Client on GCP it works.
With grpc-swift on Iphone it fails with this trace :

`
response = {Swift.Optional<Packets.Api_GetLineResponse>} nil
result = {gRPC.CallResult} status 2: Call dropped by load balancing policy
 statusCode = {Swift.Int} 2
 statusMessage = {Swift.Optional<Swift.String>} “Call dropped by load balancing policy”
 resultData = {Swift.Optional<Foundation.Data>} nil
 initialMetadata = {Swift.Optional<gRPC.Metadata> | 0x1c02393e0} 0x00000001c02393e0
 trailingMetadata = {Swift.Optional<gRPC.Metadata> | 0x1c0039500} 0x00000001c0039500
handler = {Swift.Optional<() -> ()> | 0x104e43828} Optional((Function))
`
Any idea ?

**Comment by timburks** [comment]
@muxi, do you have any perspective on this?
