### ISSUE TITLE
Consider internalising the convenience "commonly used" statuses

### ISSUE THREAD

**Issue by glbrntt** [grpc/grpc-swift#821]
### Is your feature request related to a problem? Please describe it.

It's too easy to accidentally compare a `GRPCStatus` instead of a status code.

Specifically, `GRPCStatus` has public static `.ok` [here](https://github.com/grpc/grpc-swift/blob/4dd5ee2b6e0fd74dffda2096407c186c477de04f/Sources/GRPC/GRPCStatus.swift#L42), however this is distinct from the `.ok` status code. 

This makes it really easy to write code like:

```swift
if status == .ok {
  celebrate(with: "🍺")
} else {
  commiserate(with: "🍺")
}
```

However `GRPCStatus` also contains a message so the equality check can fail when the status code is `.ok` and the messages are different.

### Describe the solution you'd like

- `GRPCStatus.ok` should be made `internal`
- Add an `isOk: Bool` computed property which checks only the `code`

### Describe alternatives you've considered

None.

### Additional context

None.

**Comment by MrMage** [comment]
On the server side, I like being able to just return `.ok` as a status. I could of course just define that myself in an extension. But what about others who don't know what to put into the message field? I like to "nudge" them towards a sane default, if you know what I mean. But I agree that the comparisons are problematic; I guess that would actually be more problematic.

**Comment by glbrntt** [comment]
Forgot about that when I wrote this one up. 100% agree that sane defaults are helpful to have.

So I think we should definitely add `isOk` which _might_ be enough to avoid the problem (with documentation). (This is what I'm leaning towards.)

We could also add factory methods: `makeOk()` etc., but that feels a bit weird for a constant.
