### ISSUE TITLE
Archive Failing on Xcode 11.4 / 11.5

### ISSUE THREAD

**Issue by mRs-** [grpc/grpc-swift#822]
### Describe the bug

When using Xcode 11.4 or 11.5 and archiving the grpc-swift implementation in a Framework or a static lib xcode is crashing with an Libtool failed command without an exit code. All grpc-swift version are **1.0.0-alpha.1** to **1.0.0-alpha.12**.

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: object: /Users/mariuslandwehr/Library/Developer/Xcode/DerivedData/Networking-cskqpnmvfnmzorctpckvxmsmisys/Build/Intermediates.noindex/ArchiveIntermediates/Networking/BuildProductsPath/Release/CGRPCZlib.o malformed object (string table at offset 0 with a size of 8, overlaps Mach-O headers at offset 0 with a size of 160)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: object: /Users/mariuslandwehr/Library/Developer/Xcode/DerivedData/Networking-cskqpnmvfnmzorctpckvxmsmisys/Build/Intermediates.noindex/ArchiveIntermediates/Networking/BuildProductsPath/Release/CNIOLinux.o malformed object (string table at offset 0 with a size of 8, overlaps Mach-O headers at offset 0 with a size of 160)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: object: /Users/mariuslandwehr/Library/Developer/Xcode/DerivedData/Networking-cskqpnmvfnmzorctpckvxmsmisys/Build/Intermediates.noindex/ArchiveIntermediates/Networking/BuildProductsPath/Release/CGRPCZlib.o malformed object (string table at offset 0 with a size of 8, overlaps Mach-O headers at offset 0 with a size of 160)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: object: /Users/mariuslandwehr/Library/Developer/Xcode/DerivedData/Networking-cskqpnmvfnmzorctpckvxmsmisys/Build/Intermediates.noindex/ArchiveIntermediates/Networking/BuildProductsPath/Release/CNIOLinux.o malformed object (string table at offset 0 with a size of 8, overlaps Mach-O headers at offset 0 with a size of 160)
Command Libtool failed with a nonzero exit code
```

### To reproduce

To Reproduce clone or zip https://github.com/mRs-/Xcode-11.4-Libtool-Regression

Steps to reproduce the bug you've found:
1. Clone or download the repo
2. Open the Xcode Project
3. Archive the Project
4. LibTool is failing

### Expected behaviour

Libtool is not failing and the network framework is building

### Additional information

Currently the only working solution is to build my macOS application under Xcode 11.3...

**Comment by weissi** [comment]
Thank you for reporting & the great example project. This is a compiler bug. I filed a bugs.swift.org for you: https://bugs.swift.org/browse/SR-12939

**Comment by mRs-** [comment]
Thanks!

**Comment by weissi** [comment]
Thanks to @abertedrud, I found a very simple workaround that fixes this:

- https://github.com/grpc/grpc-swift/pull/826
- https://github.com/apple/swift-nio/pull/1546

**Comment by weissi** [comment]
@mRs- A few minutes ago, @glbrntt released NIO 2.18.0 & gRPC Swift 1.0.0-alpha.13 which should work around this issue.

Would you mind confirming that after a File > Swift Packages > Update to Latest Package Versions everything works correctly?

**Comment by mRs-** [comment]
Yep it's working when I update the Dependencies to the latest version. Did this also for the others Dependencies. Should be okay to update this.

**Comment by mRs-** [comment]
Thanks for your help @weissi and @glbrntt !

**Comment by weissi** [comment]
Thanks for verifying this so quickly! @glbrntt I think we can close this then?
