### ISSUE TITLE
SpeechToText example does not compile due to "Type 'Google_Protobuf_Empty' does not conform to protocol 'GRPCPayload'"

### ISSUE THREAD

**Issue by vlopezferrando** [grpc/grpc-swift#823]
# Describe the bug

The SpeechToText example does not build due to the compilation error:

    Type 'Google_Protobuf_Empty' does not conform to protocol 'GRPCPayload'

The issue was reproduced in the `master` branch (`4dd5ee2b`), in macOS 10.14.6 (Apple Swift version 5.1.3).

### To reproduce

Follow the instructions in the example (note that we need to update the `Podfile` to point at `1.0.0-alpha.12`):

    git clone https://github.com/grpc/grpc-swift.git
    cd grpc-swift
    make plugins
    # Add plugins to $PATH
    cd Examples/Google/SpeechToText
    # Edit Podfile: pod 'gRPC-Swift', '1.0.0-alpha.11' -> pod 'gRPC-Swift', '1.0.0-alpha.12'
    pod install
    make protos
    make generate
    open SpeechToText-gRPC-iOS.xcworkspace

Now, when building from XCode, we get 4 errors, all being:

    Type 'Google_Protobuf_Empty' does not conform to protocol 'GRPCPayload'

### Expected behaviour

It should compile.

### Additional information

This issue may be related to https://github.com/grpc/grpc-swift/issues/801, but it is beyond my knowledge on gRPC and Swift how it can be fixed.

**Comment by glbrntt** [comment]
Thanks for the bug report @vlopezferrando -- I believe this is just an impedance mismatch: the example expects alpha.11 but the plugin on `master` has changed and is ahead of that. (The library version and plugin version should match.)

Can you try checking out the `1.0.0-alpha.11` tag, rebuilding the plugins and trying again?

Thanks for reporting though: this will need updating once the changes in `master` get tagged.

**Comment by vlopezferrando** [comment]
Thanks, @glbrntt, for the quick reply! I did what you suggested and was able to compile the project. I leave the closing of this Issue to you.

**Comment by glbrntt** [comment]
Great, glad it worked!
