### ISSUE TITLE
GRPCStatus and Error States

### ISSUE THREAD

**Issue by mRs-** [grpc/grpc-swift#836]
The `GRPCStatus` is currently a little bit missleading. Even if the Status from a response is ok the Status is still an error Type. 

Why exactly is not a result type for this sort of behaviour used, something like `Result<Void/OK, GRPCStatus>`. 

Currently it's really hard to write a wrapper around the API for the usage of Combine or RxSwift with gRPC...

**Comment by mRs-** [comment]
I know about the combine wrapper, it's currently missing initial and trailing metadata support.

**Comment by glbrntt** [comment]
> I haven't used RxSwift and have very limited experience with Combine; why does this make it difficult?

@mRs- any thoughts on this? I'd like to understand the difficulties here so we can resolve this one way or another.

**Comment by mRs-** [comment]
Sorry for the late reply.

I am thinking about gRPC calls like `Result<Response, GRPCStatus>`. When the Error case is throwed. When I'm switching through the code in my Error cases, it's a little bit weierd to handle the `.ok` code even it's not really possible to come to the place in the first place. Sure the Status Code is different but the Error is a little bit off when a error type is not really an error. 

In my opionion it would be better to have something like:

```
class GRPCStatus {
  enum Type {
    case ok
    case error(ErrorCode)
  }

  enum ErrorCode {
    case cancelled = 1
    case unknown = 2
    ...
  }
  
  let type: Type 
  ...
}
```

**Comment by MrMage** [comment]
In this case, I would rather consider conformance to `Error` as "can be used as an error", not as "is an error". Also, even "OK" calls (status code 0) can contain a custom status message, which we would need to provide to the user. Finally, we are not throwing the _error code_ itself, but the whole struct containing the message.

I don't see a good way around this, but assuming that you don't want to treat all 16 possible status codes individually, you could simply add `.ok` to your "catch-all" `case` block that handles all the unexpected errors.

**Comment by mRs-** [comment]
At least I would like to present the user what actually is happening right now 😀
