### ISSUE TITLE
Request: private var channel: Channel -> {{ access }} var channel: Channel

### ISSUE THREAD

**Issue by yoheimuta** [grpc/grpc-swift#85]
Since we need to be able to access Channel in order to set Timeout, we want to make it public rather than private.

- https://github.com/grpc/grpc-swift/blob/c37a4cd29a15cef5b4a0a4acd16ad603b608da9d/Plugin/Templates/client.pb.swift#L53

ref. https://github.com/grpc/grpc-swift/issues/67

**Comment by timburks** [comment]
Changed in [this commit](https://github.com/grpc/grpc-swift/commit/75e8ec06ab83330e58703a7d81150c6ab4395fa5).

**Comment by yoheimuta** [comment]
Thanks!
