### ISSUE TITLE
Make `ClientConnectionKeepalive` and `ServerConnectionKeepalive` `Hashable`

### ISSUE THREAD

**Issue by glbrntt** [grpc/grpc-swift#862]
https://github.com/grpc/grpc-swift/pull/850 introduced `ClientConnectionKeepalive` and `ServerConnectionKeepalive`, both should be `Hashable`.

Once https://github.com/apple/swift-nio/pull/1571 makes it into a tagged release we should update these types to be `Hashable`.

**Comment by SebastianThiebaud** [comment]
Done in #850

**Comment by glbrntt** [comment]
That was quick, thanks @SebastianThiebaud!
