### ISSUE TITLE
GRPC is scalable or not

### ISSUE THREAD

**Issue by medaminenajjar** [grpc/grpc-swift#863]
Hello,

I want to know if the GRPC is scalable or not because I tested with this example and I managed to recover the data with a list of 3 things but with a list of a 100 things it displays the timeout error. Here is the example i tested.

 ```
let configuration = ClientConnection.Configuration(target: ConnectionTarget.hostAndPort("host",9632),
                                                               eventLoopGroup: PlatformSupport.makeEventLoopGroup(loopCount: 10))
let clientConnection = ClientConnection(configuration: configuration)
```

And I use Google_Protobuf_Any as a sending and response model

requestContent: is a sending model

```
let data = try! Google_Protobuf_Any(message: requestContent)
request.content = data
```

then I make the call to service with :
`let callOptions = CallOptions(timeLimit: .timeout(.seconds(30)))`

And,

```
call.response.whenComplete({ (result) in
            switch result {
                case .success(let response):
                    let anyObject = response.content
                    if anyObject.isA(MPHikesResponse.self)  {
                        let result = try? MPHikesResponse(unpackingAny: anyObject)
                    }
                case .failure(let error):
                    print("CALL FAILED WITH ERROR\n\(error)")
            }
        }

```
In this case the failure closure is called and it is displayed:

deadlineExceeded (4): RPC timed out before completing (timeout=30000000000 nanoseconds)

**Comment by glbrntt** [comment]
When filing issues in the future please use one of the issue templates and format any code snippets using backticks (```). Doing so will make it much easier for us to understand your problem and ultimately, help you.

The first obvious question here is: what are, and how big are the “things” in the list?

**Comment by medaminenajjar** [comment]
Thanks for your quick response :)

So the data model that I use a reference and a name of type string.

`struct MPHike {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var reference: String {
    get {return _storage._reference}
    set {_uniqueStorage()._reference = newValue}
  }

  var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}
`

**Comment by medaminenajjar** [comment]
Thanks for your quick response :)

So the data model that I use a reference and a name of type string.
```
struct MPHike {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var reference: String {
    get {return _storage._reference}
    set {_uniqueStorage()._reference = newValue}
  }

  var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}
```

**Comment by glbrntt** [comment]
My understanding of your problem is:

- Make a single unary call (possibly, this is unclear) which sends some data (it's unclear what that data is)
- Receive a response which is an `Any`-protobuf which is an `MPHikesResponse` which contains a list of `MPHike` 
- When that list has 3 things it works fine, when it has 100 it times out after 30 seconds.

If that's the case then gRPC _should_ be able to handle that without any problem.

Can you share the complete code for making the call as well as the .proto including the service definitions?

**Comment by medaminenajjar** [comment]
Here is the code and for the .proto file content

```
syntax = "proto3";
option java_multiple_files = true;
option java_package = "com.mobilepowered.platform";

import "google/protobuf/any.proto";

service MotwinCompat {
  rpc processRequest(MotwinRequest) returns (MotwinResponse) { }
}

message MotwinRequest {
  string type = 1;
  int32 identifier = 2;
  google.protobuf.Any content = 3;
}

message MotwinResponse {
  int32 identifier = 1;
  int32 code = 2;
  google.protobuf.Any content = 3;
}

message stringContent {
  string content = 1;
}

message MPHike {
	 string reference=1;
	 string name=2;
}

message GetHikesRequestContent {
	 string entityId=1;
	 double latitude=2;
	 double longitude=3;
	 string language=4;
}

message MPHikesResponse {
	 repeated MPHike hikesList=1;
}

message EntityDetailsResponse {

	 string mail=1;
	 string cgu=2;
	 string appName=3;
}

message GetEntityDetailsRequest {
	 string entityId=1;
}

message HikeClosestResponse {
	
     string reference=1;
     string name=2;
     int32 typeId=3;
     int64 lastUpdated=4;
     string pictureUr=5;
     int32 lengthInMeters=6;
     int32 durationInMinutes=7;
     int32 difficultyId=8;
     int32 note=9;
     string visibility=10;
     string priceRef=11;
     string hikeDownloadUrl=12;
   }
 message HikeClosestContent {
	
	 double latitude=1;
	 double longitude=2;
     string entityId=3;
     string langue=4;    
     int64 startDate=5;
   }
```

**Code implementation :**

```
//
//  ViewController.swift
//  iOSProjectTestNewMotwin
//
//  Created by Med Amine Najjar on 5/29/20.
//  Copyright © 2020 Med Amine Najjar. All rights reserved.
//

import UIKit
import GRPC
import SwiftProtobuf

class TestViewController: UIViewController {

    ///Variables
    private var reqClient:MotwinCompatClient? = nil

    override func viewDidLoad() {
        super.viewDidLoad()
        let configuration = ClientConnection.Configuration(target: ConnectionTarget.hostAndPort(host,9632),
                                                               eventLoopGroup: PlatformSupport.makeEventLoopGroup(loopCount: 10))

        reqClient = MotwinCompatClient(channel: ClientConnection(configuration: configuration))
    }

    @IBAction func buttonCliked(){

        var hikesRequestContent = GetHikesRequestContent()
        hikesRequestContent.entityID = "582f027536ef89.12488"
        hikesRequestContent.latitude = 48.862725
        hikesRequestContent.longitude = 2.287592
        hikesRequestContent.language = "fr"
        /// Motwin Request Content
        var motwinRequest = MotwinRequest()
        motwinRequest.type = "getHikes"
        motwinRequest.identifier = 1
        let data = try! Google_Protobuf_Any(message: hikesRequestContent)
        motwinRequest.content = data
        
        let callOptions = CallOptions(timeLimit: .timeout(.seconds(30)))
        
        let call = reqClient!.processRequest(motwinRequest, callOptions: callOptions)
        
        call.response.whenComplete({ (result) in
            switch result {
                case .success(let response):
                    let anyObject = response.content
                    if anyObject.isA(MPHikesResponse.self)  {
                        let result = try? MPHikesResponse(unpackingAny: anyObject)
                        print(result?.hikesList[0].name ?? "N/A")
                    }
                case .failure(let error):
                    print("CALL FAILED WITH ERROR\n\(error)")
            }
        })
    }
}
```

**Comment by glbrntt** [comment]
Thanks for providing that: there's nothing obviously wrong here which would lead to the timeout.

It's possible that for some reason we're not actually able to establish the connection. Can you attach some debug logs? You can enable them using:

```
import Logging

... 

LoggingSystem.bootstrap {
  var handler = StreamLogHandler.standardOutput(label: $0)
  handler.logLevel = .debug
  return handler
}
```

**Comment by medaminenajjar** [comment]
But nothing happens when I added the LoggingSystem.

**Comment by glbrntt** [comment]
Sorry, I should have been more specific:

- The `LoggingSystem.bootstrap` call needs to be run exactly once (bootstrapping the logging system multiple times will cause a fatal error); doing this in the app delegate when the app finishes launching is probably fine.
- The `bootstrap` call provides a factory to produce log handlers to a global logging system (note: this is https://github.com/apple/swift-log which is separate from `os_log`). Every time a new `Logger` it will be done so using the given this factory method. As you can see this factory produces log handlers for `standardOutput` and then sets the level to `.debug` to give us more information.

The result of this is that when you build and run your test app from Xcode you should see the logs printed to the debug area.

**Comment by medaminenajjar** [comment]
Thank you very much for your quick response it displays this as a result when I put the code above.
<img width="638" alt="Screen Shot 2020-07-01 at 2 08 13 PM" src="https://user-images.githubusercontent.com/12759865/86247608-9eb64f00-bba4-11ea-8bc6-5f3b10887cae.png">

**Comment by glbrntt** [comment]
That's a printout from the debugger of a log handler, not the lines printed by the logger.

---

Here's a [minimal example](https://github.com/grpc/grpc-swift/files/4865675/Demo.zip) of an iOS app using gRPC with an implementation of your service from the proto above. Handling 100 responses is not an issue; I suspect your problem is that you don't actually have a connection to your server or that you're not holding gRPC correctly.

To run the example:
1. Unzip the attached Demo.zip
2. In `Demo/Server` run `swift run` to start the server
3. Open the Xcodeproj, run the app in a simulator.

**Comment by glbrntt** [comment]
@medaminenajjar are you still having issues?

**Comment by medaminenajjar** [comment]
Sorry because I can't answer.

And concerning the demo that you send to me thank you so much but it is displayed.
<img width="1126" alt="Screen Shot 2020-07-13 at 11 31 24 AM" src="https://user-images.githubusercontent.com/12759865/87295091-98a56400-c4fc-11ea-9015-450bb9f03be0.png">

**Comment by medaminenajjar** [comment]
@glbrntt Any idea with this result. it didn't display the 100 items.

**Comment by glbrntt** [comment]
You can see from the client logs in Xcode that there's no active connection; the first line shows the connectivity state changing from "connecting" to "transientFailure", the second line from from "transientFailure" to "connecting"; there's no log where the state becomes "ready".

Your RPC isn't working because your client doesn't have a connection to the server. If I recall correctly, the demo I prepared was setup to work on localhost port 1234; that should work fine on a Simulator. I suspect the issue you have is setup related.

**Comment by medaminenajjar** [comment]
Thank you very much because it worked well in the simulator but not with the device. 
Have you any idea about this?
The closure whenComplete not called with device.

**Comment by Lukasa** [comment]
Have you provisioned appropriate networking entitlements?

**Comment by medaminenajjar** [comment]
Yes I added it but there is no change.
Is something missing?
<img width="1364" alt="Screen Shot 2020-07-21 at 11 59 59 AM" src="https://user-images.githubusercontent.com/12759865/88047564-b6e91080-cb49-11ea-926f-06e1a5606db3.png">

**Comment by Lukasa** [comment]
Hmm, none of those should be necessary. Can you provide the logs from the failure?

**Comment by medaminenajjar** [comment]
<img width="1200" alt="Screen Shot 2020-07-21 at 1 39 12 PM" src="https://user-images.githubusercontent.com/12759865/88056428-6cbb5b80-cb58-11ea-8fcf-a811e0896c58.png">

**Comment by Lukasa** [comment]
Ok, the RPC is timing out on a 30s timeout. That's a long timeout, we could reasonably assume that the request would never succeed.

Where do the `send request` and `response request` logs come from?

**Comment by medaminenajjar** [comment]
`send request` I put it before the service call and the  `response request` in the closure whenComplete.

but with simulator it work correctly:

```
send request : 1595336738.768124
2020-07-21T14:05:38+0100 info io.grpc.client_channel : connection_id=039CB997-45FD-45F3-A33D-80ABF37A4315/0 old_state=idle new_state=connecting connectivity state change
2020-07-21T14:05:38+0100 info io.grpc.client_channel : remote_address=[IPv4]********** connection_id=039CB997-45FD-45F3-A33D-80ABF37A4315/0 event_loop=NIOTransportServices.NIOTSEventLoop gRPC connection ready
2020-07-21T14:05:38+0100 info io.grpc.client_channel : connection_id=039CB997-45FD-45F3-A33D-80ABF37A4315/0 new_state=ready old_state=connecting connectivity state change
response request : 1595336757.8331141
SUCCESS: got list with 10322 items
```

**Comment by Lukasa** [comment]
So it seems that the closure `whenComplete` is being called in both cases, no? We’re seeing `response request` in both sets of logs.

**Comment by glbrntt** [comment]
> Ok, the RPC is timing out on a 30s timeout. That's a long timeout, we could reasonably assume that the request would never succeed.

30s is a long timeout but from the numbers above the simulator takes about 19 seconds. This seems like a _really_ large request. Does it complete successfully on a physical device with a longer timeout, say 60 seconds?

**Comment by medaminenajjar** [comment]
It called when the request is timed out (Failure) or in the success case.
```
print("send request : \(Date().timeIntervalSince1970)")
        let callOptions = CallOptions(timeLimit: .timeout(.seconds(30)))
        let call = reqClient?.processRequest(request, callOptions: callOptions)
        call?.response.whenComplete { result in
            print("response request : \(Date().timeIntervalSince1970)")
            switch result {
            case .success(let response):
                if let hikes = try? MPHikesResponse(unpackingAny: response.content) {
                    print("SUCCESS: got list with \(hikes.hikesList.count) items")
                } else {
                    print("ERROR: got response but could not unpack content")
                }
            case .failure(let error):
                print("FAILURE: \(error)")
            }
        }
```

**Comment by medaminenajjar** [comment]
On a physical device no result with 120 seconds.

```
send request : 1595337812.0925732
2020-07-21T14:23:32+0100 info io.grpc.client_channel : old_state=idle connection_id=39F855CE-AD6F-4A11-804C-BAB210C232BD/0 new_state=connecting connectivity state change
2020-07-21T14:23:32+0100 info io.grpc.client_channel : remote_address=[IPv4]******* event_loop=NIOTransportServices.NIOTSEventLoop connection_id=39F855CE-AD6F-4A11-804C-BAB210C232BD/0 gRPC connection ready
2020-07-21T14:23:32+0100 info io.grpc.client_channel : new_state=ready old_state=connecting connection_id=39F855CE-AD6F-4A11-804C-BAB210C232BD/0 connectivity state change
2020-07-21T14:25:32+0100 error io.grpc.client_channel : path=/MotwinCompat/processRequest connection_id=39F855CE-AD6F-4A11-804C-BAB210C232BD/0 request_id=46B753FD-6650-4E0B-A927-A511F57ADA13 call_state=active error=RPC timed out before completing (timeout=120000000000 nanoseconds) grpc client error
response request : 1595337932.104473
FAILURE: deadlineExceeded (4): RPC timed out before completing (timeout=120000000000 nanoseconds)
```

**Comment by glbrntt** [comment]
Could you find out how large the response is (i.e. `response.serializedData().count`)?

**Comment by medaminenajjar** [comment]
When i test with simulator it display this:

```
print("send request : \(Date().timeIntervalSince1970)")
        
        let call = reqClientAgos?.processRequest(request, callOptions: callOptions)
        call?.response.whenComplete { result in
            print("response request : \(Date().timeIntervalSince1970)")
            switch result {
            case .success(let response):
                let size = try? response.serializedData().count
                print("Size =  \(String(describing: size))")
                if let hikes = try? MPHikesResponse(unpackingAny: response.content) {
                    print("SUCCESS: got list with \(hikes.hikesList.count) items")
                } else {
                    print("ERROR: got response but could not unpack content")
                }
            case .failure(let error):
                print("FAILURE: \(error)")
            }
        }
``` 

```
send request : 1595339836.03636
2020-07-21T14:57:16+0100 info io.grpc.client_channel : connection_id=D2A29D49-02D8-4CFE-A8D8-5E29268E946F/0 old_state=idle new_state=connecting connectivity state change
2020-07-21T14:57:16+0100 info io.grpc.client_channel : connection_id=D2A29D49-02D8-4CFE-A8D8-5E29268E946F/0 remote_address=[IPv4]******* event_loop=NIOTransportServices.NIOTSEventLoop gRPC connection ready
2020-07-21T14:57:16+0100 info io.grpc.client_channel : old_state=connecting new_state=ready connection_id=D2A29D49-02D8-4CFE-A8D8-5E29268E946F/0 connectivity state change
response request : 1595339854.0183082
Size =  Optional(3393840)
SUCCESS: got list with 10322 items
```

**Comment by glbrntt** [comment]
Thanks, I've been looking into this some more, I think I've found a path where we may do a bunch of unnecessary copying which might explain why this is so slow (the 19 seconds in the simulator is surprising for a ~3.4 MB response).

**Comment by medaminenajjar** [comment]
But I don't know why in the simulator it takes a little time but in a device it returns a timeout (I test the connection in my iPhone and in my iMac and it is almost the same).

**Comment by glbrntt** [comment]
Could you record a couple of traces with Instruments (running on a physical device) to help narrow things down? It'd be useful to have traces for Allocations and the Time Profiler templates. 20 seconds of each trace should be enough.

**Comment by medaminenajjar** [comment]
I did this tests Instruments:
[https://drive.google.com/file/d/1022hzG5oJPog8j_16uLFjSAcBbbPtHK6/view?usp=sharing]

**Comment by medaminenajjar** [comment]
@glbrntt Any news please ?

**Comment by glbrntt** [comment]
Nothing obvious in the Instruments traces. Can you provide an Allocations trace as well?

Also a couple of questions so I can make sure I understand your setup properly:

- Is the client your own, or the client from the demo I uploaded?
- Is the server your own, or the server from the demo I uploaded?
- If the server is your own:
  - do you observe the same problem using the server I uploaded?
  - is it running on your machine? If not is it geographically far from you?

**Comment by medaminenajjar** [comment]
Thank you for your answer, I am doing the test on the demo that you sent me it work in the simulator and not in the device.

The instrument that i do it on my demo and on a remote server, i don't know why it work on android and not on iOS.
[Archive 4.zip](https://github.com/grpc/grpc-swift/files/4971433/Archive.4.zip)

**Comment by glbrntt** [comment]
> I am doing the test on the demo that you sent me it work in the simulator and not in the device.

Sorry, which client and which server? The demo for both?

**Comment by medaminenajjar** [comment]
You can see the demo i made, it run in simulator and an Android device and not for iOS device.

[https://drive.google.com/file/d/1Lou507egryH5iPjUmtXaj1wLAcknjqNX/view?usp=sharing](https://drive.google.com/file/d/1Lou507egryH5iPjUmtXaj1wLAcknjqNX/view?usp=sharing)

**Comment by glbrntt** [comment]
I'm afraid this works fine for me, it takes less than a second to get a response on a simulator and physical device. This suggests that there's a problem in your network.

**Comment by medaminenajjar** [comment]
Hello,

I'd like to know there is any tips to do because i test with Internet and 4G but the same result.
Can you do a little video with a real device to see there is a difference or not.

**Comment by glbrntt** [comment]
I'm sorry but this isn't a gRPC Swift issue.
