### ISSUE TITLE
Echo Example doesn't enforce client cert TLS requirements?

### ISSUE THREAD

**Issue by whilesoftware** [grpc/grpc-swift#868]
Is it possible to **require** a client certificate, as opposed to "validate the client certificate **if** it is provided"?

The Echo server, when called via `./Echo server --tls 42000`, initializes the server with:
```swift
builder = Server.secure(group: group, certificateChain: [serverCert.certificate], privateKey: SamplePrivateKey.server)
  .withTLS(trustRoots: .certificates([caCert.certificate]))
```

The Echo client, when called via `./Echo client --tls localhost 42000 get foo`, initializes the client connection with:
```swift
builder = ClientConnection.secure(group: group)
  .withTLS(certificateChain: [clientCert.certificate])
  .withTLS(privateKey: SamplePrivateKey.client)
  .withTLS(trustRoots: .certificates([caCert.certificate]))
```

And this works as expected. But when I omit the client cert from the initialization altogether, I expected the call to fail.
```swift
builder = ClientConnection.secure(group: group)
  //.withTLS(certificateChain: [clientCert.certificate])
  //.withTLS(privateKey: SamplePrivateKey.client)
  .withTLS(trustRoots: .certificates([caCert.certificate]))
```

But when testing with the modified code the connection succeeds, which leads me to suspect the server is validating client certs when present, but not enforcing them as a requirement.

**Comment by Lukasa** [comment]
You omitted the issue template, which means we're missing some information? Which version or commit of grpc-swift are you using? What platform?

**Comment by Lukasa** [comment]
Assuming it's a recent release of the NIO branch, try adding `.withTLS(certificateVerification: .fullVerification)` to the server builder.

**Comment by whilesoftware** [comment]
My bad. I'm working with the master branch, commit `efb67a324eaf1696b50e66bc471a53690e41fbf6`. I'm building and testing on MacOS 10.16 (11?) with the XCode 12 beta commandline suite released last week.

I added .fullVerfification as you suggested, but now the client fails to connect even when including its cert and key.

What's the best way to turn on debugging and dive into this? If I remove the "Reduce the logging verbosity" config at the start of main() I get a bit more info from the client but the server never makes a peep.

Is there any chance someone could document the steps used to generate the keys hardcoded in GRPCSampleData.swift?

**Comment by Lukasa** [comment]
Ok, so the fact that the client now fails to connect is key. Despite the docs on the server builder, the server does _not_ default its certificate verification to required: it only does so if you ask it. Given that the client doesn't have a valid certificate for its IP, try changing `.fullVerification` to `.noHostnameVerification`.

**Comment by whilesoftware** [comment]
Switching to `.noHostnameVerification` did the trick. Thanks!
