### ISSUE TITLE
Add ability to put generated test clients into separate files from their production equivalents

### ISSUE THREAD

**Issue by davidpasztor** [grpc/grpc-swift#878]
### Is your feature request related to a problem? Please describe it.

#870 introduced the `TestClient=true` option for generating test clients, which is great for unit testing client-side gRPC code. However, the current implementation generates the test client code in the same file as the real, production client code, which isn't ideal. The test client code should only be added to the (unit) test target in most scenarios, but due to the fact that it is generated in the same file as its non-test equivalent, this cannot be achieved without manually modifying the generated files (which isn't ideal).

### Describe the solution you'd like

It would be great if a new protoc flag was introduced that would enable the test client code to be generated into separate files so that clients don't need to pollute their production targets with test code while also not having to manually edit generated code.

### Describe alternatives you've considered

If we deem that most consumers of grpc-swift want their test clients to only be accessible from the test target, instead of adding a new flag, the current implementation could simply be changed, which would result in the test clients automatically being generated into their own files.

### Additional context

Add any other context about the feature request here.

**Comment by glbrntt** [comment]
Is the real goal to have them in separate _modules_ rather than separate files? I.e. production and public generated code in one module, test client(s) in another?

At the moment `Client=true` is required for `TestClient=true` to have any effect. One option would be changing this so that if `Client=false` and `TestClient=true` then we _only_ generate the test client implementation: it would therefore _require_ the generated client protocol to be provided by elsewhere (i.e. the public facing production module).

**Comment by davidpasztor** [comment]
@glbrntt exactly, we want to be able to add the test clients to the test target module and the production clients to app/framework modules.

**Comment by glbrntt** [comment]
@davidpasztor just an FYI in case you used it: the `PayloadConformance` codegen option which was added to support this issue was removed in the latest release (because generating conformance to `GRPCProtobufPayload` is no longer required).

**Comment by davidpasztor** [comment]
@glbrntt thanks for the heads up, I'll make sure to update our generator script accordingly.
