### ISSUE TITLE
Consider throwing an error on non-success status code in unary call

### ISSUE THREAD

**Issue by novi** [grpc/grpc-swift#88]
In unary call on a client, We have no way to handle a status code of response.
We could fix that with like [this](https://github.com/novi/grpc-swift/blob/7ea88d1e8fbfa60c8da3478ccaeb21965f3e6609/Plugin/Templates/client-call-unary.swift#L22).

Plus we could add a new case for client service error.
```swift
/// Type for errors thrown from generated client code.
{{ access }} enum {{ .|clienterror:file,service }} : Error {
  case endOfStream
  case invalidMessageReceived
  case error(c: CallResult)
  case statusError(code: Int) // <-
}
```

**Comment by aleczadikian** [comment]
I ended up changing `ClientCallUnary.swift` in the current latest SwiftGRPC Cocoapods code like this, and it seems to work right:

```
@@ -33,7 +33,7 @@ open class ClientCallUnaryBase<InputType: Message, OutputType: Message>: ClientC
       sem.signal()
     }
     _ = sem.wait()
-    if let returnResponse = returnResponse {
+    if let returnResponse = returnResponse, returnCallResult.statusCode == .ok {
       return returnResponse
     } else {
       throw RPCError.callError(returnCallResult)
```

**Comment by MrMage** [comment]
Yes, that should work, but it discards the sent data completely. Ideally, we'd want to provide both the returned data and the status code in this case, but this would complicate our model. OTOH, I guess the case where we get a response _and_ a non-OK status code is fairly rare, so we could just throw the result like you did.

@timburks, what do you think?

**Comment by MrMage** [comment]
The CgRPC implementation is now officially deprecated; closing this for now.
