### ISSUE TITLE
FakeUnaryResponse sendMessage differs from real world implementation

### ISSUE THREAD

**Issue by mRs-** [grpc/grpc-swift#883]
### Describe the bug

When calling `try! fakeResponse.sendMessage(.with { _ in })`  it's behaving not as the real implementation. 

### To reproduce

Fake a Implementation with `fakeResponse.sendMessage`.

The Status Code is already send even if the trailing meta data has not arrived.

Current Order of Responses
1. InitialMetadata
2. status (from the trailing metadata)
3. response
4. trailingmetadata

### Expected behaviour

Order of Responses
1. InitialMetadata
2. response
3. trailingmetadata
4. status (from the trailing metadata)

**Comment by glbrntt** [comment]
I believe what you're observing is not a difference in the ordering in which the response parts are _delivered_, but a difference in when their callbacks are executed. 

If you call the following:

```swift
let stream = self.client.makeGetResponseStream()
let get = self.client.get(.with { $0.text = "Foo!" })

get.status.whenSuccess { _ in print("Status") }
get.trailingMetadata.whenSuccess { _ in print("Trailing") }
get.response.whenSuccess { _ in print("Response") }
get.initialMetadata.whenSuccess { _ in print("Initial") }

// Send a response.
try stream.sendMessage(.with { $0.text = "Bar!" })
```

then you'll observe the correct ordering:

```
Initial
Response
Trailing
Status
```

However, if you enqueue the callbacks _after_ sending the response, then the callbacks are executed in the order in which they are _executed_:

```swift
let stream = self.client.makeGetResponseStream()
let get = self.client.get(.with { $0.text = "Foo!" })

// Send a response.
try stream.sendMessage(.with { $0.text = "Bar!" })

get.status.whenSuccess { _ in print("Status") }
get.trailingMetadata.whenSuccess { _ in print("Trailing") }
get.response.whenSuccess { _ in print("Response") }
get.initialMetadata.whenSuccess { _ in print("Initial") }
```

Now you'll observe:

```
Status
Trailing
Response
Initial
```

The difference is that in the second case the futures _already hold their 'future' value_ when you register the callback. This is the _same_ as a 'real' client. You would observe the same behaviour with a 'real' client if you waited long enough before registering callbacks on the futures. Let me know if any of that doesn't make sense!

**Comment by mRs-** [comment]
Yep make sense to me... this was more a problem of my test setup than my actual implementation.

Thanks for heading me in the right direction.

**Comment by glbrntt** [comment]
No problem, happy to help!
