### ISSUE TITLE
Support gRPC map

### ISSUE THREAD

**Issue by billcchung** [grpc/grpc-swift#891]
### Is your feature request related to a problem? Please describe it.

Current if we define proto with a map like 
```
message UserPreferences {
  map<string, string> preference = 10;
}
```
the generated grpc.swift Will contain:
```
extension UserPreferences.PreferencesEntry: GRPCProtobufPayload {}
```
which resulted in an error:
<img width="1216" alt="Screen Shot 2020-07-14 at 21 44 41" src="https://user-images.githubusercontent.com/5371682/87428462-545db500-c61d-11ea-9402-73695f7e395d.png">
`'PreferencesEntry' is not a member type of 'UserPreferences'`

in the [proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3#maps) map can be used.

### Describe the solution you'd like

Hopefully we can have `map` supported.

### Describe alternatives you've considered

In order to work around this we had to refactor the struct to use `repeated`:
```
message UserPreferences {
  repeated UserPreference preferences = 1;
}

message UserPreference {
  string key = 10;
  string value = 20;
}
```
but this isnt really ideal, hopefully we can have map supported.

**Comment by glbrntt** [comment]
Thanks for the report @billcchung; I'm aware of this particular bug. It's related to how we support payloads other than Protobuf which has caused quite a lot of pain. As such I'm currently revisiting how we support other payloads: the work done in #886 and #889 remove the requirement to have `GRPCProtobufPayload` entirely and should just eliminate this class of bugs.

I need to make a few more PRs to finish off those changes but I'm hoping to release these changes (and resolve this bug) in the next couple of days.

**Comment by glbrntt** [comment]
In the meantime if you apply this patch to the code generator you should be able to use `map` in your proto:

```
--- a/Sources/protoc-gen-grpc-swift/Generator-Conformance.swift
+++ b/Sources/protoc-gen-grpc-swift/Generator-Conformance.swift
@@ -32,7 +32,7 @@ extension Generator {
     self.println("extension \(name): GRPCProtobufPayload {}")
 
     // Messages may be nested.
-    for message in message.messages {
+    for message in message.messages where !message.isMapEntry {
       self.printProtobufExtensions(for: message)
     }
   }
```

**Comment by billcchung** [comment]
thank you so much @glbrntt, we prefer to not apply some patches (but the suggestion is still appreciated!), 
so I'll keep an eye on the release and once it's released we can revert our work around :D

**Comment by glbrntt** [comment]
This should now be fixed in https://github.com/grpc/grpc-swift/releases/tag/1.0.0-alpha.17 -- please let us know if you have any more problems.
