### ISSUE TITLE
GRPC Communications don't work, keep getting WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by cepages** [grpc/grpc-swift#897]
I can't connect with a GRPC Server in C++, I'm getting the error:

```
  - statusCode : SwiftGRPC.StatusCode.unavailable
  ▿ statusMessage : Optional<String>
    - some : "failed to connect to all addresses"
  - resultData : nil
```

Also, probably related: Even without using certificates in GRPC, I keep getting in the console:
```
E0716 12:03:56.012884000 123145487261696 ssl_transport_security.cc:1269] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
```
I know the server works fine, because I don't have any problems connecting with Android.

Version `grpc-swift`: 0.11.0

Maybe related: 
https://github.com/grpc/grpc/issues/9538

Any idea?

**Comment by Lukasa** [comment]
This is highly likely to be user-error: this error code can appear when one side is performing a TLS handshake but the other side doesn't speak TLS. Are you _sure_ you're connecting to a TLS-capable port?

**Comment by cepages** [comment]
But it shouldn't use TSL if I'm trying to connect to an insecure port without certs. 

In my swfit project, I'm creating my ServiceClient with only the address and the port, no certs are provided:
```
ServiceClientBase("ServerAddress:InsecurePort")
```
I know the server is working because Android can connect without problems to the same address and port ( again without adding certs )

**Comment by cepages** [comment]
But it shouldn't use TSL if I'm trying to connect to an insecure port without certs. 

In my swfit project, I'm creating my ServiceClient with only the address and the port, no certs are provided:
```
ServiceClientBase("ServerAddress:InsecurePort")
```
I know the server is working because Android can connect without problems to the same address and port ( again without adding certs )

**Comment by Lukasa** [comment]
That is not how the initializer works. In fact, I can't find any initializer that exactly matches that call, but the best match is this one:

https://github.com/grpc/grpc-swift/blob/14215b0e01e95dc77e140ad3ee3c77dacb0545fa/Sources/SwiftGRPC/Runtime/ServiceClient.swift#L52-L56

That initializer has an optional parameter, `secure`, that defaults to `true`. The question of whether the connection should use TLS is not in any way predicated on the port you choose, only whether you ask for TLS or not.

**Comment by cepages** [comment]
Yes, the default value was the problem, I've changed `secure = false` and it's working. 

Thanks

No idea, how this could have worked a couple of months ago....

Thanks a lot!

**Comment by lolski** [comment]
@Lukasa you saved us on a friday night.

**Comment by Lukasa** [comment]
Pleased to hear it! Now go take a break, it’s the weekend. :grin:
