### ISSUE TITLE
Can't generate grpc plugin correctly

### ISSUE THREAD

**Issue by nikitayuratkin** [grpc/grpc-swift#909]
What is my problem? I generate proto files, everything is ok. I generate grps files and get the following error in the generated file on all files. Please tell me what am I doing wrong?
![image](https://user-images.githubusercontent.com/33174759/88505843-3d39a280-cfe1-11ea-8446-0521e7f1188a.png)

**Comment by MrMage** [comment]
If you need support, please use the corresponding issue template.

**Comment by nikitayuratkin** [comment]
Sorry, im trying to do it better.
Steps :
1. import libraries (pod 'gRPC-Swift', '1.0.0-alpha.12'
 pod "gRPC-Swift-Plugins", :podspec => 'https://raw.githubusercontent.com/Lutzifer/grpc-swift/feature/add_plugins_podspec/gRPC-Swift-Plugins.podspec')
2. Generating file .proto (its ok)
3. When trying to generate a grps file with the command protoc <your proto> --grpc-swift_out = Client = true, Server = false :. , I get a file with the extension myFile.grpc.swift. Further, having added the file myFile.grpc.swift to the project, I cannot compile due to the error "No such module 'SwiftGRPC'"

Expected behaviour:
Compile project

<img width="655" alt="Снимок экрана 2020-07-27 в 10 38 43" src="https://user-images.githubusercontent.com/33174759/88516063-6106e380-cff5-11ea-97a7-abd1307ea616.png">

**Comment by glbrntt** [comment]
"SwiftGRPC" is the name of the 0.x version of the module. You must therefore be compiling your .proto files using the old version of the plugin. You can provide protoc with the path of the plugin to use with `--plugin` flag (i.e. `protoc --plugin=/some/path/to/protoc-gen-grpc-swift --grpc-swift_out=Client=true,Server=false:.`. Please see the `protoc` documentation for more info.

**Comment by nikitayuratkin** [comment]
Sorry, but it's not entirely clear to me why I can't compile everything using this guide.
https://github.com/grpc/grpc-swift#getting-the-grpc-library
and
https://github.com/grpc/grpc-swift/blob/master/docs/plugin.md

**Comment by MrMage** [comment]
You can, but you must have installed an old version of the plugins somehow.

What command exactly are you calling to compile your `.proto` files?

**Comment by nikitayuratkin** [comment]
protoc --grpc-swift_out= blahBlah.proto

I actually don't understand whyyyyy i have to install an old version(

**Comment by MrMage** [comment]
Please provide the following:

1. Your `.proto` file. Use triple backticks to escape it as code.
2. The **full** command line invocation of `protoc`. Use single backticks to escape that line.
3. The resulting `.grpc.swift` file. Use triple backticks to escape it as code.

**Comment by glbrntt** [comment]
> I actually don't understand whyyyyy i have to install an old version(

To clarify: you don't have to install an old version; the problem seems to be that you compiled with an old version of the plugin.

**Comment by nikitayuratkin** [comment]
*file .proto*:
""" 
syntax = "proto3";
import "google/api/annotations.proto";
import "public/cars/cars.proto";
package modules;



service CarsModule {
    rpc Get (cars.GetRequest) returns (stream cars.Car) {
        option (google.api.http) = {
            get:"/v1/cars"
            additional_bindings {
				get: "/v1/cars/vin/{vin}"
			}
        };
    }
    rpc Put (cars.Car) returns (cars.Car) {
        option (google.api.http) = {
            post:"/v1/cars"
            body: "*"
            additional_bindings {
				put:"/v1/cars"
                body: "*"
			}
        };
    }

    rpc Del (cars.DelRequest) returns (cars.Car) {
        option (google.api.http) = {
            delete:"/v1/cars/{vin}"
        };
    }
}

"""
*command*:

"""
protoc -I ./ public/modules/blahBlah.proto --swiftgrpc_out=./1
"""

*.grpc.swift file*:

"""
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Modules_CarsModuleGetCall: ClientCallServerStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Cars_Car?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Cars_Car?>) -> Void) throws
}

internal extension Modules_CarsModuleGetCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Cars_Car? { return try self._receive(timeout: timeout) }
}

fileprivate final class Modules_CarsModuleGetCallBase: ClientCallServerStreamingBase<Cars_GetRequest, Cars_Car>, Modules_CarsModuleGetCall {
  override class var method: String { return "/modules.CarsModule/Get" }
}

internal protocol Modules_CarsModulePutCall: ClientCallUnary {}

fileprivate final class Modules_CarsModulePutCallBase: ClientCallUnaryBase<Cars_Car, Cars_Car>, Modules_CarsModulePutCall {
  override class var method: String { return "/modules.CarsModule/Put" }
}

internal protocol Modules_CarsModuleDelCall: ClientCallUnary {}

fileprivate final class Modules_CarsModuleDelCallBase: ClientCallUnaryBase<Cars_DelRequest, Cars_Car>, Modules_CarsModuleDelCall {
  override class var method: String { return "/modules.CarsModule/Del" }
}


/// Instantiate Modules_CarsModuleServiceClient, then call methods of this protocol to make API calls.
internal protocol Modules_CarsModuleService: ServiceClient {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  func get(_ request: Cars_GetRequest, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Modules_CarsModuleGetCall

  /// Synchronous. Unary.
  func put(_ request: Cars_Car, metadata customMetadata: Metadata) throws -> Cars_Car
  /// Asynchronous. Unary.
  @discardableResult
  func put(_ request: Cars_Car, metadata customMetadata: Metadata, completion: @escaping (Cars_Car?, CallResult) -> Void) throws -> Modules_CarsModulePutCall

  /// Synchronous. Unary.
  func del(_ request: Cars_DelRequest, metadata customMetadata: Metadata) throws -> Cars_Car
  /// Asynchronous. Unary.
  @discardableResult
  func del(_ request: Cars_DelRequest, metadata customMetadata: Metadata, completion: @escaping (Cars_Car?, CallResult) -> Void) throws -> Modules_CarsModuleDelCall

}

internal extension Modules_CarsModuleService {
  /// Asynchronous. Server-streaming.
  func get(_ request: Cars_GetRequest, completion: ((CallResult) -> Void)?) throws -> Modules_CarsModuleGetCall {
    return try self.get(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func put(_ request: Cars_Car) throws -> Cars_Car {
    return try self.put(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func put(_ request: Cars_Car, completion: @escaping (Cars_Car?, CallResult) -> Void) throws -> Modules_CarsModulePutCall {
    return try self.put(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func del(_ request: Cars_DelRequest) throws -> Cars_Car {
    return try self.del(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func del(_ request: Cars_DelRequest, completion: @escaping (Cars_Car?, CallResult) -> Void) throws -> Modules_CarsModuleDelCall {
    return try self.del(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Modules_CarsModuleServiceClient: ServiceClientBase, Modules_CarsModuleService {
  /// Asynchronous. Server-streaming.
  /// Send the initial message.
  /// Use methods on the returned object to get streamed responses.
  internal func get(_ request: Cars_GetRequest, metadata customMetadata: Metadata, completion: ((CallResult) -> Void)?) throws -> Modules_CarsModuleGetCall {
    return try Modules_CarsModuleGetCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func put(_ request: Cars_Car, metadata customMetadata: Metadata) throws -> Cars_Car {
    return try Modules_CarsModulePutCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func put(_ request: Cars_Car, metadata customMetadata: Metadata, completion: @escaping (Cars_Car?, CallResult) -> Void) throws -> Modules_CarsModulePutCall {
    return try Modules_CarsModulePutCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func del(_ request: Cars_DelRequest, metadata customMetadata: Metadata) throws -> Cars_Car {
    return try Modules_CarsModuleDelCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func del(_ request: Cars_DelRequest, metadata customMetadata: Metadata, completion: @escaping (Cars_Car?, CallResult) -> Void) throws -> Modules_CarsModuleDelCall {
    return try Modules_CarsModuleDelCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol Modules_CarsModuleProvider: ServiceProvider {
  func get(request: Cars_GetRequest, session: Modules_CarsModuleGetSession) throws -> ServerStatus?
  func put(request: Cars_Car, session: Modules_CarsModulePutSession) throws -> Cars_Car
  func del(request: Cars_DelRequest, session: Modules_CarsModuleDelSession) throws -> Cars_Car
}

extension Modules_CarsModuleProvider {
  internal var serviceName: String { return "modules.CarsModule" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/modules.CarsModule/Get":
      return try Modules_CarsModuleGetSessionBase(
        handler: handler,
        providerBlock: { try self.get(request: $0, session: $1 as! Modules_CarsModuleGetSessionBase) })
          .run()
    case "/modules.CarsModule/Put":
      return try Modules_CarsModulePutSessionBase(
        handler: handler,
        providerBlock: { try self.put(request: $0, session: $1 as! Modules_CarsModulePutSessionBase) })
          .run()
    case "/modules.CarsModule/Del":
      return try Modules_CarsModuleDelSessionBase(
        handler: handler,
        providerBlock: { try self.del(request: $0, session: $1 as! Modules_CarsModuleDelSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol Modules_CarsModuleGetSession: ServerSessionServerStreaming {
  /// Send a message to the stream. Nonblocking.
  func send(_ message: Cars_Car, completion: @escaping (Error?) -> Void) throws
  /// Do not call this directly, call `send()` in the protocol extension below instead.
  func _send(_ message: Cars_Car, timeout: DispatchTime) throws

  /// Close the connection and send the status. Non-blocking.
  /// This method should be called if and only if your request handler returns a nil value instead of a server status;
  /// otherwise SwiftGRPC will take care of sending the status for you.
  func close(withStatus status: ServerStatus, completion: (() -> Void)?) throws
}

internal extension Modules_CarsModuleGetSession {
  /// Send a message to the stream and wait for the send operation to finish. Blocking.
  func send(_ message: Cars_Car, timeout: DispatchTime = .distantFuture) throws { try self._send(message, timeout: timeout) }
}

fileprivate final class Modules_CarsModuleGetSessionBase: ServerSessionServerStreamingBase<Cars_GetRequest, Cars_Car>, Modules_CarsModuleGetSession {}

internal protocol Modules_CarsModulePutSession: ServerSessionUnary {}

fileprivate final class Modules_CarsModulePutSessionBase: ServerSessionUnaryBase<Cars_Car, Cars_Car>, Modules_CarsModulePutSession {}

internal protocol Modules_CarsModuleDelSession: ServerSessionUnary {}

fileprivate final class Modules_CarsModuleDelSessionBase: ServerSessionUnaryBase<Cars_DelRequest, Cars_Car>, Modules_CarsModuleDelSession {}
"""

**Comment by MrMage** [comment]
Backticks are this character: `. Please use that, so your text is actually readable.

**Comment by nikitayuratkin** [comment]
corrected

**Comment by MrMage** [comment]
In https://github.com/grpc/grpc-swift/issues/909#issuecomment-664198950, you claim to use `protoc --grpc-swift_out= blahBlah.proto`.

But https://github.com/grpc/grpc-swift/issues/909#issuecomment-664203756 shows that you use `protoc -I ./ public/modules/blahBlah.proto --swiftgrpc_out=./1`. `swiftgrpc_out` uses the old plugin, `grpc-swift_out` the new one.

**So you need to use `grpc-swift_out` for your `protoc` commands.** If that does not work, make sure to follow the instructions at https://github.com/grpc/grpc-swift/blob/master/docs/plugin.md closely. In particular: "The plugin must be in your PATH environment variable or specified directly when invoking protoc."

**Comment by nikitayuratkin** [comment]
I used grpc-swift_out for my protoc commands.
And now there are a lot of mistakes, just like : Type 'Users_AuthRequest' does not conform to protocol 'GRPCPayload'
Is it my mistake?

<img width="952" alt="Снимок экрана 2020-07-27 в 14 10 41" src="https://user-images.githubusercontent.com/33174759/88535810-4ba0b200-d013-11ea-9bb8-ff32d5bb4b9b.png">

**Comment by glbrntt** [comment]
The version number of the library must match the version of the plugin you used to generate the code.

**Comment by nikitayuratkin** [comment]
TY so much. The last one question, do u know how can i delete proto plugin?

**Comment by MrMage** [comment]
Like you would delete any other command line binary.
