### ISSUE TITLE
Certificate Transparency Support?

### ISSUE THREAD

**Issue by orj** [grpc/grpc-swift#913]
### What are you trying to achieve?

Apple Transport Security supports enabling certificate transparency via [NSRequiresCertificateTransparency](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsexceptiondomains) `Info.plist` key. But because Swift-gRPC uses SwiftNIO (and thus the Network framework) it doesn't participate in ATS.

Has any thought been put into how Swift-gRPC might support Certificate Transparency? Or is this something I should be asking of the Swift-NIO team?

**Comment by glbrntt** [comment]
gRPC-Swift uses SwiftNIOSSL for TLS (even when using Network.framework). SwiftNIOSSL uses Security.framework to verify certificates on Apple platforms. I *believe* certificate transparency is required by default. @Lukasa should be able to shed more light on this, however.

**Comment by orj** [comment]
Thanks for the info @Lukasa & @glbrntt!
