### ISSUE TITLE
Conflict using Firestore and gRPC-Swift pods

### ISSUE THREAD

**Issue by hugobgranja** [grpc/grpc-swift#915]
### Describe the bug

The following error results from using both Firestore and gRPC-Swift pods:
[!] The 'Pods-SwiftGRPCTest' target has frameworks with conflicting names: grpc.

Podfile:
```
target 'SwiftGRPCTest' do
  use_frameworks!

  pod 'Firebase/Firestore'
  pod 'gRPC-Swift', '1.0.0-alpha.17'
end
```

**Comment by glbrntt** [comment]
This was resolved by #917 - the next release should work fine with Firestore.

**Comment by glbrntt** [comment]
The fix here was actually in error and has been reverted: unfortunately I don't see a way to work around this properly without renaming gRPC Swift entirely.

**Comment by glbrntt** [comment]
Sorry for the churn on this one, it's a bit of an awkward issue.

The current workaround – once #945 lands – is copy our [Podfile](https://github.com/grpc/grpc-swift/blob/main/gRPC-Swift.podspec) and replace the module name with something that doesn't have conflicts, "GRPCSwift", for example.

When you generate your code from your proto file you'll have to set the "GRPCModuleName" option to whatever name you chose above.
