### ISSUE TITLE
Error with Swift Package Manager

### ISSUE THREAD

**Issue by SongJiyeon** [grpc/grpc-swift#921]
### Describe the bug

I got an error with below image during installation some package regardless of what it is.
Can you find what is wrong?

![image](https://user-images.githubusercontent.com/26474799/89515896-b1125100-d812-11ea-9d6f-de2521cdc06b.png)

### Additional information

I find this just today and grpc-swift works find.
But it doesn't work when I use Swift Package Manager.

**Comment by Lukasa** [comment]
Hmm, I think this may be related to the fact that this repository does not have a `master` branch. What Xcode version is this?

**Comment by Lukasa** [comment]
Also how have you configured the package dependency? Are you depending on the `master` branch directly?

**Comment by SongJiyeon** [comment]
We have `dev` branch instead of `master`. But this hasn't happen before. My Xcode version is **Version 11.6**.
And Except for grpc-swift, it works fine.

**Comment by yoonseok312** [comment]
Having same problem here - Xcode version 11.6, have dev branch instead of master branch and depending on it directly, added the package via Swift Pakages > Add Package Dependency. My error log is telling me the error is related to grpc-swift.

**Comment by SongJiyeon** [comment]
I solved it with remove and reinstall

**Comment by izone-airstream** [comment]
Guys, it took me dozens of minutes to figure it out that the branch "master" became "main", don't know since when. 

Use branch "main" and it works well. The things is Xcode still have "master" as default.

**Comment by SongJiyeon** [comment]
> Guys, it took me dozens of minutes to figure it out that the branch "master" became "main", don't know since when.
> 
> Use branch "main" and it works well. The things is Xcode still have "master" as default.

It works. Thanks! 🥳
