### ISSUE TITLE
grpc-swift replaces server reported error with internal error

### ISSUE THREAD

**Issue by gregfajen** [grpc/grpc-swift#926]
Calling a non-existing method on our server (proxied by Envoy) returns the following headers:

`[([], ":status", "200"), ([], "grpc-status", "12"), ([], "grpc-message", "Method not found"), ([], "x-envoy-upstream-service-time", "2"), ([], "date", "Fri, 07 Aug 2020 16:39:06 GMT"), ([], "server", "default")]`

Note that these server headers give us the correct and expected status code of 12.

Confusingly, grpc-swift transmogrifies this into an internal error of code 13:

`internalError (13): Missing 'content-type' header`

Presumably grpc-swift is unhappy with Envoy's headers.

### Expected behavior:

grpc-swift should always return the server provided status code, and only return an internal error if a status code is unavailable.

### To reproduce

1. Setup an Envoy proxy (or mock it with the headers above)
2. Make a call to a non-existent method
3. Check status code surfaced by grpc-swift

### Additional information

This is in version `1.0.0-alpha.17`, for iOS.

I'll work around this for now. I might be able to submit a patch for it, but am not entirely sure of the desired behavior.

The relevant code seems to be near line 334 of `_GRPCClientChannelHandler.swift`, function `private func readHeaders(...)`, comment `// Are they valid headers?` authored by @glbrntt.

Also, as an aside, thank you George for all your hard work!

**Comment by glbrntt** [comment]
Thanks for the report @gregfajen, I think grpc-swift is correct per the spec here:

From https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses,

> * Response → (Response-Headers *Length-Prefixed-Message Trailers) / Trailers-Only
> * Trailers-Only → HTTP-Status Content-Type Trailers
> * Content-Type → "content-type" "application/grpc" [("+proto" / "+json" / {custom})]

We have a "Trailers-Only" response here, so we must have an HTTP status, a (valid) content type that starts with "application/grpc" and any other. We're missing the content-type completely here; the server must not be sending it and is therefore not following the spec.

However, having the client follow the spec exactly here seems a bit off: we shouldn't throw away the returned status and message if the content-type is missing. Instead, I think the better behaviour would be to validate the content-type _only if it is present_.
