### ISSUE TITLE
No such module `GRPC`

### ISSUE THREAD

**Issue by IgorRosocha** [grpc/grpc-swift#928]
## Describe the bug

After updating to `1.0.0-alpha.18` using Cocoapods and re-generating protofiles, i get `No such module GRPC` compiler error on every import, including newly generated protofiles. I suspect this may be related to #916.

### To reproduce

1. Update to `1.0.0-alpha.18` using Cocoapods
2. Re-generate protofiles
3. Compile

### Expected behaviour

Generated protofiles should be compilable.

**Comment by glbrntt** [comment]
Yikes. Sorry about that -- I clearly wasn't thinking through when I made that PR, I even spelled out the consequences in the description of the PR.

**Comment by IgorRosocha** [comment]
> Yikes. Sorry about that -- I clearly wasn't thinking through when I made that PR, I even spelled out the consequences in the description of the PR.

No problem at all, just a little delay when updating to latest release. Thank you for your quick response and immediate PR to fix the issue.

**Comment by moh-abk** [comment]
Is there an ETA for this?

**Comment by glbrntt** [comment]
Within the next day or two, hopefully.

**Comment by Ambrose12Silveira** [comment]
> Within the next day or two, hopefully.

Any luck on this issue?

**Comment by IgorRosocha** [comment]
> Any luck on this issue?

Version `1.0.0-alpha.19` has already been released, and the problem no longer persits.
