### ISSUE TITLE
missing underscores

### ISSUE THREAD

**Issue by nicoleMadonna** [grpc/grpc-swift#95]
I have a .proto file that has this message:
message STREAMING_NO_RESPONSE {}

after running the code generator protoc-gen-swiftgrpc, it generated three files Ola.pb.swift, ola.proto.client.pb.swift, ola.proto.client.pb.swift.

In  Ola.pb.swift, message STREAMING_NO_RESPONSE {} became "struct Ola_Proto_STREAMING_NO_RESPONSE: SwiftProtobuf.Message" correctly BUT in the ola.proto.client.pb.swift, and ola.proto.server.pb.swift files STREAMING_NO_RESPONSE {}  became:

Ola_Proto_STREAMINGNORESPONSE. !!!!!

After editing the files to make everything : Ola_Proto_STREAMING_NO_RESPONSE 

everything compiled fine!

I'm running version 0.2.2 with Swift 3

**Comment by timburks** [comment]
Thanks for posting this! I'm hoping to update the swiftgrpc plugin soon to use the same name generation code that protoc-gen-swift uses; when I do, I'll verify that it fixes this.

**Comment by timburks** [comment]
I believe this is fixed in [0.3.1](https://github.com/grpc/grpc-swift/releases/tag/0.3.1).
