### ISSUE TITLE
iOS Background fetchs with gRPC-Swift

### ISSUE THREAD

**Issue by pacu** [grpc/grpc-swift#955]
### What are you trying to achieve?

I'm trying to support background fetch in the[ ECC Wallet ](https://github.com/zcash/zcash-ios-wallet). According to 

### What have you tried so far?
According to [Apple's documentation on background fetch](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refreshl) Background fetch uses URLSession tasks. Is there a way to make use grpc on background fetch tasks?

**Comment by glbrntt** [comment]
I'm afraid not: gRPC-Swift doesn't use `URLSession`.
