### ISSUE TITLE
ServiceClient does not conform to protocol 'GRPCClient'

### ISSUE THREAD

**Issue by Willjay90** [grpc/grpc-swift#959]
### Question Checklist

- [x]  Updated grpc-swift to the latest version `pod 'gRPC-Swift', '~> 1.0.0-alpha.19'`
- [x]  I read [README](https://github.com/grpc/grpc-swift/blob/main/README.md)
- [x]  I searched for existing GitHub issues

```
protoc --version
libprotoc 3.13.0
```
### Describe the bug
when I `make generate-helloworld` and the generated `helloworld.grpc.swift` would be different from the one in the repo, causing the error,
```
'Helloworld_GreeterServiceClient' does not conform to protocol 'GRPCClient'
```

```
// GPRCClient.swift
public protocol GRPCClient {
  var channel: GRPCChannel { get }
  var defaultCallOptions: CallOptions { get set }
}

// helloworld.grpc.swift
public final class Helloworld_GreeterServiceClient: GRPCClient, Helloworld_GreeterService {
  public let connection: ClientConnection
  public var defaultCallOptions: CallOptions

  public init(connection: ClientConnection, defaultCallOptions: CallOptions = CallOptions()) {
    self.connection = connection
    self.defaultCallOptions = defaultCallOptions
  }
  ...
}

```

however, the original `helloworld.grpc.swift` in the repo 
```
public final class Helloworld_GreeterClient: Helloworld_GreeterClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the helloworld.Greeter service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}
```

**Comment by Willjay90** [comment]
just noticed that the bug should be inside the `Makefile`. I can generate the correct `helloworld.grpc.swift` by the following command
```
protoc Sources/Examples/HelloWorld/Model/helloWorld.proto --grpc-swift-out=Client=true,Server-false:.
```

**Comment by MrMage** [comment]
> I noticed that the bug should be inside the `Makefile`. I can generate the correct `helloworld.grpc.swift` by the following command. just a bit confused which one should be the newest version.

What's the difference between that command and the one you originally used?

Also, are you 100% sure that you used the latest versions of our `protoc` plugins?
