### ISSUE TITLE
Channel gets deinitialized on main thread

### ISSUE THREAD

**Issue by edopelawi** [grpc/grpc-swift#96]
Hi all,

I'm currently using the 0.1.13 version, and I got some issue on Channel's deinitialization.

The issue occurs intermittently. On my source code, I wrapped the Protobuf-generated GRPC services, and each time the wrapper object gets deinitialized, the same thing happens on the opened Channel. Based on the stack I captured, it calls the `cgrpc_channel_destroy`, which calls blocking `grpc_pollset_work`.

 Here's a screenshot of the stack:

<img width="355" alt="screen shot 2017-12-20 at 16 36 47" src="https://user-images.githubusercontent.com/5947111/34200648-6929dab0-e5a4-11e7-9fae-1dfd39502fab.png">

Is there a way to make the process non-blocking? Or is it already fixed on the newer versions?

Thanks in advance!

**Comment by timburks** [comment]
Hi, could you share your client code with me (timburks at google dot com) or try a newer version? The generated code now contains blocking versions of all unary (nonstreaming) API client handlers.

**Comment by edopelawi** [comment]
Hi Tim, thanks for the response!

I'm not sure I could share the client code, but I could definitely try upgrading the version. Does the newer one still supports Swift 3?

**Comment by timburks** [comment]
I'm not testing with Swift 3 but don't recall any significant changes for Swift 4 (apart from the Datastore example, which uses Codable).

**Comment by edopelawi** [comment]
@timburks, I forgot to update this thread until this issue bits me again recently :| I tried to update to 0.3.3... and yeah, the problem is still there.

I tried to dig in a little bit, and found out that the `cgrpc_completion_queue_drain(c->completion_queue);` in CgRPC's channel.c might be using main thread... and I found no way to change the queue to something else, either :(

Is there any way to send this process to background? I tried to wrap the process of assigning nil to the GRPC property inside a background DispatchQueue, but it still came back to main thread...

**Comment by MrMage** [comment]
Closing this now; please open a new issue if the issue persists in Swift gRPC 0.9.0.
