### ISSUE TITLE
ClientCallTransport makes outcalls before it transitions its internal state

### ISSUE THREAD

**Issue by Lukasa** [grpc/grpc-swift#961]
In ClientCallTransport, whenever we transition to `.closed` we cancel the timeout task. Cancelling tasks like this _can_ cause side-effects due to arbitrary outcalls, as users can register to be notified when scheduled tasks are cancelled. While this doesn't happen to this task today, it could in future.

However, on the happy path we have a slight ordering issue:

https://github.com/grpc/grpc-swift/blob/6ea62df048129bd715b270e5a4021a7aea9cdbb1/Sources/GRPC/ClientCalls/ClientCallTransport.swift#L547-L554

Here we cancel the timeout and _then_ transition our internal state to `.closed`. We should really do this the other way around.

**Comment by glbrntt** [comment]
Good spot!
