### ISSUE TITLE
Are there gRPC vs REST benchmarks for iOS apps

### ISSUE THREAD

**Issue by qcloop** [grpc/grpc-swift#964]
I am looking into replacing our REST APIs with gRPC equivalents. We created a sample gRPC app to compare with REST-based version of it. Without any customization, we did not see any improvements in latency for unary calls. However, we see potential in streaming APIs. Is there a documentation, benchmarking studios, etc that would help us in deciding gRPC vs REST in mobile world?

**Comment by glbrntt** [comment]
> Without any customization, we did not see any improvements in latency for unary calls. 

Just to double check: did you this in release mode? The performance of gRPC Swift is degraded quite significantly when compiled in debug mode.

> However, we see potential in streaming APIs. Is there a documentation, benchmarking studios, etc that would help us in deciding gRPC vs REST in mobile world?

I'm not aware of any specific to gRPC Swift. [This article](https://www.grpc.io/blog/mobile-benchmarks/) may be mildly relevant: it compares gRPC to REST and JSON to Protobuf although it does so in Java so the results are not directly applicable.

Performance aside, there are some nice advantages to using gRPC:
- It's easy to define your service and generate a client for it (and there's support for a bunch of languages)
- Your request/response models are type safe and can be evolved over time
- You have the option of streaming, which may or may not be relevant to your use case

**Comment by qcloop** [comment]
Thank you for your feedback. We just linked our code against the master without any switches, did not see any debug logging. However, if you have docs on how to switch debit mode on/off, that would be great. Also, apart from setting thread in event loop group we did not tune other params.

As for API design, it does offer stronger contract that REST. And streaming is definitely a crucial differentiator.

**Comment by glbrntt** [comment]
> Thank you for your feedback. We just linked our code against the master without any switches, did not see any debug logging. However, if you have docs on how to switch debit mode on/off, that would be great. 

I mean the "Build Configuration" option under the Info tab when editing the scheme for your app in Xcode.
