### ISSUE TITLE
Get details object from error

### ISSUE THREAD

**Issue by Banck** [grpc/grpc-swift#971]
Hello! 
On the java server-side we make an error like this:
```
Status status = Status.newBuilder()
    .setCode(Code.INVALID_ARGUMENT.getNumber())
    .setMessage("Email or password malformed")
    .addDetails(Any.pack(someProtoObject))
```
But in swift I can't get details, because there is only `GRPC.GRPCStatus` object in `whenComplete`.

So how can I get a details? Thanks

**Comment by glbrntt** [comment]
This isn't actually part of the spec, however, you can still extract the details from the `trailingMetadata`. The header field should be 'grpc-status-details-bin' and will contain the details as a base64 encoded string.
