### ISSUE TITLE
SpeechToText example does not work

### ISSUE THREAD

**Issue by Halmoni100** [grpc/grpc-swift#972]
I'm trying to get this example to work.  It builds, but don't think it is working, there is no response.

I am using Xcode 12.0, protoc on v3.13.0, and the protoc plugins on this repo built on 1.0.0-alpha.19.  I changed the pod file so that the project is built with this repo on 1.0.0-alpha.19.

I tried a lot of combinations of the above except the IDE.

**Comment by glbrntt** [comment]
Can you be more specific about it not working? What happens when you run it?

**Comment by Halmoni100** [comment]
Here's the debug output for the versions mentioned above.  I inserted "//" comments to describe when the debug output occurred:

// Start app
2020-09-24 12:39:13.763708-0600 TestGC_STT[47903:20586295] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600003c625c0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
// Press record
2020-09-24 12:39:31.550262-0600 TestGC_STT[47903:20588886] [aurioc] AURemoteIO.h:323:entry: Unable to join I/O thread to workgroup ((null)): 2

I get no response afterwards, although "SpeechService.stream" is continuously called.

**Comment by Halmoni100** [comment]
I tried an earlier version, and I don't get the second debug output.  The gRPC client seems to output a "ready" state, but I don't get a response.

**Comment by glbrntt** [comment]
I'm unable to reproduce this. I've just pushed up #973 to enable logging; could you try again with that patch and provide the logs? That should give us some hints as to why this isn't working for you.

**Comment by Halmoni100** [comment]
Thanks for the logging and changes, looks like I just inputted the incorrect entry in Constants.swift for the API key, now it's working!

I'm new to Google cloud and all of this in general.
