### ISSUE TITLE
Support standard benchmarking

### ISSUE THREAD

**Issue by PeterAdams-A** [grpc/grpc-swift#976]
### Is your feature request related to a problem? Please describe it.

Most other grpc implementations run with the standard benchmarking setup as described https://grpc.io/docs/guides/benchmarking/

### Describe the solution you'd like

A qps working implementation in swift.

### Describe alternatives you've considered

Expanding  https://github.com/LesnyRumcajs/grpc_bench/tree/master/swift_grpc_bench - it has broader language coverage but fewer methods are tested.

### Additional context

The existing benchmarking has shown Grpc-swift to perform less well than expected - we should understand this more.

**Comment by PeterAdams-A** [comment]
The comments on https://github.com/grpc/grpc/issues/23297 indicate a rethink of benchmarking is coming in Q4, however for now I think this is the best there is.

**Comment by glbrntt** [comment]
I think we can close this, #990 added the unary benchmark, #1003 added a bidi scenario. We can add to this as and when necessary.
