### ISSUE TITLE
Connect with server using address instead of hostname+port number

### ISSUE THREAD

**Issue by IrisG33** [grpc/grpc-swift#981]
Hi grpc-swift team,

The ClientConnection has to be initialized with hostname and port. But often the server should be accessed through a fully qualified domain name(FQDN) from clients, and it's not necessarily easy for clients to know the port number that the server is listening to. Wondering can gRPC-swift support to connect with server using the FQDN?

**Comment by Lukasa** [comment]
The FQDN generally does not encode the port. How are you expecting to find it out?

**Comment by IrisG33** [comment]
Apologize for using FQDN which is probably not I really meant. I'm more wondering can gRPC swift support to create the ClientConnection using API endpoint.
For example, the Google Cloud gRPC service can be configured as this [example](https://cloud.google.com/endpoints/docs/grpc/grpc-service-config). The service has the endpoint name `calendar.googleapis.com`, and clients can send requests using the endpoint.  I think this is [supported in cgrpc](https://github.com/grpc/grpc-swift/blob/cgrpc/Examples/Google/NaturalLanguage/Sources/main.swift?l=34#L34) .

**Comment by Lukasa** [comment]
I'm pretty confident that the port is simply defaulted to 443 in this case.

**Comment by IrisG33** [comment]
Yeah, tried with 443, and it works.

**Comment by Lukasa** [comment]
So, yes, we could absolutely provide an alternative constructor that just defaults the port to 443.

**Comment by IrisG33** [comment]
That would be nice :)
