### ISSUE TITLE
Unfriendly quick start examples: Guide needed to run them

### ISSUE THREAD

**Issue by imWildCat** [grpc/grpc-swift#983]
### What are you trying to achieve?

I want to run an example very quickly according these `README` files. However, there is no clear guidance for me.

### What have you tried so far?

1. Enter `Sources/Examples/Echo`
2. Go into `client`
3. Run `swift main.swift`

The output looks like:
```
➜  client git:(main) swift main.swift
main.swift:16:8: error: no such module 'GRPC'
import GRPC
       ^
```

**Comment by Lukasa** [comment]
Yeah, we should update the README to say how to run them. The answer is, from the root of the checkout, to run `swift run HelloWorldClient` or `swift run HelloWorldServer`.
