### ISSUE TITLE
Is it possible make protoc-gen-grpc-swift and protoc-gen-swift in Xcode?

### ISSUE THREAD

**Issue by diuming** [grpc/grpc-swift#991]
version: 1.0.0-alpha.20

i'm a newcomer that I encountered a question.
How do I make them direct in Xcode?

![Screen Shot 2020-10-14 at 2 42 15 PM](https://user-images.githubusercontent.com/39903550/95952909-94565300-0e2b-11eb-89ec-bbc86e7fcd70.png)

**Comment by glbrntt** [comment]
I think the best way to achieve this is by using _build phases_. You'll need to get the relevant binaries (`protoc`,, `protoc-gen-swift` and `protoc-gen-grpc-swift`) and then invoke `protoc` with the plugins and your source protos.

**Comment by diuming** [comment]
@glbrntt got it. thx

**Comment by dipu-bd** [comment]
@glbrntt can you explain in more details how to achieve this?
