### ISSUE TITLE
package uppercase_capital_name in .proto file.

### ISSUE THREAD

**Issue by diuming** [grpc/grpc-swift#994]
I follow your example `Source/Examples/HelloWorld` to practice.
everything is well.
but when I change `package helloworld;` to `package HelloWorld;` in helloworld.proto file.
I encountered 4 issues in Xcode. Do i miss something?

`HelloWorld.grpc.swift` generated by plugin `protoc-gen-grpc-swift`
`HelloWorld.pb.swift` generated by plugin `protoc-gen-swift`

HelloWorld.proto
---
```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option java_outer_classname = "HelloWorldProto";
option objc_class_prefix = "HLW";

package HelloWorld;

// The greeting service definition.
service Greeter {
  // Sends a greeting.
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}
```
![Screen Shot 2020-10-15 at 4 34 10 PM](https://user-images.githubusercontent.com/39903550/96098070-49f4d500-0f04-11eb-8950-d0d8d7da0a54.png)

**Comment by glbrntt** [comment]
You changed the package name, so the names of the generated types changed (assuming you regenerated the code).

`GreeterProvider` is _not_ generated but uses generated types so needs to be updated to use the new names (i.e. should be `HelloWorld_GreeterProvider` and `HelloWorld_HelloReply`)

**Comment by diuming** [comment]
@glbrntt got it. thx
