### ISSUE TITLE
Compile new project error

### ISSUE THREAD

**Issue by Saurman** [grpc/grpc-swift#996]
Hello, I've created new Xcode project and added a swift package using URL https://github.com/grpc/grpc-swift.git (Project > Project > Swift Packages). When compiling i get an error 
`The package product 'SwiftGRPC' cannot be used as a dependency of this target because it uses unsafe build flags.`

Any idea how to fix this?

**Comment by Lukasa** [comment]
What version did you add?

**Comment by glbrntt** [comment]
As @Lukasa has alluded to, the issue you're seeing is for the 0.x series which is [no longer supported](https://github.com/grpc/grpc-swift#versions). You'll need to pick a `1.0.0-alpha` release.

**Comment by Saurman** [comment]
<img width="519" alt="Screenshot 2020-10-16 at 14 09 30" src="https://user-images.githubusercontent.com/1107926/96251509-43746500-0fb9-11eb-81e3-15fd4457dfeb.png">
how do i specify release/tag?

**Comment by Lukasa** [comment]
Change the version drop down to "exact" and write "1.0.0-alpha.20" in the box.

**Comment by Saurman** [comment]
@Lukasa thanks alot, you rock. Any idea how I can run gRPC on raspberry pi using swift?

**Comment by Lukasa** [comment]
I think I’ll need the full build log. These are linking errors, but they’re unlikely to be the initial error: I expect they’re follow-on issues.

**Comment by Saurman** [comment]
[grpc compile error on RPI.txt](https://github.com/grpc/grpc-swift/files/5396430/grpc.compile.error.on.RPI.txt)
Attached full log file

**Comment by Lukasa** [comment]
Hmm, this is not obviously compiling the NIO code at all, or indeed any of your dependencies. If you SSH manually to your raspberry pi and type `swift build` do you get any different output?

**Comment by Saurman** [comment]
@Lukasa I think I've figured this out. I was using Xcode swift project manager while RPI doesn't get it when code is transferred using Swish. Instead, RPI only gets Package.swift (which I left empty).

Thanks for your help, feel free to close this thread!
