### ISSUE TITLE
Missing Instruction for RouteGuideModel?

### ISSUE THREAD

**Issue by BarberEngineering** [grpc/grpc-swift#997]
New to Swift here so may be my lack of knowledge but in the example for RouteGuide the client file (and other files) have a "import RouteGuideModel" but other than the import line, nothing else creates or is named "RouteGuideModel"

Where is "RouteGuideModel" or how is it created to import?

ref: https://github.com/grpc/grpc-swift/blob/main/Sources/Examples/RouteGuide/Client/main.swift

**Comment by Lukasa** [comment]
The `RouteGuideModel` target is declared in the `Package.swift` [here](https://github.com/grpc/grpc-swift/blob/cdb46f4d24fc4aef5c6f4ef5ebf50215354c28bb/Package.swift#L214-L223).
